Remove jQuery dependency for Post masonry and carousel.
brainstormforce/ultimate-addons-for-gutenberg pull request #1108
Opened 2021-10-29 12:31 UTC by AbhijitNage123

### Description

- Masonry block.
- Carousel block.

### Types of changes

- Improvement

### How has this been tested?

- Drag and drop masonry 
- Enable pagination and check infinite scroll and load more button pagination settings.
- Drag and drop carousel
- Enable equal height check editor as well as frontend. Equal hight working properly or not.

### Checklist:
- [x] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [x] I've included any necessary tests 
- [ ] I've included developer documentation 
- [x] I've added proper labels to this pull request

2021-11-02 09:41 UTC, RajkiranBagal requested changes

2021-11-02 09:41 UTC, RajkiranBagal commented on assets/js/post.js
> +			const post_wrapper = scope[0].querySelectorAll( '.slick-slide' ),
Make all variables `camelCase`

2021-11-02 09:41 UTC, RajkiranBagal commented on blocks-config/post/class-uagb-post.php
> +				'postsToShow'        => ( isset( $attributes['postsToShow'] ) ) ? esc_attr( $attributes['postsToShow'] ) : 6,
Escaping is done when we are Outputting something. For Inputs, we need to sanitize the data.

2021-11-02 10:14 UTC, AbhijitNage123 commented on assets/js/post.js
> +			const post_wrapper = scope[0].querySelectorAll( '.slick-slide' ),
Updated.

2021-11-02 10:14 UTC, AbhijitNage123 commented on blocks-config/post/class-uagb-post.php
> +				'postsToShow'        => ( isset( $attributes['postsToShow'] ) ) ? esc_attr( $attributes['postsToShow'] ) : 6,
Updated.

2021-11-03 06:33 UTC, RajkiranBagal requested changes

2021-11-03 06:33 UTC, RajkiranBagal commented on assets/js/post.js
> +				const BoundingClientRect = $scope.querySelectorAll( '.uagb-post__items' )[0].lastElementChild.getBoundingClientRect();
camelCase these type of vars too

2021-11-03 06:43 UTC, AbhijitNage123 commented on assets/js/post.js
> +				const BoundingClientRect = $scope.querySelectorAll( '.uagb-post__items' )[0].lastElementChild.getBoundingClientRect();
Updated.

2021-11-08 03:30 UTC, supriyajjadhav approved these changes

2021-11-10 06:58 UTC, RajkiranBagal approved these changes

2021-11-10 07:14 UTC, sandeshjangam commented on blocks-config/post/class-uagb-post.php
> +							scope = document.querySelector( '.uagb-block-<?php echo esc_html( $key ); ?>' );
scope is not defined here

2021-11-10 07:24 UTC, AbhijitNage123 commented on blocks-config/post/class-uagb-post.php
> +							scope = document.querySelector( '.uagb-block-<?php echo esc_html( $key ); ?>' );
Updated.

2021-11-10 07:27 UTC, sandeshjangam approved these changes

2021-11-10 07:29 UTC, merged