jQuery to JS from Milestone 2.1
brainstormforce/ultimate-addons-for-gutenberg pull request #1125
Opened 2021-11-16 11:33 UTC by sandeshjangam

### Description
jQuery to JS from Milestone 2.1

### Screenshots

### Types of changes

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2021-11-16 11:40 UTC, sandeshjangam commented on src/blocks/how-to/child-blocks/step/settings.js
>  	const getImageSize = ( sizes ) => {
Add this task for 2.1, we can common out this function as a helper function.

2021-11-16 11:43 UTC, sandeshjangam commented on includes/blocks/lottie/frontend.js.php
> +	UAGBLottie._run(<?php echo wp_json_encode( $attr ); ?>, '<?php echo esc_attr( $selector ); ?>' );
```suggestion
	UAGBLottie._run( <?php echo wp_json_encode( $attr ); ?>, '<?php echo esc_attr( $selector ); ?>' );
```

2021-11-16 11:48 UTC, AbhijitNage123 commented on src/blocks/how-to/child-blocks/step/settings.js
>  	const getImageSize = ( sizes ) => {
Added task here - https://app.startinfinity.com/b/Mi5zu3VRVzk/iHKt2gD8SSQ/cdfa74f5-97d9-4ad0-9c8b-59981d008c9e?view=0a6f113f-f5c3-4b4e-82f0-1a6fc4831d3e&t=attributes

2021-11-16 12:00 UTC, RajkiranBagal requested changes

2021-11-16 12:00 UTC, RajkiranBagal commented on assets/js/inline-notice.js
> +		const unique_id = attr.c_id;
Convert all variables to camelCase.

2021-11-16 12:00 UTC, RajkiranBagal commented on assets/js/post.js
> +				selector = $this.querySelectorAll( '.uagb-post__inner-wrap' );
Instead of using querySelectorAll everywhere we can use just querySelector, as we are only using the first element found.

2021-11-16 12:00 UTC, RajkiranBagal commented on assets/js/timeline.js
> +		const line_inner = timeline[i].querySelector( '.uagb-timeline__line__inner' );
Convert all variables to camelCase.

2021-11-16 12:00 UTC, RajkiranBagal commented on src/blocks/review/settings.js
> +		for( let i = 0; i < arr.length; i++ ) {
Why are we doing Object.keys here? Can we not just use for ... in method & avoid that extra step?

2021-11-16 12:13 UTC, sandeshjangam commented on src/blocks/review/settings.js
> +		for( let i = 0; i < arr.length; i++ ) {
Avoid the for loop as much as possible. Use `for ( const item of items ) {`  or similar wherever possible.

2021-11-17 03:05 UTC, sandeshjangam commented on src/blocks/how-to/settings.js
> +import getImageSize from '@Controls/ImageSize';
@AbhijitNage123  It is not a control. It is a helper function or you can also say utils.

2021-11-17 09:04 UTC, AbhijitNage123 commented on src/blocks/how-to/settings.js
> +import getImageSize from '@Controls/ImageSize';
Updated.

2021-11-17 09:07 UTC, sandeshjangam commented on webpack.config.js
> +			'@Utils': path.resolve( __dirname, 'blocks-config//utils/' ),
```suggestion
			'@Utils': path.resolve( __dirname, 'blocks-config/utils/' ),
```

2021-11-17 09:08 UTC, AbhijitNage123 commented on assets/js/post.js
> +				selector = $this.querySelectorAll( '.uagb-post__inner-wrap' );
@RajkiranBagal querySelectorAll() is needed here. It's a carousel js we need to apply every element not just one element.

2021-11-17 09:19 UTC, AbhijitNage123 commented on assets/js/post.js
> +				selector = $this.querySelectorAll( '.uagb-post__inner-wrap' );
Updated

2021-11-17 09:21 UTC, AbhijitNage123 commented on webpack.config.js
> +			'@Utils': path.resolve( __dirname, 'blocks-config//utils/' ),
Updated

2021-11-17 09:38 UTC, AbhijitNage123 commented on assets/js/timeline.js
> +		const line_inner = timeline[i].querySelector( '.uagb-timeline__line__inner' );
Updated

2021-11-17 09:38 UTC, AbhijitNage123 commented on src/blocks/review/settings.js
> +		for( let i = 0; i < arr.length; i++ ) {
Done

2021-11-18 07:39 UTC, RajkiranBagal requested changes

2021-11-18 07:39 UTC, RajkiranBagal commented on assets/js/inline-notice.js
> +		for( let i = 0; i < main.length; i++ ){
Can we use `for of` loop here?

2021-11-18 07:39 UTC, RajkiranBagal commented on assets/js/timeline.js
> +	for ( let i = 0; i < timeline.length; i++ ) {
Can we use `for of` loop here?

2021-11-18 07:39 UTC, RajkiranBagal commented on src/blocks/cf7-designer/edit.js
> +		if( document.querySelector( '.wpcf7-submit' ) !== null ){
As `document.querySelector( '.wpcf7-submit' )` is used twice. Save it in a variable & then use it.

2021-11-18 07:39 UTC, RajkiranBagal commented on src/blocks/gf-designer/edit.js
> +		if( document.querySelector( '.wpgf-submit' ) !== null ){
As document.querySelector( '.wpgf-submit' ) is used twice. Save it in a variable & then use it.

2021-11-18 07:39 UTC, RajkiranBagal commented on src/blocks/review/edit.js
> +		if( document.querySelector( '.uagb-rating-link-wrapper' )!== null ){
Store in Variable. SAme as above

2021-11-18 07:39 UTC, RajkiranBagal commented on src/blocks/timeline/post-timeline/edit.js
> -				}
After Removing all this code Where have we managed this functionality?

2021-11-19 05:04 UTC, AbhijitNage123 commented on src/blocks/timeline/post-timeline/edit.js
> -				}
We didn't manage it anywhere. It's unnecessary code. screencast - https://share.getcloudapp.com/5zu9b1Lb

2021-11-19 05:05 UTC, AbhijitNage123 commented on src/blocks/review/edit.js
> +		if( document.querySelector( '.uagb-rating-link-wrapper' )!== null ){
Done

2021-11-19 05:05 UTC, AbhijitNage123 commented on src/blocks/gf-designer/edit.js
> +		if( document.querySelector( '.wpgf-submit' ) !== null ){
Done

2021-11-19 05:05 UTC, AbhijitNage123 commented on src/blocks/cf7-designer/edit.js
> +		if( document.querySelector( '.wpcf7-submit' ) !== null ){
Done

2021-11-19 05:05 UTC, AbhijitNage123 commented on assets/js/timeline.js
> +	for ( let i = 0; i < timeline.length; i++ ) {
Done

2021-11-19 05:05 UTC, AbhijitNage123 commented on assets/js/inline-notice.js
> +		for( let i = 0; i < main.length; i++ ){
Done

2021-11-19 05:05 UTC, RajkiranBagal commented on src/blocks/timeline/post-timeline/edit.js
> -				}
Okay!

2021-11-19 05:06 UTC, RajkiranBagal approved these changes

2021-11-19 05:07 UTC, AbhijitNage123 approved these changes

2021-11-19 06:08 UTC, sandeshjangam reviewed
Approved

2021-11-19 06:10 UTC, merged