Fix: Block padding issue.
brainstormforce/ultimate-addons-for-gutenberg pull request #1126
Opened 2021-11-17 07:43 UTC by AbhijitNage123

### Description

- https://brainstormforce.slack.com/archives/CAQ2TSA6A/p1637076864070100

### Screenshots

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

### How has this been tested?

Case - 1 - Backward compatibility check.
Case - 2
- Drag and drop TOC.
- Set padding empty it will inherit 30px
- set padding 0 it will add padding 0 in frontend as well as backend.

### Checklist:
- [x] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [x] I've included any necessary tests 
- [ ] I've included developer documentation 
- [x] I've added proper labels to this pull request

2021-11-17 08:34 UTC, RajkiranBagal requested changes

2021-11-17 08:34 UTC, RajkiranBagal commented on includes/blocks/table-of-contents/frontend.css.php
> +$top_padding    = ( isset( $attr['topPadding'] ) || ! empty( $attr['topPadding'] ) ) ? $attr['topPadding'] : $attr['vPaddingDesktop'];
There should be && here instead of || or just isset then. Because it is not logical to checl isset & !empty in ||

2021-11-17 08:40 UTC, sandeshjangam commented on includes/blocks/table-of-contents/frontend.css.php
> +$bottom_padding = ( isset( $attr['bottomPadding'] ) || ! empty( $attr['bottomPadding'] ) ) ? $attr['bottomPadding'] : $attr['vPaddingDesktop'];
for 0  value `empty( $attr['topPadding'] )` will return true

2021-11-17 08:42 UTC, AbhijitNage123 commented on includes/blocks/table-of-contents/frontend.css.php
> +$top_padding    = ( isset( $attr['topPadding'] ) || ! empty( $attr['topPadding'] ) ) ? $attr['topPadding'] : $attr['vPaddingDesktop'];
Updated.

2021-11-17 08:42 UTC, AbhijitNage123 commented on includes/blocks/table-of-contents/frontend.css.php
> +$bottom_padding = ( isset( $attr['bottomPadding'] ) || ! empty( $attr['bottomPadding'] ) ) ? $attr['bottomPadding'] : $attr['vPaddingDesktop'];
Right. Updated condition.

2021-11-17 10:11 UTC, RajkiranBagal approved these changes

2021-11-17 10:28 UTC, sandeshjangam approved these changes

2021-11-22 04:26 UTC, sandeshjangam approved these changes

2021-11-22 04:27 UTC, merged