Improvement: Marketing button HTML optimization.
brainstormforce/ultimate-addons-for-gutenberg pull request #1132
Opened 2021-11-23 07:30 UTC by AbhijitNage123

### Description

- Task - https://app.startinfinity.com/b/Mi5zu3VRVzk/iHKt2gD8SSQ/ea592036-54b9-4155-9907-545aa011ba50?view=0a6f113f-f5c3-4b4e-82f0-1a6fc4831d3e&t=attributes
- Removed unnecessary classes and div from the marketing button.
- Manage remove classes CSS in style.scss.
- Doc for changes - https://docs.google.com/document/d/1ZNsQoG4eEtac9_bxWwwt6XBkOSdfarQ3D9vaulpcss0/edit

### Screenshots

### Types of changes

- Improvement

### How has this been tested?

- All settings working fine or not on the frontend as well as backend.
- Backward compatibility.

### Checklist:
- [x] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [x] I've included any necessary tests 
- [ ] I've included developer documentation 
- [x] I've added proper labels to this pull request

2021-11-23 08:03 UTC, RajkiranBagal requested changes
Still can see too much nesting of HTML elements, - https://share.bsf.io/jkuEpyO7

2021-11-24 06:39 UTC, AbhijitNage123 commented
@RajkiranBagal Updated HTML as discuss - https://share.getcloudapp.com/xQujJPOd

2021-11-24 07:08 UTC, RajkiranBagal approved these changes

2021-11-30 08:32 UTC, akshaylakh commented
Backward Compatibility-  Alignement is disturbed in editor - https://share.bsf.io/kpu6rZLx
Style > Heading > Bottom spacing not working

2021-12-01 04:37 UTC, akshaylakh commented
> @AbhijitNage123
> * Backward Compatibility-  Alignment is disturbed in editor - https://share.bsf.io/kpu6rZLx  -- (fixed)
> * Style > Heading > Bottom spacing not working -- (not working -  https://share.bsf.io/bLudLxew)

2021-12-03 06:45 UTC, akshaylakh commented
working fine

2021-12-03 06:58 UTC, sandeshjangam approved these changes

2021-12-03 07:32 UTC, sandeshjangam commented on package-lock.json
> +      "resolved": "http://registry.npmjs.org/through/-/through-2.3.8.tgz",
```suggestion
      "resolved": "https://registry.npmjs.org/through/-/through-2.3.8.tgz",
```

2021-12-03 07:32 UTC, sandeshjangam approved these changes

2021-12-03 07:32 UTC, merged