Improvement: Content timeline html optimization.
brainstormforce/ultimate-addons-for-gutenberg pull request #1139
Opened 2021-11-25 11:04 UTC by AbhijitNage123

### Description

- Removed classes listed here - https://docs.google.com/document/d/1ZNsQoG4eEtac9_bxWwwt6XBkOSdfarQ3D9vaulpcss0/edit

### Screenshots

- https://share.getcloudapp.com/04u5nwN2

### Types of changes

- Improvement

### How has this been tested?

- Case 1 - Backward compatibility.
- Case 2 - By checking all Settings.
- Case 3 - Special test case - Check all Orientation, Stack-On, Alignment options with left/right orientation.

### Checklist:
- [x] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [x] I've included any necessary tests 
- [ ] I've included developer documentation 
- [x] I've added proper labels to this pull request

2021-11-25 12:49 UTC, RajkiranBagal requested changes
@AbhijitNage123 Please check in editor - https://share.bsf.io/o0u7Aw8Z

Tried Regenerate Assets too.

2021-11-25 12:54 UTC, AbhijitNage123 commented
> @AbhijitNage123 Please check in editor - https://share.bsf.io/o0u7Aw8Z
> 
> Tried Regenerate Assets too.

@RajkiranBagal could you please delete custom-style-blocks.css and check again. I'm not able to replicate the same at my end.

2021-12-06 13:01 UTC, RajkiranBagal approved these changes

2021-12-07 09:04 UTC, akshaylakh commented
@AbhijitNage123 - 
Post Timeline > Console error -  https://share.bsf.io/Z4ur0Prw 
Post Timeline > Spacing > Content Spacing not working
Post/Content Timeline > Arrow disappeeared for center orientation - https://share.bsf.io/5zu9z7jR
Content timeline - left/ right orientation > layout break -  https://share.bsf.io/qGuReyYQ

2021-12-08 12:06 UTC, akshaylakh commented
@AbhijitNage123 -  Post Timeline > Console error - https://share.bsf.io/Z4ur0Prw
Others are working fine

2021-12-09 07:07 UTC, supriyajjadhav commented
On mobile view date element also align on center Please update media query - https://share.getcloudapp.com/Qwu2ggyp

2021-12-10 11:44 UTC, AbhijitNage123 commented
> On mobile view date element also align on center Please update media query - https://share.getcloudapp.com/Qwu2ggyp

This issue is fixed. Working fine on Mobile. See here - https://share.getcloudapp.com/7KuADGDj

2021-12-22 04:51 UTC, akshaylakh commented
Post timeline - Block error - [img](https://share.bsf.io/6quERPZq)
Content timeline breaking on front end -  [rec](https://share.bsf.io/GGuEXrlp)

2021-12-22 08:34 UTC, AbhijitNage123 commented
> Post timeline - Block error - [img](https://share.bsf.io/6quERPZq) Content timeline breaking on front end - [rec](https://share.bsf.io/GGuEXrlp)

Fixed

2021-12-22 10:21 UTC, akshaylakh commented
working fine

2021-12-23 05:44 UTC, sandeshjangam commented on src/blocks/timeline/content-timeline/edit.js
>  			.getBlocksByClientId( props.clientId )[ 0 ]
JS formatting?

2021-12-23 05:57 UTC, AbhijitNage123 commented on src/blocks/timeline/content-timeline/edit.js
>  			.getBlocksByClientId( props.clientId )[ 0 ]
Updated

2021-12-23 07:50 UTC, sandeshjangam approved these changes

2021-12-23 07:50 UTC, merged