Improvement: Price list block html optimization
brainstormforce/ultimate-addons-for-gutenberg pull request #1149
Opened 2021-12-02 12:51 UTC by AbhijitNage123

### Description

- Remove unnecessary classes and div
- Optimized SCSS editor/frontend.
- Remove classes mentioned here - https://docs.google.com/document/d/1ZNsQoG4eEtac9_bxWwwt6XBkOSdfarQ3D9vaulpcss0/edit

### Screenshots

### Types of changes

- Improvement (Breaking change)

### How has this been tested?

- Case 1 - Backward compatibility
- Case 2 - All settings
- Special test case -
                     - Without image and all setting option 
                     - With Image all setting option

### Checklist:
- [x] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [x] I've included any necessary tests 
- [ ] I've included developer documentation 
- [x] I've added proper labels to this pull request

2021-12-03 04:51 UTC, RajkiranBagal requested changes
We can remove 2 more div by replacing display:table by display:flex

2021-12-06 10:05 UTC, AbhijitNage123 commented
> We can remove 2 more div by replacing display: table by display: flex

As discussed we can not remove that div as it is needed when the image is added and alignment is used(with and without img). So keeping it same.

2021-12-06 10:11 UTC, RajkiranBagal approved these changes

2021-12-07 06:26 UTC, akshaylakh commented
working fine

2021-12-07 11:16 UTC, merged