Improvement: Icon List block HTML optimization
brainstormforce/ultimate-addons-for-gutenberg pull request #1150
Opened 2021-12-03 04:02 UTC by supriyajjadhav

### Description

- Task - https://app.startinfinity.com/b/Mi5zu3VRVzk/iHKt2gD8SSQ/ea592036-54b9-4155-9907-545aa011ba50?view=0a6f113f-f5c3-4b4e-82f0-1a6fc4831d3e&t=attributes
- Removed unnecessary classes and div.
- Manage remove classes CSS in style.scss.
- Doc for changes - https://docs.google.com/document/d/1ZNsQoG4eEtac9_bxWwwt6XBkOSdfarQ3D9vaulpcss0/edit

### Types of changes

- Improvement

### How has this been tested?

Test case 1 - Backward compatibility.
Test case 2 - Check all settings are working or not.

### Checklist:
- [x] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [x] I've included any necessary tests 
- [ ] I've included developer documentation 
- [x] I've added proper labels to this pull request

2021-12-03 05:32 UTC, RajkiranBagal requested changes
Please try to remove the uagb-icon-list__wrap div & remove the span for img & svg

2021-12-06 12:56 UTC, RajkiranBagal approved these changes

2021-12-07 05:27 UTC, akshaylakh commented
icons are disappearing on switching to this branch -  https://share.bsf.io/9ZuRZG7L
Style > Icon > Increase Background size icon size is reducing - https://share.bsf.io/yAu05xGZ
@supriyajjadhav please check these

2021-12-10 04:38 UTC, akshaylakh commented
@supriyajjadhav There are issues with images. 
1. In editor while testing backward compatibility, images are missing
2. On front-end images are visible in their original size
Screenshot - https://share.bsf.io/eDugGZ6K

2021-12-20 03:46 UTC, closed without merging