Improvement: Star Rating block HTML optimization
brainstormforce/ultimate-addons-for-gutenberg pull request #1154
Opened 2021-12-07 10:58 UTC by supriyajjadhav

### Description

- Task - https://app.startinfinity.com/b/Mi5zu3VRVzk/iHKt2gD8SSQ/ea592036-54b9-4155-9907-545aa011ba50?view=0a6f113f-f5c3-4b4e-82f0-1a6fc4831d3e&t=attributes
- Removed unnecessary classes and div.
- Manage remove classes CSS in style.scss.
- Doc for changes - https://docs.google.com/document/d/1ZNsQoG4eEtac9_bxWwwt6XBkOSdfarQ3D9vaulpcss0/edit

### Types of changes

- Improvement

### How has this been tested?

Test case 1 - Backward compatibility.
Test case 2 - Check all settings are working or not.

### Checklist:
- [x] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [x] I've included any necessary tests 
- [ ] I've included developer documentation 
- [x] I've added proper labels to this pull request

2021-12-07 12:12 UTC, AbhijitNage123 commented
- Full width not working properly editor as well as frontend - https://share.getcloudapp.com/7KuAKRxK
- Star issue as discussed on call.
@supriyajjadhav ^

2021-12-08 03:47 UTC, akshaylakh commented
@supriyajjadhav Working fine. Please resolve conflicts.

2021-12-08 04:58 UTC, AbhijitNage123 requested changes

2021-12-08 04:58 UTC, AbhijitNage123 commented on src/blocks/star-rating/render.js
> -			<div className="uag-star-rating" title={ `${ rating }/${ range }` }>
This Div is needed if we add alignment full width it will add space in between. Also, the Star count depends on this. The issue reported yesterday is still present. Please check once.

2021-12-08 05:20 UTC, akshaylakh commented on src/blocks/star-rating/render.js
> -			<div className="uag-star-rating" title={ `${ rating }/${ range }` }>
Yes, This is reproducible.

2021-12-09 04:05 UTC, supriyajjadhav commented on src/blocks/star-rating/render.js
> -			<div className="uag-star-rating" title={ `${ rating }/${ range }` }>
Resolved Please check

2021-12-09 04:56 UTC, AbhijitNage123 commented
@supriyajjadhav We can remove this `uag-star-rating__wrapper` class from main wrap please check and update it accordingly

2021-12-09 06:52 UTC, akshaylakh commented
@supriyajjadhav In case of stack layout alignment is disturbing - https://share.bsf.io/2NuP446j

2021-12-09 07:05 UTC, akshaylakh commented
working fine

2021-12-09 07:37 UTC, AbhijitNage123 approved these changes

2021-12-09 07:38 UTC, RajkiranBagal approved these changes

2021-12-10 06:13 UTC, sandeshjangam approved these changes

2021-12-10 06:13 UTC, merged