Improvement: Inline notice - HTML Optimization.
brainstormforce/ultimate-addons-for-gutenberg pull request #1155
Opened 2021-12-08 13:13 UTC by AbhijitNage123

### Description

- Removed extra class uagb-inline_notice__outer-wrap from wraper and updated css.

### Screenshots

### Types of changes

### How has this been tested?

- Backward testing.
- All setting option.

### Checklist:
- [x] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [x] I've included any necessary tests 
- [ ] I've included developer documentation 
- [x] I've added proper labels to this pull request

2021-12-08 13:43 UTC, RajkiranBagal reviewed
We can remove uagb-notice-text div and add it's class to child p tag

2021-12-09 06:59 UTC, AbhijitNage123 commented
> We can remove uagb-notice-text div and add it's class to child p tag

@RajkiranBagal  No we can't it shows an issue on the front-end as discussed on the call. See here - https://share.getcloudapp.com/DOu6ppJg So keeping it as it is Please check

2021-12-09 07:05 UTC, RajkiranBagal requested changes

2021-12-09 07:05 UTC, RajkiranBagal commented on assets/js/inline-notice.js
> +			const closeBtn = mainWrap.querySelector( '.uagb-notice-dismiss' ) ? mainWrap.querySelector( '.uagb-notice-dismiss' ) : mainWrap.querySelector( 'svg' );
Take mainWrap.querySelector( '.uagb-notice-dismiss' ) in a variable

2021-12-09 07:10 UTC, AbhijitNage123 commented on assets/js/inline-notice.js
> +			const closeBtn = mainWrap.querySelector( '.uagb-notice-dismiss' ) ? mainWrap.querySelector( '.uagb-notice-dismiss' ) : mainWrap.querySelector( 'svg' );
Updated

2021-12-09 07:16 UTC, RajkiranBagal approved these changes

2021-12-09 10:05 UTC, akshaylakh commented
working fine

2021-12-10 05:54 UTC, sandeshjangam approved these changes

2021-12-10 05:55 UTC, merged