Improvement: Team HTML Optimization
brainstormforce/ultimate-addons-for-gutenberg pull request #1157
Opened 2021-12-10 10:08 UTC by AbhijitNage123

### Description

- [Doc](https://docs.google.com/document/d/1ZNsQoG4eEtac9_bxWwwt6XBkOSdfarQ3D9vaulpcss0/edit)
- Removed unnecessary classes and div.

### Screenshots

### Types of changes

- Improvement

### How has this been tested?

- Backword testing.
- All setting options.
- Image Position left/right.

### Checklist:
- [x] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [x] I've included any necessary tests 
- [ ] I've included developer documentation 
- [x] I've added proper labels to this pull request

2021-12-15 11:15 UTC, RajkiranBagal requested changes

2021-12-15 11:15 UTC, RajkiranBagal commented on includes/blocks/team/frontend.css.php
> +	$attr['imageLeftMargin']  = '20';
This will keep the margin always 20 even if I change it to any value

2021-12-15 11:15 UTC, RajkiranBagal commented on src/blocks/team/edit.js
> +			props.setAttributes( { imageLeftMargin: '20' } );
This will keep the margin always 20 even if I change it to any value

2021-12-15 13:37 UTC, AbhijitNage123 commented on src/blocks/team/edit.js
> +			props.setAttributes( { imageLeftMargin: '20' } );
Updated

2021-12-15 13:37 UTC, AbhijitNage123 commented on includes/blocks/team/frontend.css.php
> +	$attr['imageLeftMargin']  = '20';
Updated

2021-12-17 09:52 UTC, RajkiranBagal approved these changes

2021-12-20 06:31 UTC, akshaylakh commented
Image Margin not working on front end -  https://share.bsf.io/2NuvJnGy
Prefix - Bottom spacing not working - https://share.bsf.io/2NuvJGdb

2021-12-20 11:52 UTC, AbhijitNage123 commented
> Image Margin not working on front end - https://share.bsf.io/2NuvJnGy Prefix - Bottom spacing not working - https://share.bsf.io/2NuvJGdb

Fixed

2021-12-20 12:16 UTC, akshaylakh commented
working fine

2021-12-21 07:05 UTC, sandeshjangam approved these changes

2021-12-21 07:05 UTC, merged