Improvement: Added action hook on form submission
brainstormforce/ultimate-addons-for-gutenberg pull request #1181
Opened 2021-12-27 13:01 UTC by supriyajjadhav

### Description
Added an action hook which is fired on successful submission of UAG forms.

### Types of changes
non-breaking change 

### How has this been tested?

### Checklist:
- [x] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [x] I've added proper labels to this pull request

2021-12-27 13:08 UTC, RajkiranBagal requested changes

2021-12-27 13:08 UTC, RajkiranBagal commented on blocks-config/forms/class-uagb-forms.php
> +				add_action( 'uagb_form_submission', 'uagb_form_success', 10, 2 );
@supriyajjadhav we need to do_action here

2021-12-27 13:39 UTC, RajkiranBagal requested changes

2021-12-27 13:39 UTC, RajkiranBagal commented on blocks-config/forms/class-uagb-forms.php
> +				do_action( 'uagb_form_success', get_the_ID(), $subject, $body );
No use of sending get_the_ID(), Also instead of sending @subject & body just sent the array which contains all the data needed.

2021-12-28 04:43 UTC, supriyajjadhav commented on blocks-config/forms/class-uagb-forms.php
> +				do_action( 'uagb_form_success', get_the_ID(), $subject, $body );
Yes, Discussed with leena, providing forms data array in action

2021-12-28 04:57 UTC, RajkiranBagal approved these changes

2021-12-28 04:58 UTC, RajkiranBagal commented
@mahajanleena1995 Please test this, Once tested then approve this PR. We will merge it.

2021-12-28 11:32 UTC, mahajanleena1995 approved these changes

2021-12-28 12:20 UTC, sandeshjangam approved these changes

2021-12-28 12:24 UTC, merged