Improvement : Units-wise min/max option for Range and Responsive Slider.
brainstormforce/ultimate-addons-for-gutenberg pull request #1191
Opened 2022-01-05 06:28 UTC by AbhijitNage123

### Description

- Added option to add min/max by unit
- eg. For PX I want max 1600 and for % I want max 100 now it is possible.
- We just need to pass attribute to min/max of Range and Responsive slider.
- `unitmin1,unitmax1 is for PX`, `unitmin2,unitmax2 is for %`, `unitmin3,unitmax3 is for VM`, and `unitmin4,unitmax4 is for EM` 

### Types of changes

- New feature (non-breaking change which adds functionality)

### How has this been tested?

- For Responsive Slider - Drag and drop TOC
- Go to the Content Tab > Gap Between Lists setting for PX max is 1600px and for % max is 100%.
- For Range - Dran and drop Info-box
- Go to Style Tab > Icon/Image tab > Size setting for PX max is 1600px and for EM max is 100em

### Checklist:
- [x] My code is tested
- [x] I've included any necessary tests 
- [x] I've added proper labels to this pull request

2022-01-07 05:17 UTC, RajkiranBagal requested changes

2022-01-07 05:17 UTC, RajkiranBagal commented on src/components/range/Range.js
> +	const max = ( props.limitMax ) ? limitMax( props.unit?.value, props ) : props.max;
Can we write just `const max = limitMax( props.unit?.value, props )` here? as we are checking necessary conditions in the function. Same applies everywhere.

2022-01-07 07:36 UTC, AbhijitNage123 commented on src/components/range/Range.js
> +	const max = ( props.limitMax ) ? limitMax( props.unit?.value, props ) : props.max;
Updated.

2022-01-07 08:45 UTC, RajkiranBagal requested changes

2022-01-07 08:45 UTC, RajkiranBagal commented on src/components/responsive-slider/index.js
> +	const isResponsive = true;
Instead of declaring a variable, directly pass true

2022-01-07 09:02 UTC, AbhijitNage123 commented on src/components/responsive-slider/index.js
> +	const isResponsive = true;
Done

2022-01-07 09:27 UTC, RajkiranBagal approved these changes

2022-01-07 10:53 UTC, akshaylakh commented
Working fine

2022-01-10 06:30 UTC, sandeshjangam approved these changes

2022-01-10 06:30 UTC, merged