Improvement: Added Infobox and Marketing button preset designs and SVG
brainstormforce/ultimate-addons-for-gutenberg pull request #1197
Opened 2022-01-07 07:55 UTC by supriyajjadhav

### Description
Added Infobox and Marketing button preset designs and SVG
Removed advanced heading presets

### Types of changes
-breaking change which adds functionality

### How has this been tested?

### Checklist:
- [x] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [x] I've added proper labels to this pull request

2022-01-10 05:03 UTC, AbhijitNage123 commented
@supriyajjadhav Could you please check backword issue - https://share.getcloudapp.com/v1uLrBgY

2022-01-10 05:56 UTC, AbhijitNage123 commented
SVG mismatch issue Resolve. both info-box and marketing button preset's are working fine.

2022-01-20 06:11 UTC, RajkiranBagal requested changes

2022-01-20 06:11 UTC, RajkiranBagal commented on src/blocks/advanced-heading/settings.js
> +							<UAGPresets
Add this in a function

2022-01-20 06:11 UTC, RajkiranBagal commented on src/blocks/call-to-action/settings.js
> +						>
Add this in a function

2022-01-20 06:11 UTC, RajkiranBagal commented on src/blocks/faq/settings.js
> +						>
Add this in a function & all like these

2022-01-20 06:38 UTC, RajkiranBagal approved these changes

2022-01-20 06:38 UTC, merged