Fix: Styling not applying on frontend when block used in widget area.
brainstormforce/ultimate-addons-for-gutenberg pull request #1210
Opened 2022-01-13 13:16 UTC by AbhijitNage123

### Description

- https://app.startinfinity.com/b/Mi5zu3VRVzk/3sAgbH1y7qY/f92da082-c136-4358-8d2f-2a5947267ea9?redirect=true&view=6e170ea7-8708-4546-8b82-23d2eebdf694&t=attributes

### Screenshots

- Output - https://share.getcloudapp.com/6quEexY9

### Types of changes

- Bug fix (non-breaking change which fixes an issue

### How has this been tested?

- Check is there any notice/error visible in the widget area when UAG is activated.
- Drag and drop block add styling and enable sidebar or footer.
- Check blocks on front is it visible, is styling applying to block properly.

### Checklist:
- [x] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [x] I've included any necessary tests 
- [ ] I've included developer documentation 
- [x] I've added proper labels to this pull request

2022-01-28 08:36 UTC, RajkiranBagal requested changes

2022-01-28 08:36 UTC, RajkiranBagal commented on classes/class-uagb-post-assets.php
> +			return true;
Because of this, if any sidebar is activated then the regenerate assets will always be triggered & the cache will never load. Need to change this Logic.

2022-02-11 11:09 UTC, RajkiranBagal requested changes

2022-02-11 11:18 UTC, AbhijitNage123 commented on classes/class-uagb-init-blocks.php
> +		$script_dep = array_merge( $script_info['dependencies'], array( 'wp-blocks', 'wp-i18n', 'wp-element', 'wp-components', 'wp-api-fetch', 'uagb-cross-site-cp-helper-js' ) );
We can use both logic to add a dependency. In version comparison, we were discussed this on a call regarding the test case of old/new WordPress version. to be sure the updated conditions look good to me. It works for all user.

2022-02-11 11:31 UTC, AbhijitNage123 commented on classes/class-uagb-post-assets.php
> +	public function widget_area_assets( $content ) {
Updated

2022-02-14 03:56 UTC, RajkiranBagal commented on classes/class-uagb-init-blocks.php
> +		$script_dep = array_merge( $script_info['dependencies'], array( 'wp-blocks', 'wp-i18n', 'wp-element', 'wp-components', 'wp-api-fetch', 'uagb-cross-site-cp-helper-js' ) );
Let's discuss this over a call

2022-02-14 06:03 UTC, RajkiranBagal approved these changes

2022-02-14 06:10 UTC, sandeshjangam commented on src/blocks/social-share-child/edit.js
> +
```suggestion
```

2022-02-14 06:37 UTC, sandeshjangam commented on classes/class-uagb-post-assets.php
> +			$content = get_option( 'widget_block' );
Need to final optimized way to load widget area css

2022-02-14 14:17 UTC, sandeshjangam approved these changes

2022-02-14 14:26 UTC, merged