Updated preview in how to blocks
brainstormforce/ultimate-addons-for-gutenberg pull request #1226
Opened 2022-01-26 07:58 UTC by supriyajjadhav

### Description
if i just deactivate infobox block and then hover How to block from left sidebar then this error fired. 
Issue - https://www.awesomescreenshot.com/image/20889574?key=5f63a936b4fe42d1a045e2d6f7d51c58 

### Types of changes
non-breaking change which fixes an issue

### How has this been tested?

### Checklist:
- [x] My code is tested
- [x] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [x] I've added proper labels to this pull request

2022-01-26 08:12 UTC, RajkiranBagal requested changes

2022-01-26 08:12 UTC, RajkiranBagal commented on src/blocks/how-to/block.js
>  					infoBoxTitle: 'Step 1',
Need to also update attributes?

2022-01-26 10:30 UTC, supriyajjadhav commented on src/blocks/how-to/block.js
>  					infoBoxTitle: 'Step 1',
yes, updated

2022-01-26 10:46 UTC, RajkiranBagal approved these changes

2022-01-27 09:45 UTC, akshaylakh commented
Console error -  [img](https://share.bsf.io/z8ukkNPv)

2022-01-31 08:10 UTC, supriyajjadhav commented
> Console error - [img](https://share.bsf.io/z8ukkNPv)
@akshaylakh Added a separate [card ](https://app.startinfinity.com/b/Mi5zu3VRVzk/5s2b2cSP7a5/20482254-3031-4950-99db-4ca592613ee9?open=true&view=0f0c95d5-d336-4bdd-bb8b-f7cfb212b3d1&t=attributes&redirect=true) for this issue.

2022-01-31 08:41 UTC, sandeshjangam approved these changes

2022-01-31 08:42 UTC, merged