Fix: Info-Box CTA padding issue on front-end
brainstormforce/ultimate-addons-for-gutenberg pull request #1231
Opened 2022-01-31 12:37 UTC by supriyajjadhav

### Description
CTA > Button - Padding is 10 px on front end but in editor no value is displayed - 
https://share.bsf.io/kpu48qWA 

### Types of changes
non-breaking change 

### How has this been tested?

### Checklist:
- [x] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2022-02-01 10:49 UTC, AbhijitNage123 approved these changes

2022-02-01 10:53 UTC, RajkiranBagal approved these changes

2022-02-08 14:13 UTC, sandeshjangam commented on .gitattributes
> +# package-lock.json 	-diff
```suggestion
package-lock.json 	-diff
```

2022-02-08 14:18 UTC, sandeshjangam approved these changes

2022-02-08 14:20 UTC, sandeshjangam commented on includes/blocks/info-box/frontend.css.php
> -		'width'         => $icon_size,
WIll it create a problem for majority of icons

2022-02-09 04:20 UTC, AbhijitNage123 commented on includes/blocks/info-box/frontend.css.php
> -		'width'         => $icon_size,
No, it is not. I tested multiple info-box on-page and with different icons and different sizes, it's working fine.

2022-02-09 04:40 UTC, RajkiranBagal requested changes

2022-02-09 04:40 UTC, RajkiranBagal commented on .github/workflows/code-analysis.yml
WHy this change?

2022-02-09 04:42 UTC, RajkiranBagal requested changes

2022-02-09 04:42 UTC, RajkiranBagal commented on includes/blocks/info-box/frontend.css.php
> -		'width'         => $icon_size,
@AbhijitNage123 Why this change is done? Let's discuss

2022-02-09 04:42 UTC, AbhijitNage123 commented on .github/workflows/code-analysis.yml
We are facing an issue while code analysis action. @sandeshjangam did that change to resolve the action issue.

2022-02-09 04:48 UTC, RajkiranBagal commented on .github/workflows/code-analysis.yml
@AbhijitNage123 Remove this change from this PR & do it in a separate PR with proper description.

2022-02-09 05:08 UTC, RajkiranBagal requested changes

2022-02-09 05:08 UTC, RajkiranBagal commented on .github/workflows/code-analysis.yml
> +        run: npm install
@sandeshjangam Should this be npm ci ?

2022-02-09 05:10 UTC, sandeshjangam approved these changes

2022-02-09 05:11 UTC, sandeshjangam commented on .github/workflows/code-analysis.yml
> +        run: npm install
Yes will update it, it is causing an issue. Will fix it.

2022-02-09 05:12 UTC, sandeshjangam commented on .github/workflows/code-analysis.yml
I Have added it. It wasn't replicated in different PR.

2022-02-09 05:14 UTC, RajkiranBagal approved these changes

2022-02-09 05:15 UTC, merged