Fix Border Component: Console issue when border width does not have any units.
brainstormforce/ultimate-addons-for-gutenberg pull request #1237
Opened 2022-02-01 12:25 UTC by AbhijitNage123

### Description

- https://app.startinfinity.com/b/Mi5zu3VRVzk/3sAgbH1y7qY/43cd55f0-f123-4655-ab16-bfcee24df299?redirect=true&view=6e170ea7-8708-4546-8b82-23d2eebdf694&t=attributes

### Screenshots

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

### How has this been tested?

- Drag and drop any block which has a border e.g. info-box CTA.
- Check style > border settings > Set width option and reset it. and check console issue is visible.
- Now move to the above branch and check issue is resolved or not.

### Checklist:
- [x] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [x] I've included any necessary tests 
- [ ] I've included developer documentation 
- [x] I've added proper labels to this pull request

2022-02-01 12:34 UTC, RajkiranBagal requested changes

2022-02-01 12:34 UTC, RajkiranBagal commented on src/components/range/Range.js
> +		if( cachedValueUpdate?.unit ){
Remove ? here OR do not write if statement & just write `onChangeUnits( cachedValueUpdate?.unit );`

2022-02-01 12:46 UTC, AbhijitNage123 commented on src/components/range/Range.js
> +		if( cachedValueUpdate?.unit ){
Updated the condition

2022-02-09 11:02 UTC, RajkiranBagal approved these changes

2022-02-10 05:03 UTC, sandeshjangam approved these changes

2022-02-10 05:05 UTC, merged