Fix: CSS not applying on responsive devices and multi-buttons settings not visible in editor issue.
brainstormforce/ultimate-addons-for-gutenberg pull request #1243
Opened 2022-02-02 13:35 UTC by AbhijitNage123

### Description

= 1.25.4 =
* Fix: CSS not applying on responsive devices.
* Fix: Multi Buttons - Child setting are not visible in editor.

### Screenshots

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

### How has this been tested?

### Checklist:
- [x] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [x] I've included any necessary tests 
- [ ] I've included developer documentation 
- [x] I've added proper labels to this pull request

2022-02-04 13:16 UTC, RajkiranBagal requested changes

2022-02-04 13:16 UTC, RajkiranBagal commented on classes/class-uagb-block-helper.php
> +						'.wp-block-gallery.has-nested-images.columns-' . $col_count => array(
Purpose of this change in this PR?

2022-02-04 13:16 UTC, RajkiranBagal commented on classes/class-uagb-block-helper.php
> +					'column-count' => '3',
Why is this change in this PR?

2022-02-04 13:16 UTC, RajkiranBagal commented on classes/class-uagb-block-helper.php
> +				),
Why is this change in this PR?

2022-02-04 13:16 UTC, RajkiranBagal commented on classes/class-uagb-init-blocks.php
> +		$script_dep = array_merge( $script_info['dependencies'], array( 'wp-blocks', 'wp-i18n', 'wp-element', 'wp-components', 'wp-api-fetch' ) );
Why is this change in this PR?

2022-02-04 13:16 UTC, RajkiranBagal commented on src/blocks/forms/edit.js
> +			formscope = mainDiv.getElementsByClassName('uagb-forms__outer-wrap')
Why is this change in this PR?

2022-02-04 13:16 UTC, RajkiranBagal commented on src/blocks/table-of-contents/edit.js
> +			mainDiv = iframeEl.find('.is-root-container' ).find('h1, h2, h3, h4, h5, h6' );
Why is this change in this PR?

2022-02-04 13:16 UTC, RajkiranBagal commented on src/blocks/table-of-contents/edit.js
> +				...ownProps.attributes,
use props.attributes

2022-02-04 13:20 UTC, AbhijitNage123 commented on src/blocks/table-of-contents/edit.js
> +			mainDiv = iframeEl.find('.is-root-container' ).find('h1, h2, h3, h4, h5, h6' );
To find out heading tag on responsive devices

2022-02-04 13:22 UTC, AbhijitNage123 commented on src/blocks/forms/edit.js
> +			formscope = mainDiv.getElementsByClassName('uagb-forms__outer-wrap')
Forms get broken when check on a responsive device due to that I made these changes

2022-02-04 13:24 UTC, AbhijitNage123 commented on classes/class-uagb-init-blocks.php
> +		$script_dep = array_merge( $script_info['dependencies'], array( 'wp-blocks', 'wp-i18n', 'wp-element', 'wp-components', 'wp-api-fetch' ) );
Just updated condition as we discuss with widget area PR. load wp-editor dependency only on editor not widget editor

2022-02-04 13:25 UTC, AbhijitNage123 commented on classes/class-uagb-block-helper.php
> +						'.wp-block-gallery.has-nested-images.columns-' . $col_count => array(
Actually, I pull of mater in this branch due to which it shows this changes

2022-02-04 13:30 UTC, RajkiranBagal commented
@AbhijitNage123 All the changes you have done in this PR should be represented in the title, description and each change should have their test cases in the Pr description. Currently the title, description and testcases are only for the one change.

2022-02-04 13:39 UTC, AbhijitNage123 commented
Updated the test case in the PR description.

2022-02-04 13:42 UTC, RajkiranBagal commented
> Updated the test case in the PR description.
Please update PR title and description accordingly

2022-02-07 04:23 UTC, AbhijitNage123 commented on src/blocks/table-of-contents/edit.js
> +				...ownProps.attributes,
Done

2022-02-07 04:54 UTC, AbhijitNage123 commented on classes/class-uagb-block-helper.php
> +					'column-count' => '3',
Pull master due to which its showing this changes

2022-02-07 04:55 UTC, AbhijitNage123 commented on classes/class-uagb-block-helper.php
> +				),
Pull master in dev due to which its showing this

2022-02-07 05:23 UTC, RajkiranBagal approved these changes

2022-02-07 05:45 UTC, sandeshjangam commented on readme.txt
> +* Fix: Multi Buttons - Child setting are not visible in editor.
```suggestion
* Fix: CSS was not applying on responsive devices.
* Fix: Multi Buttons - Child settings were not visible in the editor.
```

2022-02-07 06:04 UTC, sandeshjangam approved these changes

2022-02-07 07:25 UTC, akshaylakh commented
working fine

2022-02-07 10:18 UTC, sandeshjangam commented on readme.txt
> += 1.25.4 =
```suggestion
= 1.25.4 - MONDAY, 7TH FEBRUARY 2022 =
```

2022-08-16 13:46 UTC, merged