Param: Color - Theme icon look off centered and color issue when theme color is choose.
brainstormforce/ultimate-addons-for-gutenberg pull request #1342
Opened 2022-02-25 09:21 UTC by AbhijitNage123

### Description

- https://app.startinfinity.com/b/Mi5zu3VRVzk/M7Dpq9yR4Pe/2af43800-6ae0-4fad-a388-d9dd720bd3b0?redirect=true&view=0ce18087-e6b2-4a91-b54c-c386ce1f811c&t=attributes
- `mix-blend-mode` CSS causing issue to make color orange when Theme blue color is selected.

### Screenshots

- https://d.pr/v/SGcFyI

### Types of changes

- Improvement

### How has this been tested?

- See here - https://share.getcloudapp.com/NQux8nxP

### Checklist:
- [x] My code is tested
- [x] I've included any necessary tests 
- [x] I've added proper labels to this pull request

2022-02-28 09:19 UTC, RajkiranBagal requested changes

2022-02-28 09:19 UTC, RajkiranBagal commented on src/components/color-control/advanced-pop-color-control.js
> +		const parsed_color = result
JS variables should be camelCase

2022-02-28 09:19 UTC, RajkiranBagal commented on src/components/color-control/advanced-pop-color-control.js
> +		}
What if parsedColor is null? Then nothing will return? There should be some default return either black or white.

2022-02-28 09:42 UTC, AbhijitNage123 commented on src/components/color-control/advanced-pop-color-control.js
> +		const parsed_color = result
Updated

2022-02-28 09:42 UTC, AbhijitNage123 commented on src/components/color-control/advanced-pop-color-control.js
> +		}
Done

2022-02-28 09:56 UTC, RajkiranBagal approved these changes

2022-03-01 07:20 UTC, supriyajjadhav approved these changes

2022-03-01 07:38 UTC, merged