Param: Reset Button - Reset enabled always.
brainstormforce/ultimate-addons-for-gutenberg pull request #1344
Opened 2022-02-25 11:28 UTC by AbhijitNage123

### Description

- https://app.startinfinity.com/b/Mi5zu3VRVzk/M7Dpq9yR4Pe/6bfbc06a-6936-481a-93bb-07910a4400ae?redirect=true&view=0ce18087-e6b2-4a91-b54c-c386ce1f811c&t=attributes

### Screenshots

### Types of changes

- Improvement

### How has this been tested?

- See here - https://share.getcloudapp.com/04uLpZ6e

### Checklist:
- [x] My code is tested
- [x] I've included any necessary tests 
- [x] I've added proper labels to this pull request

2022-02-25 11:47 UTC, RajkiranBagal requested changes

2022-02-25 11:47 UTC, RajkiranBagal commented on src/components/color-control/advanced-pop-color-control.js
> +					disabled={ false }
If disabled is always false then we can entirely remove this. Update this change everywhere

2022-02-25 12:05 UTC, AbhijitNage123 commented on src/components/color-control/advanced-pop-color-control.js
> +					disabled={ false }
Done

2022-02-25 12:33 UTC, RajkiranBagal approved these changes

2022-03-01 07:20 UTC, supriyajjadhav approved these changes

2022-03-01 07:42 UTC, merged