Fix: Console issue in editor for review drag and drop and when hover over a forms preview.
brainstormforce/ultimate-addons-for-gutenberg pull request #1346
Opened 2022-03-01 05:55 UTC by AbhijitNage123

### Description

- https://app.startinfinity.com/b/Mi5zu3VRVzk/M7Dpq9yR4Pe/ef5763b9-bef1-4a86-ba4b-6615a57973e7?redirect=true&view=0ce18087-e6b2-4a91-b54c-c386ce1f811c&t=attributes

### Types of changes

- https://share.getcloudapp.com/Apux7xD4

### How has this been tested?

- See here - https://share.getcloudapp.com/Apux7xD4

### Checklist:
- [x] My code is tested
- [x] I've included any necessary tests 
- [x] I've added proper labels to this pull request

2022-03-03 13:15 UTC, RajkiranBagal requested changes

2022-03-03 13:15 UTC, RajkiranBagal commented on src/blocks/forms/edit.js
> +		if ( formscope && null !== formscope[ 0 ] && undefined !== formscope[ 0 ] ) {
Instead of checking `null !== formscope[ 0 ] && undefined !== formscope[ 0 ]`  you can just check `&& formscope[ 0 ]`

2022-03-08 11:25 UTC, RajkiranBagal approved these changes

2022-03-08 11:26 UTC, supriyajjadhav approved these changes

2022-03-08 11:26 UTC, merged