Fix: Post layout - Content padding 0 issue, Line height in editor and starting offset option.
brainstormforce/ultimate-addons-for-gutenberg pull request #1351
Opened 2022-03-03 12:18 UTC by AbhijitNage123

### Description

- Link - https://app.startinfinity.com/b/Mi5zu3VRVzk/M7Dpq9yR4Pe/120ab759-bb2c-40b2-a5f4-942908090d72?redirect=true&view=0ce18087-e6b2-4a91-b54c-c386ce1f811c&t=attributes

### Screenshots

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

### How has this been tested?

- Offset Starting Post, should add this option ( Done )
- Content padding setting is not saving when 0 is the value( Done - https://share.getcloudapp.com/4guKw2qw )
- Title font line-height does not look right in the backend. ( Done - https://share.getcloudapp.com/E0ug5rej )

### Checklist:
- [x] My code is tested
- [x] I've included any necessary tests 
- [x] I've added proper labels to this pull request

2022-03-03 13:02 UTC, RajkiranBagal requested changes

2022-03-03 13:16 UTC, AbhijitNage123 commented on src/blocks/post/post-carousel/edit.js
> +			if ( undefined === paddingTopMobile ) {
Added test case for in description for content padding.

2022-03-03 13:20 UTC, RajkiranBagal approved these changes

2022-03-04 05:40 UTC, RajkiranBagal approved these changes

2022-03-04 05:40 UTC, merged