New - Counter Block
brainstormforce/ultimate-addons-for-gutenberg pull request #1365
Opened 2022-03-10 05:07 UTC by imrantushar

### Description
New Counter Block. This block is only responsible for the count number. 

### Screenshots

### Types of changes
New Features/Block

### How has this been tested?
This Block Have 3 Layout. 
- Number Layout - Only Count Number
- Circle Layout - Count Number with Circle Progress Bar 
- Bars Layout - Count Number with Bars Progress Bar
check all start, end, and total numbers very carefully with the proper percentage working or not

### Checklist:
- [ ] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2022-10-04 02:57 UTC, RajkiranBagal approved these changes

2022-10-11 04:51 UTC, bsf-zanev commented on assets/js/uagb-counter.js
> +				// entry.isIntersecting && ! el.classList.contains( 'is-visible' )
@aapatre - Is this comment required in the current stage of development?

2022-10-11 04:56 UTC, bsf-zanev approved these changes
Updates reviewed and approved.

2022-10-11 04:56 UTC, aapatre commented on assets/js/uagb-counter.js
> +				// entry.isIntersecting && ! el.classList.contains( 'is-visible' )
Nope, it's old comment
Will delete it

2022-10-12 05:22 UTC, aapatre commented on assets/js/uagb-counter.js
> +				// entry.isIntersecting && ! el.classList.contains( 'is-visible' )
Deleted the commented code

2022-10-12 06:02 UTC, bsf-zanev approved these changes
All changes, including the update to Number Control, have been verified.

2022-10-12 11:26 UTC, bsf-zanev approved these changes
Updated code reviewed.

2022-10-12 11:35 UTC, aapatre commented on src/blocks/counter/settings.js
> +						{/* {layout !== 'number' && boxShadowSettings} */}
Yes, it's required for box shadow

2022-10-26 00:57 UTC, bsf-zanev commented on includes/blocks/counter/frontend.js.php
> + * @package UAG_PRO
Package and Version need to be updated.

2022-10-26 01:00 UTC, bsf-zanev requested changes
All New Updates have been verified, but the Package Name and Version on some PHP Files are incorrect.

Since @aapatre is unavailable today, I shall add the necessary commit.

2022-10-26 01:15 UTC, bsf-zanev commented on includes/blocks/counter/frontend.js.php
> + * @package UAG_PRO
This has been updated in [commit 024ee71](https://github.com/brainstormforce/ultimate-addons-for-gutenberg/pull/1365/commits/024ee713403b65aa91ca1e491e778fe272048f98)

2022-10-26 01:15 UTC, bsf-zanev approved these changes
All New Updates Verified and Approved.

2022-11-03 05:03 UTC, bsf-zanev approved these changes
All updates Verified.

2022-11-11 11:24 UTC, RajkiranBagal approved these changes

2022-11-11 11:26 UTC, merged