Improvement: Added new attribute to store phone default country code in Forms
brainstormforce/ultimate-addons-for-gutenberg pull request #1370
Opened 2022-03-15 11:47 UTC by supriyajjadhav

### Description
Added new attribute to store phone default country code in Forms

### Screenshots

### Types of changes

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2022-03-16 04:04 UTC, AbhijitNage123 approved these changes

2022-03-16 05:14 UTC, RajkiranBagal requested changes

2022-03-16 05:14 UTC, RajkiranBagal commented on src/blocks/forms/child-blocks/phone/save.js
> +					<option value={ o.props.value } key={ index } selected>
Instead of adding this whole logic, just add value to the <select> element

2022-03-16 10:54 UTC, supriyajjadhav commented on src/blocks/forms/child-blocks/phone/save.js
> +					<option value={ o.props.value } key={ index } selected>
Updated logic

2022-03-16 11:32 UTC, RajkiranBagal approved these changes

2022-03-21 10:26 UTC, RajkiranBagal approved these changes

2022-03-21 10:31 UTC, merged