Improvement: Post Layout - Added show taxonomy above title and normal/highlighted taxonomy styling option in grid, masonry and carousel.
brainstormforce/ultimate-addons-for-gutenberg pull request #1375
Opened 2022-03-17 09:19 UTC by AbhijitNage123

### Description

- https://app.startinfinity.com/b/Mi5zu3VRVzk/M7Dpq9yR4Pe/120ab759-bb2c-40b2-a5f4-942908090d72?redirect=true&view=0ce18087-e6b2-4a91-b54c-c386ce1f811c&t=attributes

### Screenshots

### Types of changes

- New feature (non-breaking change which adds functionality)

### How has this been tested?

- Drag and drop grid, masonry, and carousel.
- Go to the content > Enable show taxonomy you will see 2 options Show taxonomy above title and when enabling this you will get again 2 options hide taxonomy icon and taxonomy style normal/highlighted.
- If you set taxonomy style highlighted then the styling option for highlighted layout comes in meta like this - https://share.getcloudapp.com/xQuq0KwX

### Checklist:
- [x] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [x] I've included any necessary tests 
- [ ] I've included developer documentation 
- [x] I've added proper labels to this pull request

2022-03-17 10:36 UTC, RajkiranBagal requested changes

2022-03-17 10:36 UTC, RajkiranBagal commented on blocks-config/post/class-uagb-post.php
> +				<?php echo $attributes['hideTaxonomyIcon'] ? '' : '<span class="dashicons-tag dashicons"></span>'; ?>
verify this condition

2022-03-17 10:36 UTC, RajkiranBagal commented on blocks-config/post/class-uagb-post.php
> +							! $attributes['displayPostTaxonomyAboveTitle'] ? $this->render_meta_taxonomy( $attributes ) : '';
this will cause backward issues, please confirm

2022-03-17 11:56 UTC, AbhijitNage123 commented on blocks-config/post/class-uagb-post.php
> +				<?php echo $attributes['hideTaxonomyIcon'] ? '' : '<span class="dashicons-tag dashicons"></span>'; ?>
Verified. Above condition if hideTaxonomyIcon is false then it will display the dash icon else it will echo the empty string.

2022-03-17 12:06 UTC, AbhijitNage123 commented on blocks-config/post/class-uagb-post.php
> +							! $attributes['displayPostTaxonomyAboveTitle'] ? $this->render_meta_taxonomy( $attributes ) : '';
There are 2 conditions one is if displayPostTaxonomyAboveTitle is true then display posts above the title and hide from meta. And another one is if displayPostTaxonomyAboveTitle is false then display taxonomy inside meta. By default displayPostTaxonomyAboveTitle is false so it does not cause the backward issue

2022-04-05 06:25 UTC, RajkiranBagal approved these changes

2022-04-07 09:12 UTC, merged