Fix : Responsive conditions appear at the inappropriate position in other blocks
brainstormforce/ultimate-addons-for-gutenberg pull request #1405
Opened 2022-03-31 05:07 UTC by AbhijitNage123

### Description

- https://app.startinfinity.com/b/Mi5zu3VRVzk/M7Dpq9yR4Pe/999e91fd-4a41-4ad0-ab8e-0e33a57b6554?redirect=true&view=6d3bcc3d-b047-4739-8e05-d9621e9f9445&t=attributes

### Screenshots

- https://share.getcloudapp.com/7KuQPArP

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

### How has this been tested?

- Drag and drop core/gallery block add an image.
- And check our extension tab should be visible at last above the advanced tab.
- Check with other blocks too.

### Checklist:
- [x] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [x] I've included any necessary tests 
- [ ] I've included developer documentation 
- [x] I've added proper labels to this pull request

2022-03-31 13:00 UTC, RajkiranBagal requested changes

2022-03-31 13:00 UTC, RajkiranBagal commented on src/blocks/extensions/condition-block/index.js
> +				let DisplayPanelBody = document.querySelector( '.uag-advance-panel-body-display' );
use camelCases for JS variables

2022-03-31 13:07 UTC, AbhijitNage123 commented on src/blocks/extensions/condition-block/index.js
> +				let DisplayPanelBody = document.querySelector( '.uag-advance-panel-body-display' );
Done

2022-04-01 09:26 UTC, RajkiranBagal requested changes

2022-04-01 09:26 UTC, RajkiranBagal commented on src/blocks/extensions/condition-block/index.js
> +			childBlocks = getSelectedBlock().innerBlocks;
line 175 -> 178 can be converted to:
`let childBlocks = getSelectedBlock()?.innerBlocks;`

2022-04-01 09:26 UTC, RajkiranBagal commented on src/blocks/extensions/condition-block/index.js
> +						displayPanel = displayPanel ? displayPanel : '';
displayPanel is already checked above, so this condition is meaningless

2022-04-01 09:26 UTC, RajkiranBagal commented on src/blocks/extensions/condition-block/index.js
> +						if( tabsParent.lastChild.className.includes( 'components-panel__body is-opened' ) ){
Why this condition is needed?

2022-04-01 12:52 UTC, AbhijitNage123 commented on src/blocks/extensions/condition-block/index.js
> +						if( tabsParent.lastChild.className.includes( 'components-panel__body is-opened' ) ){
@RajkiranBagal tabsParent returning a masonry panel body so we need to check if there any core `'components-panel__body is-opened'` is present or not. See the screencast here - https://share.getcloudapp.com/d5u9Anv7

2022-04-01 12:52 UTC, AbhijitNage123 commented on src/blocks/extensions/condition-block/index.js
> +						displayPanel = displayPanel ? displayPanel : '';
Resolved.

2022-04-01 12:52 UTC, AbhijitNage123 commented on src/blocks/extensions/condition-block/index.js
> +			childBlocks = getSelectedBlock().innerBlocks;
Resolved.

2022-04-04 12:29 UTC, RajkiranBagal approved these changes

2022-04-06 09:53 UTC, merged