Improvement: Added multiple new settings in multi button block
brainstormforce/ultimate-addons-for-gutenberg pull request #1432
Opened 2022-04-08 11:04 UTC by supriyajjadhav

### Description
Added multiple new settings in multi button block

### Screenshots

### Types of changes
breaking change which adds functionality

### How has this been tested?

### Checklist:
- [x] My code is tested
- [x] My code follows accessibility standards 
- [x] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [x] I've added proper labels to this pull request

2022-04-12 13:44 UTC, RajkiranBagal requested changes

2022-04-12 13:44 UTC, RajkiranBagal commented on src/components/border/index.js
> +		{ !title && (
We can use disabledBorderTitle variable directly here instead of creating a new variable

2022-04-12 13:49 UTC, supriyajjadhav commented on src/components/border/index.js
> +		{ !title && (
Removed variable.

2022-04-20 07:50 UTC, RajkiranBagal approved these changes

2022-04-20 07:51 UTC, merged