New - Image block
brainstormforce/ultimate-addons-for-gutenberg pull request #1440
Opened 2022-04-13 07:02 UTC by imrantushar

### Description
New Block for an image. This Block is only for showcasing images with some necessary info(title, caption)

### Screenshots

### Types of changes
New Image Block Added
New SelectControl Components Added

### How has this been tested?
This is just another simple block. Used to showcase just image. Here is some test case below

Multi-Type Image Upload (direct upload, default uploader, upload from URL)
Check all toolbar settings like alignment, duotone filter, cropping, etc
Check all general & styles settings
Default and Custom mask settings with mask position

### Checklist:
- [ ] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2022-04-13 09:22 UTC, RajkiranBagal requested changes

2022-04-13 09:22 UTC, RajkiranBagal commented on includes/blocks/image/frontend.css.php
> +UAGB_Block_JS::blocks_advanced_heading_gfont( $attr );
Do we need this here?

2022-04-14 11:56 UTC, imrantushar commented on includes/blocks/image/frontend.css.php
> +UAGB_Block_JS::blocks_advanced_heading_gfont( $attr );
@RajkiranBagal yes we need it but it is the wrong method name. I am fixing that

2022-04-14 11:59 UTC, RajkiranBagal approved these changes

2022-04-14 13:20 UTC, AbhijitNage123 requested changes

2022-04-14 13:20 UTC, AbhijitNage123 commented on blocks-config/image/class-uagb-image.php
> +		 * @since 1.18.1
since x.x.x

2022-04-14 13:20 UTC, AbhijitNage123 commented on blocks-config/image/class-uagb-image.php
> +		 * @since 0.0.1
since x.x.x

2022-04-14 13:20 UTC, AbhijitNage123 commented on src/blocks/image/block.js
> +	icon: UAGB_Block_Icons.post_masonry,
We need an image Icon here. Get in touch with the designer

2022-04-14 13:20 UTC, AbhijitNage123 commented on src/blocks/image/edit.js
> +	}, [ props ] );
I think we need to pass deviceType too. So CSS style tag will generate on responsive devices. Please check once

2022-04-14 13:26 UTC, AbhijitNage123 requested changes

2022-04-14 13:26 UTC, AbhijitNage123 commented on blocks-config/image/class-uagb-image.php
> +		 * Registers the `core/latest-posts` block on server.
* Register the `image` block on the server.

2022-04-14 13:37 UTC, imrantushar commented on blocks-config/image/class-uagb-image.php
> +		 * @since 1.18.1
Fixed

2022-04-14 13:38 UTC, imrantushar commented on blocks-config/image/class-uagb-image.php
> +		 * @since 0.0.1
Fixed

2022-04-14 13:39 UTC, imrantushar commented on src/blocks/image/block.js
> +	icon: UAGB_Block_Icons.post_masonry,
Already talked with designers and waiting...

2022-04-14 14:11 UTC, imrantushar commented on blocks-config/image/class-uagb-image.php
> +		 * Registers the `core/latest-posts` block on server.
Updated comment

2022-04-15 04:25 UTC, AbhijitNage123 approved these changes

2022-04-20 07:39 UTC, merged