Fix: Info-Box - Acceptance Testing 2.
brainstormforce/ultimate-addons-for-gutenberg pull request #1454
Opened 2022-04-20 12:58 UTC by AbhijitNage123

### Description

- https://app.startinfinity.com/b/Mi5zu3VRVzk/M7Dpq9yR4Pe/4a70e27c-773e-4536-992c-78f25fc2fada?redirect=true&view=0ce18087-e6b2-4a91-b54c-c386ce1f811c&t=attributes

### Screenshots

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

### How has this been tested?

- Backword user 
  - Drag and drop info-box in master made some changes in padding/margin for Icon, Image, Button, Bottom spacing.
  - Switch to add info-box-atr2 branch & check the front as well as the editor. ( It does not break anything ).
- New User
  - Drag and drop block.
  - Check issue and improvement suggested by the tester is fixed or not.

### Checklist:
- [x] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [x] I've included any necessary tests 
- [ ] I've included developer documentation 
- [x] I've added proper labels to this pull request

2022-04-20 13:34 UTC, RajkiranBagal requested changes

2022-04-20 13:34 UTC, RajkiranBagal commented on src/blocks/info-box/attributes.js
> +	showIcon: {
Add Copy Paste Styles support here

2022-04-20 13:56 UTC, AbhijitNage123 commented on src/blocks/info-box/attributes.js
> +	showIcon: {
We have not added any copy/paste style support for setting like Show Title, Show Desc & Show Prefix. Do we really need that support here? Copy Paste is only for styling.

2022-04-21 07:23 UTC, RajkiranBagal approved these changes

2022-04-22 10:44 UTC, merged