Improvement: Remove Email field from setting and updated logic to submit the form without ID.
brainstormforce/ultimate-addons-for-gutenberg pull request #1513
Opened 2022-05-04 14:12 UTC by supriyajjadhav

### Description
https://app.startinfinity.com/b/Mi5zu3VRVzk/M7Dpq9yR4Pe/b8ead1f3-99a0-4b9a-8ed1-da82a6d762b0?view=9ffa5ed5-3613-4de6-a585-375ce1031729&t=attributes

### Types of changes
non-breaking change which adds functionality

### How has this been tested?

### Checklist:
- [x] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [x] I've added proper labels to this pull request

2022-05-05 10:57 UTC, RajkiranBagal requested changes

2022-05-05 10:57 UTC, RajkiranBagal commented on src/blocks/forms/settings.js
> +						'P.S. Note that You must enter Email ID to receive Form data. If you kept blank then Form will not be submitted. ',
```suggestion
						'Note: It is recommended to enter an email id in order to receive the data submitted through a form, else you will not receive any data.',
```

2022-05-05 12:17 UTC, supriyajjadhav commented on src/blocks/forms/settings.js
> +						'P.S. Note that You must enter Email ID to receive Form data. If you kept blank then Form will not be submitted. ',
Updated

2022-05-05 13:21 UTC, RajkiranBagal approved these changes

2022-05-12 10:24 UTC, RajkiranBagal approved these changes

2022-05-12 10:32 UTC, merged