Container color settings
brainstormforce/ultimate-addons-for-gutenberg pull request #1533
Opened 2022-05-12 05:59 UTC by aapatre

### Description
Added color settings in styling tab of Container

### Screenshots
![image](https://user-images.githubusercontent.com/20199688/168002009-996537d3-0b92-4704-a7a4-29d584b4b29d.png)

### Types of changes
New feature (non-breaking change which adds functionality) - Added new settings section for Container Block

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2022-05-16 04:42 UTC, RajkiranBagal requested changes

2022-05-16 04:42 UTC, RajkiranBagal commented on src/blocks/container/render.js
> +				'uagb-container'
Why do we need to add a class here?

2022-05-16 04:42 UTC, RajkiranBagal commented on src/blocks/container/save.js
> +				'uagb-container',
Why do we need to add a class here?

2022-05-16 04:46 UTC, supriyajjadhav commented on src/blocks/container/attributes.js
> +			styleType: 'text-color'
Instead of text-color, we can use 'desc-color'

2022-05-16 04:51 UTC, supriyajjadhav commented on src/blocks/container/attributes.js
> +			styleType: 'link-color'
Replace this with 'btn-color'.

2022-05-16 04:51 UTC, supriyajjadhav commented on src/blocks/container/attributes.js
> +			styleType: 'link-hover-color'
btn-hover-color

2022-05-16 06:21 UTC, aapatre commented on src/blocks/container/render.js
> +				'uagb-container'
I wanted to target the parent wrapper and also add a parent class as per BEM comvention:
![image](https://user-images.githubusercontent.com/20199688/168530782-8f9dd09a-ea5a-41c7-a71f-4d44a8cf22e0.png)

Please let me know if I should `uagb-block-${ block_id }` to target the parent wrapper in place of the current class?

cc: @RajkiranBagal

2022-05-16 06:27 UTC, RajkiranBagal commented on src/blocks/container/render.js
> +				'uagb-container'
Yes, avoid adding new classes.

2022-05-16 07:32 UTC, aapatre commented on src/blocks/container/render.js
> +				'uagb-container'
Removed class

2022-05-16 08:34 UTC, RajkiranBagal approved these changes

2022-05-16 08:49 UTC, supriyajjadhav commented on src/blocks/container/save.js
> +				isBlockRootParent ? 'uagb-is-root-container' : '',
Instead of writing the same thing twice. We can merge  _uagb-is-root-container_ class in the above condition.

2022-05-16 10:46 UTC, supriyajjadhav commented on src/blocks/container/save.js
> +				isBlockRootParent ? contentWidth + 'uagb-is-root-container' : '',
Please check - https://share.getcloudapp.com/eDu5mPN1

2022-05-16 10:48 UTC, supriyajjadhav commented on src/blocks/container/save.js
> +				isBlockRootParent ? contentWidth + 'uagb-is-root-container' : '',
`uagb-is-root-container ${contentWidth}`

2022-05-18 10:42 UTC, RajkiranBagal approved these changes

2022-05-18 11:02 UTC, merged