SPCTR-595 - Added Responsive
brainstormforce/ultimate-addons-for-gutenberg pull request #1549
Opened 2022-05-16 13:35 UTC by aapatre

### Description
- Added responsive size select control in settings
- Fixed border radius issue in responsive preview (when we switch to tablet/mobile preview in Astra theme, the button has a border-radius of 9999px)

### Screenshots

### Types of changes
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)

### How has this been tested?
- Manual testing

### Checklist:
- [ ] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2022-05-16 13:51 UTC, aapatre commented
The changes are tested on my local system and are functional.
But since the responsive sizing is based on the static styling from style.scss (which isn't being loaded in the the tablet/mobile preview), the editor preview for sizing doesn't work (but works fine on frontend).

cc: @RajkiranBagal @supriyajjadhav

2022-05-16 14:19 UTC, RajkiranBagal commented
> The changes are tested on my local system and are functional. But since the responsive sizing is based on the static styling from style.scss (which isn't being loaded in the the tablet/mobile preview), the editor preview for sizing doesn't work (but works fine on frontend).
> 
> cc: @RajkiranBagal @supriyajjadhav

@aapatre Please pull latest next-release & check. The iframe issue for static issue loading is resolved.

2022-05-16 15:08 UTC, aapatre commented
iFrame fix is working
Thanks @RajkiranBagal 
cc: @supriyajjadhav

2022-05-17 05:23 UTC, RajkiranBagal requested changes

2022-05-17 05:23 UTC, RajkiranBagal commented on classes/class-uagb-block-helper.php
> -				'padding-top'    => UAGB_Helper::get_css_value( $attr['topMobilePadding'], $attr['mobilePaddingUnit'] ),
@aapatre We should avoid using !important wherever possible. IMO We can avoid using here too.

2022-05-17 05:24 UTC, RajkiranBagal commented
@aapatre Please list down all the possible test cases for the PR you have created in the Task.

2022-05-17 07:19 UTC, supriyajjadhav commented on includes/blocks/buttons-child/attributes.php
> +	'borderRadius'           => 0,
Undo this change. We are applying the theme button default styling after drag drop. If we add border-radius then it will conflict with theme button styling.

2022-05-23 10:19 UTC, RajkiranBagal approved these changes

2022-05-23 10:21 UTC, merged