SPCTR-803 : Fix: price list css
brainstormforce/ultimate-addons-for-gutenberg pull request #1564
Opened 2022-05-19 08:35 UTC by jamyrbsf

### Description
All issues mention for price list in Spectra Acceptance Testing R:3

### Screenshots

### Types of changes

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2022-05-20 07:29 UTC, bsf-zanev approved these changes
All Updated Code Reviewed and Approved

2022-05-23 10:35 UTC, RajkiranBagal requested changes

2022-05-23 10:35 UTC, RajkiranBagal commented on src/blocks/price-list/style.scss
> +			// 	flex-direction: column;
Ig this code is not needed we can remove it. Confirm it once.

2022-05-23 10:35 UTC, RajkiranBagal commented on src/blocks/price-list/editor.lazy.scss
> +			padding-left: unset;
Why do we need this CSS? Please confirm it once.

2022-05-24 13:01 UTC, jamyrbsf commented on src/blocks/price-list/style.scss
> +			// 	flex-direction: column;
done

2022-05-24 13:03 UTC, jamyrbsf commented on src/blocks/price-list/editor.lazy.scss
> +			padding-left: unset;
as this code is not organized i have added this as a extra step

2022-05-24 13:07 UTC, RajkiranBagal approved these changes

2022-05-25 04:37 UTC, merged