SPCTR-804 : Added Responsive Stacking, Bug fixes
brainstormforce/ultimate-addons-for-gutenberg pull request #1569
Opened 2022-05-19 12:31 UTC by aapatre

### Description
- Added responsive stacking feature (upgraded previous stacking multi-button to responsive)
- Fixed vertical alignment of stars and title
- Made changes and new additions to alignment code since `display: flex` is now used for some elements and there were breaking changes that needed to be fixed

### Issue References
- [JIRA](https://brainstormforce.atlassian.net/browse/SPCTR-804)
- [R3 Docs](https://docs.google.com/document/d/1jGAQGdVevCytKOb6pihU1ZPURFFKs0PanrOG97Xxj-o/edit#heading=h.eo8f2i54l70p)

### Types of changes
- Bug fix (non-breaking change which fixes an issue)
- New feature (upgraded Stacking to Responsive Stacking)

### How has this been tested?

### Checklist:
- [x] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [x] I've added proper labels to this pull request

2022-05-19 13:08 UTC, bsf-zanev approved these changes
All Updated Code Reviewed and Approved.

2022-05-23 07:24 UTC, RajkiranBagal requested changes

2022-05-23 09:36 UTC, aapatre commented on includes/blocks/star-rating/frontend.css.php
> +	 *
Done

2022-05-23 10:40 UTC, RajkiranBagal requested changes

2022-05-23 10:40 UTC, RajkiranBagal commented on classes/class-uagb-block-helper.php
> +		 *
add a since tag.

2022-05-23 10:40 UTC, RajkiranBagal commented on classes/class-uagb-block-helper.php
> +			switch ( $textAlign ) {
php variables should always be `snake_case`

2022-05-23 10:40 UTC, RajkiranBagal commented on classes/class-uagb-block-helper.php
> +		public static function flex_alignment( $textAlign ) {
add meaningful function name so anyone can understand what it does.

2022-05-23 13:36 UTC, RajkiranBagal approved these changes

2022-05-24 04:42 UTC, aapatre commented
Ensured that all the comments are resolved and all the requested changes are made :+1:

2022-05-24 04:56 UTC, RajkiranBagal approved these changes

2022-05-24 05:00 UTC, RajkiranBagal approved these changes

2022-05-24 05:00 UTC, merged