SPCTR-668 - New: Responsive Border Components
brainstormforce/ultimate-addons-for-gutenberg pull request #1577
Opened 2022-05-20 13:54 UTC by imrantushar

### Description
Added Border Responsive Components, used this component inside **Heading Block**

### Screenshots

### Types of changes
New Features

### How has this been tested?
Goto Heading Block Highlight style settings => border panel

### Checklist:
- [ ] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2022-05-26 06:38 UTC, supriyajjadhav commented on src/blocks/wp-search/attributes.js
> +	},
Please add copy-paste object

2022-06-03 11:10 UTC, supriyajjadhav approved these changes

2022-06-03 11:11 UTC, RajkiranBagal requested changes

2022-06-03 11:11 UTC, RajkiranBagal commented on classes/class-uagb-block-helper.php
> +			$borderCSS       = self::uag_generate_border_css( $attr, 'btn' );
PHP variables should be `snake_case`

2022-06-03 11:11 UTC, RajkiranBagal commented on blocks-config/post/class-uagb-post.php
> +			$paginationMasonryBorderAttribute = UAGB_Block_Helper::uag_generate_border_attribute( 'paginationMasonry' );
PHP variables should be `snake_case`

2022-06-03 11:11 UTC, RajkiranBagal commented on blocks-config/post/class-uagb-post.php
> +			$btnBorderAttribute = UAGB_Block_Helper::uag_generate_border_attribute( 'btn' );
PHP variables should be `snake_case`

2022-06-03 11:11 UTC, RajkiranBagal commented on classes/class-uagb-block-helper.php
> +		 *
Add since x.x.x tag for this function description

2022-06-03 11:11 UTC, RajkiranBagal commented on classes/class-uagb-block-helper.php
> +		 * @param  string $prefix Attribuate prefix .
Add since x.x.x tag

2022-06-03 11:11 UTC, RajkiranBagal commented on classes/class-uagb-block-helper.php
> +		 * @param  string $border_radius Border Radius.
Add since x.x.x tag

2022-06-03 11:11 UTC, RajkiranBagal commented on includes/blocks/advanced-heading/attributes.php
> +$highLightBorderAttribute = UAGB_Block_Helper::uag_generate_border_attribute( 'highLight' );
PHP variables should be `snake_case` Do this change in all file where needed

2022-06-03 11:12 UTC, imrantushar commented on blocks-config/post/class-uagb-post.php
> +				'btnBorderHColor'               => array(
@supriyajjadhav please remove **btnBorderHColor** attribute, our function automatically generating it.

2022-06-03 11:20 UTC, imrantushar commented on includes/blocks/container/frontend.css.php
> +	( isset( $attr['borderRadius'] ) ? $attr['borderRadius'] : '' ),
@supriyajjadhav Don't needed extra array isset checking

2022-06-03 11:24 UTC, imrantushar commented on includes/blocks/info-box/attributes.php
> +	...$ctaBorderAttribute,
@supriyajjadhav I think PHP old version will be not supported this operator, please cross check it or use array_merge.

2022-06-03 11:27 UTC, imrantushar commented on includes/blocks/post-masonry/attributes.php
> +	'btnBorderHColor'                   => '',
@supriyajjadhav Please remove this attribute, our function automatically generating it.

2022-06-03 11:30 UTC, imrantushar commented on includes/blocks/testimonial/attributes.php
> +	'btnBorderHoverColor'     => '',
@supriyajjadhav it is wrong attribute, remove it. our functional automatically generate **btnBorderHColor** attribute. cross check it inside frontend.css.php and styling.js

2022-06-03 11:35 UTC, imrantushar commented on src/blocks/cf7-designer/settings.js
> +				prefix={'button'}
@supriyajjadhav if possible use **btn** prefix For cross copy/paste style

2022-06-06 09:10 UTC, RajkiranBagal approved these changes

2022-06-06 09:38 UTC, imrantushar commented on includes/blocks/post-masonry/attributes.php
> +	'btnBorderHColor'                   => '',
@supriyajjadhav are you remove `btnBorderHColor` attributes?

2022-06-23 10:14 UTC, supriyajjadhav approved these changes

2022-06-23 13:42 UTC, merged