SPCTR-837 : Content Timeline Block - Fix default text alignment for right-oriented content timeline block
brainstormforce/ultimate-addons-for-gutenberg pull request #1581
Opened 2022-05-23 12:07 UTC by aapatre

### Description
- [JIRA](https://brainstormforce.atlassian.net/browse/SPCTR-837?atlOrigin=eyJpIjoiNjg3OGY4NmE4ZDUwNDYzYWIxZWRiNzYxYTFjMGVlZWEiLCJwIjoiaiJ9)

### Types of changes
Bug fix (non-breaking change which fixes an issue)

### Checklist:
- [x] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [x] I've added proper labels to this pull request

2022-05-24 05:06 UTC, RajkiranBagal requested changes

2022-05-24 05:06 UTC, RajkiranBagal commented on src/blocks/timeline/style.scss
> +			text-align: right;
@aapatre The Parent class of this CSS is also the `uagb-timeline__left` class. So I guess it will also align right in case of the left timeline. Can you confirm?

2022-05-24 05:19 UTC, aapatre commented on src/blocks/timeline/style.scss
> +			text-align: right;
Confirmed, it's working fine :+1: 
`.uagb-timeline__left` stands for the child-block which would appear on the left if the parent block's orientation is set to center

Refer the image below:
![image](https://user-images.githubusercontent.com/20199688/169954428-99d0831d-f6cf-428d-877c-d47bdf6d7bbd.png)

Left orientation:
![image](https://user-images.githubusercontent.com/20199688/169954506-101f8467-3030-4b6a-8d88-71b4e8849fdc.png)

Right orientation:
![image](https://user-images.githubusercontent.com/20199688/169954599-3ff7bda0-f664-44df-a3cf-4102c3aa471c.png)

Works as intended in frontend too

2022-05-24 06:14 UTC, RajkiranBagal approved these changes

2022-05-24 12:57 UTC, RajkiranBagal approved these changes

2022-05-26 06:52 UTC, aapatre commented
As per the discussion on the [JIRA thread](https://brainstormforce.atlassian.net/browse/SPCTR-837), also added fixes for the Post-Timeline block (since it's a related block).

2022-05-26 07:00 UTC, RajkiranBagal approved these changes

2022-05-27 09:30 UTC, RajkiranBagal approved these changes

2022-05-27 09:30 UTC, merged