SPCTR-864 Container Block: Responsive Spacing UNITS
brainstormforce/ultimate-addons-for-gutenberg pull request #1613
Opened 2022-05-27 09:18 UTC by aapatre

### Description
- [JIRA](https://brainstormforce.atlassian.net/browse/SPCTR-864): In container block, for Desktop if we add padding in px and in Tablet if we add padding in EM, then the container is overwriting the padding settings of desktop in EM.
- Initially only one unit (px/vw/percentage) was shared across all devices
- Hence, added responsive units for all Spacing section controls (Margin, Padding, Row Gap, Column Gap)

### Types of changes
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)

### Checklist:
- [x] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [x] I've added proper labels to this pull request

2022-05-27 09:36 UTC, RajkiranBagal requested changes

2022-05-27 09:36 UTC, RajkiranBagal commented on src/blocks/container/settings.js
> +					// 	label: 'columnGapType',
If this code is not needed please remove it.

2022-05-27 09:45 UTC, aapatre commented on src/blocks/container/settings.js
> +					// 	label: 'columnGapType',
Removed

2022-05-28 12:14 UTC, RajkiranBagal approved these changes

2022-05-28 12:20 UTC, merged