SPCTR-905-fixed-preset-fixed-frontend-string-error
brainstormforce/ultimate-addons-for-gutenberg pull request #1631
Opened 2022-06-01 09:19 UTC by jamyrbsf

### Description
https://brainstormforce.atlassian.net/browse/SPCTR-905

### Screenshots

### Types of changes
Fixed preset height issue
Fixed frontend error as an int was getting set to a string

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2022-06-02 05:09 UTC, RajkiranBagal approved these changes

2022-06-07 04:07 UTC, RajkiranBagal requested changes

2022-06-07 04:07 UTC, RajkiranBagal commented on includes/blocks/call-to-action/frontend.css.php
> +$contentWidth     = is_int( $attr['contentWidth'] ) ? $attr['contentWidth'] : 70;
PHP variables should always be `snake_case`

2022-06-07 06:32 UTC, jamyrbsf commented on includes/blocks/call-to-action/frontend.css.php
> +$contentWidth     = is_int( $attr['contentWidth'] ) ? $attr['contentWidth'] : 70;
Converted all camel case to snake_case

2022-06-07 07:08 UTC, RajkiranBagal approved these changes

2022-06-09 06:54 UTC, RajkiranBagal approved these changes

2022-06-09 06:59 UTC, merged