SPCTR-900 - Update: Added Icon list block global color control
brainstormforce/ultimate-addons-for-gutenberg pull request #1634
Opened 2022-06-01 10:25 UTC by imrantushar

### Description
Global color Control added for icon list block

### Screenshots

### Types of changes
New Features

### How has this been tested?
Drag and Drop Icon List Block then see label and color control

### Checklist:
- [ ] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2022-06-06 12:22 UTC, RajkiranBagal requested changes

2022-06-06 12:22 UTC, RajkiranBagal commented on src/blocks/icon-list/attributes.js
> +	icon_color: {
@imrantushar attribute names should always be `camelCase`

2022-06-07 05:25 UTC, RajkiranBagal requested changes

2022-06-07 05:25 UTC, RajkiranBagal commented on classes/class-uagb-block-helper.php
> +			if ( ! empty( $attr['icon_hover_color'] ) ) {
@imrantushar We need to change updated attributes names here too Right?

2022-06-08 07:16 UTC, RajkiranBagal commented on classes/class-uagb-block-helper.php
> +			if ( ! empty( $attr['icon_hover_color'] ) ) {
We cannot change old attributes because of backward compatibility issues, But at least we should not repeat old mistakes again.

2022-06-08 07:18 UTC, imrantushar commented on classes/class-uagb-block-helper.php
> +			if ( ! empty( $attr['icon_hover_color'] ) ) {
@RajkiranBagal your mentioned attribute is an old attribute, so we can move it to QA.

2022-06-08 07:27 UTC, RajkiranBagal approved these changes

2022-06-10 14:02 UTC, RajkiranBagal approved these changes

2022-06-13 03:21 UTC, RajkiranBagal approved these changes

2022-06-13 03:21 UTC, merged