Using only CSS instead of JS calculations for container padding
brainstormforce/ultimate-addons-for-gutenberg pull request #1643
Opened 2022-06-02 12:32 UTC by patilvikasj

### Description

### Screenshots

### Types of changes

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2022-06-02 13:24 UTC, RajkiranBagal requested changes

2022-06-02 13:24 UTC, RajkiranBagal commented on includes/blocks/container/frontend.css.php
> -		'--padding-left'               => $left_padding_tablet . $attr['paddingTypeTablet'],
Can we common out some code? As we discussed on call?

2022-06-03 05:36 UTC, patilvikasj commented on includes/blocks/container/frontend.css.php
> -		'--padding-left'               => $left_padding_tablet . $attr['paddingTypeTablet'],
Done.

2022-06-03 07:56 UTC, RajkiranBagal approved these changes

2022-06-06 10:38 UTC, RajkiranBagal approved these changes

2022-06-06 10:42 UTC, merged