SPCTR-1027 Designed scrollbar of editor sidebar
brainstormforce/ultimate-addons-for-gutenberg pull request #1682
Opened 2022-06-10 05:31 UTC by sushmak02

### Description
While switching between General / Style / Adv tabs the screen resizes.
The screen is resizing due to the scrollbar is hiding when there are less settings.

This can not be fixed without adding static width css for sidebar.

So, instead of that to make the scrollbar minimal I have re-designed the scrollbar like this - https://share.getcloudapp.com/BluGZyqk

### Screenshots
[](https://d.pr/v/S6vCEi)

### Types of changes

Improvement

### How has this been tested?

### Checklist:
- [x] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2022-06-10 13:26 UTC, RajkiranBagal requested changes

2022-06-10 13:26 UTC, RajkiranBagal commented on src/common-editor.scss
> +	width: 5px;
@sushmak02 Please add comments in CSS. For What purpose the CSS is added. & Start & End CSS Comment too.

2022-06-15 10:59 UTC, sushmak02 commented on src/common-editor.scss
> +	width: 5px;
Done.

2022-06-15 11:17 UTC, RajkiranBagal approved these changes

2022-06-15 11:17 UTC, merged