SPCTR-1051 Fix: Scroll delay fix for table of contents
brainstormforce/ultimate-addons-for-gutenberg pull request #1706
Opened 2022-06-15 08:29 UTC by jamyrbsf

### Description
Scroll delay time was not working. It has been fixed now.

### Screenshots
https://brainstormforce.atlassian.net/browse/SPCTR-1051

### Types of changes
Scroll delay

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2022-06-15 09:34 UTC, RajkiranBagal requested changes

2022-06-15 09:34 UTC, RajkiranBagal commented on assets/js/table-of-contents.js
> +				setTimeout( () => {
@jamyrbsf setTimeout does not increase the smooth scroll time, it just delays the smooth scroll. We cannot use this approach.

cc - @AbhijitNage123

2022-06-17 05:02 UTC, AbhijitNage123 approved these changes

2022-06-20 06:29 UTC, RajkiranBagal approved these changes

2022-06-20 06:41 UTC, merged