WIP - SPCTR-1040: Spectra Style Guide
brainstormforce/ultimate-addons-for-gutenberg pull request #1723
Opened 2022-06-17 13:17 UTC by bsf-zanev

### Description
Greatly Updated the UI of the Spectra Editor.

### Types of changes
New feature (non-breaking change which adds functionality)

### How has this been tested?
1. All the UI Updates have been tested cross components.
2. Functionality of the Components has been tested to remain the same for all blocks after updates.
3. Fallbacks have been added for new features that are not required in most blocks.

### Checklist:
- [x] My code is tested
- [x] My code follows accessibility standards 
- [x] My code has proper inline documentation 
- [x] I've included any necessary tests 
- [x] I've added proper labels to this pull request

2022-06-21 05:16 UTC, RajkiranBagal requested changes

2022-06-21 05:16 UTC, RajkiranBagal commented on src/common-editor.scss
> +	// }
Do not keep commented code. If we don't need it, then remove it.

2022-06-21 05:16 UTC, RajkiranBagal commented on src/components/tabs/editor.lazy.scss
> +	// 	padding-bottom: $spectra-control-vertical-gap;
Removed code that we don't need. Check the whole PR.

2022-06-24 13:08 UTC, bsf-zanev reviewed
All Unrequired Comments Removed.

2022-06-24 13:29 UTC, RajkiranBagal approved these changes

2022-06-24 13:29 UTC, merged