SPCTR-1164 - Fix: Deformed Form Toggle
brainstormforce/ultimate-addons-for-gutenberg pull request #1796
Opened 2022-06-29 14:15 UTC by bsf-zanev

### Description
Fixed the Form Toggle (Responsive) in the Front-end and Editor. New fix allows for Responsive Border Customization without breaking.

### Types of changes
Bug fix (non-breaking change which fixes an issue)

### How has this been tested?
Tested as per the task's description.

### Checklist:
- [x] My code is tested
- [x] My code follows accessibility standards 
- [x] My code has proper inline documentation 
- [x] I've included any necessary tests 
- [x] I've included developer documentation 
- [x] I've added proper labels to this pull request

2022-07-01 11:29 UTC, AbhijitNage123 requested changes

2022-07-01 11:29 UTC, AbhijitNage123 commented on includes/blocks/forms/frontend.css.php
> +$toggle_border_top_fallback           = UAGB_Block_Helper::get_attribute_fallback( $toggle_border['border-top-width'], 'checkBoxToggleBorderTopWidth', $block_name );
@bsf-zanev toggle variable name not in proper snake_case. Also, check the whole file for toggle variables only.

2022-07-04 04:20 UTC, AbhijitNage123 approved these changes

2022-07-04 05:12 UTC, RajkiranBagal approved these changes

2022-07-04 05:13 UTC, merged