Improvement: Container - Added z index property for Container
brainstormforce/ultimate-addons-for-gutenberg pull request #1934
Opened 2022-07-15 12:59 UTC by sushmak02

### Description
Container: Added z index property for Container

### Screenshots
Fix - https://share.getcloudapp.com/Jruoe5q2

### Types of changes

- New feature

### How has this been tested?
- Drag drop container
- Got to advanced -> advanced -> Z-Index

### Checklist:
- [x] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2022-07-18 06:22 UTC, RajkiranBagal requested changes

2022-07-18 06:22 UTC, RajkiranBagal commented on src/blocks/extensions/condition-block/index.js
>  		UAGHideMob,
Please rename the folder name "condition-block" as well as the Component/Fuctions names to something generic as we are combining multiple setting instead of just Display Conditions

2022-07-18 06:39 UTC, sushmak02 commented on src/blocks/extensions/condition-block/index.js
>  		UAGHideMob,
Sure

2022-07-18 06:51 UTC, sushmak02 commented on src/blocks/extensions/condition-block/index.js
>  		UAGHideMob,
@RajkiranBagal I have renamed the "condition-block" folder with "advanced-settings".
Please let me know what exactly I need to change in Component/Fuctions, did not understood what exactly.

2022-07-18 06:55 UTC, RajkiranBagal commented on src/blocks/extensions/condition-block/index.js
>  		UAGHideMob,
Looks Good!

2022-07-18 06:55 UTC, RajkiranBagal approved these changes

2022-07-19 13:32 UTC, RajkiranBagal approved these changes

2022-07-20 04:43 UTC, AbhijitNage123 requested changes

2022-07-20 04:43 UTC, AbhijitNage123 commented on src/blocks/extensions/advanced-settings/index.js
> +				displayUnit={ false }
@sushmak02 Currently, the slider is not working whenever we slide the control. Please add min/max to responsive control to make the slider work.

2022-07-20 05:04 UTC, sushmak02 commented on src/blocks/extensions/advanced-settings/index.js
> +				displayUnit={ false }
Done.

2022-07-20 05:13 UTC, AbhijitNage123 approved these changes

2022-07-25 04:30 UTC, AbhijitNage123 approved these changes

2022-07-25 12:02 UTC, RajkiranBagal approved these changes

2022-07-25 12:12 UTC, merged