SPCTR-910 Table of Content - Separator Feature
brainstormforce/ultimate-addons-for-gutenberg pull request #1949
Opened 2022-07-19 12:57 UTC by aapatre

### Description

- Added separator feature

### Types of changes

- New feature (non-breaking change which adds functionality)

### Checklist:
- [x] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [x] I've added proper labels to this pull request

2022-07-20 05:00 UTC, RajkiranBagal requested changes

2022-07-20 05:00 UTC, RajkiranBagal commented on blocks-config/table-of-content/class-uagb-table-of-content.php
> +								<div class='uagb-toc__separator'></div>
Do we need 2 divs to add separator?

2022-07-20 05:58 UTC, aapatre commented on blocks-config/table-of-content/class-uagb-table-of-content.php
> +								<div class='uagb-toc__separator'></div>
@RajkiranBagal we can remove the wrapper div as it serves no necessary function
 
- I had added a wrapper div to adhere to the usual coding practices (of adding wrappers) and,
- Also because the separator in Advanced Heading block had one (which I used as a reference)

Nevertheless, I’ve removed the wrapper div with new commits :heavy_check_mark:

2022-07-20 06:14 UTC, RajkiranBagal approved these changes

2022-07-21 06:24 UTC, RajkiranBagal requested changes

2022-07-21 06:24 UTC, RajkiranBagal commented on includes/blocks/table-of-contents/frontend.css.php
> +	$calcPaddingLeft  = UAGB_Helper::get_css_value( $attr['leftPadding'], $attr['paddingTypeDesktop'] );
PHP variables should be snake_case

2022-07-21 07:44 UTC, RajkiranBagal approved these changes

2022-07-22 14:09 UTC, RajkiranBagal approved these changes

2022-07-22 14:13 UTC, merged