SPCTR-1039 All Blocks - Shifted all alignment controls to General Tab
brainstormforce/ultimate-addons-for-gutenberg pull request #1956
Opened 2022-07-20 09:45 UTC by aapatre

### Description

- Shifted all alignment controls to General Tab
- [Documentation](https://docs.google.com/document/d/1pBsd-WzGqPxzbbEnJ3mpirw5w8yE4bTti5BhvvYauRM/edit?usp=sharing)
- [JIRA](https://brainstormforce.atlassian.net/browse/SPCTR-1039)

### Types of changes

- Bug fix (non-breaking change which fixes an issue)
- Restructuring visible settings

### Checklist:
- [x] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [x] I've included any necessary tests (in documentation) 
- [x] I've included developer documentation 
- [x] I've added proper labels to this pull request

2022-07-21 06:28 UTC, RajkiranBagal requested changes

2022-07-21 06:28 UTC, RajkiranBagal commented on src/blocks/image/settings.js
> +			<MultiButtonsControl
You missed the default' === layout condition here it seems

2022-07-21 07:22 UTC, aapatre commented on src/blocks/image/settings.js
> +			<MultiButtonsControl
The condition is for captionAlign, this segment is for overall alignment
Recorded a video to explain the changes:
https://d.pr/v/HL746x

2022-07-21 07:39 UTC, RajkiranBagal approved these changes

2022-07-21 12:45 UTC, aapatre commented
Video explaining changes:
https://d.pr/v/5WakGC

2022-07-25 11:42 UTC, RajkiranBagal approved these changes

2022-07-25 11:52 UTC, merged