SPCTR-1449 Post Grid Block: Pagination not working.
brainstormforce/ultimate-addons-for-gutenberg pull request #1998
Opened 2022-07-29 06:47 UTC by AbhijitNage123

### Description

- https://brainstormforce.atlassian.net/browse/SPCTR-1449

### Screenshots

- https://share.getcloudapp.com/ApuXdR8w

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

### How has this been tested?

- Added in the card.

### Checklist:
- [x] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [x] I've included any necessary tests 
- [ ] I've included developer documentation 
- [x] I've added proper labels to this pull request

2022-07-29 07:33 UTC, RajkiranBagal requested changes

2022-07-29 07:33 UTC, RajkiranBagal commented on classes/class-uagb-helper.php
> +			$fallbackForpostsToShow = UAGB_Block_Helper::get_fallback_number( $attributes['postsToShow'], 'postsToShow', $attributes['blockName'] );
PHP variables should be snake_case

2022-07-29 07:33 UTC, RajkiranBagal commented on src/blocks/post/post-carousel/edit.js
> +		setAttributes( { enableOffset: value } );
We do not pass any value to this function from Toggle. What is the use of this?

2022-07-29 10:06 UTC, AbhijitNage123 commented on classes/class-uagb-helper.php
> +			$fallbackForpostsToShow = UAGB_Block_Helper::get_fallback_number( $attributes['postsToShow'], 'postsToShow', $attributes['blockName'] );
Done

2022-07-29 10:14 UTC, AbhijitNage123 commented on src/blocks/post/post-carousel/edit.js
> +		setAttributes( { enableOffset: value } );
We are calling it on toggle onChange so it will take the value passed to the checked parameter and set it when toggle ON/Off

2022-07-29 12:19 UTC, RajkiranBagal approved these changes

2022-08-03 11:46 UTC, RajkiranBagal approved these changes

2022-08-03 11:47 UTC, merged