SPCTR-346 Fix: cls issue fix for all img tag added image height width
brainstormforce/ultimate-addons-for-gutenberg pull request #2005
Opened 2022-08-01 06:30 UTC by jamyrbsf

### Description
https://brainstormforce.atlassian.net/browse/SPCTR-346

### Screenshots

### Types of changes
 cls issue fix for all img tag added image height width
 
### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2022-08-03 06:03 UTC, AbhijitNage123 approved these changes

2022-08-15 05:23 UTC, RajkiranBagal requested changes

2022-08-15 05:23 UTC, RajkiranBagal commented on src/blocks/testimonial/deprecated.js
> +								"is-carousel",
Why have we made changes in previous arrays in deprecated file?

2022-08-15 05:31 UTC, jamyrbsf commented on src/blocks/testimonial/deprecated.js
> +								"is-carousel",
This was done by @AbhijitNage123. You can see the full detail in the description card.
Here is the pr for the changes that @AbhijitNage123 made.
https://github.com/brainstormforce/ultimate-addons-for-gutenberg/pull/2005/commits/afc95d1be87712ac9b697a5f265d69ba4cec07d8#diff-9303ce898ed53c3519aec7f5d84877c3b9aeb7804800971bf8b1c62a7a4b495f

2022-08-18 05:16 UTC, AbhijitNage123 commented on src/blocks/price-list-child/attributes.js
> +		default: 100,
Closing bracket `{` missing.

2022-08-18 05:17 UTC, AbhijitNage123 commented on src/blocks/price-list-child/attributes.js
> +}
Unwanted closing bracket.

2022-08-18 05:24 UTC, jamyrbsf commented on src/blocks/price-list-child/attributes.js
> +		default: 100,
fixed it.

2022-08-18 05:24 UTC, jamyrbsf commented on src/blocks/price-list-child/attributes.js
> +}
fixed it also

2022-08-18 07:19 UTC, AbhijitNage123 commented on src/blocks/blockquote/components/AuthorImage.js
> +		const { authorImageWidth } = attributes;
Can this 2 line can be combined and written as 
`const { authorImageWidth, authorImageSize } = attributes;`

2022-08-18 12:17 UTC, jamyrbsf commented on src/blocks/blockquote/components/AuthorImage.js
> +		const { authorImageWidth } = attributes;
Fixed this issue

2022-08-19 12:15 UTC, AbhijitNage123 approved these changes

2022-10-18 09:23 UTC, RajkiranBagal requested changes

2022-10-18 09:23 UTC, RajkiranBagal commented on blocks-config/uagb-controls/getImageHeightWidth.js
> +		setAttributes( { imgTagHeight: this.naturalHeight } )
please write like this to be extra sure. `this?.naturalHeight` Do this change wherever needed or some doubt if the value will be present or not.

2022-10-18 09:23 UTC, RajkiranBagal commented on src/blocks/social-share-child/render.js
> +			<img className="uagb-ss__source-image" src={ image.url } alt={ defaultedAlt }  width="640" height="360" loading="lazy"/>
Why have we added static widths & heights?

2022-10-18 09:23 UTC, RajkiranBagal commented on src/blocks/social-share-child/save.js
> +			<img className="uagb-ss__source-image" src={ image.url } alt={ defaultedAlt } width="640" height="360" loading="lazy"/>
Why have we added static widths & heights?

2022-10-18 12:46 UTC, jamyrbsf commented on blocks-config/uagb-controls/getImageHeightWidth.js
> +		setAttributes( { imgTagHeight: this.naturalHeight } )
Applied this?.naturalHeight. now to resolve unexpected cases.

2022-10-18 12:46 UTC, jamyrbsf commented on src/blocks/social-share-child/save.js
> +			<img className="uagb-ss__source-image" src={ image.url } alt={ defaultedAlt } width="640" height="360" loading="lazy"/>
Added dynamic options now.

2022-10-18 12:46 UTC, jamyrbsf commented on src/blocks/social-share-child/render.js
> +			<img className="uagb-ss__source-image" src={ image.url } alt={ defaultedAlt }  width="640" height="360" loading="lazy"/>
Added dynamic part now.

2022-10-19 04:42 UTC, RajkiranBagal commented on blocks-config/uagb-controls/getImageHeightWidth.js
> +		setAttributes( { imgTagHeight: this.naturalHeight } )
Did you not read this @jamyrbsf ? -  Do this change wherever needed or some doubt if the value will be present or not.

2022-10-19 08:15 UTC, jamyrbsf commented on blocks-config/uagb-controls/getImageHeightWidth.js
> +		setAttributes( { imgTagHeight: this.naturalHeight } )
I have added ? whenever it is needed just to be extra sure as u mentioned through out the whole pr.

2022-10-19 09:03 UTC, RajkiranBagal approved these changes

2022-11-11 11:08 UTC, AbhijitNage123 requested changes

2022-11-11 11:08 UTC, AbhijitNage123 commented on src/blocks/team/render.js
> +		{ isPreview ? <img src={previewImageData} alt='' loading='lazy' height={ imgWidth } width={ imgWidth } /> :
Why changes here? If it is needed for preview image need made changes for every preview image not only this team.

2022-11-11 11:11 UTC, AbhijitNage123 commented on src/blocks/team/render.js
> +		{ isPreview ? <img src={previewImageData} alt='' loading='lazy' height={ imgWidth } width={ imgWidth } /> :
Right @jamyrbsf please remove that `loading, height and width` attribute for team preview image.

2022-11-11 11:29 UTC, jamyrbsf commented on src/blocks/team/render.js
> +		{ isPreview ? <img src={previewImageData} alt='' loading='lazy' height={ imgWidth } width={ imgWidth } /> :
Ok. @AbhijitNage123

2022-11-11 11:38 UTC, AbhijitNage123 approved these changes

2022-11-11 11:39 UTC, aapatre requested changes
Do we need CLS for SVGs too? @RajkiranBagal @AbhijitNage123 @jamyrbsf 
If yes we might need to update our RenderSVG component too

2022-11-11 11:43 UTC, raojip approved these changes

2022-11-11 12:56 UTC, imrantushar commented
> Do we need CLS for SVGs too? @RajkiranBagal @AbhijitNage123 @jamyrbsf If yes we might need to update our RenderSVG component too

2022-11-11 12:57 UTC, jamyrbsf commented
> Do we need CLS for SVGs too? @RajkiranBagal @AbhijitNage123 @jamyrbsf If yes we might need to update our RenderSVG component too

Normally svg has viewbox which have value  attribute which are: min-x, min-y, width and height. So if the SVG has viewbox it should not have problem.

2022-11-14 04:13 UTC, aapatre commented
Alright!
cc: @jamyrbsf @RajkiranBagal @AbhijitNage123

2022-11-14 06:55 UTC, bsf-zanev commented on README.md
> +* Improvement: Implemented CLS for all the blocks which have image tag.
Ideally Improvements should be above the fixes rather than between them.

2022-11-14 07:06 UTC, bsf-zanev requested changes
Almost all changes have been verified, only a minor misplacement of the Improvement in the Readme persists.

2022-11-14 07:19 UTC, bsf-zanev approved these changes
Looks Good to Go.

2022-11-14 07:24 UTC, RajkiranBagal approved these changes

2022-11-14 07:25 UTC, aapatre approved these changes
LGTM! ✅

2022-11-14 07:25 UTC, aapatre commented on src/blocks/google-map/render.js
> +				width="640" height={ height }
Since Google Maps is responsive and it's an iframe, do we need to add CLS support and a fixed width here?

cc: @jamyrbsf @RajkiranBagal @AbhijitNage123

2022-11-14 07:26 UTC, aapatre commented on src/blocks/google-map/render.js
> +				width="640" height={ height }
Had a conversation with @jamyrbsf, 640 was already present and CLS support will be necessary for iframe too

2022-11-14 07:26 UTC, jamyrbsf commented on src/blocks/google-map/render.js
> +				width="640" height={ height }
iframe also causes layout shifts.
That was added by @supriyajjadhav  in her pr before but I checked and this CSS was added so I let it be as we don't control width right now

2022-11-14 07:33 UTC, merged