Container: Background Image Custom Positioning with appropriate units needed
brainstormforce/ultimate-addons-for-gutenberg pull request #2017
Opened 2022-08-02 10:14 UTC by sushmak02

### Description
Container: Background Image Custom Positioning with appropriate units needed

### Screenshots
https://share.getcloudapp.com/qGuOLLX2

### Types of changes

Improvement

### How has this been tested?
- Drag drop container
- Set background image
- Choose background-position - custom

### Checklist:
- [x] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2022-08-02 10:52 UTC, RajkiranBagal requested changes

2022-08-02 10:52 UTC, RajkiranBagal commented on classes/class-uagb-block-helper.php
> +			$customPosition = isset( $bg_obj['customPosition'] ) ? $bg_obj['customPosition'] : '';
PHP must have sname_case variable names.

2022-08-02 11:30 UTC, sushmak02 commented on classes/class-uagb-block-helper.php
> +			$customPosition = isset( $bg_obj['customPosition'] ) ? $bg_obj['customPosition'] : '';
Done

2022-08-03 12:49 UTC, RajkiranBagal approved these changes

2022-08-03 13:08 UTC, RajkiranBagal approved these changes

2022-08-03 13:12 UTC, merged