SPCTR-1509 Fix: maps backward compatibility fix
brainstormforce/ultimate-addons-for-gutenberg pull request #2028
Opened 2022-08-03 08:57 UTC by jamyrbsf

### Description
https://brainstormforce.atlassian.net/browse/SPCTR-1509

### Screenshots

### Types of changes
fixed backward backward compatibility for maps

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2022-08-03 11:12 UTC, RajkiranBagal requested changes

2022-08-03 11:12 UTC, RajkiranBagal commented on src/blocks/google-map/deprecated.js
>  	},
There was no deprecated file in master & in this branch there are multiple arrays of deprecated. Please confirm this. Ideally there should only be 1 array in this file.

2022-08-03 11:48 UTC, jamyrbsf commented on src/blocks/google-map/deprecated.js
>  	},
there are already 3 deprecated code in master and I added 1 more. in total there are 4 now.

2022-08-03 13:14 UTC, RajkiranBagal approved these changes

2022-08-04 13:05 UTC, RajkiranBagal approved these changes

2022-08-04 13:06 UTC, merged