SPCTR-1533 UAG Number Control - For offset by and post per page option.
brainstormforce/ultimate-addons-for-gutenberg pull request #2054
Opened 2022-08-05 09:48 UTC by AbhijitNage123

### Description

- https://brainstormforce.atlassian.net/browse/SPCTR-1533

### Screenshots

- https://share.getcloudapp.com/E0uy1QEp

### Types of changes

- Improvement.

### How has this been tested?

- Added in the card.

### Checklist:
- [x] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [x] I've included any necessary tests 
- [ ] I've included developer documentation 
- [x] I've added proper labels to this pull request

2022-08-05 10:11 UTC, RajkiranBagal requested changes

2022-08-05 10:11 UTC, RajkiranBagal commented on src/blocks/post/post-carousel/edit.js
> +					displayUnit={ false }
Remove unwanted props passed to UAGNUmberControl, check all files.

2022-08-05 10:11 UTC, RajkiranBagal commented on src/components/number-control/editor.lazy.scss
> +		color: #50575E;
Use variable for applying color

2022-08-05 11:18 UTC, AbhijitNage123 commented on src/blocks/post/post-carousel/edit.js
> +					displayUnit={ false }
display unit and other props may be needed in future, So keeping it same

2022-08-05 11:19 UTC, AbhijitNage123 commented on src/components/number-control/editor.lazy.scss
> +		color: #50575E;
Resolved

2022-08-05 11:21 UTC, RajkiranBagal approved these changes

2022-08-08 14:30 UTC, RajkiranBagal approved these changes

2022-08-08 16:45 UTC, merged