SPCTR-628 Fix: block descriptions updated
brainstormforce/ultimate-addons-for-gutenberg pull request #2058
Opened 2022-08-05 12:16 UTC by jamyrbsf

### Description
https://brainstormforce.atlassian.net/browse/SPCTR-628

### Screenshots

### Types of changes
Fix: block descriptions updated

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2022-08-05 13:36 UTC, Avneeshv18 commented on src/blocks/faq-child/block.js
> +	description: __( 'Add a frequently asked quesion/accordian to display information.', 'ultimate-addons-for-gutenberg' ),
There's a typo:

question/accordion

2022-08-05 14:09 UTC, Avneeshv18 requested changes

2022-08-08 06:08 UTC, jamyrbsf commented on src/blocks/faq/block.js
> +	description: __( 'Add accordians/FAQ schema to your page.', 'ultimate-addons-for-gutenberg' ),
fixed it.

2022-08-08 06:09 UTC, jamyrbsf commented on src/blocks/testimonial/block.js
> +	description: __( 'Display customer testimonials with customizable layouts.', 'ultimate-addons-for-gutenberg' ), // Block description.
fixed it.

2022-08-08 06:09 UTC, jamyrbsf commented on src/blocks/faq-child/block.js
> +	description: __( 'Add a frequently asked quesion/accordian to display information.', 'ultimate-addons-for-gutenberg' ),
fixed it.

2022-08-08 06:17 UTC, Avneeshv18 approved these changes

2022-08-08 07:14 UTC, RajkiranBagal approved these changes

2022-08-09 06:34 UTC, Avneeshv18 commented on src/blocks/forms/child-blocks/checkbox/block.js
> +	description: __( 'Add checkboxes to allow mulitple choices from optons.', 'ultimate-addons-for-gutenberg' ),
"Options" spelling needs to be replaced.

Add checkboxes to allow multiple choices from options.

2022-08-09 06:34 UTC, Avneeshv18 commented on src/blocks/timeline/content-timeline-child/block.js
> +	description: __( 'Add and customize displaying content of this timeline.', 'ultimate-addons-for-gutenberg' ),
Please replace it with:-

Add and customize content of this timeline.

2022-08-09 07:04 UTC, jamyrbsf commented on src/blocks/forms/child-blocks/checkbox/block.js
> +	description: __( 'Add checkboxes to allow mulitple choices from optons.', 'ultimate-addons-for-gutenberg' ),
resolved this.

2022-08-09 07:04 UTC, jamyrbsf commented on src/blocks/timeline/content-timeline-child/block.js
> +	description: __( 'Add and customize displaying content of this timeline.', 'ultimate-addons-for-gutenberg' ),
resolved this.

2022-08-09 15:26 UTC, RajkiranBagal approved these changes

2022-08-09 15:26 UTC, merged