SPCTR-1581 Price List Presets Fix- Presets overriding image data and columns
brainstormforce/ultimate-addons-for-gutenberg pull request #2075
Opened 2022-08-08 12:52 UTC by aapatre

### Description
- Selected images were overriden when using/switching presets but now this has been fixed by introducing the 'Show image' toggle
- Switching/using presets was overriding columns, so hence removed the feature for overriding columns using presets since it was inconvenient UX

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

### Checklist:
- [x] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [x] I've added proper labels to this pull request

2022-08-08 14:03 UTC, aapatre commented
Changed the logic 
cc: @RajkiranBagal

2022-08-08 14:06 UTC, RajkiranBagal requested changes

2022-08-08 14:06 UTC, RajkiranBagal commented on src/blocks/price-list/edit.js
> +                    block.clientId, {
Why are you updating twice?

2022-08-08 14:13 UTC, aapatre commented on src/blocks/price-list/edit.js
> +                    block.clientId, {
Duplicate code added by mistake, removed it

2022-08-08 14:13 UTC, aapatre commented
removed the duplicate code 
cc: @RajkiranBagal

2022-08-08 14:14 UTC, RajkiranBagal approved these changes

2022-08-09 16:35 UTC, RajkiranBagal approved these changes

2022-08-09 16:40 UTC, RajkiranBagal approved these changes

2022-08-09 16:40 UTC, merged