SPCTR-1584 - PHP : Fatal Error while testing buttons or Taxonomy List block
brainstormforce/ultimate-addons-for-gutenberg pull request #2076
Opened 2022-08-08 13:59 UTC by supriyajjadhav

### Description
PHP : Fatal Error while testing buttons or Taxonomy List block

### Types of changes
Bug fix (non-breaking change which fixes an issue) 

### How has this been tested?

### Checklist:
- [x] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [x] I've added proper labels to this pull request

2022-08-08 14:21 UTC, RajkiranBagal requested changes

2022-08-08 14:21 UTC, RajkiranBagal commented on blocks-config/post/class-uagb-post.php
> +			if ( function_exists( 'uag_generate_php_border_attribute' ) ) {
@supriyajjadhav IMO we should use - https://www.php.net/manual/en/function.method-exists.php

2022-08-08 14:32 UTC, supriyajjadhav commented on blocks-config/post/class-uagb-post.php
> +			if ( function_exists( 'uag_generate_php_border_attribute' ) ) {
Yes, Updated conditions

2022-08-08 16:46 UTC, RajkiranBagal approved these changes

2022-08-09 14:13 UTC, RajkiranBagal approved these changes

2022-08-10 05:47 UTC, RajkiranBagal approved these changes

2022-08-10 05:50 UTC, merged