SPCTR-934 Updated next-release with release after v1.25.4
brainstormforce/ultimate-addons-for-gutenberg pull request #2135
Opened 2022-08-16 11:39 UTC by AbhijitNage123

### Description

- https://brainstormforce.atlassian.net/browse/SPCTR-974?atlOrigin=eyJpIjoiMTM5OTY1MTZhMWViNDBhZWI5NDY3MjVjMWU2ZTEwN2MiLCJwIjoiaiJ9

### Screenshots

- NA

### Types of changes

- NA

### How has this been tested?

- NA

### Checklist:
- [x] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [x] I've included any necessary tests 
- [ ] I've included developer documentation 
- [x] I've added proper labels to this pull request

2022-08-16 11:49 UTC, RajkiranBagal requested changes

2022-08-16 11:49 UTC, RajkiranBagal commented on .github/workflows/push-asset-readme-update.yml
> +    - fix-css-issue-on-responsive-and-button-child-setting-not-visible
Change to master.

2022-08-16 11:53 UTC, AbhijitNage123 commented on .github/workflows/push-asset-readme-update.yml
> +    - fix-css-issue-on-responsive-and-button-child-setting-not-visible
Resolved

2022-08-16 12:15 UTC, RajkiranBagal approved these changes

2022-08-16 12:16 UTC, merged

2022-08-17 12:01 UTC, aapatre commented on lib/astra-notices/composer.json
> -    "version": "1.1.8",
Version seems to be removed
Is it intentional? :thinking:

2022-08-17 12:06 UTC, AbhijitNage123 commented on lib/astra-notices/composer.json
> -    "version": "1.1.8",
The composer file gets updated when we do `composer update` cmd. It will automatically update composer.json file.

2022-08-17 12:07 UTC, aapatre commented on lib/astra-notices/composer.json
> -    "version": "1.1.8",
Got it, thanks! :)