SPCTR-1738 Responsive and Display Condition - Added responsive and display condition for core block again.
brainstormforce/ultimate-addons-for-gutenberg pull request #2233
Opened 2022-08-26 13:45 UTC by AbhijitNage123

### Description

- https://brainstormforce.atlassian.net/browse/SPCTR-1738

### Screenshots

- NA

### Types of changes

- New

### How has this been tested?

- Tested as per card description.

### Checklist:
- [x] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [x] I've included any necessary tests 
- [ ] I've included developer documentation 
- [x] I've added proper labels to this pull request

2022-08-30 13:24 UTC, RajkiranBagal requested changes

2022-08-30 13:24 UTC, RajkiranBagal commented on classes/class-uagb-init-blocks.php
> +		$show = is_array( $value ) && ! empty( $value ) ? in_array( $user_agent, $value, true ) : $value === $user_agent;
Why have we checked array conditions here? In which case does $value comes as array?

2022-08-30 13:31 UTC, AbhijitNage123 commented on classes/class-uagb-init-blocks.php
> +		$show = is_array( $value ) && ! empty( $value ) ? in_array( $user_agent, $value, true ) : $value === $user_agent;
Updated condition and tested.

2022-09-01 07:24 UTC, RajkiranBagal requested changes

2022-09-01 07:24 UTC, RajkiranBagal commented on classes/class-uagb-init-blocks.php
> +		$show       = false;
Why Is this variable definition needed?

2022-09-01 07:24 UTC, RajkiranBagal commented on lib/astra-notices/notices.css
> +}
I think we need this CSS

2022-09-01 07:33 UTC, AbhijitNage123 commented on lib/astra-notices/notices.css
> +}
I'm not sure how it gets deleted. I'll add it again

2022-09-01 07:37 UTC, AbhijitNage123 commented on classes/class-uagb-init-blocks.php
> +		$show       = false;
Removed unwanted $show variable definition from file.

2022-09-01 07:38 UTC, AbhijitNage123 commented on lib/astra-notices/notices.css
> +}
Updated rtl CSS astra notice back

2022-09-01 09:03 UTC, RajkiranBagal approved these changes

2022-09-01 09:03 UTC, merged