Fix: Undefined index for load-google-fonts-locally for new user
brainstormforce/ultimate-addons-for-gutenberg pull request #2239
Opened 2022-08-29 12:29 UTC by AbhijitNage123

### Description

### Screenshots

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

### How has this been tested?

- Reset the site with the Astra theme activate.
- Refresh the admin. You will see the issue in debug log.
- Switch to our branch and try doing the same. The issue gets resolved.

### Checklist:
- [x] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [x] I've included any necessary tests 
- [ ] I've included developer documentation 
- [x] I've added proper labels to this pull request

2022-08-29 12:41 UTC, RajkiranBagal requested changes

2022-08-29 12:41 UTC, RajkiranBagal commented on readme.txt
> +* Fix: Undefined index for `load-google-fonts-locally` for new user when Astra theme activated.
Fix: PHP notice for new users when they activate Astra theme.

2022-08-29 12:41 UTC, RajkiranBagal commented on compatibility/class-uagb-astra-compatibility.php
> +			if ( is_array( $astra_settings ) && empty( $astra_settings['load-google-fonts-locally'] ) || array_key_exists( 'load-google-fonts-locally', $astra_settings ) && false === $astra_settings['load-goo
Can we just check isset instead of array_key_exists?

2022-08-30 03:58 UTC, AbhijitNage123 commented on readme.txt
> +* Fix: Undefined index for `load-google-fonts-locally` for new user when Astra theme activated.
Done

2022-08-30 03:58 UTC, AbhijitNage123 commented on compatibility/class-uagb-astra-compatibility.php
> +			if ( is_array( $astra_settings ) && empty( $astra_settings['load-google-fonts-locally'] ) || array_key_exists( 'load-google-fonts-locally', $astra_settings ) && false === $astra_settings['load-goo
Done

2022-08-30 04:08 UTC, RajkiranBagal approved these changes

2022-08-30 13:26 UTC, RajkiranBagal requested changes

2022-08-30 13:26 UTC, RajkiranBagal commented on compatibility/class-uagb-astra-compatibility.php
> +			if ( is_array( $astra_settings ) && empty( $astra_settings['load-google-fonts-locally'] ) || isset( $astra_settings['load-google-fonts-locally'] ) && false === $astra_settings['load-google-fonts-l
Add the whole thing after `||` in a separate bracket. It may generate unexpected results.

2022-09-01 02:40 UTC, RajkiranBagal approved these changes

2022-09-01 06:23 UTC, RajkiranBagal approved these changes

2022-09-01 06:23 UTC, merged