SPCTR-1740 - Fix: Call To Action Block button css conflict with newspaper theme
brainstormforce/ultimate-addons-for-gutenberg pull request #2247
Opened 2022-08-31 07:48 UTC by imrantushar

### Description
Call To Action Block button css conflict with newspaper theme

### Screenshots

### Types of changes

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2022-09-20 09:13 UTC, AbhijitNage123 approved these changes

2022-09-26 11:05 UTC, RajkiranBagal approved these changes

2022-09-26 11:06 UTC, RajkiranBagal requested changes

2022-09-26 11:06 UTC, RajkiranBagal commented on README.md
> +* Fix: Call To Action - Button css conflict with newspaper theme.
`Newspaper`

2022-09-26 12:03 UTC, supriyajjadhav commented on README.md
> +* Fix: Call To Action - Button css conflict with newspaper theme.
Updated

2022-09-26 12:36 UTC, RajkiranBagal approved these changes

2022-09-26 12:42 UTC, RajkiranBagal approved these changes

2022-09-26 12:44 UTC, merged