Spctr-1767 advanced column paragraph wrap image align
brainstormforce/ultimate-addons-for-gutenberg pull request #2274
Opened 2022-09-07 03:51 UTC by jamyrbsf

### Description
https://brainstormforce.atlassian.net/browse/SPCTR-1767

### Screenshots

### Types of changes
Image. right align fixed and text wrap fixed also.

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2022-09-08 12:08 UTC, RajkiranBagal approved these changes

2022-09-19 04:50 UTC, AbhijitNage123 approved these changes

2022-09-26 11:19 UTC, RajkiranBagal requested changes

2022-09-26 11:19 UTC, RajkiranBagal commented on README.md
> +* Fix: Advanced Column: Paragraph will not wrap inside column for text and image.
Changelog sentences are not proper, please mention what is the issue you fixed. Check for Grammar too

2022-09-26 11:50 UTC, jamyrbsf commented on README.md
> +* Fix: Advanced Column: Paragraph will not wrap inside column for text and image.
Updated the cahnge log

2022-09-26 12:24 UTC, RajkiranBagal approved these changes

2022-09-26 12:58 UTC, RajkiranBagal approved these changes

2022-09-26 13:01 UTC, RajkiranBagal approved these changes

2022-09-26 13:04 UTC, merged