SPCTR-1801 Fix: Responsive condition option does not save when hide on multiple devices is selected.
brainstormforce/ultimate-addons-for-gutenberg pull request #2304
Opened 2022-09-14 10:56 UTC by AbhijitNage123

### Description

- https://brainstormforce.atlassian.net/browse/SPCTR-1801

### Screenshots

- https://share.getcloudapp.com/GGuzojwg

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

### How has this been tested?

- Added to the card.

### Checklist:
- [x] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [x] I've included any necessary tests 
- [ ] I've included developer documentation 
- [x] I've added proper labels to this pull request

2022-09-14 12:09 UTC, RajkiranBagal requested changes

2022-09-14 12:09 UTC, RajkiranBagal commented on src/blocks/extensions/advanced-settings/index.js
> -						UAGResponsiveConditions: ! UAGResponsiveConditions
This is needed for old users.

2022-09-14 12:19 UTC, AbhijitNage123 commented on src/blocks/extensions/advanced-settings/index.js
> -						UAGResponsiveConditions: ! UAGResponsiveConditions
It is causing settings are not saved

2022-09-14 13:41 UTC, AbhijitNage123 commented on src/blocks/extensions/advanced-settings/index.js
> -						UAGResponsiveConditions: ! UAGResponsiveConditions
Updated logic. Please verify

2022-09-15 06:11 UTC, AbhijitNage123 commented on src/blocks/extensions/advanced-settings/index.js
> -						UAGResponsiveConditions: ! UAGResponsiveConditions
@RajkiranBagal As discussed, I have tested the case and it does not adding any class to block whenever toggle is set to off. Cause we have added condition inside of if again to check is if toggle is true then only add the class to the block. Screencast - https://share.getcloudapp.com/v1uQ2b79

2022-09-15 07:37 UTC, RajkiranBagal approved these changes

2022-09-15 07:37 UTC, merged