SPCTR-1810 - Fix: TOC - Adding 'uagb-toc-hide-heading' class to exclude heading from TOC list not working on front-end.
brainstormforce/ultimate-addons-for-gutenberg pull request #2308
Opened 2022-09-15 09:05 UTC by supriyajjadhav

### Description
Adding 'uagb-toc-hide-heading' class to exclude heading in TOC list not working on front-end.

### Types of changes
Bug fix (non-breaking change which fixes an issue) 

### How has this been tested?

### Checklist:
- [x] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [x] I've added proper labels to this pull request

2022-09-20 10:09 UTC, AbhijitNage123 approved these changes

2022-09-26 10:59 UTC, RajkiranBagal approved these changes

2022-09-26 11:01 UTC, RajkiranBagal requested changes

2022-09-26 11:01 UTC, RajkiranBagal commented on src/blocks/table-of-contents/edit.js
> +		if ( excludeBlock !== 'undefined' ) {
Can we just check like this? - `if ( excludeBlock ) { `

2022-09-26 11:01 UTC, RajkiranBagal commented on src/blocks/table-of-contents/edit.js
> +				if ( innerHeading !== 'undefined' ) {
Can we just check like this? - `if ( innerHeading ) { `

2022-09-26 12:26 UTC, supriyajjadhav commented on src/blocks/table-of-contents/edit.js
> +		if ( excludeBlock !== 'undefined' ) {
Updated condition.

2022-09-26 12:26 UTC, supriyajjadhav commented on src/blocks/table-of-contents/edit.js
> +				if ( innerHeading !== 'undefined' ) {
Updated condition.

2022-09-27 04:15 UTC, RajkiranBagal requested changes

2022-09-27 04:15 UTC, RajkiranBagal commented on README.md
> +* Fix: TOC - Adding 'uagb-toc-hide-heading' class to exclude heading from TOC list not working on front-end.
TOC -> Table of Contents

2022-09-27 04:35 UTC, supriyajjadhav commented on README.md
> +* Fix: TOC - Adding 'uagb-toc-hide-heading' class to exclude heading from TOC list not working on front-end.
Updated

2022-09-27 06:12 UTC, RajkiranBagal approved these changes

2022-09-27 06:12 UTC, merged