SPCTR-556 - New: Instagram Admin
brainstormforce/ultimate-addons-for-gutenberg pull request #2319
Opened 2022-09-19 12:16 UTC by bsf-zanev

### Description
This PR will consist of All Instagram Admin Updates, Including Linking and Unlinking Accounts.

### Types of changes
New feature (non-breaking change which adds functionality)

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2023-02-17 15:42 UTC, RajkiranBagal requested changes

2023-02-17 15:42 UTC, RajkiranBagal commented on admin-core/assets/src/dashboard-app/pages/settings/block-settings/Login.js
> +import apiFetch from '@wordpress/api-fetch';
This file is not related to the current PR. It should not be here.

2023-02-17 15:42 UTC, RajkiranBagal commented on admin-core/assets/src/utils/setInitialState.js
> +            instaLinkedAccounts: data.insta_linked_accounts,
```suggestion
            instaLinkedAccounts: data?.insta_linked_accounts,
```

2023-02-17 15:42 UTC, RajkiranBagal commented on classes/class-uagb-block.php
> +				die( file_exists( $block_file ) );
Why is this added?

2023-02-20 13:24 UTC, bsf-zanev commented on admin-core/assets/src/dashboard-app/pages/settings/block-settings/Login.js
> +import apiFetch from '@wordpress/api-fetch';
This file has been removed.

2023-02-20 13:25 UTC, bsf-zanev commented on classes/class-uagb-block.php
> +				die( file_exists( $block_file ) );
This part of code was not added by me - checking the commit history I found that this was pulled from the working Login/Register Fix Branch - It never gets triggered though, I've safely removed it.

[Link to Commit](https://github.com/brainstormforce/ultimate-addons-for-gutenberg/commit/2d39e181254f19998fb659cb84137ab7318d71c2#diff-b4990594ed5de366b05d14f81e7f12ea574ee5f3a7836aabf499289f7fcecf82).

2023-03-06 10:58 UTC, adi3890 commented on admin-core/ajax/common-settings.php
> +			wp_send_json_error( $response_data );
same as above

2023-03-06 10:58 UTC, adi3890 commented on admin-core/ajax/common-settings.php
> +	 * @return void
since missing

2023-03-06 10:58 UTC, adi3890 commented on admin-core/ajax/common-settings.php
> +		$response_data = array( 'messsage' => $this->get_error_msg( 'permission' ) );
can you check comments mentioned in above function for this too.

2023-03-06 10:58 UTC, adi3890 commented on admin-core/ajax/common-settings.php
> +		\UAGB_Admin_Helper::update_admin_settings_option( 'uag_insta_linked_accounts', $this->sanitize_form_inputs( $value ) );
Is it ok to save empty array if $_POST['value'] is not set.
this way it seems like minor manipulation can reset data

2023-03-06 10:58 UTC, adi3890 commented on admin-core/assets/src/dashboard-app/SettingsSavedNotification.js
> +		'Account Exists!',
are these strings appearing on frontend, should this be transaltable.

2023-03-06 10:58 UTC, adi3890 commented on admin-core/assets/src/dashboard-app/SettingsSavedNotification.js
> +		'Failed to Add Account',
Please check for strings here too

2023-03-06 10:58 UTC, adi3890 commented on admin-core/assets/src/dashboard-app/pages/settings/block-settings/InstagramUnlinkPopup.js
> +import { Fragment, useRef } from 'react';
Can you please check if we can use '@wordpress/element' in place of 'react'
in this PR.

2023-03-06 10:58 UTC, adi3890 commented on admin-core/assets/src/dashboard-app/pages/settings/block-settings/InstagramUnlinkPopup.js
> +											{ __( `?`, 'ultimate-addons-for-gutenberg' ) }
Why this question mark is separate?

2023-03-06 10:58 UTC, adi3890 commented on classes/class-uagb-admin-helper.php
> +		 * @since x.x.x
Ideally we should follow same structure for comments in a project.
Reference https://d.pr/i/6BOi04

2023-03-06 11:45 UTC, adi3890 commented on classes/class-uagb-admin-helper.php
> +			for ( $i = 0; $i < $total_users; $i++ ) {
we should check for ! is_array or empty to return early.
This throw error in the PHPStan implementation

2023-03-06 11:45 UTC, adi3890 commented on classes/class-uagb-admin-helper.php
> +				$refresh_link = wp_remote_get( 'https://graph.instagram.com/refresh_access_token?grant_type=ig_refresh_token&access_token=' . $the_user['token'] );
Can you please explain why we are running wp_remote_get in the loop.
seems like this is independent of loop and maybe we can retrieve data before and can use in the loop if required.

2023-03-06 11:45 UTC, adi3890 commented on classes/class-uagb-admin-helper.php
> +		 * Refresh All Users.
Description seems very generic. It may not solve the purpose.

2023-03-07 00:48 UTC, bsf-zanev commented on admin-core/ajax/common-settings.php
> +		if ( empty( $_POST ) ) {
By my understanding it should, but there may be a case that I'm unaware of since this practice has been followed for all the common settings methods - including the more recent ones.

2023-03-07 00:50 UTC, bsf-zanev commented on admin-core/ajax/common-settings.php
> +	 * @return void
I've added since to the PHP Doc Comments for both the Instagram Methods, the rest of the Doc Comments that missing for methods not related to this PR have been skipped, as they should be done in the optimization PR.

2023-03-07 00:51 UTC, bsf-zanev commented on admin-core/ajax/common-settings.php
> +			wp_send_json_error( $response_data );
I've added arrays directly in all the wp_send_json functions.

2023-03-07 00:51 UTC, bsf-zanev commented on admin-core/ajax/common-settings.php
> +			wp_send_json_error( $response_data );
I've added arrays directly in all the wp_send_json functions.

2023-03-07 00:51 UTC, bsf-zanev commented on admin-core/ajax/common-settings.php
> +	 * @return void
I've added since to the PHP Doc Comments for both the Instagram Methods, the rest of the Doc Comments that missing for methods not related to this PR have been skipped, as they should be done in the optimization PR.

2023-03-07 00:51 UTC, bsf-zanev commented on admin-core/ajax/common-settings.php
> +		$response_data = array( 'messsage' => $this->get_error_msg( 'permission' ) );
I've added arrays directly in all the wp_send_json functions.

2023-03-07 00:51 UTC, bsf-zanev commented on admin-core/assets/src/dashboard-app/pages/settings/block-settings/InstagramUnlinkPopup.js
> +import { Fragment, useRef } from 'react';
Replaced React with WP Elements.

2023-03-07 00:53 UTC, bsf-zanev commented on admin-core/assets/src/dashboard-app/pages/settings/block-settings/InstagramUnlinkPopup.js
> +											{ __( `?`, 'ultimate-addons-for-gutenberg' ) }
That question mark is separate since we show the username variable between the translated text - and we can't translate variables.

I'd attempted to use sprintf as well, but to no avail.

Any possible suggestion for this one?

2023-03-07 01:14 UTC, bsf-zanev commented on admin-core/ajax/common-settings.php
> +		\UAGB_Admin_Helper::update_admin_settings_option( 'uag_insta_linked_accounts', $this->sanitize_form_inputs( $value ) );
This is done to check in the admin if the last user has been unlinked - if so, then the no users placeholder is used in the dashboard.

If no value was posted, the last user was unlinked, so the option is set to an empty array. The posted value is an updated user matrix of the currently linked IG Users.

2023-03-07 06:41 UTC, bsf-zanev commented on admin-core/assets/src/dashboard-app/SettingsSavedNotification.js
> +		'Account Exists!',
These strings are not appearing on front-end, they're just to set the type of icon.

But since these strings are compared to the internationalized strings of the same value, I've added translation to these as well as a precautionary measure.

2023-03-07 06:43 UTC, bsf-zanev commented on admin-core/assets/src/dashboard-app/SettingsSavedNotification.js
> +		'Failed to Add Account',
Changes made as stated above - I've also replaced the react components with `@wordpress/element` components.

2023-03-07 07:04 UTC, bsf-zanev commented on classes/class-uagb-admin-helper.php
> +		 * @since x.x.x
This was written long ago to match the doc comments of the functions above.

It has been updated now, but the functions above have remained untouched, as that should be done in the optimization task for the overall plugin.

2023-03-08 01:45 UTC, bsf-zanev commented on classes/class-uagb-admin-helper.php
> +			for ( $i = 0; $i < $total_users; $i++ ) {
I've added a check to return if total users is empty or is not an array.

2023-03-08 01:46 UTC, bsf-zanev commented on classes/class-uagb-admin-helper.php
> +				$refresh_link = wp_remote_get( 'https://graph.instagram.com/refresh_access_token?grant_type=ig_refresh_token&access_token=' . $the_user['token'] );
Although this check happens only once in the loop due to the continue on the very first condition in the loop, I've moved the remote get outside the loop for easier readability.

2023-03-08 01:46 UTC, bsf-zanev commented on classes/class-uagb-admin-helper.php
> +		 * Refresh All Users.
The description has been updated.

2023-03-08 02:26 UTC, bsf-zanev commented on admin-core/ajax/common-settings.php
> +		$value = isset( $_POST['value'] ) ? json_decode( stripslashes( $_POST['value'] ), true ) : array(); // phpcs:ignore
I've added comments stating why the PHPCS Rule `WordPress.Security.ValidatedSanitizedInput.InputNotSanitized` is ignored, and why `stripslashes()` is used instead of `wp_unslash()`.

Since both the function values are arrays of arrays, we're using the class method `sanitize_form_inputs()` to recursively sanitizise the data in the array of arrays.

2023-03-08 11:34 UTC, adi3890 commented on admin-core/assets/src/dashboard-app/pages/settings/block-settings/InstagramUnlinkPopup.js
> +/* This example requires Tailwind CSS v2.0+ */
Please replace this with relevant desscription

2023-03-08 11:34 UTC, adi3890 commented on admin-core/assets/src/dashboard-app/pages/settings/block-settings/InstagramUnlinkPopup.js
> +											{ __( `?`, 'ultimate-addons-for-gutenberg' ) }
Can you please try this https://github.com/brainstormforce/cartflows/blob/master/admin-core/assets/src/fields/ProNotification.js#L38

2023-03-08 11:58 UTC, adi3890 commented on admin-core/assets/src/dashboard-app/pages/settings/block-settings/InstagramUnlinkPopup.js
> +											{ __( `?`, 'ultimate-addons-for-gutenberg' ) }
Can you please try this https://github.com/brainstormforce/cartflows/blob/master/admin-core/assets/src/fields/ProNotification.js#L38

2023-03-09 01:27 UTC, bsf-zanev commented on admin-core/assets/src/dashboard-app/pages/settings/block-settings/InstagramUnlinkPopup.js
> +											{ __( `?`, 'ultimate-addons-for-gutenberg' ) }
I've added the same, and implemented sprintf in the Rollback Popup as well. ( And Tested )

2023-03-09 01:28 UTC, bsf-zanev commented on admin-core/assets/src/dashboard-app/pages/settings/block-settings/InstagramUnlinkPopup.js
> +/* This example requires Tailwind CSS v2.0+ */
I've updated the same in this popup, as well as the rollback popup which this popup was based on.

2023-03-10 03:01 UTC, adi3890 approved these changes

2023-03-17 09:27 UTC, RajkiranBagal approved these changes

2023-03-20 13:19 UTC, RajkiranBagal approved these changes

2023-03-20 13:19 UTC, merged