SPCTR-1778 Fix: Resolved customizer get stuck when theme blog settings has been changed.
brainstormforce/ultimate-addons-for-gutenberg pull request #2321
Opened 2022-09-20 10:46 UTC by AbhijitNage123

### Description

- https://brainstormforce.atlassian.net/browse/SPCTR-1778

### Screenshots

- https://share.getcloudapp.com/WnuDl6JK

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

### How has this been tested?

- Added to the card.

### Checklist:
- [x] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [x] I've included any necessary tests 
- [ ] I've included developer documentation 
- [x] I've added proper labels to this pull request

2022-09-21 06:07 UTC, supriyajjadhav approved these changes

2022-09-26 11:23 UTC, RajkiranBagal requested changes

2022-09-26 11:23 UTC, RajkiranBagal commented on README.md
> +* Fix: Resolved customizer get stuck when theme blog settings has been change.
Check Grammar

2022-09-26 11:41 UTC, AbhijitNage123 commented on README.md
> +* Fix: Resolved customizer get stuck when theme blog settings has been change.
Resolved. `Fix: Customizer was frozen when theme blog settings were changed.`

2022-09-26 12:22 UTC, RajkiranBagal approved these changes

2022-09-26 12:23 UTC, merged