SPCTR-1851 - Fix: FAQ - Throwing an undefined style issue in console when html anchor is used.
brainstormforce/ultimate-addons-for-gutenberg pull request #2322
Opened 2022-09-21 10:21 UTC by supriyajjadhav

### Description
Fix: FAQ - Throwing an undefined style issue in console when html anchor is used.

### Screenshots
Testing Evidence - https://share.getcloudapp.com/z8uQPYD6

### Types of changes
Bug fix (non-breaking change which fixes an issue) 

### How has this been tested?

### Checklist:
- [x] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [x] I've added proper labels to this pull request

2022-09-22 04:51 UTC, AbhijitNage123 requested changes

2022-09-22 04:51 UTC, AbhijitNage123 commented on assets/js/faq.js
> +			const faqContent =  elementToOpen.getElementsByClassName( 'uagb-faq-content' )[0];
Can we use directly below code instead of adding extra condition.
`elementToOpen?.getElementsByClassName( 'uagb-faq-content' )[ 0 ],
				500
			);`

2022-09-22 05:59 UTC, supriyajjadhav commented on assets/js/faq.js
> +			const faqContent =  elementToOpen.getElementsByClassName( 'uagb-faq-content' )[0];
@AbhijitNage123 This will return undefined in the function parameter, So we need to check first if this is not undefined, then only we can call the function.

2022-09-22 06:33 UTC, AbhijitNage123 reviewed
@supriyajjadhav Need the same condition for all slideDown as well as slideUp functions. Please update it accordingly. Seem like you only update at one line

2022-09-22 06:41 UTC, AbhijitNage123 approved these changes

2022-09-22 06:46 UTC, supriyajjadhav commented
> @supriyajjadhav Need the same condition for all slideDown as well as slideUp functions. Please update it accordingly. Seem like you only update at one line

@AbhijitNage123 Tested all the possible cases. We no need to add conditions everywhere.

2022-09-22 06:47 UTC, AbhijitNage123 approved these changes

2022-09-26 11:34 UTC, RajkiranBagal requested changes

2022-09-26 11:34 UTC, RajkiranBagal commented on assets/js/faq.js
> +			if( faqContent !== undefined ){
Can we write `if ( faqContent ) {`

2022-09-26 11:51 UTC, supriyajjadhav commented on assets/js/faq.js
> +			if( faqContent !== undefined ){
yes, updated code with suggested changes

2022-09-26 12:02 UTC, RajkiranBagal approved these changes

2022-09-26 12:48 UTC, RajkiranBagal approved these changes

2022-09-26 12:51 UTC, RajkiranBagal approved these changes

2022-09-26 12:53 UTC, merged