SPCTR-1795-Forms Block Multiple issues fix
brainstormforce/ultimate-addons-for-gutenberg pull request #2324
Opened 2022-09-22 09:29 UTC by jamyrbsf

### Description
https://brainstormforce.atlassian.net/browse/SPCTR-1795

### Screenshots
N/A

### Types of changes
Bug Fix:
1. Border fix  on the editor for phone/ Country code field is not aligned properly in the editor -> Fixed
2. fixed phone drop icon responsive:
editor-> fixed
Frontend -> fixed
3. black frontend arrow (#1D2327) → fixed
spacing -> fixed
4. mobile overlapping country code text with drop icon:
frontend -> fixed
5. Height issue on the form phone child block:
editor -> fixed

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2022-09-26 09:26 UTC, AbhijitNage123 approved these changes

2022-09-26 10:19 UTC, AbhijitNage123 approved these changes

2022-09-26 12:07 UTC, RajkiranBagal requested changes

2022-09-26 12:07 UTC, RajkiranBagal commented on README.md
> +* Fix: Forms - phone option (Country code) dropdown arrow position is responsive.
Please review changelog yourself & make it perfect.

2022-09-27 12:34 UTC, jamyrbsf commented on README.md
> +* Fix: Forms - phone option (Country code) dropdown arrow position is responsive.
Fixed this issue

2022-10-06 09:41 UTC, RajkiranBagal approved these changes

2022-10-06 10:17 UTC, RajkiranBagal approved these changes

2022-10-06 10:17 UTC, merged