SPCTR-1794 - Post Carousel - Taxonomy Meta looks different after upgrading from v1.25.6 to Spectra
brainstormforce/ultimate-addons-for-gutenberg pull request #2326
Opened 2022-09-26 06:50 UTC by supriyajjadhav

### Description
Post Carousel - Taxonomy Meta looks different after upgrading from v1.25.6 to Spectra

### Screenshots

### Types of changes

### How has this been tested?

### Checklist:
- [x] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [x] I've added proper labels to this pull request

2022-09-26 12:01 UTC, RajkiranBagal requested changes

2022-09-26 12:01 UTC, RajkiranBagal commented on README.md
> +* Fix: Post carousel - Taxonomy layout is breaking on both the sides.
Please add proper descriptive changelog

2022-09-26 12:16 UTC, supriyajjadhav commented on README.md
> +* Fix: Post carousel - Taxonomy layout is breaking on both the sides.
Updated changelog

2022-10-06 11:00 UTC, RajkiranBagal approved these changes

2022-10-06 11:53 UTC, RajkiranBagal approved these changes

2022-10-06 11:54 UTC, merged