SPCTR-1773 Fix: Review Schema - Star ratings does not reflect on the frontend same as editor when multiple review block used.
brainstormforce/ultimate-addons-for-gutenberg pull request #2327
Opened 2022-09-26 10:12 UTC by AbhijitNage123

### Description

- https://brainstormforce.atlassian.net/browse/SPCTR-1773

### Screenshots

- https://share.getcloudapp.com/04uW2xGW

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

### How has this been tested?

- Added to the card.

### Checklist:
- [x] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [x] I've included any necessary tests 
- [ ] I've included developer documentation 
- [x] I've added proper labels to this pull request

2022-09-26 12:12 UTC, RajkiranBagal requested changes

2022-09-26 12:12 UTC, RajkiranBagal commented on readme.txt
> +* Fix: Review Schema - Stars appear left in editor and right on frontend issue when clicked.
Fix: Review Schema - Stars appear left in editor and right on frontend  when clicked.

2022-09-26 12:23 UTC, AbhijitNage123 commented on readme.txt
> +* Fix: Review Schema - Stars appear left in editor and right on frontend issue when clicked.
Resolved

2022-09-27 04:13 UTC, RajkiranBagal approved these changes

2022-09-27 07:34 UTC, RajkiranBagal approved these changes

2022-09-27 07:38 UTC, merged