SPCTR-1890 Info Box - Remove default image width for new users only
brainstormforce/ultimate-addons-for-gutenberg pull request #2330
Opened 2022-09-28 11:07 UTC by aapatre

### Description

- Info Box - Remove default image width for new users only
- For old users the default image width must be 120px
- [JIRA](url)

### Screenshots
- https://d.pr/v/Ztq8Go
- https://d.pr/v/IU3LR9

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

### How has this been tested?

### Checklist:
- [x] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [x] I've added proper labels to this pull request

2022-09-28 13:22 UTC, RajkiranBagal requested changes

2022-09-28 13:22 UTC, RajkiranBagal commented on src/blocks/info-box/attributes.js
> + const imageWidthDefault = ( 'yes' === uagb_blocks_info.uagb_old_user_less_than_2 ) ? 120 : undefined;
set it '' instead of undefined

2022-09-29 04:35 UTC, aapatre commented on src/blocks/info-box/attributes.js
> + const imageWidthDefault = ( 'yes' === uagb_blocks_info.uagb_old_user_less_than_2 ) ? 120 : undefined;
Done

2022-09-29 05:28 UTC, RajkiranBagal approved these changes

2022-09-29 05:40 UTC, RajkiranBagal approved these changes

2022-09-29 05:40 UTC, merged