SPCTR-1872 Fix: Form block - Checkbox throw an issue in console when required toggle is ON.
brainstormforce/ultimate-addons-for-gutenberg pull request #2339
Opened 2022-10-03 05:41 UTC by raojip

### Description
https://brainstormforce.atlassian.net/browse/SPCTR-1872
Fix:- Checkbox throws an issue in the console when the required toggle is ON.

### Screenshots
Here is the Tested Video:-  [https://d.pr/v/oriPwz]

### Types of changes

Bug fix (non-breaking change which fixes an issue)

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2022-10-03 07:42 UTC, RajkiranBagal requested changes

2022-10-03 07:42 UTC, RajkiranBagal commented on src/blocks/forms/style.scss
> +	// visibility: hidden;
Do not keep commented code. If it's not needed then remove it.

2022-10-03 07:42 UTC, RajkiranBagal commented on src/blocks/forms/child-blocks/checkbox/save.js
> -							onInvalid="this.setCustomValidity('Please check this box if you want to proceed.')"
Why was this removed?

2022-10-03 11:09 UTC, raojip commented on src/blocks/forms/child-blocks/checkbox/save.js
> -							onInvalid="this.setCustomValidity('Please check this box if you want to proceed.')"
This is creating an issue in the checkbox

2022-10-03 11:26 UTC, raojip commented on src/blocks/forms/style.scss
> +	// visibility: hidden;
Removed

2022-10-04 12:58 UTC, AbhijitNage123 commented on src/blocks/forms/child-blocks/checkbox/save.js
> -							onInvalid="this.setCustomValidity('Please check this box if you want to proceed.')"
You are removing code from save.js. Have u tested the backward case? (Creating forms with a checkbox in v2.0.13 and switching to your branch to verify is it throwing any validation issue by keeping auto-block recovery off)

2022-10-06 03:30 UTC, AbhijitNage123 commented on src/blocks/forms/child-blocks/checkbox/save.js
> -							onInvalid="this.setCustomValidity('Please check this box if you want to proceed.')"
@raojip ^

2022-10-10 12:47 UTC, raojip commented on src/blocks/forms/child-blocks/checkbox/save.js
> -							onInvalid="this.setCustomValidity('Please check this box if you want to proceed.')"
Added the deprecated file because of block recovery issue.

2022-10-11 04:39 UTC, AbhijitNage123 approved these changes

2022-10-17 13:19 UTC, RajkiranBagal approved these changes

2022-10-18 12:46 UTC, RajkiranBagal approved these changes

2022-10-18 12:46 UTC, merged