SPCTR-1901 Fix: Marketing button title color backward compatibility issue
brainstormforce/ultimate-addons-for-gutenberg pull request #2350
Opened 2022-10-06 11:34 UTC by jamyrbsf

### Description
https://brainstormforce.atlassian.net/browse/SPCTR-1901

### Screenshots
https://share.getcloudapp.com/E0uZyxdP

### Types of changes
CSS changes in frontend.css.php file to add the backward compatibility cases.

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2022-10-07 05:10 UTC, RajkiranBagal requested changes

2022-10-07 05:10 UTC, RajkiranBagal commented on readme.txt
> +* FIx: Marketing Button - Backward Compatibility title color and hover issue on the frontend.
`Fix`

2022-10-07 05:14 UTC, jamyrbsf commented on readme.txt
> +* FIx: Marketing Button - Backward Compatibility title color and hover issue on the frontend.
Fixed this issue.

2022-10-07 05:33 UTC, RajkiranBagal approved these changes

2022-10-17 11:03 UTC, RajkiranBagal approved these changes

2022-10-17 11:08 UTC, merged