SPCTR-1889 - Fix: Container - Does not work properly when it is used inside cover block.
brainstormforce/ultimate-addons-for-gutenberg pull request #2354
Opened 2022-10-07 10:07 UTC by supriyajjadhav

### Description
 Fix: Container - Does not work properly when it is used inside the cover block.

### Types of changes
Bug fix (non-breaking change which fixes an issue) 

### How has this been tested?
Testing Evidence - [Screen Recording 07-10-2022 at 15.55](https://share.getcloudapp.com/L1u99918)

### Checklist:
- [x] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [x] I've added proper labels to this pull request

2022-10-07 12:35 UTC, RajkiranBagal requested changes

2022-10-07 12:35 UTC, RajkiranBagal commented on src/blocks/container/edit.js
> +		if ( parentBlockName[0] && 'uagb/container' !== parentBlockName[0].name ) {
What if there is not parent at all?

2022-10-07 12:59 UTC, supriyajjadhav commented on src/blocks/container/edit.js
> +		if ( parentBlockName[0] && 'uagb/container' !== parentBlockName[0].name ) {
Yes, Updated condition.

2022-10-17 09:42 UTC, RajkiranBagal approved these changes

2022-10-17 09:45 UTC, RajkiranBagal approved these changes

2022-10-17 09:59 UTC, merged