SPCTR-1899 - Fix: TOC - If the list is empty then getting a console error on the front-end.
brainstormforce/ultimate-addons-for-gutenberg pull request #2358
Opened 2022-10-10 06:20 UTC by raojip

### Description
https://brainstormforce.atlassian.net/browse/SPCTR-1899
Fix: TOC - If the list is empty then getting a console error on the front-end.

### Screenshots
Here is the tested video:- https://d.pr/v/OAHqlt

### Types of changes

 Bug fix (non-breaking change which fixes an issue)

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2022-10-10 06:34 UTC, AbhijitNage123 commented on README.md
> +* Fix: TOC - If the list is empty then getting a console error on the front-end.
`Fix: Table Of Contents - Empty heading list, throwing a console error on the front end.`

2022-10-10 06:46 UTC, raojip commented on README.md
> +* Fix: TOC - If the list is empty then getting a console error on the front-end.
Added

2022-10-10 07:02 UTC, AbhijitNage123 commented on assets/js/table-of-contents.js
>  				let headerText = parseTocSlug( divsArr[i].innerText );
What if we don't allow empty headings? Can we add condition like this - `if( '' !== divsArr[i].innerText )`

2022-10-10 07:26 UTC, raojip commented on assets/js/table-of-contents.js
>  				let headerText = parseTocSlug( divsArr[i].innerText );
Yes, This is working fine, I added this code.

2022-10-10 08:55 UTC, RajkiranBagal requested changes

2022-10-10 08:55 UTC, RajkiranBagal commented on assets/js/table-of-contents.js
> +				if( '' !== divsArr[i].innerText ) {
Please explain why we have checked this condition with respect to the console error?

2022-10-10 09:07 UTC, raojip commented on assets/js/table-of-contents.js
> +				if( '' !== divsArr[i].innerText ) {
Like here we not allowing empty headings, in the console if we don't have any headings then error occurs, that is why we use this if heading not empty then below code work.

2022-10-10 09:15 UTC, raojip commented on assets/js/table-of-contents.js
> +				if( '' !== divsArr[i].innerText ) {
we can use this is also,  if ( headerText.length < 0 ) instead of this if ( headerText.length < 1 )

2022-10-11 03:22 UTC, raojip commented on assets/js/table-of-contents.js
> +				if( '' !== divsArr[i].innerText ) {
We check this condition because on the console we are getting the error like "cannot read properties of null" because of our const divsArr = Array.from( allHeader ); this line is empty and tocListWrap variable can't read any querySelector, so 
we are getting errors like  "cannot read properties of null (reading getElementsByTagName)"  ;

CC:- @RajkiranBagal

2022-10-11 04:49 UTC, AbhijitNage123 approved these changes

2022-10-17 11:21 UTC, RajkiranBagal approved these changes

2022-10-17 11:26 UTC, merged