SPCTR-1855 Fix: Table of contents - On the front end, reusable headings are not listed-down in to block.
brainstormforce/ultimate-addons-for-gutenberg pull request #2363
Opened 2022-10-11 13:18 UTC by AbhijitNage123

### Description

- https://brainstormforce.atlassian.net/browse/SPCTR-1855

### Screenshots

- https://share.getcloudapp.com/P8u72x2Q

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

### How has this been tested?

- Added in the card.

### Checklist:
- [x] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [x] I've included any necessary tests 
- [ ] I've included developer documentation 
- [x] I've added proper labels to this pull request

2022-10-12 09:17 UTC, RajkiranBagal approved these changes

2022-10-17 10:11 UTC, RajkiranBagal requested changes

2022-10-17 10:11 UTC, RajkiranBagal commented on README.md
> +* Fix: Table Of Contents - On the front end, reusable headings are not listed-down in to block.
Fix: Table Of Contents - Reusable headings are not listed in TOC on the frontend.

@AbhijitNage123 Update to this 👆

2022-10-17 10:24 UTC, AbhijitNage123 commented on README.md
> +* Fix: Table Of Contents - On the front end, reusable headings are not listed-down in to block.
Updated.

2022-10-17 10:36 UTC, RajkiranBagal approved these changes

2022-10-17 10:36 UTC, merged