Spctr-1912  Fix: Info Box - Some translation waas missing for some blocks.
brainstormforce/ultimate-addons-for-gutenberg pull request #2374
Opened 2022-10-18 14:13 UTC by jamyrbsf

### Description
https://brainstormforce.atlassian.net/browse/SPCTR-1912

### Screenshots
Not avalable 

### Types of changes
Changes in attributes.js in info to make the default translatable for loco translate.

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2022-10-19 04:38 UTC, RajkiranBagal requested changes

2022-10-19 04:38 UTC, RajkiranBagal commented on README.md
> +* Fix: Info Box - Some translation waas missing for some blocks.
Please add a proper changelog. 

- Check for spelling mistakes.
- You have written Info Box at the start & further it's written for some blocks, which is confusing.

2022-10-19 05:00 UTC, jamyrbsf commented on README.md
> +* Fix: Info Box - Some translation waas missing for some blocks.
Added a proper changelog.

2022-10-19 05:51 UTC, RajkiranBagal commented on README.md
> +* Fix: Info Box - Some translation waas missing for some blocks.
@jamyrbsf I see changes in Call to Action Block & not Info Box. Am I missing something? 

Also Update PR title.

2022-10-19 06:34 UTC, AbhijitNage123 requested changes

2022-10-19 06:34 UTC, AbhijitNage123 commented on src/blocks/call-to-action/attributes.js
> +		default: __( 'Call To Action' ),
Text-domain is missing. Translation format should be like this - `__( 'Call To Action', 'ultimate-addons-for-gutenberg' )`

2022-10-19 06:34 UTC, AbhijitNage123 commented on src/blocks/call-to-action/attributes.js
> +			__( 'Click here to change this text. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo.' ),
Text-domain is missing.

2022-10-19 06:34 UTC, AbhijitNage123 commented on src/blocks/call-to-action/attributes.js
> +		default: __( 'Read More' ),
Text-domain is missing.

2022-10-19 06:34 UTC, AbhijitNage123 commented on src/blocks/call-to-action/attributes.js
> +		default: __( 'Click Here' ),
Text-domain is missing.

2022-10-19 06:38 UTC, AbhijitNage123 requested changes

2022-10-19 07:31 UTC, jamyrbsf commented on README.md
> +* Fix: Info Box - Some translations were missing.
Updated this text

2022-10-19 07:31 UTC, jamyrbsf commented on src/blocks/call-to-action/attributes.js
> +		default: __( 'Click Here' ),
Text-domain added

2022-10-19 07:31 UTC, jamyrbsf commented on src/blocks/call-to-action/attributes.js
> +		default: __( 'Read More' ),
Text-domain added

2022-10-19 07:31 UTC, jamyrbsf commented on src/blocks/call-to-action/attributes.js
> +			__( 'Click here to change this text. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo.' ),
Text-domain added

2022-10-19 07:31 UTC, jamyrbsf commented on src/blocks/call-to-action/attributes.js
> +		default: __( 'Call To Action' ),
Text-domain added

2022-10-19 07:32 UTC, jamyrbsf commented on README.md
> +* Fix: Info Box - Some translation waas missing for some blocks.
I have updated the pr name, and added text-domain and also updated changelog

2022-10-20 12:24 UTC, RajkiranBagal approved these changes

2022-10-21 14:31 UTC, merged