SPCTR-1910 Fix: Z-index extension - Was not working for the dynamic block.
brainstormforce/ultimate-addons-for-gutenberg pull request #2376
Opened 2022-10-19 08:44 UTC by AbhijitNage123

### Description

- https://brainstormforce.atlassian.net/browse/SPCTR-1910

### Screenshots

- Screencast - https://share.getcloudapp.com/6quGo7bn
- Screenshot - https://share.getcloudapp.com/OAujZEyR

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

### How has this been tested?

- Added to the card.

### Checklist:
- [x] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [x] I've included any necessary tests 
- [ ] I've included developer documentation 
- [x] I've added proper labels to this pull request

2022-10-19 09:02 UTC, aapatre approved these changes
Once Image Gallery, Counter, Login, Register blocks are merged, we can probably even create a PHP helper function for z-index functionality

2022-10-19 09:07 UTC, RajkiranBagal requested changes

2022-10-19 09:07 UTC, RajkiranBagal commented on README.md
> +* Fix: Z-index extension - Was not working for dynamic block.
```suggestion
* Fix: Z-Index extension is not working for the dynamic blocks.
```

2022-10-19 09:07 UTC, RajkiranBagal commented on blocks-config/lottie/class-uagb-lottie.php
> +			if ( array_key_exists( 'zIndex', $attributes ) || array_key_exists( 'zIndexTablet', $attributes ) || array_key_exists( 'zIndexMobile', $attributes ) ) {
This is a very un optimized may of doing this logic. Please improve this. Avoid unnecessary function calls & condition checks.

2022-10-19 10:04 UTC, AbhijitNage123 commented on blocks-config/lottie/class-uagb-lottie.php
> +			if ( array_key_exists( 'zIndex', $attributes ) || array_key_exists( 'zIndexTablet', $attributes ) || array_key_exists( 'zIndexMobile', $attributes ) ) {
I removed unnecessary condition checks from the variable. Please re-check.

2022-10-19 11:12 UTC, RajkiranBagal approved these changes

2022-10-20 07:33 UTC, RajkiranBagal approved these changes

2022-10-20 07:42 UTC, merged