SPCTR-1936 - Fix: Marketing Button - Block does not remain in the stack order when the blocksy theme is active.
brainstormforce/ultimate-addons-for-gutenberg pull request #2384
Opened 2022-10-20 09:59 UTC by raojip

### Description
Fix: Marketing Button - Block does not remain in the stack order when the Blocksy theme is active.
https://brainstormforce.atlassian.net/browse/SPCTR-1936

### Screenshots
Here is the tested video:-  https://d.pr/v/5AQKth

### Types of changes

 Bug fix (non-breaking change which fixes an issue)

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2022-10-20 12:24 UTC, RajkiranBagal approved these changes

2022-11-02 09:01 UTC, RajkiranBagal approved these changes

2022-11-07 04:10 UTC, RajkiranBagal requested changes

2022-11-07 04:10 UTC, RajkiranBagal commented on src/blocks/marketing-button/styling.js
> +	const id = `.editor-styles-wrapper .uagb-block-${ props.clientId.substr( 0, 8 ) }.wp-block-button:not(.is-style-outline)`;
Adding this will have too many test cases for each & every styling.

2022-11-07 06:04 UTC, raojip commented on src/blocks/marketing-button/styling.js
> +	const id = `.editor-styles-wrapper .uagb-block-${ props.clientId.substr( 0, 8 ) }.wp-block-button:not(.is-style-outline)`;
Yes, because blocksy theme styling priority is high, that why Abhijit suggestion me to increase here priority.
also, I tried different things but those are not working, then Abhijit suggested this.

2022-11-07 06:22 UTC, AbhijitNage123 commented on src/blocks/marketing-button/styling.js
> +	const id = `.editor-styles-wrapper .uagb-block-${ props.clientId.substr( 0, 8 ) }.wp-block-button:not(.is-style-outline)`;
Right, increasing priority directly to selector wan't working so we increases the priority of base selector. @raojip Please confirm you have tested this apart from blocksy and GeneratePress theme try with other theme like 2022, Astra. make sure all setting is working fine.

2022-11-07 06:24 UTC, RajkiranBagal commented on src/blocks/marketing-button/styling.js
> +	const id = `.editor-styles-wrapper .uagb-block-${ props.clientId.substr( 0, 8 ) }.wp-block-button:not(.is-style-outline)`;
@AbhijitNage123 @raojip Please find a better solution. Changing base selector is not ideal.

2022-11-07 09:01 UTC, raojip commented on src/blocks/marketing-button/styling.js
> +	const id = `.editor-styles-wrapper .uagb-block-${ props.clientId.substr( 0, 8 ) }.wp-block-button:not(.is-style-outline)`;
@RajkiranBagal Fixed this issue in another way.

2022-11-07 10:36 UTC, RajkiranBagal approved these changes

2022-11-09 09:55 UTC, RajkiranBagal approved these changes

2022-11-09 09:59 UTC, merged