SPCTR-1966 New Block - Style settings added for modal block
brainstormforce/ultimate-addons-for-gutenberg pull request #2390
Opened 2022-10-21 08:01 UTC by sushmak02

### Description
This task will include styling options for the modal popup triggers and their content. It will include the following settings - 
Modal Popup - overlay, box-shadow, padding, etc.
Modal trigger
Modal close button

Also, it should work correctly at the front.

### Screenshots

### Types of changes

New

### How has this been tested?

### Checklist:
- [x] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2022-10-21 10:39 UTC, RajkiranBagal approved these changes

2022-10-28 02:14 UTC, bsf-zanev commented on README.md
> +* Improvement: Table of content - Added overall block alignment option.
@AbhijitNage123 - Is this PR ahead of its base branch final-modal?

2022-10-28 02:24 UTC, bsf-zanev requested changes
The updated code is as per standards, but this branch is ahead of its base branch.

2022-10-28 04:10 UTC, AbhijitNage123 commented on README.md
> +* Improvement: Table of content - Added overall block alignment option.
Updated

2022-10-31 01:45 UTC, bsf-zanev approved these changes
Verified Changes.

2022-11-08 12:49 UTC, AbhijitNage123 approved these changes

2022-11-09 04:37 UTC, merged