SPCTR-1907 New Block - Modal
brainstormforce/ultimate-addons-for-gutenberg pull request #2391
Opened 2022-10-21 08:02 UTC by sushmak02

### Description
The modal block is for simple things. For example, on the SureCart website which is built with Spectra, if I have an image with a play button on it, there is no way to have a video popup. We have to add a plugin for this seemingly standard thing. 

### Screenshots

### Types of changes

New

### How has this been tested?

### Checklist:
- [x] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2022-12-23 04:08 UTC, AbhijitNage123 approved these changes

2022-12-23 04:35 UTC, bsf-zanev requested changes
Please address the comments below.

2022-12-23 04:35 UTC, bsf-zanev commented on .eslintrc.js
> +		UAGBCounter: true,
Should these two entries in eslintrc.js exist? ( UAGBModal, UAGBCounter )

2022-12-23 04:45 UTC, AbhijitNage123 commented on .eslintrc.js
> +		UAGBCounter: true,
Removing UAGBCounter and keeping UAGBModal to resolve undefined UAGBModal while running the lint-js cmd.

2022-12-26 06:26 UTC, bsf-zanev approved these changes
Looks good to me.

2022-12-26 08:23 UTC, RajkiranBagal approved these changes

2022-12-26 08:23 UTC, merged