SPCTR-1924 - Fix: Spectra CSS conflict due to which date picker of post scheduler does not show the navigation.
brainstormforce/ultimate-addons-for-gutenberg pull request #2398
Opened 2022-10-28 05:52 UTC by raojip

### Description
https://brainstormforce.atlassian.net/browse/SPCTR-1924.
- Spectra CSS conflict due to which date picker of post scheduler does not show the navigation

### Screenshots
Here is the tested video:- https://d.pr/v/cpjh9N

### Types of changes

 Bug fix (non-breaking change which fixes an issue)

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2022-10-28 09:49 UTC, RajkiranBagal approved these changes

2022-11-01 11:39 UTC, RajkiranBagal requested changes

2022-11-01 11:39 UTC, RajkiranBagal commented on README.md
> +* Fix: Fix: Spectra CSS conflict due to which date picker of post scheduler does not show the navigation.
Fix is double here.

2022-11-02 03:32 UTC, raojip commented on README.md
> +* Fix: Fix: Spectra CSS conflict due to which date picker of post scheduler does not show the navigation.
resolved PR comments

2022-11-02 11:57 UTC, RajkiranBagal approved these changes

2022-11-02 12:48 UTC, RajkiranBagal approved these changes

2022-11-02 12:50 UTC, merged