SPCTR-2007 - Fix: Responsive condition does not save when we use the legacy blocks.
brainstormforce/ultimate-addons-for-gutenberg pull request #2432
Opened 2022-11-09 12:22 UTC by raojip

### Description
(https://brainstormforce.atlassian.net/browse/SPCTR-2007)
Fix: Responsive condition does not save when we use the legacy blocks.

### Screenshots
Here is the tested video:- https://d.pr/v/FGUPY3

### Types of changes

 Bug fix (non-breaking change which fixes an issue)

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2022-11-09 13:42 UTC, RajkiranBagal requested changes

2022-11-09 13:42 UTC, RajkiranBagal commented on README.md
> +* Fix: legacy blocks - Responsive condition does not save when we use the legacy blocks.
What are Legacy Blocks? How many are there? @raojip

2022-11-09 13:56 UTC, raojip commented on README.md
> +* Fix: legacy blocks - Responsive condition does not save when we use the legacy blocks.
Legacy Block means, Legacy Widget, there are two blocks - Meta and Navigation Menu, I and @AbhijitNage123  discuss this, We do not give support for dynamic core block because they have PHP rendering, and we not give support for PHP rendering, 

cc:- @RajkiranBagal

2022-11-10 03:39 UTC, RajkiranBagal requested changes

2022-11-10 03:39 UTC, RajkiranBagal commented on README.md
> +* Fix: legacy blocks - Responsive condition does not save when we use the legacy blocks.
I see we have excluded just one block, ie core/legacy-widget, I do not see Meta & Navigation menu in this PR?

2022-11-10 03:45 UTC, raojip commented on README.md
> +* Fix: legacy blocks - Responsive condition does not save when we use the legacy blocks.
Those block are Inside the core/legacy-widget block, the main block is core/legacy-widget only.

2022-11-10 04:10 UTC, raojip commented on README.md
> +* Fix: legacy blocks - Responsive condition does not save when we use the legacy blocks.
Here is the screencast:- https://d.pr/v/xjjGPw

2022-11-10 09:58 UTC, RajkiranBagal requested changes

2022-11-10 10:29 UTC, raojip commented on README.md
> +* Fix: legacy blocks - Responsive condition does not save when we use the legacy blocks.
updated

2022-11-10 10:30 UTC, RajkiranBagal approved these changes

2022-11-11 11:02 UTC, RajkiranBagal approved these changes

2022-11-11 11:09 UTC, merged