SPCTR 2002 - Created Spectra Text Control/Component and replaced old Gutenberg TextControls and TextareaControls
brainstormforce/ultimate-addons-for-gutenberg pull request #2433
Opened 2022-11-09 12:59 UTC by aapatre

### Description
- Created a new Spectra Text Component (UAGTextControl)
- 3 variants: full-width (default), inline, textarea
- [JIRA](https://brainstormforce.atlassian.net/browse/SPCTR-2002)

### Screenshots

### Types of changes

- New feature (non-breaking change which adds functionality)
- New Spectra Component

### Checklist:
- [x] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [x] I've added proper labels to this pull request

2022-11-09 23:56 UTC, bsf-zanev commented on README.md
> +* Improvement: Spectra Text Control: New text component in settings for a more consistent styling.
The Text Control is a 2.1 Improvement, but the Readme shows it in 2.0.15.

2022-11-09 23:59 UTC, bsf-zanev commented on readme.txt
> +* Improvement: Spectra Text Control: New text component in settings for a more consistent styling.
This PR's Base needs to be NR-2.1 instead of Next release.

2022-11-10 00:02 UTC, bsf-zanev commented on src/blocks/blockquote/settings.js
> +import UAGTextControl from '@Components/text-control';
We could rename this component as SpectraTextControl - since it came after the release of Spectra 2.0. Let me know your thoughts on the same.

2022-11-10 00:03 UTC, bsf-zanev commented on src/blocks/post/post-grid/attributes.js
> +	taxDivider: {
Why was this Post Grid Attribute added here?

2022-11-10 00:05 UTC, bsf-zanev requested changes
I've added 4 comments, 3 of which are crucial.

2022-11-10 03:57 UTC, aapatre commented on src/blocks/post/post-grid/attributes.js
> +	taxDivider: {
When this block was coded, the attribute declaration was missed and hence the reset feature was not working.
To fix it I had to declare this attribute along with it's default value (please refer the taxDivider attribute in other 2 post blocks)

2022-11-10 04:01 UTC, aapatre commented on src/blocks/blockquote/settings.js
> +import UAGTextControl from '@Components/text-control';
1. The code name/prefix for most components is UAG
2. Hence this will maintain consistency in code
3. Shorter and distinct code names (or prefixes) are generally preferred
4. We also use UAG/UAGB in our markup's class names so I think this won't be an issue 🤔

2022-11-10 08:09 UTC, aapatre commented on readme.txt
> +* Improvement: Spectra Text Control: New text component in settings for a more consistent styling.
Resolving this as discussed since we are planning for 2.0.15 release

2022-11-10 08:09 UTC, aapatre commented on README.md
> +* Improvement: Spectra Text Control: New text component in settings for a more consistent styling.
Resolving this as discussed since we are planning for 2.0.15 release

2022-11-10 11:18 UTC, bsf-zanev approved these changes
All updates verified and approved.

2022-11-10 11:21 UTC, RajkiranBagal approved these changes

2022-11-11 06:29 UTC, RajkiranBagal approved these changes

2022-11-11 06:29 UTC, merged