SPCTR-2052 - Package Testing v2.0.15 container slanted lines issue
brainstormforce/ultimate-addons-for-gutenberg pull request #2451
Opened 2022-11-15 12:25 UTC by supriyajjadhav

### Description

### Types of changes

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2022-11-15 12:41 UTC, RajkiranBagal requested changes

2022-11-15 12:41 UTC, RajkiranBagal commented on blocks-config/uagb-controls/responsiveConditionPreview.js
> +                        $style.innerHTML += '#block-' + props.clientId + '.uagb-editor-preview-mode-desktop:before{ content: ""; display: block; position: absolute; top: 0; left: 0; width: 100%; heig
We can remove this & below code as common?

2022-11-15 12:41 UTC, supriyajjadhav commented on blocks-config/uagb-controls/responsiveConditionPreview.js
> +                        $style.innerHTML += '#block-' + props.clientId + '.uagb-editor-preview-mode-desktop:before{ content: ""; display: block; position: absolute; top: 0; left: 0; width: 100%; heig
No, Selectors are different.

2022-11-15 13:06 UTC, RajkiranBagal approved these changes

2022-11-16 04:04 UTC, RajkiranBagal approved these changes

2022-11-16 04:04 UTC, merged