SPCTR-2044: Fix - Border: Misaligned reset control button issue.
brainstormforce/ultimate-addons-for-gutenberg pull request #2454
Opened 2022-11-15 15:00 UTC by raojip

### Description
- https://brainstormforce.atlassian.net/browse/SPCTR-2044
- Fix - Border: Misaligned reset control button issue.

### Screenshots
- Here is the tested video:- https://d.pr/v/rtmfOQ

### Types of changes

Bug fix (non-breaking change which fixes an issue)

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2022-11-16 04:08 UTC, RajkiranBagal requested changes

2022-11-16 04:08 UTC, RajkiranBagal commented on src/styles/control-header.scss
> -			margin-right: 10px;
This margin right applies to all uag-resets, Did you confirm if all resets in all controls wherever this class is present is working fine?

2022-11-16 04:52 UTC, raojip commented on src/styles/control-header.scss
> -			margin-right: 10px;
Yes, I Tested this with all blocks, it working fine. (Tested video:- https://d.pr/v/mrPeGZ)

2022-11-16 05:12 UTC, RajkiranBagal commented on src/styles/control-header.scss
> -			margin-right: 10px;
I did not say all Blocks @raojip. Please read the comment carefully.

2022-11-16 05:14 UTC, RajkiranBagal commented on src/styles/control-header.scss
> -			margin-right: 10px;
I can see in the video you shared for spacing control the reset icon is misaligned.

2022-11-20 16:11 UTC, raojip commented on src/styles/control-header.scss
> -			margin-right: 10px;
Yes, I removed margin-right: 10px; from uag-resets class, and I checked where we use this class is working fine.
basically, where we need margin-right:10px there I added padding-left or padding-right.

2022-11-21 06:08 UTC, RajkiranBagal commented on src/styles/control-header.scss
> -			margin-right: 10px;
I see issue in video itself. @AbhijitNage123 Can you please review.

2022-11-21 12:28 UTC, AbhijitNage123 requested changes

2022-11-21 12:28 UTC, AbhijitNage123 commented on src/styles/control-header.scss
> -			margin-right: 10px;
@raojip See here - https://share.getcloudapp.com/geuO8d60 reset icon is not aligned properly with the preset setting. Verify other settings too. Use the grid ruler extension to check the alignment of the reset icon.

2022-11-22 09:03 UTC, raojip commented on src/styles/control-header.scss
> -			margin-right: 10px;
Fixed the alignment issue with the preset setting, and tested it properly for all settings, now working fine, please check.

2022-11-28 12:05 UTC, AbhijitNage123 approved these changes

2022-11-29 02:34 UTC, RajkiranBagal approved these changes

2022-11-29 02:52 UTC, RajkiranBagal approved these changes

2022-11-29 02:52 UTC, merged