Spctr 2058 Fix: Icon List - Resolved an issue as the link was getting disabled for the icon list child.
brainstormforce/ultimate-addons-for-gutenberg pull request #2469
Opened 2022-11-17 04:02 UTC by jamyrbsf

### Description
https://brainstormforce.atlassian.net/browse/SPCTR-2058

### Screenshots
https://share.getcloudapp.com/WnuZ2vdj
https://share.getcloudapp.com/4gu4QqbG
https://share.getcloudapp.com/4gu4Qq79

### Types of changes
Fixed links working issue on frontend

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2022-11-17 05:53 UTC, RajkiranBagal requested changes

2022-11-17 05:53 UTC, RajkiranBagal commented on src/blocks/icon-list-child/edit.js
> -			} else {
Why did we remove this code?

2022-11-17 05:53 UTC, RajkiranBagal commented on src/blocks/icon-list-child/render.js
> -
Why did we remove this code?

2022-11-17 06:07 UTC, jamyrbsf commented on src/blocks/icon-list-child/edit.js
> -			} else {
It was causing the links to be disabled when the toggle is enabled. So I removed it

2022-11-17 06:07 UTC, jamyrbsf commented on src/blocks/icon-list-child/render.js
> -
This value was not used in my new code so I removed it.

2022-11-17 07:30 UTC, RajkiranBagal commented on src/blocks/icon-list-child/edit.js
> -			} else {
Did you check the case why we added that code in first place? Also you have removed the code in which we sset block_id which is unrelated here.

2022-11-18 12:48 UTC, RajkiranBagal commented on src/blocks/icon-list-child/edit.js
> -			} else {
Why we removed this check? uagb_old_user_less_than_2? It must be added for some reason, did we check that?

2022-11-18 13:00 UTC, jamyrbsf commented on src/blocks/icon-list-child/edit.js
> -			} else {
As we discussed in the call, we have used single variables to maintain 2 values which are causing some problems. sol I removed it.

2022-11-21 06:06 UTC, RajkiranBagal approved these changes

2022-11-28 11:41 UTC, RajkiranBagal approved these changes

2022-11-28 11:47 UTC, RajkiranBagal approved these changes

2022-11-28 11:47 UTC, merged