SPCTR-2083 - Fix: Post carousel block is broken on the front-end side, when we select background image.
brainstormforce/ultimate-addons-for-gutenberg pull request #2491
Opened 2022-11-23 05:05 UTC by raojip

### Description
https://brainstormforce.atlassian.net/browse/SPCTR-2083
Fix: block is broken on the front-end side, we we select background image.

### Screenshots
- Here is the tested video:- https://d.pr/v/sBGPcU

### Types of changes

 Bug fix (non-breaking change which fixes an issue) 

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2022-11-24 04:55 UTC, AbhijitNage123 requested changes

2022-11-24 04:55 UTC, AbhijitNage123 commented on src/blocks/post/style.scss
> +		flex-wrap: wrap !important;
No need to add important here. Verify condition added in frontend.css.php file line #22 issue will resolve then.

2022-11-24 07:51 UTC, raojip commented on src/blocks/post/style.scss
> +		flex-wrap: wrap !important;
Yes, Fixed this issue with the condition added in frontend.css.php.

2022-11-24 09:42 UTC, AbhijitNage123 approved these changes

2022-11-24 10:04 UTC, RajkiranBagal approved these changes

2022-11-28 12:31 UTC, RajkiranBagal approved these changes

2022-11-28 12:34 UTC, RajkiranBagal approved these changes

2022-11-28 12:34 UTC, merged