SPCTR-2095 - Fix: Tabs - Need to removed Link option in the toolbar.
brainstormforce/ultimate-addons-for-gutenberg pull request #2498
Opened 2022-11-24 09:42 UTC by raojip

### Description
https://brainstormforce.atlassian.net/browse/SPCTR-2095
Fix: Tabs - Need to removed Link option in the toolbar. 

### Screenshots
Here is the tested video:- https://d.pr/v/rW0Zsi

### Types of changes

 Bug fix (non-breaking change which fixes an issue) 

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2022-11-25 04:07 UTC, RajkiranBagal requested changes

2022-11-25 04:07 UTC, RajkiranBagal commented on src/blocks/tabs/render.js
> +									allowedFormats={ [ 'core/bold', 'core/italic' ] }
As we have only allowed these formats, will these formats work now? - https://share.getcloudapp.com/p9uLEZBE

2022-11-25 07:11 UTC, raojip commented on src/blocks/tabs/render.js
> +									allowedFormats={ [ 'core/bold', 'core/italic' ] }
I fixed this issue in another way, now all other formats are working fine.

CC:- @RajkiranBagal

2022-11-25 07:14 UTC, RajkiranBagal approved these changes

2022-11-28 12:28 UTC, RajkiranBagal approved these changes

2022-11-28 12:28 UTC, merged