SPCTR-2106 - Fix: Separator issue - Unwanted space is added if the separator is used.
brainstormforce/ultimate-addons-for-gutenberg pull request #2499
Opened 2022-11-24 12:05 UTC by raojip

### Description
https://brainstormforce.atlassian.net/browse/SPCTR-2106
Fix: Separator issue - Unwanted space is added if the separator is used.

### Screenshots
Here is the tested video:- https://d.pr/v/kcnVGR

### Types of changes

### How has this been tested?

### Checklist:
- [x] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2022-11-28 06:16 UTC, RajkiranBagal requested changes

2022-11-28 06:16 UTC, RajkiranBagal commented on readme.txt
> +* Fix: Separator issue - Unwanted space is added if the separator is used.
Fix: Separator Control - Unwanted space is added if the separator is used.

2022-12-01 06:13 UTC, raojip commented on readme.txt
> +* Fix: Separator issue - Unwanted space is added if the separator is used.
Added

2022-12-01 13:57 UTC, RajkiranBagal approved these changes

2022-12-12 14:04 UTC, patilvikasj approved these changes

2022-12-12 14:08 UTC, merged