SPCTR-2094 - Fix: Tabs - Content overlapping after adding container inside tabs block.
brainstormforce/ultimate-addons-for-gutenberg pull request #2505
Opened 2022-11-28 09:16 UTC by raojip

### Description
https://brainstormforce.atlassian.net/browse/SPCTR-2094
 Fix: Tabs - Content overlapping after adding container inside tabs block.

### Screenshots
Here is the tested video:- https://d.pr/v/IhsrBS

### Types of changes

 Bug fix (non-breaking change which fixes an issue)

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2022-11-29 02:55 UTC, RajkiranBagal requested changes

2022-11-29 02:55 UTC, RajkiranBagal commented on src/blocks/container/style.scss
> +		margin-left: auto !important;
Can we try fixing this in other way? This can cause many test case as anything can be added in container.

2023-01-03 13:32 UTC, RajkiranBagal approved these changes

2023-01-05 10:30 UTC, AbhijitNage123 commented
Closing this PR as the issue is already resolved and does not persist anymore.

2023-01-05 10:30 UTC, closed without merging