SPCTR-2057 Countdown Timer Block
brainstormforce/ultimate-addons-for-gutenberg pull request #2545
Opened 2022-12-09 07:22 UTC by aapatre

### Description
- New Base Block: Countdown Timer
- This lets you add stylish, yet simple countdown timers to create a sense of urgency or hype among your audience

### Types of changes

- New block/feature (non-breaking change which adds functionality)

### How has this been tested?

### Checklist:
- [x] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [x] I've added proper labels to this pull request

2022-12-19 11:50 UTC, bsf-zanev commented on admin-core/assets/src/common/block-icons.js
> +		{ width: 40, height: 40, viewBox: '0 0 18 21', fill: 'none' },
The 18 x 21 viewbox has been updated in the Figma to match the 24 x 24 format - update the icons accordingly.

2022-12-19 12:03 UTC, bsf-zanev commented on classes/class-uagb-config.php
> +<?php
This file isn't used from 2.1 onwards.

2022-12-19 12:05 UTC, bsf-zanev requested changes
Resolve the comments mentioned above and below.

2022-12-19 12:05 UTC, bsf-zanev commented on includes/blocks/countdown/attributes.php
> + * @since 2.1.0
Add the since tag as x.x.x for any new PHP declaration.

2022-12-19 12:05 UTC, bsf-zanev commented on includes/blocks/countdown/block.php
> + * @since 2.1.0
Add the since tag as x.x.x for any new PHP declaration.

2022-12-19 12:05 UTC, bsf-zanev commented on includes/blocks/countdown/frontend.js.php
> + * @since 2.1.0
Add the since tag as x.x.x for any new PHP declaration.

2022-12-19 12:05 UTC, bsf-zanev commented on includes/blocks/countdown/frontend.css.php
> + * @since 2.1.0
Add the since tag as x.x.x for any new PHP declaration.

2022-12-20 09:40 UTC, bsf-zanev requested changes
Please address the following changes.

2022-12-20 09:40 UTC, bsf-zanev commented on blocks-config/uagb-controls/block-icons.js
> +			stroke: '#1E293B',
Use the Stroke Color Variable defined in this file.

2022-12-20 09:54 UTC, bsf-zanev approved these changes
Looks good to me.

2023-01-06 09:38 UTC, aapatre commented
I will resolve the conflicts for the release base branch, since it may be different from next-release
cc: @RajkiranBagal @bsf-zanev @AbhijitNage123

2023-01-19 09:32 UTC, merged