SPCTR-2141 - Container - core list block conflict on responsive devices on front-end
brainstormforce/ultimate-addons-for-gutenberg pull request #2570
Opened 2022-12-16 04:34 UTC by supriyajjadhav

### Description
Container - core list block conflict on responsive devices on front-end

### Types of changes
Bug fix (non-breaking change which fixes an issue) 

### How has this been tested?

### Checklist:
- [x] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [x] I've added proper labels to this pull request

2022-12-16 06:32 UTC, bsf-zanev commented on README.md
> +### 2.1.1 - WEDNESDAY, 14th DECEMBER 2022 ###
Changelog Date Incorrect.

2022-12-16 06:36 UTC, bsf-zanev requested changes
Please Update the Readme

2022-12-16 07:03 UTC, bsf-zanev approved these changes
Looks good to me.

2022-12-20 06:04 UTC, patilvikasj approved these changes

2022-12-20 09:27 UTC, patilvikasj approved these changes

2022-12-20 09:27 UTC, merged