SPCTR-2089 Global: SVG Icons for blocks looks big after switching in responsive devices inside editor.
brainstormforce/ultimate-addons-for-gutenberg pull request #2586
Opened 2022-12-28 10:34 UTC by AbhijitNage123

### Description

- https://brainstormforce.atlassian.net/browse/SPCTR-2089

### Screenshots

- https://share.getcloudapp.com/YEuDZ61G

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

### How has this been tested?

### Checklist:
- [x] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [x] I've included any necessary tests 
- [ ] I've included developer documentation 
- [x] I've added proper labels to this pull request

2022-12-29 06:40 UTC, RajkiranBagal approved these changes

2023-01-06 06:23 UTC, RajkiranBagal requested changes

2023-01-06 06:24 UTC, AbhijitNage123 commented on blocks-config/uagb-controls/renderIcon.js
> +function renderSVG( svg, setAttributes ) {
if it is not passed it is undefined. and we already check condition below.

2023-01-06 07:09 UTC, AbhijitNage123 commented on blocks-config/uagb-controls/renderIcon.js
> +function renderSVG( svg, setAttributes ) {
Resolved and tested.

2023-01-06 09:08 UTC, RajkiranBagal approved these changes

2023-01-10 07:54 UTC, merged