SPCTR-2189 Fix: Admin Dashboard - Enable legacy block options is not working for new users.
brainstormforce/ultimate-addons-for-gutenberg pull request #2629
Opened 2023-01-16 12:38 UTC by AbhijitNage123

### Description

- https://brainstormforce.atlassian.net/browse/SPCTR-2189

### Screenshots

- https://share.getcloudapp.com/NQu44yjb

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

### How has this been tested?

- Added to the card

### Checklist:
- [x] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [x] I've included any necessary tests 
- [ ] I've included developer documentation 
- [x] I've added proper labels to this pull request

2023-01-16 14:30 UTC, RajkiranBagal requested changes

2023-01-17 05:57 UTC, AbhijitNage123 commented on admin-core/assets/src/utils/setInitialState.js
> +			enableLegacyBlocks: data.uag_enable_legacy_blocks,
Did build in admin core and root as suggested. Please review again

2023-01-17 08:07 UTC, RajkiranBagal approved these changes

2023-01-17 14:48 UTC, RajkiranBagal approved these changes

2023-01-17 14:50 UTC, merged