fix:removal of get_fallback from frontend.css.php of advance-heading …
brainstormforce/ultimate-addons-for-gutenberg pull request #2633
Opened 2023-01-18 06:35 UTC by rajmohanreddy774

…block

### Description

### Screenshots

### Types of changes

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2023-01-18 10:35 UTC, adi3890 commented on includes/blocks/blockquote/frontend.css.php
> +			$author_space_mobile,
be carefull about such variables this will always give value 0
instead of this your should use
$attr['authorSpaceMobile']

2023-01-18 10:48 UTC, rajmohanreddy774 commented on includes/blocks/blockquote/frontend.css.php
> +			$author_space_mobile,
done

2023-01-26 07:16 UTC, bsf-zanev requested changes
Please address the comments below.

2023-01-26 07:16 UTC, bsf-zanev commented on includes/blocks/call-to-action/frontend.css.php
> +$ctaLeftMargin = $attr['ctaLeftSpace'];
We don't need this variable.

2023-01-26 08:08 UTC, rajmohanreddy774 commented on includes/blocks/call-to-action/frontend.css.php
> +$ctaLeftMargin = $attr['ctaLeftSpace'];
removed

2023-01-26 08:23 UTC, bsf-zanev approved these changes
Looks good to me.

2023-02-24 04:12 UTC, RajkiranBagal approved these changes

2023-02-24 04:16 UTC, merged