SPCTR-1858 - Display Conditions: Addition options to display blocks
brainstormforce/ultimate-addons-for-gutenberg pull request #2640
Opened 2023-01-19 07:44 UTC by supriyajjadhav

### Description
Display Conditions: Addition options to display blocks

### Types of changes
New feature (non-breaking change which adds functionality) 

### How has this been tested?

### Checklist:
- [x] My code is tested
- [x] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [x] I've added proper labels to this pull request

2023-02-08 14:50 UTC, RajkiranBagal requested changes

2023-02-08 14:50 UTC, RajkiranBagal commented on src/blocks/extensions/condition-block/index.js
> +				<>
Need to add checkbox here for Core Blocks

2023-02-08 15:16 UTC, supriyajjadhav commented on src/blocks/extensions/condition-block/index.js
> +				<>
Added.

2023-02-09 06:56 UTC, RajkiranBagal approved these changes

2023-02-17 15:33 UTC, merged