SPCTR-2288-code-refactor-of blocks
brainstormforce/ultimate-addons-for-gutenberg pull request #2641
Opened 2023-01-19 08:02 UTC by rajmohanreddy774

### Description
Removal of get_fallback function calls from frontend.css.php of blocks forms, gf-styler, google-map, how-to, icon-list, image, image-gallery.
### Screenshots
forms: https://d.pr/v/Rmi8Kz
gf-styler: https://d.pr/v/jEN7Od
google-map: https://d.pr/v/kjRB3q
how-to: https://d.pr/v/frVzm0
icon-list: https://d.pr/v/PMMchX
image: https://d.pr/v/d6J3my
image-gallery: https://d.pr/v/oGW7LH

### Types of changes

### How has this been tested?
- have added null value to the attributes in editor.
- using x-debug have checked the value of the attributes it take default values if we give null.
- by giving a value to the attributes it take the current value we have passed.

### Checklist:
- [x] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2023-01-26 07:11 UTC, bsf-zanev requested changes
Please address the comments below.

2023-01-26 07:11 UTC, bsf-zanev commented on includes/blocks/how-to/frontend.css.php
> +$step_gap_fallback = $attr['step_gap'];
We don't need this variable.

2023-01-26 07:11 UTC, bsf-zanev commented on includes/blocks/how-to/frontend.css.php
>  $block_name = 'how-to';
Is the Block Name being used anywhere else?

2023-01-26 08:12 UTC, rajmohanreddy774 commented on includes/blocks/how-to/frontend.css.php
> +$step_gap_fallback = $attr['step_gap'];
removed

2023-01-26 08:12 UTC, rajmohanreddy774 commented on includes/blocks/how-to/frontend.css.php
>  $block_name = 'how-to';
removed

2023-01-26 08:24 UTC, bsf-zanev approved these changes
Looks good to me.

2023-05-03 09:54 UTC, rahulvarma722 approved these changes

2023-05-03 11:11 UTC, merged