SPCTR-2299-code-refactor
brainstormforce/ultimate-addons-for-gutenberg pull request #2647
Opened 2023-01-20 09:18 UTC by rajmohanreddy774

### Description

### Screenshots

### Types of changes

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2023-01-26 07:06 UTC, bsf-zanev requested changes
Please address the comments below.

2023-01-26 07:06 UTC, bsf-zanev commented on includes/blocks/star-rating/frontend.css.php
> +$gap_fallback       = $attr['gap'];
We don't require these variables.

2023-01-26 07:06 UTC, bsf-zanev commented on includes/blocks/table-of-contents/frontend.css.php
> +$width_desktop_fallback     = $attr['widthDesktop'];
We don't require these variables either.

2023-01-26 08:21 UTC, rajmohanreddy774 commented on includes/blocks/star-rating/frontend.css.php
> +$gap_fallback       = $attr['gap'];
removed

2023-01-26 08:21 UTC, rajmohanreddy774 commented on includes/blocks/table-of-contents/frontend.css.php
> +$width_desktop_fallback     = $attr['widthDesktop'];
removed

2023-01-26 08:24 UTC, bsf-zanev approved these changes
Looks good to me.

2023-05-03 09:42 UTC, rahulvarma722 approved these changes

2023-05-03 11:11 UTC, merged