SPCTR-2201 counter typography letter spacing
brainstormforce/ultimate-addons-for-gutenberg pull request #2663
Opened 2023-01-24 11:11 UTC by rajmohanreddy774

### Description
Added letter-spacing to Typography of number and heading of counter block

### Screenshots

### Types of changes

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2023-01-24 13:05 UTC, aapatre requested changes
All good, just ensure the following:

1. Fix PHPCS issues (you can try running `phpcbf .` )
2. Do a `git pull origin next-release` on this branch and resolve conflicts (you might need to rebuild the files and commit)

2023-01-25 03:32 UTC, rajmohanreddy774 commented
> All good, just ensure the following:
> 
> 1. Fix PHPCS issues (you can try running `phpcbf .` )
> 2. Do a `git pull origin next-release` on this branch and resolve conflicts (you might need to rebuild the files and commit)

done with changes

2023-01-25 03:37 UTC, aapatre approved these changes
Good to go! 🚀

2023-01-26 03:59 UTC, AbhijitNage123 approved these changes

2023-01-26 06:44 UTC, bsf-zanev approved these changes
Looks good to me.

2023-01-30 07:46 UTC, bsf-zanev commented on .vscode/launch.json
> +    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
This comment should not be here.

2023-01-30 07:50 UTC, rajmohanreddy774 commented on .vscode/launch.json
> +    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
removed

2023-01-30 11:02 UTC, RajkiranBagal approved these changes

2023-02-08 14:40 UTC, RajkiranBagal approved these changes

2023-02-08 14:40 UTC, merged