Spctr 2226 icon block assets
brainstormforce/ultimate-addons-for-gutenberg pull request #2667
Opened 2023-01-25 04:26 UTC by adi3890

### Description

### Screenshots

### Types of changes

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2023-01-26 04:39 UTC, AbhijitNage123 approved these changes

2023-01-30 09:51 UTC, RajkiranBagal requested changes

2023-01-30 09:51 UTC, RajkiranBagal commented on src/blocks/icon/components/settings/GeneralSettings.js
> +			<UAGAdvancedPanelBody title={__( 'Icon', 'ultimate-addons-for-gutenberg' )} initialOpen={ true }>
initialOpen here should be false

2023-01-30 09:52 UTC, AbhijitNage123 approved these changes

2023-01-30 09:59 UTC, adi3890 commented on src/blocks/icon/components/settings/GeneralSettings.js
> +			<UAGAdvancedPanelBody title={__( 'Icon', 'ultimate-addons-for-gutenberg' )} initialOpen={ true }>
updated

2023-01-30 10:03 UTC, RajkiranBagal approved these changes

2023-01-31 06:32 UTC, RajkiranBagal approved these changes

2023-01-31 06:32 UTC, merged