SPCTR-2320 Fix: Heading - disabling heading and sub-heading hides the separator.
brainstormforce/ultimate-addons-for-gutenberg pull request #2681
Opened 2023-01-26 10:49 UTC by AbhijitNage123

### Description

- https://brainstormforce.atlassian.net/browse/SPCTR-2320

### Screenshots

- https://share.getcloudapp.com/bLuOvJLE

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

### How has this been tested?

- Added to the card.

### Checklist:
- [x] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [x] I've included any necessary tests 
- [ ] I've included developer documentation 
- [x] I've added proper labels to this pull request

2023-01-27 06:03 UTC, bsf-zanev requested changes
Please address the comments below

2023-01-27 06:03 UTC, bsf-zanev commented on src/blocks/advanced-heading/deprecated.js
> +	},
Why are the closing brackets on 418 and 419 in the same charater position?

2023-01-27 08:32 UTC, AbhijitNage123 commented on src/blocks/advanced-heading/deprecated.js
> +	},
one for save() and one for to close specific deprecated code. Please check - https://share.getcloudapp.com/6quN1nzp

2023-01-29 06:23 UTC, bsf-zanev commented on src/blocks/advanced-heading/deprecated.js
> +	},
Thanks for the clarification!

As shown in the screenshot, the bracket at 218 should be 1 tab space ahead to match with the one at line 365.

2023-01-30 05:56 UTC, AbhijitNage123 commented on src/blocks/advanced-heading/deprecated.js
> +	},
Resolved.

2023-01-30 07:02 UTC, bsf-zanev approved these changes
Looks good to me.

2023-02-01 14:02 UTC, supriyajjadhav approved these changes

2023-02-01 14:49 UTC, RajkiranBagal approved these changes

2023-02-01 14:52 UTC, merged