SPCTR-2283 info box cta button hover fix
brainstormforce/ultimate-addons-for-gutenberg pull request #2683
Opened 2023-01-26 14:52 UTC by rajmohanreddy774

### Description

### Screenshots

### Types of changes

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2023-01-29 06:27 UTC, bsf-zanev requested changes
Please address the comments below.

2023-01-29 06:27 UTC, bsf-zanev commented on src/blocks/info-box/components/CallToAction.js
> +
These extra tab spaces aren't needed.

2023-01-30 03:59 UTC, rajmohanreddy774 commented on src/blocks/info-box/components/CallToAction.js
> +
changes done

2023-01-30 06:59 UTC, bsf-zanev approved these changes
Looks good to me.

2023-02-08 11:43 UTC, RajkiranBagal requested changes

2023-02-08 11:43 UTC, RajkiranBagal commented on src/blocks/info-box/style.scss
> +.wp-block-button {
wp-block-button is a very general class that is used in multiple other blocks, this CSS may apply to other unwanted blocks & cause issues.

If you need CSS only for info box then use info box-specific classes or add CSS to existing selector in the file.

2023-02-08 14:16 UTC, RajkiranBagal approved these changes

2023-02-20 10:42 UTC, RajkiranBagal commented on src/blocks/info-box/components/CTA.js
> -		ctaIconOutput = renderSVG( attributes.ctaIcon, setAttributes );
Why is this removed?

2023-02-20 10:42 UTC, RajkiranBagal commented on src/blocks/info-box/components/CTA.js
> -								allowedFormats={ [] } // Removed the WP default link/bold/italic from the toolbar for button.
Why is this removed?

2023-02-20 10:42 UTC, RajkiranBagal commented on src/blocks/info-box/components/CTA.js
> -								allowedFormats={ [] } // Removed the WP default link/bold/italic from the toolbar for button.
Why is this removed?

2023-02-20 11:06 UTC, rajmohanreddy774 commented on src/blocks/info-box/components/CTA.js
> -		ctaIconOutput = renderSVG( attributes.ctaIcon, setAttributes );
added back

2023-02-20 11:07 UTC, rajmohanreddy774 commented on src/blocks/info-box/components/CTA.js
> -								allowedFormats={ [] } // Removed the WP default link/bold/italic from the toolbar for button.
added

2023-02-20 13:19 UTC, supriyajjadhav approved these changes

2023-02-20 15:12 UTC, RajkiranBagal approved these changes

2023-02-23 13:48 UTC, merged