Spectra v2.3.5
brainstormforce/ultimate-addons-for-gutenberg pull request #2698
Opened 2023-02-01 15:07 UTC by RajkiranBagal

* Global - Removed Backward compatibility of button padding for old users from multiple blocks.
* Global - Updated SVG icons rendering conditions & optimized the loading.
* Fix: Container - Full height and Fixed background Image not working properly on editor.
* Fix: Info-Box - CTA padding not working on responsive devices.
* Fix: Heading - Disabling heading and sub-heading hides the separator.
* Fix: Forms - Using form inside inner blocks, it was showing an error on submit.
* Fix: Background control - Image has wrong units for custom positioning.

2023-02-01 15:33 UTC, aapatre commented on src/blocks/advanced-heading/deprecated.js
> +		attributes: attributes_v2_3_5,
I think all looks good but for the naming convention of deprecated markup, we can use the previous release as the name (v2_3_4).

2023-02-02 04:40 UTC, AbhijitNage123 commented on blocks-config/forms/class-uagb-forms.php
> +		 * @return array $final_inner_forms_array inner blocks Array.
Change to name of a function instead of `$final_inner_forms_array` .

2023-02-02 04:42 UTC, AbhijitNage123 commented on blocks-config/forms/class-uagb-forms.php
> +		 * @return array $final_inner_forms_array inner blocks Array.
PR for same - https://github.com/brainstormforce/ultimate-addons-for-gutenberg/pull/2699

2023-02-02 04:42 UTC, AbhijitNage123 commented on src/blocks/advanced-heading/deprecated.js
> +		attributes: attributes_v2_3_5,
PR for same - https://github.com/brainstormforce/ultimate-addons-for-gutenberg/pull/2699

2023-02-02 04:49 UTC, AbhijitNage123 approved these changes

2023-02-02 04:58 UTC, patilvikasj commented on blocks-config/forms/class-uagb-forms.php
> +				if ( ! empty( $blocks ) ) {
We can do `continue` loop when $blocks is empty instead of big if block.

2023-02-02 04:59 UTC, patilvikasj requested changes
Please check the comment. Rest looks good to me.

2023-02-02 05:57 UTC, AbhijitNage123 commented on blocks-config/forms/class-uagb-forms.php
> +				if ( ! empty( $blocks ) ) {
Rise a PR for same - https://github.com/brainstormforce/ultimate-addons-for-gutenberg/pull/2700

2023-02-02 06:10 UTC, patilvikasj approved these changes

2023-02-02 06:22 UTC, adi3890 approved these changes

2023-02-02 06:25 UTC, rajmohanreddy774 approved these changes

2023-02-02 07:20 UTC, supriyajjadhav approved these changes

2023-02-03 00:40 UTC, bsf-zanev requested changes

2023-02-03 00:40 UTC, bsf-zanev commented on readme.txt
> +* Global - Updated SVG icons rendering conditions & optimized the loading.
These Global Entries should be tagged as improvements.

2023-02-03 05:54 UTC, AbhijitNage123 commented on readme.txt
> +* Global - Updated SVG icons rendering conditions & optimized the loading.
Resolved

2023-02-03 06:06 UTC, RajkiranBagal commented on readme.txt
> +* Global - Updated SVG icons rendering conditions & optimized the loading.
Done

2023-02-03 06:13 UTC, bsf-zanev approved these changes
Looks good to me.

2023-02-03 06:23 UTC, merged