SPCTR-1989 - Feature: Image Gallery Lightbox
brainstormforce/ultimate-addons-for-gutenberg pull request #2715
Opened 2023-02-08 07:35 UTC by bsf-zanev

### Description
Added the all new Lightbox Feature for the Image Gallery.

### Types of changes
New feature (non-breaking change which adds functionality)

### How has this been tested?

### Checklist:
- [x] My code is tested
- [x] My code follows accessibility standards 
- [x] My code has proper inline documentation 
- [x] I've included any necessary tests 
- [x] I've included developer documentation 
- [x] I've added proper labels to this pull request

2023-02-08 09:11 UTC, RajkiranBagal approved these changes

2023-02-17 15:49 UTC, RajkiranBagal requested changes

2023-02-17 15:49 UTC, RajkiranBagal commented on src/blocks/image-gallery/edit.js
> +import React, { useEffect, useState } from 'react';
```suggestion
import { useEffect, useState } from '@wordpress/element';
```

2023-02-22 13:34 UTC, RajkiranBagal approved these changes

2023-02-23 06:30 UTC, rahulvarma722 commented on src/blocks/image-gallery/render.js
> +						/>
```suggestion
						<ImageGallery
								{ ...{ name,setAttributes,attributes }}
						/>
```
Can we change like this

2023-02-23 06:30 UTC, rahulvarma722 commented on src/blocks/image-gallery/render.js
> +							/>
```suggestion
							<Lightbox
							{ ...{ attributes,setAttributes,setLightboxPreview }}
							/>
```

2023-02-23 06:30 UTC, rahulvarma722 commented on src/blocks/image-gallery/render.js
>  					<InitialSelector
Can we we change like above suggestion

2023-02-24 00:04 UTC, bsf-zanev commented on blocks-config/image-gallery/class-spectra-image-gallery.php
> +				<div class="swiper spectra-image-gallery__control-lightbox--main" dir="<?= is_rtl() ? 'rtl' : '' ?>">
This one was already resolved in [commit bdb71a4](https://github.com/brainstormforce/ultimate-addons-for-gutenberg/pull/2715/commits/bdb71a42016c31062ddcf9c6b01bd6f3afe7a234)

2023-02-24 00:04 UTC, bsf-zanev commented on blocks-config/image-gallery/class-spectra-image-gallery.php
> +								<img class="swiper-lazy" data-src="<?= esc_url( $attributes['mediaGallery'][ $i ]['url'] ); ?>" alt="<?= esc_attr( $attributes['mediaGallery'][ $i ]['alt'] ) ?>"/>
This one was already resolved in [commit bdb71a4](https://github.com/brainstormforce/ultimate-addons-for-gutenberg/pull/2715/commits/bdb71a42016c31062ddcf9c6b01bd6f3afe7a234)

2023-02-24 00:04 UTC, bsf-zanev commented on blocks-config/image-gallery/class-spectra-image-gallery.php
> +									<img src="<?= esc_url( $attributes['mediaGallery'][ $i ]['sizes']['thumbnail']['url'] ); ?>" alt="<?= esc_attr( $attributes['mediaGallery'][ $i ]['alt'] ) ?>"/>
This one was already resolved in [commit bdb71a4](https://github.com/brainstormforce/ultimate-addons-for-gutenberg/pull/2715/commits/bdb71a42016c31062ddcf9c6b01bd6f3afe7a234)

2023-02-24 00:04 UTC, bsf-zanev commented on blocks-config/image-gallery/class-spectra-image-gallery.php
> +			<div class='spectra-image-gallery__media-wrapper<?= esc_attr( $focusedClass ); ?>' data-spectra-gallery-image-id='<?= esc_attr( $mediaArray['id'] ) ?>' >
This one was already resolved in [commit bdb71a4](https://github.com/brainstormforce/ultimate-addons-for-gutenberg/pull/2715/commits/bdb71a42016c31062ddcf9c6b01bd6f3afe7a234)

2023-02-24 00:15 UTC, bsf-zanev commented on blocks-config/image-gallery/class-spectra-image-gallery.php
> +				let blockScope = document.querySelector( '.uagb-block-<?= esc_html( $id ); ?>' );
This one was already resolved in [commit bdb71a4](https://github.com/brainstormforce/ultimate-addons-for-gutenberg/pull/2715/commits/bdb71a42016c31062ddcf9c6b01bd6f3afe7a234)

esc_html_e has not been added, since the class does not need to be translated.

2023-02-24 00:20 UTC, bsf-zanev commented on src/blocks/image-gallery/edit.js
> +				<Render
I've updated as per this suggestion in Render and Settings.

2023-02-24 00:25 UTC, bsf-zanev commented on src/blocks/image-gallery/render.js
>  	props = props.parentProps;
This suggestion has been updated in render.js and settings.js

2023-02-24 00:28 UTC, bsf-zanev commented on src/blocks/image-gallery/render.js
> +						/>
An update has been done as per this suggestion.

2023-02-24 00:28 UTC, bsf-zanev commented on src/blocks/image-gallery/render.js
> +							/>
An update has been done as per this suggestion.

2023-02-24 00:28 UTC, bsf-zanev commented on src/blocks/image-gallery/render.js
>  					<InitialSelector
An update has been done as per this suggestion.

2023-02-24 00:44 UTC, bsf-zanev commented on includes/blocks/image-gallery/frontend.js.php
>  $paginate_arrow_size_fallback = UAGB_Block_Helper::get_fallback_number( $attr['paginateArrowSize'], 'paginateArrowSize', $block_name );
This fallback function exists in the Next-Release, along with the fallback functions in frontend.css.php.

I've removed them in this PR.
Were these files missed during the next-release optimization?

2023-02-24 00:51 UTC, bsf-zanev commented on src/blocks/image-gallery/components/ImageGallery.js
>  const classNames = ( ...classes ) => ( classes.filter( Boolean ).join( ' ' ) );
I've added the same to @Utils/Helpers.

2023-02-24 00:55 UTC, bsf-zanev commented on src/blocks/image-gallery/components/LightBox.js
> +		}, 500 );
Timeout Cleanup has been implement for both the Lightbox setTimeout implementations.

2023-02-24 00:55 UTC, bsf-zanev commented on src/blocks/image-gallery/components/LightBox.js
> +	useEffect( () => {
Timeout Cleanup has been implement for both the Lightbox setTimeout implementations.

2023-02-24 00:57 UTC, bsf-zanev commented on src/blocks/image-gallery/edit.js
>  		props.attributes.isPreview ? <img width='100%' src={ previewImageData } alt=''/> : (
Shouldn't this suggestion be done in the Code Refactoring PR to Next Release...?

2023-02-24 04:36 UTC, rahulvarma722 approved these changes

2023-02-24 04:41 UTC, RajkiranBagal approved these changes

2023-02-24 04:42 UTC, merged