Spctr 2292 modal block pro custom close icon implementation
brainstormforce/ultimate-addons-for-gutenberg pull request #2717
Opened 2023-02-08 14:53 UTC by abhishekrijal

### Description

### Screenshots

### Types of changes

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2023-02-08 15:19 UTC, RajkiranBagal requested changes

2023-02-08 15:19 UTC, RajkiranBagal commented on src/blocks/modal/settings.js
> +			title={ __( 'Close Button Styles', 'ultimate-addons-for-gutenberg' ) }
title should be the "Close Button" itself. No need to add Styles as it's already in the Style tab.

2023-02-08 15:19 UTC, RajkiranBagal commented
@abhishekrijal 
Fix: Code Analysis
Add a Proper title & description to PR

2023-02-14 03:10 UTC, abhishekrijal commented on src/blocks/modal/settings.js
> +			title={ __( 'Close Button Styles', 'ultimate-addons-for-gutenberg' ) }
Updated.

2023-02-15 09:28 UTC, RajkiranBagal approved these changes

2023-02-15 11:26 UTC, rahulvarma722 approved these changes

2023-02-22 10:53 UTC, RajkiranBagal approved these changes

2023-02-22 11:04 UTC, merged