SPSCTR-2309 Confirmation popup for svg upload
brainstormforce/ultimate-addons-for-gutenberg pull request #2719
Opened 2023-02-09 04:42 UTC by adi3890

### Description
- Adds a confirmation message for the first time to allow SVGs

### Screenshots

### Types of changes

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2023-02-09 08:21 UTC, AbhijitNage123 approved these changes

2023-02-09 08:32 UTC, RajkiranBagal commented on lib/gutenberg-templates/classes/class-ast-block-templates.php
> -			$mimes['svg'] = 'image/svg+xml';
i think we should not remove this. if user never uses icon block then he may get issues with templates import

2023-02-09 08:37 UTC, RajkiranBagal approved these changes

2023-02-17 04:59 UTC, RajkiranBagal requested changes

2023-02-17 04:59 UTC, RajkiranBagal commented on .eslintrc.js
>  		'camelcase': 'off',
Are these changes still needed?

2023-02-17 04:59 UTC, RajkiranBagal commented on classes/class-uagb-init-blocks.php
> +		// temporary code for testing purpose of QA. need to remove before merging.
Is this code needed?

2023-02-17 07:13 UTC, adi3890 commented on .eslintrc.js
>  		'camelcase': 'off',
Thanx for reminding, removed this.

2023-02-17 07:13 UTC, adi3890 commented on classes/class-uagb-init-blocks.php
> +		// temporary code for testing purpose of QA. need to remove before merging.
removed

2023-02-17 07:43 UTC, RajkiranBagal requested changes

2023-02-17 07:43 UTC, RajkiranBagal commented on src/components/popup-confirm/index.js
> +import React, { useLayoutEffect, useState } from 'react';
Import from @wordpress/element & remove React import.

2023-02-17 07:57 UTC, adi3890 commented on src/components/popup-confirm/index.js
> +import React, { useLayoutEffect, useState } from 'react';
done

2023-02-17 07:59 UTC, RajkiranBagal approved these changes

2023-02-17 08:00 UTC, merged