SPCTR-2215 Countdown Pro - Freemium hooks and acceptance
brainstormforce/ultimate-addons-for-gutenberg pull request #2723
Opened 2023-02-09 10:25 UTC by aapatre

### Description
- Pulled in hooks and designer's acceptance testing changes
- This PR allows pro features to work

### Screenshots

### Types of changes

- New feature (non-breaking change which adds functionality)

### How has this been tested?

### Checklist:
- [x] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [x] I've added proper labels to this pull request

2023-02-21 10:38 UTC, aapatre commented
Please merge https://github.com/brainstormforce/ultimate-addons-for-gutenberg/pull/2744 first

2023-02-23 07:49 UTC, adi3890 commented on includes/blocks/countdown/frontend.css.php
> +	'desktop' => apply_filters( 'spectra_' . $block_name . '_styling', $selectors, $attr ),
Please follow **[Spectra block development checklist](https://docs.google.com/document/d/1pcSs5OrvHrJG5DDKPeInU5H_JGZz_sa2ylD1LGSVoB0/edit#heading=h.zdhj6buga7o)** for this PR

2023-02-23 08:42 UTC, aapatre commented on includes/blocks/countdown/frontend.css.php
> +	'desktop' => apply_filters( 'spectra_' . $block_name . '_styling', $selectors, $attr ),
resolved

2023-02-23 10:06 UTC, adi3890 approved these changes

2023-02-23 10:18 UTC, aapatre commented on src/blocks/countdown/edit.js
>  		props.attributes.isPreview ? <img width='100%' src={previewImageData} alt=''/> :
Done

2023-02-28 14:33 UTC, RajkiranBagal requested changes

2023-02-28 14:33 UTC, RajkiranBagal commented on src/blocks/countdown/render.js
> +				{ innerblocks_structure }
Do we need to check if pro is active here?

2023-03-02 04:29 UTC, aapatre commented on src/blocks/countdown/render.js
> +				{ innerblocks_structure }
I've now added a condition at the top, where the `innerblocks_structure` is declared and initialized.

Although this will lead to 'Attempt Block Recovery' error in the editor, the user can expect the same since they are disabling a significant feature (Spectra Pro). And anyways the functionality won't entirely work even if we choose to not add the condition and the user has disabled Spectra Pro.

Also the `innerblocks_structure` received would be empty/null when Spectra Pro isn't active.

2023-03-02 04:30 UTC, aapatre commented on src/blocks/countdown/save.js
> +				{ innerblocks_structure }
I've now added a condition at the top, where the `innerblocks_structure` is declared and initialized.

Although this will lead to 'Attempt Block Recovery' error in the editor, the user can expect the same since they are disabling a significant feature (Spectra Pro). And anyways the functionality won't entirely work even if we choose to not add the condition and the user has disabled Spectra Pro.

Also the `innerblocks_structure` received would be empty/null when Spectra Pro isn't active.

2023-03-03 07:13 UTC, RajkiranBagal approved these changes

2023-03-03 08:13 UTC, adi3890 approved these changes

2023-03-03 10:09 UTC, merged