SPCTR-2348 - Code refactor and optimisation
brainstormforce/ultimate-addons-for-gutenberg pull request #2726
Opened 2023-02-10 03:59 UTC by rahulvarma722

### Description
Code optimisation remove unwanted codes

2023-02-11 14:13 UTC, RajkiranBagal requested changes
@rahulvarma722 Added a comment on PR & also why there are changes in package-lock.json?

2023-02-11 14:13 UTC, RajkiranBagal commented on classes/class-uagb-init-blocks.php
> +		return preg_match( '@' . $os[ $block_attributes['UAGSystem'] ] . '@', $user_agent ) ? '' : $block_content;
equivalent of isset( $os[ $value ] ) check skipped?

2023-02-13 04:36 UTC, rahulvarma722 commented on classes/class-uagb-init-blocks.php
> +		return preg_match( '@' . $os[ $block_attributes['UAGSystem'] ] . '@', $user_agent ) ? '' : $block_content;
i have add isset and isset added after my pr created

2023-02-13 04:46 UTC, RajkiranBagal approved these changes

2023-02-13 05:34 UTC, patilvikasj approved these changes

2023-02-13 10:10 UTC, adi3890 commented on classes/class-uagb-post-assets.php
> +			if ( isset( $value['content'] ) && has_blocks( $value['content'] ) ) {
ideally we should be checking is_array as it may gives issues in PHPStan

2023-02-13 11:29 UTC, adi3890 approved these changes

2023-02-14 12:10 UTC, RajkiranBagal approved these changes

2023-02-14 12:10 UTC, merged