v2.4.0 release to next-release
brainstormforce/ultimate-addons-for-gutenberg pull request #2744
Opened 2023-02-20 05:48 UTC by aapatre

### Description
- `v2.4.0-release` branch to `next-release`
- Countdown block

### Screenshots

### Types of changes

- New feature (non-breaking change which adds functionality)

### How has this been tested?

### Checklist:
- [x] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [x] I've added proper labels to this pull request

2023-02-20 06:24 UTC, RajkiranBagal requested changes

2023-02-20 06:24 UTC, RajkiranBagal commented on src/blocks/countdown/edit.js
> +	}, [ props ] );
```suggestion
	}, [ attributes ] );
```

2023-02-20 06:24 UTC, RajkiranBagal commented on src/blocks/countdown/save.js
> +import React from 'react';
Is this needed?

2023-02-20 06:29 UTC, RajkiranBagal requested changes

2023-02-20 06:29 UTC, RajkiranBagal commented on src/blocks/countdown/edit.js
> +import React, { useEffect, useState, useRef } from 'react';
```suggestion
import { useEffect, useState, useRef } from '@wordpress/element';
```

2023-02-20 06:51 UTC, RajkiranBagal approved these changes

2023-02-20 07:09 UTC, adi3890 commented on includes/blocks/countdown/frontend.css.php
> +$block_name = 'countdown';
Do we need this. Are we using it somewhere?

2023-02-20 07:09 UTC, adi3890 commented on includes/blocks/countdown/frontend.js.php
> +$block_name = 'countdown';
check for this too

2023-02-20 07:14 UTC, aapatre commented
@adi3890 I've removed the redundant block name variables
We were using them for fallbacks which have now been removed

2023-02-20 07:33 UTC, adi3890 commented on src/blocks/countdown/settings.js
> +		block_id,
improper indentation.

2023-02-20 08:11 UTC, aapatre commented on src/blocks/countdown/settings.js
> +		block_id,
Fixed

2023-02-20 09:17 UTC, aapatre commented
Fixed all indentations @adi3890

2023-02-20 09:40 UTC, adi3890 commented on src/blocks/countdown/block.js
> +	title: __( 'Countdown', 'ultimate-addons-for-gutenberg' ),
as this is a new block should we implement apiVersion 2 for this.
@RajkiranBagal

2023-02-20 10:47 UTC, aapatre commented on src/blocks/countdown/render.js
> +import React, { useLayoutEffect } from 'react';
Done

2023-02-20 10:48 UTC, aapatre commented on src/blocks/countdown/render.js
> +    const countdownRef = props.countdownRef;
I've tried that but the ref received in JS asset is then null, breaking the code.
Probably refs can't be destructured that way

2023-02-20 10:50 UTC, aapatre commented on src/blocks/countdown/save.js
> +	const { attributes } = props;
I think this is a matter of a preference for each developer. Also most of our blocks destructure attributes separately.

2023-02-20 10:51 UTC, aapatre commented on src/blocks/countdown/components/CountdownBox.js
> +        ) }>
- classnames library ensures a cleaner code and is being used across all blocks
- also it's more readable this way

2023-02-20 10:53 UTC, aapatre commented on src/blocks/countdown/render.js
> +	const { attributes } = props;
- Most of our blocks destructure attributes separately.
- Also, I think this is a matter of a preference for each developer.

2023-02-20 11:02 UTC, aapatre commented on assets/js/uagb-countdown.js
> +        if( typeof this.elements[ mainSelector ] !== 'undefined' ){
The usage of `typeof` function itself returns the type of a data type in a string value.

2023-02-20 11:07 UTC, aapatre commented on assets/js/uagb-countdown.js
> +        if( typeof this.elements[ mainSelector ] !== 'undefined' ){
`console.log( typeof ( typeof( undefined ) ) )`

2023-02-20 11:09 UTC, aapatre commented on assets/js/uagb-countdown.js
> +	getDefaultElements( mainSelector ) {
True, I've removed the getDefaultElements() function

2023-02-20 11:09 UTC, aapatre commented on assets/js/uagb-countdown.js
> +	getElement( selector, childSelector = null ) {
removed child selector and redundant logic

2023-02-20 11:23 UTC, aapatre commented on assets/js/uagb-countdown.js
> +	elements: {},
I commited the change 0c8ee2f but it seems to break things on frontend.
Reverting back since the old logic is necessary.

<img width="936" alt="image" src="https://user-images.githubusercontent.com/20199688/220092516-514cedd3-e6de-4ef9-a266-05d82c0b9876.png">

2023-02-20 11:25 UTC, aapatre commented on assets/js/uagb-countdown.js
> +	elements: {},
Reverted changes

2023-02-20 12:19 UTC, aapatre commented on src/blocks/countdown/render.js
> +export default Render;
Added memo

2023-02-20 12:36 UTC, aapatre commented on src/blocks/countdown/render.js
> +	const { attributes } = props;
I've implemented the changes

2023-02-20 13:14 UTC, aapatre commented on src/blocks/countdown/block.js
> +	title: __( 'Countdown', 'ultimate-addons-for-gutenberg' ),
Added apiVersion and blockProps

2023-02-20 14:21 UTC, adi3890 approved these changes

2023-02-20 17:01 UTC, abhishekrijal approved these changes

2023-02-21 12:46 UTC, aapatre commented
Please note:
- Responsive conditions are working fine for the block but slanted lines are not seen in the editor
- I debugged this and also confirmed the same with @supriyajjadhav that it's an issue with the component (rather than the block) and hence I've created the following card:
https://brainstormforce.atlassian.net/browse/SPCTR-2388

cc: @RajkiranBagal

2023-02-21 13:05 UTC, adi3890 commented on src/blocks/countdown/edit.js
> +			<Settings parentProps={ props } />
Settings is required only when block isSelected.
https://github.com/brainstormforce/ultimate-addons-for-gutenberg/blob/8495d8090c6c6ff87996ed14f9d36a8377057f7b/src/blocks/icon/edit.js#L21
Take reference from https://github.com/brainstormforce/ultimate-addons-for-gutenberg/blob/8495d8090c6c6ff87996ed14f9d36a8377057f7b/src/blocks/icon/edit.js#L56

this improves performance

2023-02-22 03:13 UTC, aapatre commented on src/blocks/countdown/edit.js
> +			<Settings parentProps={ props } />
done

2023-02-22 06:51 UTC, rahulvarma722 commented on assets/js/uagb-countdown.js
> +	elements: {},
Please check i think we should not keep any unknown code in our file so please be sure

2023-02-22 07:25 UTC, abhishekrijal approved these changes

2023-02-22 07:31 UTC, RajkiranBagal approved these changes

2023-02-22 09:50 UTC, RajkiranBagal approved these changes

2023-02-22 10:31 UTC, adi3890 approved these changes

2023-02-22 10:50 UTC, merged