Spctr 2312 Countdown Block Evergreen Timer
brainstormforce/ultimate-addons-for-gutenberg pull request #2752
Opened 2023-02-24 05:33 UTC by abhishekrijal

### Description

### Screenshots

### Types of changes

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2023-02-24 08:54 UTC, patilvikasj approved these changes

2023-02-24 09:26 UTC, aapatre approved these changes

2023-03-06 08:11 UTC, RajkiranBagal requested changes

2023-03-06 08:11 UTC, RajkiranBagal commented on classes/class-uagb-scripts-utils.php
> +			'uagb_countdown_data',
Looks like duplicate code

2023-03-06 08:27 UTC, abhishekrijal commented on classes/class-uagb-scripts-utils.php
> +			'uagb_countdown_data',
I think this is required for backend and frontend triggers, thus required in both places. @RajkiranBagal

2023-03-06 09:54 UTC, RajkiranBagal approved these changes

2023-03-06 09:54 UTC, merged