SPCTR-2361-Post-timeline in style setting the left padding side is not changing in front end
brainstormforce/ultimate-addons-for-gutenberg pull request #2753
Opened 2023-02-24 06:44 UTC by ravinishadcoder

### Description

The left padding is not updated on front-end

### Screenshots

### Types of changes

Bug fix (The left padding is not updated on front-end)
### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2023-02-24 07:12 UTC, supriyajjadhav approved these changes

2023-02-24 07:14 UTC, adi3890 approved these changes

2023-02-24 08:05 UTC, RajkiranBagal requested changes

2023-02-24 08:05 UTC, RajkiranBagal commented on README.md
> +* Fix: Post-timeline - in style setting the left padding side is not changing in front end
```suggestion
* Fix: Post-timeline - Left Padding not applicable on the frontend.
```

2023-02-24 08:05 UTC, RajkiranBagal commented on readme.txt
> +* Fix: Post-timeline - in style setting the left padding side is not changing in front end
```suggestion
* Fix: Post-timeline - Left Padding not applicable on the frontend.
```

2023-02-28 13:28 UTC, RajkiranBagal requested changes

2023-02-28 13:28 UTC, RajkiranBagal commented on readme.txt
> +* Fix: Post-timeline - Left Padding not applicable on the frontend.
```suggestion
* Fix: Post Timeline - Left Padding not applicable on the frontend.
```

2023-02-28 13:28 UTC, RajkiranBagal commented on README.md
> +* Fix: Post-timeline - Left Padding not applicable on the frontend.
```suggestion
* Fix: Post Timeline - Left Padding not applicable on the frontend.
```

2023-02-28 13:34 UTC, RajkiranBagal approved these changes

2023-02-28 13:34 UTC, merged