SPCTR-2388-Responsive Conditions - Slanted lines not visible for Countdown and Slider
brainstormforce/ultimate-addons-for-gutenberg pull request #2759
Opened 2023-02-28 09:48 UTC by ravinishadcoder

### Description
Slanted lines not visible for Countdown and Slider

### Screenshots

### Types of changes

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2023-02-28 10:15 UTC, supriyajjadhav approved these changes

2023-02-28 10:42 UTC, RajkiranBagal requested changes

2023-02-28 10:42 UTC, RajkiranBagal commented on README.md
> +* Fix: Responsive Conditions Slanted lines not visible for Countdown and Slider
```suggestion
* Fix: Responsive Conditions Slanted lines not visible for Counter and Slider
```

2023-02-28 10:42 UTC, RajkiranBagal commented on readme.txt
> +* Fix: Responsive Conditions Slanted lines not visible for Countdown and Slider
```suggestion
* Fix: Responsive Conditions Slanted lines not visible for Counter and Slider
```

2023-02-28 15:35 UTC, RajkiranBagal approved these changes

2023-03-01 03:13 UTC, adi3890 approved these changes

2023-03-06 11:09 UTC, RajkiranBagal requested changes

2023-03-06 11:20 UTC, RajkiranBagal approved these changes

2023-03-06 11:26 UTC, aapatre approved these changes

2023-03-06 11:33 UTC, merged