Spctr 2444 code optimization update admin settings option
brainstormforce/ultimate-addons-for-gutenberg pull request #2767
Opened 2023-03-02 12:49 UTC by rajmohanreddy774

### Description
code-optimization of Common_Settings class function.

### Screenshots

### Types of changes

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2023-03-03 08:29 UTC, adi3890 commented on admin-core/ajax/common-settings.php
> +	 */
function comment improper should have all params detail

2023-03-03 08:29 UTC, adi3890 commented on admin-core/ajax/common-settings.php
> +		if ( ! isset( $arr [ $key ] ) ) {
we need only empty check

2023-03-03 08:29 UTC, adi3890 commented on admin-core/ajax/common-settings.php
> +	 */
incomplete doc comment

2023-03-03 08:29 UTC, adi3890 commented on admin-core/ajax/common-settings.php
> +	private function save_and_send_success_response( $admin_settings_option, $value ) {
we can have simple variable name $option
as this is in scope of function.

sanitize data

2023-03-03 08:29 UTC, adi3890 commented on admin-core/ajax/common-settings.php
> +		$this->check_value_in_post( $_POST, 'value' );
create one function

2023-03-03 08:59 UTC, rajmohanreddy774 commented on admin-core/ajax/common-settings.php
> +	 */
Added params

2023-03-03 09:00 UTC, rajmohanreddy774 commented on admin-core/ajax/common-settings.php
> +	 */
Added complete comment

2023-03-03 09:12 UTC, rajmohanreddy774 commented on admin-core/ajax/common-settings.php
> +		if ( ! isset( $arr [ $key ] ) ) {
done changes

2023-03-03 09:12 UTC, rajmohanreddy774 commented on admin-core/ajax/common-settings.php
> +	private function save_and_send_success_response( $admin_settings_option, $value ) {
done changes

2023-03-03 09:15 UTC, rajmohanreddy774 commented on admin-core/ajax/common-settings.php
> +		$this->check_value_in_post( $_POST, 'value' );
can you pls elaborate?

2023-03-06 12:27 UTC, RajkiranBagal commented
@rajmohanreddy774  
- PR title not valid
 - Code analysis in PR

2023-03-13 04:34 UTC, rajmohanreddy774 commented
> @rajmohanreddy774
> 
> * PR title not valid
> * Code analysis in PR

@RajkiranBagal 
code analysis in PR is passed.
PR title changed.

2023-03-13 04:39 UTC, RajkiranBagal commented
@rajmohanreddy774 PR title still not proper. As per [this](https://docs.google.com/document/d/1oiF7iFLSx5GQprXhnLjwdVcHK7dFwaCW1-qqOxcs1CA/edit)

2023-03-16 07:28 UTC, rahulvarma722 approved these changes

2023-03-20 09:28 UTC, rajmohanreddy774 commented on admin-core/ajax/common-settings.php
> +		if ( isset( $_POST['value'] ) ) { // phpcs:ignore WordPress.Security.NonceVerification.Missing
Removed and Tested works fine.

2023-03-20 09:32 UTC, rajmohanreddy774 commented on admin-core/ajax/common-settings.php
> +		if ( ! check_ajax_referer( $option, 'security', false ) ) {
Added third parameter now.

2023-03-20 09:32 UTC, rajmohanreddy774 commented on admin-core/ajax/common-settings.php
>  	 * Save settings.
updated descriptions of functions.

2023-03-20 09:33 UTC, rajmohanreddy774 commented
> @rajmohanreddy774 PR title still not proper. As per [this](https://docs.google.com/document/d/1oiF7iFLSx5GQprXhnLjwdVcHK7dFwaCW1-qqOxcs1CA/edit)

--Added proper PR title as per docs

2023-03-21 15:44 UTC, rajmohanreddy774 commented on admin-core/ajax/common-settings.php
> +		// nonce verification done in function check_permission_nonce.
Removed

2023-03-22 07:02 UTC, bsf-zanev requested changes

2023-03-22 07:02 UTC, bsf-zanev commented on admin-core/ajax/common-settings.php
>  	 * @param array $input_settings settimg data.
Could we add `@return` under this param?

2023-03-22 07:11 UTC, supriyajjadhav approved these changes

2023-03-22 07:13 UTC, bsf-zanev commented on admin-core/ajax/common-settings.php
>  	 * @param array $input_settings settimg data.
```suggestion
	 * @param array $input_settings settimg data.
	 * @return array    The sanitized data form inputs.
```

2023-03-22 07:14 UTC, rajmohanreddy774 commented on admin-core/ajax/common-settings.php
>  	 * @param array $input_settings settimg data.
done changes

2023-03-22 07:18 UTC, bsf-zanev approved these changes

2023-03-22 07:34 UTC, aapatre approved these changes

2023-03-22 07:48 UTC, adi3890 commented on admin-core/ajax/common-settings.php
> +		$value = isset( $value ) ? json_decode( stripslashes( $value ), true ) : array(); // phpcs:ignore WordPress.Security.ValidatedSanitizedInput.InputNotSanitized
do we need isset here.
please check for similar instance in this PR.

Proper comment not available for phpcs:ignore
please check for same everywhere in this file.

2023-03-22 13:12 UTC, rajmohanreddy774 commented on admin-core/ajax/common-settings.php
> +		$value = isset( $_POST['value'] ) ? json_decode( stripslashes( $_POST['value'] ), true ) : array(); // phpcs:ignore WordPress.Security.ValidatedSanitizedInput.InputNotSanitized,WordPress.Security.N
yes done changes

2023-03-22 13:12 UTC, rajmohanreddy774 commented on admin-core/ajax/common-settings.php
> +		$this->check_post_value();
removed

2023-03-22 13:14 UTC, rajmohanreddy774 commented on admin-core/ajax/common-settings.php
> +		$value = isset( $value ) ? json_decode( stripslashes( $value ), true ) : array(); // phpcs:ignore WordPress.Security.ValidatedSanitizedInput.InputNotSanitized
yes removed isset in similar instances,
removed phpcs:ignore that is of no use.

2023-03-23 07:32 UTC, adi3890 approved these changes

2023-03-29 09:25 UTC, RajkiranBagal approved these changes

2023-03-29 09:30 UTC, merged