SPCTR-2347 - Test Spectra blocks with Site Editor theme and report bugs.
brainstormforce/ultimate-addons-for-gutenberg pull request #2771
Opened 2023-03-06 08:22 UTC by supriyajjadhav

### Description
 Test Spectra blocks with Site Editor theme and report bugs.

### Types of changes
Bug fix (non-breaking change which fixes an issue) 

### How has this been tested?

### Checklist:
- [x] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [x] I've added proper labels to this pull request

2023-03-14 07:10 UTC, RajkiranBagal requested changes

2023-03-14 07:10 UTC, RajkiranBagal commented on src/components/typography/fontloader.js
> +		if( siteEditTheme.length !== 0 ) {
Check condition for iframe present too, like below

2023-03-14 07:38 UTC, supriyajjadhav commented on src/components/typography/fontloader.js
> +		if( siteEditTheme.length !== 0 ) {
Resolved.

2023-03-15 15:43 UTC, rahulvarma722 commented on src/components/typography/fontloader.js
> +					context: responsiveIframe?.frameElement?.contentWindow
If responsiveIframe?.frameElement?.contentWindow = undefined then how can we manage please add proper condition here

2023-03-15 15:43 UTC, rahulvarma722 commented on src/components/typography/fontloader.js
> +				context: window.frames[0]?.frameElement?.contentWindow,
If window.frames[0]?.frameElement?.contentWindow = undefined then how can we manage please add proper condition here

2023-03-17 08:12 UTC, supriyajjadhav commented on src/components/typography/fontloader.js
> +					context: responsiveIframe?.frameElement?.contentWindow
@rahulvarma722 I have updated the comment please check

2023-03-17 08:12 UTC, supriyajjadhav commented on src/components/typography/fontloader.js
> +				context: window.frames[0]?.frameElement?.contentWindow,
@rahulvarma722 I have updated the comment please check

2023-03-17 08:13 UTC, rahulvarma722 approved these changes

2023-03-17 08:18 UTC, rahulvarma722 approved these changes

2023-03-20 06:19 UTC, AbhijitNage123 approved these changes

2023-03-20 09:30 UTC, RajkiranBagal approved these changes

2023-03-20 09:30 UTC, merged