Spctr 2450 optimize react components of content timeline post timeline lottie
brainstormforce/ultimate-addons-for-gutenberg pull request #2776
Opened 2023-03-08 04:20 UTC by rajmohanreddy774

### Description

### Screenshots

### Types of changes

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2023-04-05 09:34 UTC, RajkiranBagal requested changes

2023-04-05 09:34 UTC, RajkiranBagal commented on src/blocks/lottie/block.js
> +import attributes from '../lottie/attributes';
```suggestion
import attributes from './attributes';
```

2023-04-17 10:35 UTC, rahulvarma722 approved these changes

2023-04-17 10:44 UTC, RajkiranBagal approved these changes

2023-04-18 02:49 UTC, RajkiranBagal requested changes

2023-04-18 02:49 UTC, RajkiranBagal commented on src/blocks/lottie/edit.js
> +import './editor.lazy.scss';
This is not correct way of importing editor.lazy.scss. Please refer other blocks

2023-04-18 15:11 UTC, rajmohanreddy774 commented on src/blocks/lottie/edit.js
> +import './editor.lazy.scss';
Missed to remove, removed it.

2023-04-20 10:34 UTC, RajkiranBagal approved these changes

2023-04-20 11:20 UTC, RajkiranBagal approved these changes

2023-04-20 11:20 UTC, merged