SPCTR-2390 Carousel - TwentyTwentyone theme hover style override for arrow and dot.
brainstormforce/ultimate-addons-for-gutenberg pull request #2777
Opened 2023-03-08 04:30 UTC by ravinishadcoder

### Description

Post Carousel - TwentyTwentyone theme hover style override for arrow and dot.
### Screenshots

### Types of changes

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2023-03-08 04:59 UTC, aapatre requested changes
Please pull in next-release

2023-03-08 05:41 UTC, AbhijitNage123 approved these changes

2023-03-08 06:08 UTC, aapatre approved these changes

2023-03-08 06:08 UTC, aapatre commented
Please add 'Post Carousel' to heading in place of 'Carousel'

2023-03-08 06:57 UTC, supriyajjadhav commented on src/blocks/post/style.scss
> +		color: #fff;
If we add static CSS to apply color then the theme's default color will not work.

2023-03-09 06:19 UTC, AbhijitNage123 requested changes

2023-03-09 06:19 UTC, AbhijitNage123 commented on src/blocks/post/post-button/edit.js
> +
Is there any reason to delete this?

2023-03-09 06:32 UTC, AbhijitNage123 commented on src/blocks/post/post-button/edit.js
> -	useLayoutEffect( () => {
Is there any reason to delete this?

2023-03-09 12:47 UTC, ravinishadcoder commented on src/blocks/post/post-button/edit.js
> -	useLayoutEffect( () => {
I had tested at my end. CSS was not loaded anywhere on the page of these files. So I discussed with Supriya and removed the editor.lazy.scss file for post-image,post-meta and post-title

2023-03-10 08:36 UTC, RajkiranBagal approved these changes

2023-03-23 11:33 UTC, RajkiranBagal approved these changes

2023-03-23 11:36 UTC, supriyajjadhav approved these changes

2023-03-29 08:03 UTC, RajkiranBagal approved these changes

2023-03-29 08:46 UTC, merged