SPCTR-2471-Add Zen Dots font from Google Fonts
brainstormforce/ultimate-addons-for-gutenberg pull request #2782
Opened 2023-03-09 09:47 UTC by ravinishadcoder

### Description

[Description link](https://brainstormforce.atlassian.net/browse/SPCTR-2471?atlOrigin=eyJpIjoiN2NlNDYyMTg5YjcxNGUwM2I4NWY1NjUwNzBhMjg1ZTIiLCJwIjoiaiJ9)
### Screenshots

[Screencast](https://d.pr/v/eUxy4C)
### Types of changes

Bug fix (non-breaking change which fixes an issue) 

### How has this been tested?

### Checklist:
- [x] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [x] I've added proper labels to this pull request

2023-03-09 12:52 UTC, RajkiranBagal approved these changes

2023-03-10 02:15 UTC, RajkiranBagal requested changes

2023-03-10 02:15 UTC, RajkiranBagal commented on readme.txt
> +* Improvement: Typography - Added Zen dots Google fonts from in Font Families.
```suggestion
* Improvement: Typography - Added Zen dots Google font in Font Families. 
```

2023-03-10 02:15 UTC, RajkiranBagal commented on README.md
> +* Improvement: Typography - Added Zen dots Google fonts from in Font Families.
```suggestion
* Improvement: Typography - Added Zen dots Google font in Font Families. 
```

2023-03-10 02:20 UTC, bsf-zanev approved these changes
Looks good to me.

2023-03-10 02:21 UTC, merged