Spectra v2.4.0
brainstormforce/ultimate-addons-for-gutenberg pull request #2792
Opened 2023-03-10 12:41 UTC by RajkiranBagal

* New: Introducing the Countdown block that will help you generate hype and create a sense of urgency among your audience, during product sales or releases!
* New: Introducing the Icon block that allows you to add FontAwesome 6 icons on your website with tonnes of styling options.
* Feature: Image Gallery - Added a new lightbox feature with all the essential customizability that you'll need.
* Improvement: Performance - Optimized the editor performance for all Spectra Blocks.
* Improvement: Performance - Improved the archive page speed.
* Improvement: Image Gallery - Added a dropdown to select the image size for all the images in the gallery.
* Improvement: Custom CSS - Disabled the option for "on page-level CSS".
* Improvement: Typography - Added Fahkwang and Jost Google Fonts in Font Families.
* Improvement: Typography - Added Zen dots Google font in Font Families.
* Improvement: Display Conditions - Added a "Day" option to display Spectra blocks on specific days.
* Fix: Container - Resolved the full-width issue when adding a Container block inside the Slider block.
* Fix: Container - Resolved an issue where the content was misaligned vertically when the background type was set to "video".
* Fix: Image - Resolve an issue that was encountered when the Gutenberg plugin was activated.
* Fix: Image - Updated the image dimensions width & height box as per the Spectra UI guidelines.
* Fix: Buttons - Fixed the stack orientation and responsive alignment settings not working as expected on the front end.
* Fix: Info Box - Resolved an issue where the icon was misaligned on tablet/mobile when padding was added.
* Fix: Info Box - Updated the CTA hover styling on the front end.
* Fix: Call To Action - Resolved an issue where the additional button's icon color was not changing on hover in the front end.
* Fix: Forms- Resolved an issue where the form submit throws a success message without adding the "To" email address field.
* Fix: Forms/Tabs/Table Of Contents - Resolved an issue where the JS throws an error in the console on blog/home page.
* Fix: Post Timeline - Resolved an issue where the left padding was not applicable on the front end.
* Fix: Team - Resolved an issue where images were not working as expected on responsive device presets.
* Fix: Display Conditions - Fixed the undefined `key/index` when the Operating System is set to none.
* Fix: Responsive Conditions - Updated slanted lines visibility for Counter and Slider Blocks.
* Fix: Global - Updated Border Settings to remove all Border CSS when set to "default".
* Fix: Global - Excluded BR Tags from buttons' text.
* Fix: Global - Cartflows templates throw an error in the editor's Spectra Page Settings.

2023-03-10 12:50 UTC, aapatre commented on src/blocks/countdown/attributes.js
> +	endDateTime: {
We need to merge this PR to save a copy of endDateTime value in a separate attribute (we require it if we are planning to fix [SPCTR-2458](https://brainstormforce.atlassian.net/browse/SPCTR-2458) while switching between modes)
https://github.com/brainstormforce/ultimate-addons-for-gutenberg/pull/2781

2023-03-11 04:28 UTC, adi3890 commented on includes/blocks/slider/frontend.css.php
> +	'desktop' => apply_filters( 'spectra_slider_styling', $selectors, $attr ),
Reference https://github.com/brainstormforce/ultimate-addons-for-gutenberg/blob/00f2bbdf074e46e9448f8e2034b4243822e58106/includes/blocks/modal/frontend.css.php#L386

2023-03-13 04:59 UTC, RajkiranBagal commented on src/blocks/countdown/attributes.js
> +	endDateTime: {
Merged.

2023-03-13 06:49 UTC, AbhijitNage123 requested changes

2023-03-13 06:49 UTC, AbhijitNage123 commented on src/blocks/buttons-child/block.js
> +			<PreviewImage image="buttons-child" />
`isChildren={ true }` is missing for previewImage.

2023-03-13 07:37 UTC, rahulvarma722 commented on bin/icons-configure/README.md
> +grunt.registerTask( 'font-awesome-v6', function () {
I have confirmed

2023-03-13 07:51 UTC, RajkiranBagal commented on admin-core/ajax/common-settings.php
> +	 * @return void
Resolved  by @AbhijitNage123  - https://github.com/brainstormforce/ultimate-addons-for-gutenberg/pull/2800

2023-03-13 08:01 UTC, RajkiranBagal commented on classes/class-uagb-block-js.php
> +		 * @param array $attr the blocks attr.
Done by @aapatre https://github.com/brainstormforce/ultimate-addons-for-gutenberg/pull/2801

2023-03-13 08:10 UTC, bsf-zanev reviewed
I've added a few comments below.

2023-03-13 08:49 UTC, aapatre commented on classes/class-uagb-block-js.php
> +		 * @param array $attr the blocks attr.
Marking as resolved

2023-03-13 09:19 UTC, RajkiranBagal commented on src/blocks/buttons-child/block.js
> +			<PreviewImage image="buttons-child" />
@rahulvarma722 fixed this - https://github.com/brainstormforce/ultimate-addons-for-gutenberg/pull/2802

2023-03-13 09:27 UTC, RajkiranBagal commented on admin-core/assets/src/dashboard-app/pages/settings/OnPageCSS.js
> +function classNames( ...classes ) {
This is in admin-core/ folder & @Utils alias is not accessible here. For now we will skip it, we will do it later for all admin core folder.

2023-03-13 09:28 UTC, RajkiranBagal commented on admin-core/ajax/common-settings.php
> +		if ( empty( $_POST ) ) {
These are optimised by optimisation team in a PR which will be resolved in that PR.

2023-03-13 09:29 UTC, aapatre commented on src/blocks/container/edit.js
> +	// const { variationSelected } = props.attributes;
Addressed in https://github.com/brainstormforce/ultimate-addons-for-gutenberg/pull/2803

2023-03-13 09:29 UTC, aapatre commented on src/blocks/countdown/components/CountdownBox.js
> +import classnames from 'classnames';
Addressed in https://github.com/brainstormforce/ultimate-addons-for-gutenberg/pull/2803

2023-03-13 09:30 UTC, aapatre commented on src/blocks/countdown/edit.js
> +			UAGBCountdown.changeEndTime( '.uagb-block-' + props.attributes.block_id, props.attributes, countdownRef.current ) // eslint-disable-line no-undef
Addressed in https://github.com/brainstormforce/ultimate-addons-for-gutenberg/pull/2803

2023-03-13 09:30 UTC, aapatre commented on src/blocks/countdown/edit.js
> +	}, [ attributes ] );
Addressed in https://github.com/brainstormforce/ultimate-addons-for-gutenberg/pull/2803

2023-03-13 09:35 UTC, abhishekrijal commented on admin-core/inc/admin-menu.php
> +					'image-gallery-pro',
@bsf-zanev Shouldn't we only add pro-registered blocks to the list? Modal Pro options are additional options only, no new `modal-pro` block is registered

CC @RajkiranBagal

2023-03-13 09:37 UTC, AbhijitNage123 commented on admin-core/ajax/common-settings.php
> +		 * Nonce verification
It is just a comment to condition. it don't need since and return type.

2023-03-13 09:37 UTC, AbhijitNage123 commented on admin-core/ajax/common-settings.php
> +		if ( empty( $_POST ) ) {
Yes, we throwing an error when $_POST is empty.

2023-03-13 09:38 UTC, supriyajjadhav commented on src/blocks/icon/attributes.js
> +		isUAGStyle: true,
@adi3890 We are not using `isUAGStyle` attribute. Please Remove from everywhere in this file

2023-03-13 09:49 UTC, rahulvarma722 commented on blocks-config/uagb-controls/previewImage.js
> +		console.error( __( 'Please add preview image.', 'ultimate-addons-for-gutenberg' ) ); // eslint-disable-line
@bsf-zanev If we accidentally do not put an image in props so we will show an error message in the console.

2023-03-13 09:57 UTC, AbhijitNage123 commented on src/blocks/advanced-heading/styling.js
> +	mobile_selectors = wp.hooks.applyFilters( `spectra.${blockName}.mobileStyling`, mobile_selectors, props.attributes );
https://github.com/brainstormforce/ultimate-addons-for-gutenberg/pull/2804

2023-03-13 10:02 UTC, aapatre commented on blocks-config/uagb-controls/previewImage.js
> +		console.error( __( 'Please add preview image.', 'ultimate-addons-for-gutenberg' ) ); // eslint-disable-line
I think it would be a good idea to rewrite it as 'Error loading preview image!' (just in case the preview image file is deleted from the server manually/tampered with). Although an edge case, let me know what you think about it.

cc: @bsf-zanev @rahulvarma722

2023-03-13 10:18 UTC, adi3890 commented on src/blocks/icon/attributes.js
> +		isUAGStyle: true,
Raised a PR https://github.com/brainstormforce/ultimate-addons-for-gutenberg/pull/2806 for same. Please review

2023-03-13 11:46 UTC, AbhijitNage123 approved these changes

2023-03-13 11:46 UTC, rahulvarma722 approved these changes

2023-03-13 11:47 UTC, adi3890 approved these changes

2023-03-13 12:01 UTC, aapatre approved these changes

2023-03-13 16:19 UTC, abhishekrijal approved these changes

2023-03-13 16:51 UTC, rajmohanreddy774 approved these changes

2023-03-14 00:36 UTC, bsf-zanev approved these changes
Looks good to me.

2023-03-15 11:42 UTC, ravinishadcoder approved these changes

2023-03-15 11:43 UTC, supriyajjadhav approved these changes

2023-03-15 12:05 UTC, patilvikasj approved these changes

2023-03-15 12:15 UTC, merged