SPCTR-2470-fix: content settings of inline-notice block
brainstormforce/ultimate-addons-for-gutenberg pull request #2809
Opened 2023-03-13 12:16 UTC by rajmohanreddy774

### Description

### Screenshots

### Types of changes

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2023-03-15 16:07 UTC, rahulvarma722 approved these changes

2023-03-17 06:20 UTC, aapatre commented on readme.txt
> +* Fix: Inline-Notice - Content color and FontStyle issues.
Please add more detailed/specific bug description in the changelog.

2023-03-17 06:21 UTC, aapatre requested changes
Add more specific title and description to the PR.

2023-03-17 06:31 UTC, rajmohanreddy774 commented on readme.txt
> +* Fix: Inline-Notice - Content color and FontStyle issues.
Added

2023-03-17 06:44 UTC, aapatre approved these changes

2023-03-17 10:02 UTC, RajkiranBagal requested changes

2023-03-17 10:02 UTC, RajkiranBagal commented on README.md
> +* Fix: Inline-Notice - Content color not visible in backend and FontStyle not loading for Content.
```suggestion
* Fix: Inline Notice - Content color is not working in the backend.
* Fix: Inline Notice - Content typography is not working.
```

2023-03-17 10:11 UTC, rajmohanreddy774 commented on README.md
> +* Fix: Inline-Notice - Content color not visible in backend and FontStyle not loading for Content.
Added as per suggestion

2023-03-17 10:37 UTC, RajkiranBagal approved these changes

2023-03-17 10:41 UTC, RajkiranBagal approved these changes

2023-03-17 10:49 UTC, merged