SPCTR-380 Animations Feature
brainstormforce/ultimate-addons-for-gutenberg pull request #2810
Opened 2023-03-13 12:52 UTC by aapatre

### Description
Created Animations feature in Advanced Tab:
- Animation Type
- Easing function
- Duration
- Delay
- Repeat/Play-Once
- Play in editor button

Library: [AOS (Animate on Scroll)](https://github.com/michalsnik/aos)

### Screenshots
<img width="283" alt="image" src="https://user-images.githubusercontent.com/20199688/224706929-49c00702-f468-4fc6-aabe-86404b1e0a91.png">

### Types of changes

- New feature (non-breaking change which adds functionality)

### Checklist:
- [x] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [x] I've added proper labels to this pull request

2023-03-14 04:31 UTC, aapatre commented on admin-core/ajax/common-settings.php
> +			wp_send_json_error( $response_data );
done

2023-03-14 04:32 UTC, aapatre commented on admin-core/ajax/common-settings.php
> +			wp_send_json_error( $response_data );
done

2023-03-14 04:32 UTC, aapatre commented on admin-core/ajax/common-settings.php
> +		if ( empty( $_POST ) ) {
Done

2023-03-14 04:32 UTC, aapatre commented on admin-core/ajax/common-settings.php
> +	 */
Done

2023-03-14 04:57 UTC, bsf-zanev reviewed
Please address the comments below.

2023-03-14 04:57 UTC, bsf-zanev commented on admin-core/ajax/common-settings.php
> +	 */
@aapatre - Let's follow the protocol marked in the [dev checklist](https://docs.google.com/document/d/1pcSs5OrvHrJG5DDKPeInU5H_JGZz_sa2ylD1LGSVoB0/edit#heading=h.o9ot4iqv3hsp).

2023-03-14 04:57 UTC, bsf-zanev commented on admin-core/assets/src/common/block-icons.js
> +			fill: '#1E293B',
Why is this fill used here?

2023-03-14 05:56 UTC, aapatre commented on admin-core/assets/src/common/block-icons.js
> +			fill: '#1E293B',
Done

2023-03-14 06:02 UTC, bsf-zanev commented on admin-core/assets/src/common/block-icons.js
> +			fill: '#1E293B',
Thanks for replacing the hex with the variable!

Could you also check out with the designers to update this icon to remove fill, and set stroke to 1.4 instead of 0.1?

The current SVG will not disable properly due to the fill.

2023-03-14 11:14 UTC, aapatre commented on admin-core/assets/src/common/block-icons.js
> +			fill: '#1E293B',
Changed

2023-03-14 11:16 UTC, aapatre commented
@adi3890 for enqueuing the library assets `lib`, it will be a global change and we need to ensure other mechanisms like caching work with the same

Hence, we can skip it for the current PR

Confirmed with @RajkiranBagal

2023-03-14 11:26 UTC, adi3890 commented on admin-core/ajax/common-settings.php
> +		$response_data = array(
seems like a logical issue.
sends success message even if $_POST['value] is not set
should we return early if required value is not set with error message

also we can pass array directly no need to create a variable for single use.

2023-03-14 11:32 UTC, adi3890 commented on admin-core/assets/src/dashboard-app/pages/blocks/AnimationsExtension.js
> +        key={'animations-extension'}
can you please verify this value for key

2023-03-14 11:32 UTC, adi3890 commented on admin-core/assets/src/dashboard-app/pages/blocks/AnimationsExtension.js
> +import { useEffect } from 'react';
can we use wordpress/element

2023-03-14 14:05 UTC, aapatre commented on admin-core/ajax/common-settings.php
> +		$response_data = array(
done

2023-03-14 14:05 UTC, aapatre commented on admin-core/assets/src/dashboard-app/pages/blocks/AnimationsExtension.js
> +import { useEffect } from 'react';
done

2023-03-14 14:06 UTC, aapatre commented on admin-core/assets/src/dashboard-app/pages/blocks/AnimationsExtension.js
> +        key={'animations-extension'}
Removed the key since the admin dashboard extensions cards are not inside a loop

2023-03-14 14:54 UTC, adi3890 approved these changes

2023-03-15 01:34 UTC, bsf-zanev approved these changes
Looks good to me.

2023-03-15 15:11 UTC, rahulvarma722 commented on classes/class-uagb-init-blocks.php
> +			$aos_attributes = '<div data-aos= "' . $attrs['UAGAnimationType'] . '" data-aos-duration="' . $attrs['UAGAnimationTime'] . '" data-aos-delay="' . $attrs['UAGAnimationDelay'] . '" data-aos-easing="
missing esc_attr

2023-03-16 03:37 UTC, aapatre commented on admin-core/ajax/common-settings.php
> +	public function enable_animations_extension() {
Got it, so need for any changes at the moment, right?
I see that the functions are anyways unavailable right now

Will keep this comment unresolved

2023-03-16 05:37 UTC, aapatre commented on .eslintignore
> +assets/js/aos.js
Done

2023-03-16 05:37 UTC, aapatre commented on admin-core/assets/src/dashboard-app/pages/blocks/AnimationsExtension.js
> +    useEffect( () => {
Done

2023-03-19 18:59 UTC, rahulvarma722 commented on admin-core/assets/src/dashboard-app/pages/blocks/AnimationsExtension.js
> +function classNames( ...classes ) {
Please take reference from https://github.com/brainstormforce/ultimate-addons-for-gutenberg/blob/next-release/src/components/icon-picker/modal-container.js - uagbClassNames for classNames

2023-03-19 18:59 UTC, rahulvarma722 commented on classes/class-uagb-init-blocks.php
> +			$attrs['UAGAnimationTime']   = array_key_exists( 'UAGAnimationTime', $attrs ) ? $attrs['UAGAnimationTime'] : 400;
Please remove array_key_exists from all places and instead of this use isset because array_key_exists will iterate all of your array and we need to check only one variable

2023-03-22 08:52 UTC, aapatre commented on classes/class-uagb-init-blocks.php
> +			$attrs['UAGAnimationTime']   = array_key_exists( 'UAGAnimationTime', $attrs ) ? $attrs['UAGAnimationTime'] : 400;
Done

2023-03-22 09:22 UTC, aapatre commented on admin-core/assets/src/dashboard-app/pages/blocks/AnimationsExtension.js
> +function classNames( ...classes ) {
Okay, I checked this, apparently the node and webpack setup in `admin-core` is different from the main directory.
Hence we cannot use the helper functions from main directory.

2023-03-22 10:17 UTC, bsf-zanev commented on admin-core/assets/src/dashboard-app/pages/blocks/AnimationsExtension.js
> +                {/* Animations Reminder: Please update the icon */}
This comment can be removed if I'm not mistaken.

2023-03-22 10:50 UTC, bsf-zanev commented on admin-core/assets/src/utils/Helpers.js
> + * @return {string} classes - Classes string.
```suggestion
 * @param {...string} classes - Selectors to combine.
 * @return {string} The single-line selector string.
```

2023-03-22 11:01 UTC, aapatre commented on admin-core/assets/src/utils/Helpers.js
> + * @return {string} classes - Classes string.
Done

2023-03-22 11:02 UTC, bsf-zanev approved these changes

2023-03-22 11:14 UTC, adi3890 commented on admin-core/assets/src/dashboard-app/pages/blocks/AnimationsExtension.js
> +                    className={uagbClassNames(
is this correct way of passing arguments to uagbClassNames
please check other reference from plugin
@rahulvarma722 please check

2023-03-22 12:11 UTC, aapatre commented on admin-core/assets/src/dashboard-app/pages/blocks/AnimationsExtension.js
> +                    className={uagbClassNames(
This is a new helper function I've created for admin-core files (the helpers from main directory aren't accessible here). It's slightly different from the helper in main directory (the main dir helper accepts arrays as class names, while this one uses spread parameter `{...string}` )

The reason I'm following the second convention is because this will ensure minimal changes in admin-core directory if we upgrade the old code to use the new/common helper function.

cc: @adi3890 @rahulvarma722

2023-03-22 12:17 UTC, rahulvarma722 commented on admin-core/assets/src/dashboard-app/pages/blocks/AnimationsExtension.js
> +                    className={uagbClassNames(
We have decided that instead of a string we will use an array everywhere for better readability also if we send a string to a function this will convert it to an array so the passing array is better because it will reduce unnecessary conversion string to array.

2023-03-24 08:56 UTC, adi3890 approved these changes

2023-03-24 09:05 UTC, aapatre commented on admin-core/assets/src/utils/Helpers.js
> +    return classes.filter( Boolean ).join( ' ' )
Already done

2023-03-27 10:33 UTC, RajkiranBagal requested changes

2023-03-27 10:33 UTC, RajkiranBagal commented on src/blocks/extensions/copy-paste-styles/index.js
Can you try adding your attributes using this filter `uagb.blocksAttributes` in `src/blocks/extensions/copy-paste-styles/index.js`

2023-03-27 11:17 UTC, aapatre commented on src/blocks/extensions/copy-paste-styles/index.js
I checked this, and it looks like `uagb.blocksAttributes` is only used for fetching attributes.js data from Pro. We cannot register new attributes with the filter.

2023-03-27 18:47 UTC, rahulvarma722 approved these changes

2023-04-18 06:29 UTC, aapatre commented on admin-core/ajax/common-settings.php
> +	public function enable_animations_extension() {
Done

2023-04-21 07:59 UTC, rahulvarma722 commented on src/blocks/extensions/advanced-settings/index.js
> +const { createHigherOrderComponent } = wp.compose;
Get compose from @wordpress package

2023-04-21 07:59 UTC, rahulvarma722 commented on src/blocks/faq-child/edit.js
>  			<Render parentProps={ props } state={ state } />
check state, is required or not if not remove all state-related code and can we remove parentPropsand add like this <Render { ...props } state={ state } /> from both component

2023-04-25 11:31 UTC, aapatre commented on src/blocks/faq-child/edit.js
>  			<Render parentProps={ props } state={ state } />
Since this is animations feature related PR, it wouldn't be apt to make optimization changes to other blocks via this.
Let's create a task for the same.

2023-04-25 12:16 UTC, rahulvarma722 approved these changes

2023-05-01 11:13 UTC, RajkiranBagal requested changes

2023-05-01 11:13 UTC, RajkiranBagal commented on classes/class-uagb-post-assets.php
> +			isset( $block['attrs']['UAGAnimationType'] ) &&
check `! empty()` instead of 2 conditions

2023-05-01 11:25 UTC, RajkiranBagal approved these changes

2023-05-01 11:26 UTC, merged