SPCTR-2481-Fix: Modal: info box loading issue in modal
brainstormforce/ultimate-addons-for-gutenberg pull request #2814
Opened 2023-03-14 12:31 UTC by rajmohanreddy774

### Description

### Screenshots

### Types of changes

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2023-03-17 10:04 UTC, RajkiranBagal requested changes

2023-03-17 10:04 UTC, RajkiranBagal commented on README.md
> +* Fix: Modal - Info box as a innerBlock not loading in modal block when gutenberg is activated
```suggestion
* Fix: Modal - Info box as a inner block not loading in the Modal block when Gutenberg is activated.
```

2023-03-17 10:52 UTC, rajmohanreddy774 commented on README.md
> +* Fix: Modal - Info box as a innerBlock not loading in modal block when gutenberg is activated
Added

2023-03-17 10:59 UTC, RajkiranBagal approved these changes

2023-03-17 11:03 UTC, RajkiranBagal approved these changes

2023-03-21 13:48 UTC, aapatre commented
Have you confirmed backward-compatibility?

2023-03-21 14:02 UTC, rajmohanreddy774 commented
> Have you confirmed backward-compatibility?

Yes backward-compatibility check.

2023-03-21 14:09 UTC, aapatre approved these changes

2023-03-24 06:23 UTC, AbhijitNage123 approved these changes

2023-03-24 06:58 UTC, rahulvarma722 commented on src/blocks/modal/render.js
> +	const defaultedAlt = ( iconImage && iconImage )?.alt ? iconImage?.alt : '';
```suggestion
	const defaultedAlt = iconImage?.alt ? iconImage.alt : '';
```
Please check this once

2023-03-24 06:58 UTC, rahulvarma722 commented on src/blocks/modal/modalConfig.js
> +export const defaultContent = [
Add proper description for this variable like when you add first time this content will show

2023-03-24 06:58 UTC, rahulvarma722 commented on src/blocks/modal/modalConfig.js
> +export const excludeBlocks = [
Add proper description for this

2023-03-24 06:58 UTC, rahulvarma722 commented on src/blocks/modal/render.js
> +	if ( iconImage && iconImage.url ) {
```suggestion
	if ( iconImage?.url ) {
```

2023-03-24 07:22 UTC, rajmohanreddy774 commented on src/blocks/modal/modalConfig.js
> +export const defaultContent = [
Added

2023-03-24 07:22 UTC, rajmohanreddy774 commented on src/blocks/modal/modalConfig.js
> +export const excludeBlocks = [
Added

2023-03-24 07:43 UTC, rahulvarma722 approved these changes

2023-03-27 09:14 UTC, RajkiranBagal approved these changes

2023-03-27 09:19 UTC, RajkiranBagal approved these changes

2023-03-27 09:19 UTC, merged