SPCTR-2479-Fix: backend font loading issue in footer
brainstormforce/ultimate-addons-for-gutenberg pull request #2829
Opened 2023-03-16 12:45 UTC by chandan-30

### Description

### Screenshots

### Types of changes

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2023-03-17 05:58 UTC, aapatre approved these changes

2023-03-17 06:33 UTC, RajkiranBagal commented on classes/class-uagb-rest-api.php
I see only this file change is needed in this PR, Why other files are changed? Please undo other file changes.

2023-03-17 06:33 UTC, RajkiranBagal commented on classes/class-uagb-rest-api.php
> +			if ( 'uagb/advanced-heading' === $block['blockName'] && ! empty( $style ) ) {
Is the issue only for the Heading block? Do other blocks work fine?

2023-03-20 06:29 UTC, chandan-30 commented on classes/class-uagb-rest-api.php
Made changes. Removed all the other files

2023-03-20 06:31 UTC, chandan-30 commented on classes/class-uagb-rest-api.php
> +			if ( 'uagb/advanced-heading' === $block['blockName'] && ! empty( $style ) ) {
I have rechecked all the blocks and found few blocks are having same issue, so I changed code logic which works for all.

2023-03-20 09:40 UTC, RajkiranBagal approved these changes

2023-03-27 18:31 UTC, rahulvarma722 requested changes

2023-03-27 18:31 UTC, rahulvarma722 commented on classes/class-uagb-rest-api.php
>  		}
Please verify once and modify your code

`
function content_pre_render( $block ) {
	$tab_styling_css  = '';
	$mob_styling_css  = '';
	$UAGB_Post_Assets = new UAGB_Post_Assets( get_the_ID() );

	$assets = $UAGB_Post_Assets->get_block_css_and_js( $block );

	$desktop_css = isset( $assets['css']['desktop'] ) ? $assets['css']['desktop'] : '';

	if ( isset( $assets['css']['tablet'] ) && ! empty( $assets['css']['tablet'] ) ) {
		$tab_styling_css .= '@media only screen and (max-width: ' . UAGB_TABLET_BREAKPOINT . 'px) {';
		$tab_styling_css .= $assets['css']['tablet'];
		$tab_styling_css .= '}';
	}

	if ( isset( $assets['css']['mobile'] ) && ! empty( $assets['css']['mobile'] ) ) {
		$mob_styling_css .= '@media only screen and (max-width: ' . UAGB_MOBILE_BREAKPOINT . 'px) {';
		$mob_styling_css .= $assets['css']['mobile'];
		$mob_styling_css .= '}';
	}

	$block_css_style = $desktop_css . $tab_styling_css . $mob_styling_css;

	if( empty( $block_css_style ) ){
		return $block;
	}

	$link_tag_list = '';
	// This line of code creates a new array named $font_family_attrs by searching through the keys of an existing array.
	$font_family_attrs = preg_grep( '/fontfamily/i', array_keys( $block['attrs'] ) );

	foreach ( $font_family_attrs as $attr ) {
		if ( ! empty( $block['attrs'][ $attr ] ) ) {
			// Get the font family value and construct the Google Fonts URL.
			$gfont_url   = 'https://fonts.googleapis.com/css?family=' . urlencode( $block['attrs'][ $attr ] );

			// Create a link tag for the stylesheet with the constructed URL.
			$link_tag_list .= '<link rel="stylesheet" href="' . esc_url( $gfont_url ) . '" media="all">';
		}
	}

	$style = '<style class="uagb-widgets-style-renderer">' . $block_css_style . '</style>';
	$style = $style . $link_tag_list;
	array_push( $block['innerContent'], $style );

	return $block;
}`

2023-03-28 06:37 UTC, chandan-30 commented on classes/class-uagb-rest-api.php
>  		}
@rahulvarma722 Made required changes, Please re-review.

2023-03-29 07:58 UTC, rahulvarma722 requested changes

2023-03-29 07:58 UTC, rahulvarma722 commented on classes/class-uagb-rest-api.php
> +			$style = '<style class="uagb-widgets-style-renderer">' . $block_css_style . '</style>';
This should be in before line number 108 and after 107

2023-03-29 07:58 UTC, rahulvarma722 commented on classes/class-uagb-rest-api.php
> +			}
Leave a space after this statement

2023-03-29 08:46 UTC, chandan-30 commented on classes/class-uagb-rest-api.php
> +			}
It's done.

2023-03-29 09:02 UTC, rahulvarma722 approved these changes

2023-03-29 10:53 UTC, RajkiranBagal approved these changes

2023-03-29 11:05 UTC, RajkiranBagal approved these changes

2023-03-29 11:06 UTC, merged