General:SPCTR-2372-No need of Negative Line height/Font-Size/Border Radius/Border Width
brainstormforce/ultimate-addons-for-gutenberg pull request #2833
Opened 2023-03-20 06:05 UTC by ravinishadcoder

### Description
No need of Negative Line height/Font-Size/Border Radius/Border Width
[https://brainstormforce.atlassian.net/browse/SPCTR-2372?atlOrigin=eyJpIjoiYjBiYjI3ZWJmYzYxNDhjOWI2N2M4OTAxMTg0OTc5MzIiLCJwIjoiaiJ9](url)
### Screenshots

[https://d.pr/v/MsfgHj](url)
### Types of changes

Bug fix (non-breaking change which fixes an issue)

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2023-03-20 09:24 UTC, RajkiranBagal requested changes

2023-03-20 09:24 UTC, RajkiranBagal commented on src/components/spacing-control/index.js
This is a very unprofessional way of implementing things. Are we going to determine based on Labels the min value of controls? How many labels we will do this? 

@AbhijitNage123 Please guide the developer here.

2023-03-20 09:24 UTC, RajkiranBagal commented on src/components/typography/range-typography.js
This is a very unprofessional way of implementing things. Are we going to determine based on Labels the min value of controls? How many labels we will do this? 

@AbhijitNage123 Please guide the developer here.

2023-03-20 09:24 UTC, RajkiranBagal commented on readme.txt
> +* General: No need of Negative Line height/Font-Size/Border Radius/Border Width.
Follow our standard practices for adding changelog.
```suggestion
* Fix: Spacing Control - Removed the capability to set negative values for width & radius settings.
* Fix: Typography Control - Removed the capability to set negative values for line-height & font size settings.
```

2023-03-22 06:10 UTC, AbhijitNage123 commented on src/components/spacing-control/index.js
> +					min={ props.min }
in attribute object set `min = 0` just like `helpText` and use only min. and make sure you have tested it with padding/margin also

2023-03-22 06:13 UTC, AbhijitNage123 commented on src/components/typography/range-typography.js
> +				min={ props.min }
let's create a const {} = props and add all attributes that we are taking from props into that const. Refer -https://github.com/brainstormforce/ultimate-addons-for-gutenberg/blob/95f92db9b52f325f0022312bf78214a3bfcc6667/src/components/spacing-control/index.js#L37

2023-03-22 07:19 UTC, ravinishadcoder commented on src/components/spacing-control/index.js
> +					min={ props.min }
I have done the suggested changes and tested

2023-03-22 07:19 UTC, ravinishadcoder commented on src/components/typography/range-typography.js
> +				min={ props.min }
I have done the suggested changes

2023-03-23 11:29 UTC, RajkiranBagal approved these changes

2023-03-24 06:17 UTC, AbhijitNage123 approved these changes

2023-03-29 04:32 UTC, RajkiranBagal approved these changes

2023-03-29 04:40 UTC, RajkiranBagal approved these changes

2023-03-29 04:44 UTC, merged