SPCTR-2499-update the box shadow feature as per new standards and implement missing hover box-shadow features
brainstormforce/ultimate-addons-for-gutenberg pull request #2870
Opened 2023-03-23 13:28 UTC by ravinishadcoder

### Description

### Screenshots

### Types of changes

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2023-04-05 15:15 UTC, aapatre commented on src/blocks/buttons-child/presets.js
> +const boxShadowHoverPresets = [
Can we do `export const` here itself?

2023-04-06 04:39 UTC, aapatre commented
Also, please make sure to add the changelog.

2023-04-06 06:22 UTC, bsf-zanev requested changes
Added a few comments, besides that later we can look into creating the box shadow component separately and calling it inside the tabs based on whether or not it's a hover attribute.

It would make the code much more neater.

2023-04-06 06:22 UTC, bsf-zanev commented on src/blocks/buttons-child/settings.js
> +import boxShadowPresets, {boxShadowHoverPresets, buttonsPresets } from './presets';
Let's leave a space after this curly bracket.

2023-04-07 07:07 UTC, ravinishadcoder commented on src/blocks/buttons-child/presets.js
> +const boxShadowHoverPresets = [
I have done the suggested change

2023-04-07 07:08 UTC, ravinishadcoder commented on classes/class-uagb-block-helper.php
>  			if ( 0 !== $attr['boxShadowHOffset'] || 0 !== $attr['boxShadowVOffset'] ) {
No, I have removed that if the condition that is not required

2023-04-07 07:09 UTC, ravinishadcoder commented on src/blocks/buttons-child/settings.js
> +import boxShadowPresets, {boxShadowHoverPresets, buttonsPresets } from './presets';
Yes, I have added the space there

2023-05-05 10:50 UTC, aapatre approved these changes

2023-05-10 08:54 UTC, rahulvarma722 approved these changes

2023-05-10 10:22 UTC, bsf-zanev commented on classes/class-uagb-block-helper.php
> +					'transition' => 'box-shadow 0.2s ease',
Should we keep this transition outside the `:hover` psuedoclass, and in a static CSS file?

Since the transition properties will be common across blocks of this type, and should be defined before the hover is triggered so that it transitions smoothly.

2023-05-10 10:22 UTC, bsf-zanev commented on src/blocks/buttons-child/styling.js
> +			'transition' : 'box-shadow 0.2s ease'
Should we keep this transition outside the :hover psuedoclass, and in a static CSS file?

Since the transition properties will be common across blocks of this type, and should be defined before the hover is triggered so that it transitions smoothly.

2023-05-10 12:15 UTC, bsf-zanev commented on includes/blocks/countdown/frontend.css.php
> +			'transition'       => 'box-shadow 0.2s ease',
Can we keep these transitions in `style.scss` instead of keeing the exact same ones in `frontend.css.php` and `styling.js`?

Do the same changes in all the other PRs too and test them after regenerating assets to ensure that they work as required in the editor and front-end.

2023-05-11 05:41 UTC, adi3890 commented on classes/class-uagb-block-helper.php
> +			);
just wanted to confirm hon't we have this key alt_color for $box_shadow_properties

2023-05-11 05:41 UTC, adi3890 commented on src/blocks/countdown/styling.js
> +			'transition': 'box-shadow 0.2s ease',
as mentioned in one of the comment above.
we have have static css in style.scss.
Please try same.

2023-05-15 04:33 UTC, ravinishadcoder commented on classes/class-uagb-block-helper.php
> +			);
No, we don't have key alt_color for $box_shadow_properties

2023-05-22 03:38 UTC, bsf-zanev approved these changes

2023-05-29 09:20 UTC, RajkiranBagal approved these changes

2023-05-29 09:31 UTC, merged