Fix:SPCTR-2499-[Icon]-Box-Shadow-hover and animation Implemented
brainstormforce/ultimate-addons-for-gutenberg pull request #2886
Opened 2023-03-24 12:47 UTC by ravinishadcoder

### Description

### Screenshots

### Types of changes

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2023-04-05 15:13 UTC, aapatre approved these changes

2023-04-06 06:34 UTC, bsf-zanev requested changes
Minor Changes requested.

2023-04-06 06:34 UTC, bsf-zanev commented on includes/blocks/icon/attributes.php
> +		'iconBoxShadowColorHover'          => '#00000070',
I don't think hover color should be set by default.

2023-04-06 06:34 UTC, bsf-zanev commented on src/blocks/icon/attributes.js
> +		default: '#00000070',
I don't think hover color should be set by default.

2023-04-07 07:39 UTC, ravinishadcoder commented on includes/blocks/icon/attributes.php
> +		'iconBoxShadowColorHover'          => '#00000070',
I have removed the default value for hover color

2023-04-07 07:39 UTC, ravinishadcoder commented on src/blocks/icon/attributes.js
> +		default: '#00000070',
I have removed the default hover color value

2023-05-10 10:24 UTC, bsf-zanev commented on src/blocks/icon/styling.js
> +			'transition' : 'box-shadow 0.2s ease'
Should we keep this transition outside the :hover psuedoclass, and in a static CSS file?

Since the transition properties will be common across blocks of this type, and should be defined before the hover is triggered so that it transitions smoothly.

2023-05-22 03:40 UTC, bsf-zanev approved these changes
Looks good, just make this one small change.

2023-05-22 03:40 UTC, bsf-zanev commented on src/blocks/icon/styling.js
> +			'box-shadow': boxShadow,
Remove this extra space.

2023-05-22 04:02 UTC, ravinishadcoder commented on src/blocks/icon/styling.js
> +			'box-shadow': boxShadow,
I have removed this extra space.

2023-05-29 08:35 UTC, RajkiranBagal approved these changes

2023-05-29 09:11 UTC, merged