Fix:SPCTR-2499-[Image]-Box-Shadow-hover and animation Implemented and animation implemented in Post grid and slider
brainstormforce/ultimate-addons-for-gutenberg pull request #2915
Opened 2023-03-28 13:38 UTC by ravinishadcoder

### Description

- Implemented Box-shadow-hover and animation for Image block
- Implemented new Box-shadow generate function and animation Box-shadow-hover for Post Grid and Slider blocks
### Screenshots

[Screencast](https://d.pr/v/S6tgO1)
### Types of changes

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2023-04-05 15:11 UTC, aapatre approved these changes

2023-04-06 06:41 UTC, bsf-zanev requested changes
Minor Changes Requested.

2023-04-06 06:41 UTC, bsf-zanev commented on includes/blocks/image/attributes.php
> +		'imageBoxShadowColorHover'    => '#00000070',
I don't think hover color should be set by default.

2023-04-06 06:41 UTC, bsf-zanev commented on src/blocks/image/attributes.js
> +		default: '#00000070',
I don't think hover color should be set by default.

2023-04-07 09:40 UTC, ravinishadcoder commented on includes/blocks/image/attributes.php
> +		'imageBoxShadowColorHover'    => '#00000070',
I have removed imageBoxShadowColorHover default value

2023-04-07 09:40 UTC, ravinishadcoder commented on src/blocks/image/attributes.js
> +		default: '#00000070',
I have removed imageBoxShadowColorHover default value

2023-04-07 09:40 UTC, ravinishadcoder commented on src/blocks/post/post-grid/settings.js
> +
Changes done as suggested

2023-05-10 09:02 UTC, rahulvarma722 approved these changes

2023-05-10 10:25 UTC, bsf-zanev commented on src/blocks/image/styling.js
> +			'transition': 'box-shadow 0.2s ease'
Should we keep this transition outside the :hover psuedoclass, and in a static CSS file?

Since the transition properties will be common across blocks of this type, and should be defined before the hover is triggered so that it transitions smoothly.

2023-05-10 10:25 UTC, bsf-zanev commented on includes/blocks/image/frontend.css.php
> +		'transition' => 'box-shadow 0.2s ease',
Should we keep this transition outside the :hover psuedoclass, and in a static CSS file?

Since the transition properties will be common across blocks of this type, and should be defined before the hover is triggered so that it transitions smoothly.

2023-05-22 03:43 UTC, bsf-zanev approved these changes

2023-05-29 09:14 UTC, RajkiranBagal approved these changes

2023-05-29 09:19 UTC, merged