Fix:SPCTR-2551- Post carousel - Gap between post not visible when only 2 post is present.
brainstormforce/ultimate-addons-for-gutenberg pull request #2922
Opened 2023-04-03 13:11 UTC by ravinishadcoder

### Description

### Screenshots

### Types of changes

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2023-04-05 05:16 UTC, rahulvarma722 requested changes

2023-04-05 05:16 UTC, rahulvarma722 commented on blocks-config/post/class-uagb-post.php
> +									}
```suggestion
							let image = article.getElementsByClassName('uagb-post__image');
									if ( image[0] ) {
									let articleWidth = article.offsetWidth;
									let rowGap = <?php echo esc_html( $value['rowGap'] ); ?>;
									let imageWidth = 100 - ( rowGap / articleWidth ) * 100;

										image[0].style.width = imageWidth + '%';
										image[0].style.marginLeft = rowGap / 2 + 'px';

									}
```

2023-04-05 05:47 UTC, rahulvarma722 requested changes

2023-04-05 05:47 UTC, rahulvarma722 commented on blocks-config/post/class-uagb-post.php
> +							let image = article.getElementsByClassName('uagb-post__image');
Add proper indentation.

2023-04-05 05:47 UTC, rahulvarma722 commented on blocks-config/post/class-uagb-post.php
> +									let articleWidth = article.offsetWidth;
Add proper indentation.

2023-04-05 06:01 UTC, rahulvarma722 requested changes

2023-04-05 06:01 UTC, rahulvarma722 commented on blocks-config/post/class-uagb-post.php
> +								for( let article of articles ) {
Validate articles first.

2023-04-05 16:29 UTC, supriyajjadhav commented
Please add changelog

2023-04-10 04:20 UTC, ravinishadcoder commented on blocks-config/post/class-uagb-post.php
> +								for( let article of articles ) {
Added validation for articles

2023-04-10 04:35 UTC, AbhijitNage123 approved these changes

2023-04-13 07:53 UTC, RajkiranBagal approved these changes

2023-04-13 07:54 UTC, RajkiranBagal requested changes

2023-04-13 07:54 UTC, RajkiranBagal commented on package-lock.json
@ravinishadcoder Undo this change. Copy next-release file & paste it if needed.

2023-04-13 09:35 UTC, ravinishadcoder commented on package-lock.json
I have undo the changes

2023-04-14 07:38 UTC, RajkiranBagal approved these changes

2023-04-14 08:47 UTC, rahulvarma722 requested changes

2023-04-14 08:47 UTC, rahulvarma722 commented on blocks-config/post/class-uagb-post.php
> +								}
```suggestion
								if( articles?.length ) {
									return;
								}
```
This should be

2023-04-14 09:45 UTC, ravinishadcoder commented on blocks-config/post/class-uagb-post.php
> +								}
I implemented the code you suggested. But it is not working as expected. This is always returned from line number 1720.
[Screencast](https://d.pr/v/4GRnco)

2023-04-17 16:15 UTC, RajkiranBagal approved these changes

2023-04-18 05:44 UTC, rahulvarma722 approved these changes

2023-04-20 11:13 UTC, RajkiranBagal approved these changes

2023-04-20 11:13 UTC, merged