Implemented logic to append style tag inside blocks html to resolve an issue loading block dynamic CSS in iframe.
brainstormforce/ultimate-addons-for-gutenberg pull request #2929
Opened 2023-04-05 11:09 UTC by AbhijitNage123

### Description

- NA

### Screenshots

- https://share.getcloudapp.com/DOulmY0R

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

### How has this been tested?

- Drag and drop any block.
- Add a styling to it.
- Inspect it, and make sure style tag is appended within block HTML as shown in [here](https://share.getcloudapp.com/DOulmY0R)
- Check by making it template part or switching it into tablet/mobile devices.

### Checklist:
- [x] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [x] I've included any necessary tests 
- [ ] I've included developer documentation 
- [x] I've added proper labels to this pull request

2023-04-05 12:51 UTC, RajkiranBagal requested changes

2023-04-05 12:51 UTC, RajkiranBagal commented on src/blocks/advanced-heading/FontLoader.js
This component should be generic & can be able to use in any block we want.

Why is this added in advanced-heading folder?

2023-04-05 12:51 UTC, RajkiranBagal commented on src/blocks/advanced-heading/cssComponent.js
This component should be generic & can be able to use in any block we want.

Why is this added in advanced-heading folder?

2023-04-05 12:51 UTC, RajkiranBagal commented on src/blocks/advanced-heading/cssComponent.js
> +const CssComponent = ( { attributes, clientId, name, deviceType } ) => {
```suggestion
const DynamicCSSLoader = ( { attributes, clientId, name, deviceType } ) => {
```

2023-04-05 13:07 UTC, AbhijitNage123 commented on src/blocks/advanced-heading/cssComponent.js
> +const CssComponent = ( { attributes, clientId, name, deviceType } ) => {
Resolve

2023-04-05 13:07 UTC, AbhijitNage123 commented on src/blocks/advanced-heading/cssComponent.js
Resolve

2023-04-05 13:07 UTC, AbhijitNage123 commented on src/blocks/advanced-heading/FontLoader.js
Resolve

2023-04-05 14:20 UTC, RajkiranBagal requested changes

2023-04-05 14:20 UTC, RajkiranBagal commented on src/blocks/advanced-heading/dynamicFontLoader.js
This file should also be in components & component should be dynamic ie. Can be used by any block.

2023-04-05 14:43 UTC, AbhijitNage123 commented on src/components/dynamic-css-loader/dynamicCSSLoader.js
Resolved

2023-04-05 14:47 UTC, AbhijitNage123 commented on src/blocks/advanced-heading/dynamicFontLoader.js
I already tried it but it is not possible also discuss it with @rahulvarma722. We get different font variable by diff block

2023-04-05 14:59 UTC, rahulvarma722 approved these changes

2023-04-05 15:01 UTC, rahulvarma722 commented on src/blocks/advanced-heading/dynamicFontLoader.js
We will do after completing style part and after style part we will optimise dynamicFontLoader.js file then we will create commpon component for this or we can put this in css component.

2023-04-06 04:19 UTC, RajkiranBagal commented on src/blocks/advanced-heading/dynamicFontLoader.js
@rahulvarma722 @AbhijitNage123 I do not think we have thought this through, this seems not good implementation to me. Let's skip this @AbhijitNage123 is you are not able to do it in a optimized way.

@rahulvarma722 OR I myself will do it later.

Just keep fonts loading as it is.

2023-04-06 06:46 UTC, AbhijitNage123 commented on src/blocks/advanced-heading/dynamicFontLoader.js
As this process is cleaning up the edit.js and memoize the fontLoader component. We will be optimizing it later phase. as per discusstion with @rahulvarma722 .

2023-04-17 07:12 UTC, RajkiranBagal approved these changes

2023-04-17 07:17 UTC, merged