FontLoader and CSSLoader changes for Forms, GF-Styler, Google map, HowTo, and Icon.
brainstormforce/ultimate-addons-for-gutenberg pull request #2934
Opened 2023-04-06 13:20 UTC by AbhijitNage123

### Description

- Base - https://github.com/brainstormforce/ultimate-addons-for-gutenberg/pull/2929

### Screenshots

- NA

### Types of changes

- NA

### How has this been tested?

- NA

### Checklist:
- NA

2023-04-07 12:09 UTC, rahulvarma722 requested changes

2023-04-07 12:11 UTC, AbhijitNage123 commented on src/blocks/forms/edit.js
> +import { useLayoutEffect, useEffect, useCallback, useMemo } from '@wordpress/element';
Yes it is already used.

2023-04-10 04:51 UTC, rahulvarma722 approved these changes

2023-04-10 04:55 UTC, RajkiranBagal approved these changes

2023-04-10 04:57 UTC, merged