Fix:SPCTR-1848-Container-Initial layout selection UI in editor and customizer block editor
brainstormforce/ultimate-addons-for-gutenberg pull request #2977
Opened 2023-04-13 13:07 UTC by ravinishadcoder

### Description

Fix: Container-Initial layout selection UI in editor and customizer block editor
[Task link](https://brainstormforce.atlassian.net/browse/SPCTR-1848?atlOrigin=eyJpIjoiZTFlNjgwMDE1ZjhiNDlhMWFkZTU5YzM1OGVlZjY4ZWYiLCJwIjoiaiJ9)
### Screenshots

[Screencast](https://d.pr/v/t9bTMT)
### Types of changes

Bug fix (non-breaking change which fixes an issue) 

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2023-04-13 13:30 UTC, AbhijitNage123 approved these changes

2023-04-13 13:59 UTC, bsf-zanev requested changes

2023-04-13 13:59 UTC, bsf-zanev commented on src/blocks/container/edit.js
> +							`</br>` // eslint-disable-line no-undef
Why are we using no-undef for this break tag...?

2023-04-13 13:59 UTC, bsf-zanev commented on src/blocks/container/editor.lazy.scss
> +			stroke: #0063a1;
Let's use `$spectra-color-secondary` here.

2023-04-13 13:59 UTC, bsf-zanev commented on src/blocks/container/editor.lazy.scss
> +			color: #1e1e1e;
Confirm with designers if we need to add this color to our palette, or if we can use one of our existing colors from the [Figma Spectra Color Palette](https://www.figma.com/file/Adn6EAVPWePS5BuB86p5ng/Spectra-Style-Guide?node-id=109-155&t=ipm90EaTDNrQX2oz-0).

2023-04-13 13:59 UTC, bsf-zanev commented on src/blocks/container/editor.lazy.scss
> +			margin-right: 11.5px;
We can make this 12px.

2023-04-13 13:59 UTC, bsf-zanev commented on src/blocks/container/editor.lazy.scss
> +			color: #50575e;
Let's use `$spectra-color-body` here.

2023-04-13 13:59 UTC, bsf-zanev commented on src/blocks/container/editor.lazy.scss
> +			max-width: 100% !important;
Why is important used here?

2023-04-14 04:50 UTC, ravinishadcoder commented on src/blocks/container/editor.lazy.scss
> +			max-width: 100% !important;
`BlockVariationPicker` which we are using from  `@wordpress/block-editor`, has set default `max-width` for `components-placeholder__fieldset`, to overwrite that default CSS, I have used` ! important` there.

2023-04-14 06:48 UTC, ravinishadcoder commented on src/blocks/container/edit.js
> +							`</br>` // eslint-disable-line no-undef
I have removed that no-undef

2023-04-14 06:49 UTC, ravinishadcoder commented on src/blocks/container/editor.lazy.scss
> +			stroke: #0063a1;
Done the suggested changes.

2023-04-14 06:49 UTC, ravinishadcoder commented on src/blocks/container/editor.lazy.scss
> +			margin-right: 11.5px;
Done the suggested changes.

2023-04-14 06:50 UTC, ravinishadcoder commented on src/blocks/container/editor.lazy.scss
> +			color: #50575e;
Done the suggested changes.

2023-04-14 12:11 UTC, ravinishadcoder commented on src/blocks/container/editor.lazy.scss
> +			color: #1e1e1e;
I have confirmed with Akbar Hartomo and used the color from the [Figma Spectra Color Palette](https://www.figma.com/file/Adn6EAVPWePS5BuB86p5ng/Spectra-Style-Guide?node-id=109-155&t=ipm90EaTDNrQX2oz-0).

2023-04-14 13:13 UTC, RajkiranBagal approved these changes

2023-04-20 10:37 UTC, RajkiranBagal approved these changes

2023-04-20 11:14 UTC, RajkiranBagal approved these changes

2023-04-20 11:19 UTC, bsf-zanev approved these changes
Good to go, just remove that Eslint-disable-lint and test once.

2023-04-20 11:19 UTC, bsf-zanev commented on src/blocks/container/edit.js
> +							`</br>` // eslint-disable-line
Is this eslint comment required?

2023-04-20 12:05 UTC, ravinishadcoder commented on src/blocks/container/edit.js
> +							`</br>` // eslint-disable-line
I have removed this line

2023-04-20 12:13 UTC, RajkiranBagal approved these changes

2023-04-20 12:15 UTC, merged