Fix:SPCTR-2553-Table of content - not properly shown in preview of post when used as a custom layout inside post/page content.
brainstormforce/ultimate-addons-for-gutenberg pull request #2986
Opened 2023-04-14 13:01 UTC by ravinishadcoder

### Description

Fix: Table of content - not properly shown in the preview of the post when used as a custom layout inside post/page content.
[Task link](https://brainstormforce.atlassian.net/browse/SPCTR-2553?atlOrigin=eyJpIjoiN2RkOWU0ZDFjYzM1NGU5ZDk1OTBmNzUyYTViNGEyMWIiLCJwIjoiaiJ9)
### Screenshots

[Screencast](https://d.pr/v/WJ5OLU)
### Types of changes

Bug fix (non-breaking change which fixes an issue)

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2023-04-17 11:20 UTC, RajkiranBagal approved these changes

2023-04-20 10:46 UTC, RajkiranBagal requested changes

2023-04-20 10:46 UTC, RajkiranBagal commented on classes/class-uagb-post-assets.php
> +		$result = Astra_Target_Rules_Fields::get_instance()->get_posts_by_conditions( ASTRA_ADVANCED_HOOKS_POST_TYPE, $option );
Should we first check if the `Astra_Target_Rules_Fields` class exists?

2023-04-20 11:59 UTC, supriyajjadhav commented
Please add Changelog.

2023-04-20 13:10 UTC, ravinishadcoder commented on classes/class-uagb-post-assets.php
> +		$result = Astra_Target_Rules_Fields::get_instance()->get_posts_by_conditions( ASTRA_ADVANCED_HOOKS_POST_TYPE, $option );
I have added validation for `Astra_Target_Rules_Fields` class.

2023-04-21 04:08 UTC, imnavanath commented on classes/class-uagb-post-assets.php
> +		if ( ! class_exists( 'Astra_Target_Rules_Fields' ) ) {
```suggestion
		if ( ! defined( 'ASTRA_ADVANCED_HOOKS_POST_TYPE' ) ) {
```

2023-04-21 04:09 UTC, imnavanath commented on classes/class-uagb-post-assets.php
> +		if ( ! class_exists( 'Astra_Target_Rules_Fields' ) ) {
Because we use this rule engine library in many internal plugins, so add this condition to check this constant.

2023-04-21 04:09 UTC, imnavanath commented on classes/class-uagb-post-assets.php
> +		if ( ! class_exists( 'Astra_Target_Rules_Fields' ) ) {
FYI - https://github.com/brainstormforce/header-footer-elementor/blob/master/inc/lib/target-rule/class-astra-target-rules-fields.php

2023-04-21 04:19 UTC, ravinishadcoder commented on classes/class-uagb-post-assets.php
> +		if ( ! class_exists( 'Astra_Target_Rules_Fields' ) ) {
I have done the suggested change

2023-04-21 04:27 UTC, imnavanath commented on classes/class-uagb-post-assets.php
> +			$this->prepare_assets_of_ast_custom_layout_post();
```suggestion
			$this->prepare_ast_custom_layout_post_assets();
```

2023-04-21 04:28 UTC, imnavanath commented on classes/class-uagb-post-assets.php
> +	public function prepare_assets_of_ast_custom_layout_post() {
```suggestion
	public function prepare_ast_custom_layout_post_assets() {
```

2023-04-21 04:28 UTC, imnavanath commented on classes/class-uagb-post-assets.php
> +			$this->prepare_assets_of_ast_custom_layout_post();
Avoid `of, for, the` kind of words in function name.

2023-04-21 04:40 UTC, imnavanath approved these changes

2023-04-21 05:34 UTC, AbhijitNage123 commented on classes/class-uagb-post-assets.php
> +	 * Generate assets of Astra custom layout post in preview
New function should have `Since` tag added.

2023-04-24 07:28 UTC, bsf-zanev requested changes

2023-04-24 07:28 UTC, bsf-zanev commented on readme.txt
> +* Fix: Table of content - not properly shown in the preview of the post when used as a custom layout inside post/page content.
I've cross verified all the changelog entries in this PR.

All the newly added changelog entries can be removed, and this one can be replaced with 
```suggestion
* Fix: Table Of Contents - Updated the front-end Preview UI to match in the "Inside post/page content" type of Astra's Custom Layout.
```

**Move your changelog entry underneath the other Table of Contents changelog entry.**

@AbhijitNage123 - Please verify that this changelog entry accurately defines the fix that was requested.

2023-04-24 07:28 UTC, bsf-zanev commented on classes/class-uagb-post-assets.php
> +	 * Generate assets of Astra custom layout post in preview
Also add the `@return` tag for all new functions.

2023-04-24 07:28 UTC, bsf-zanev commented on README.md
> +* Fix: Forms - Missing fields label Accessibility issues for date and toggle child.
Running the command `grunt readme` will remove all these entries and replace them with your change's entry instead.

2023-04-24 08:12 UTC, ravinishadcoder commented on classes/class-uagb-post-assets.php
> +	 * Generate assets of Astra custom layout post in preview
added since and return both to the function

2023-04-24 08:13 UTC, ravinishadcoder commented on readme.txt
> +* Fix: Table of content - not properly shown in the preview of the post when used as a custom layout inside post/page content.
I have undone the changes of readme file

2023-04-24 08:14 UTC, ravinishadcoder commented on README.md
> +* Fix: Forms - Missing fields label Accessibility issues for date and toggle child.
done

2023-04-24 09:05 UTC, AbhijitNage123 approved these changes

2023-04-24 09:33 UTC, bsf-zanev approved these changes

2023-04-25 04:30 UTC, RajkiranBagal approved these changes

2023-05-05 06:07 UTC, RajkiranBagal requested changes

2023-05-05 06:07 UTC, RajkiranBagal commented on classes/class-uagb-post-assets.php
> +		if ( empty( $result ) ) {
```suggestion
		if ( empty( $result ) || ! is_array( $result ) ) {
```

2023-05-08 04:22 UTC, ravinishadcoder commented on classes/class-uagb-post-assets.php
> +		if ( empty( $result ) ) {
Implemented suggested code changes

2023-05-09 13:17 UTC, RajkiranBagal requested changes

2023-05-09 13:17 UTC, RajkiranBagal commented on classes/class-uagb-post-assets.php
> +	 * @since 2.5.0
```suggestion
	 * @since x.x.x
```

2023-05-09 13:21 UTC, merged