SPCTR-2554 - Fix: Table of content - shows html validation issue in validator.
brainstormforce/ultimate-addons-for-gutenberg pull request #2995
Opened 2023-04-17 03:54 UTC by supriyajjadhav

### Description
Fix: Table of content - shows html validation issue in validator.

### Screenshots
https://share.getcloudapp.com/L1uDDmEv

### Types of changes
Bug fix (non-breaking change which fixes an issue) 

### How has this been tested?

### Checklist:
- [x] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [x] I've added proper labels to this pull request

2023-04-17 04:11 UTC, patilvikasj approved these changes

2023-04-17 04:12 UTC, RajkiranBagal requested changes

2023-04-17 04:12 UTC, RajkiranBagal commented on readme.txt
> +* Fix: Table of content - shows html validation issue in validator.
```suggestion
* Fix: Table of Contents - HTML validation issue in the HTML validator.
```

2023-04-17 04:48 UTC, adi3890 commented on blocks-config/table-of-content/class-uagb-table-of-content.php
> +					$toc .= sprintf( '<a href="#%s">%s</a></li>', esc_attr( $id ), $title );
should we use esc_html for title.
multiple instance

2023-04-18 02:56 UTC, supriyajjadhav commented on blocks-config/table-of-content/class-uagb-table-of-content.php
> +					$toc .= sprintf( '<a href="#%s">%s</a></li>', esc_attr( $id ), $title );
Made suggested changes. Thanks

2023-04-20 10:39 UTC, RajkiranBagal approved these changes

2023-04-20 10:41 UTC, adi3890 approved these changes

2023-04-20 10:42 UTC, merged