SPCTR-2702 Fix for issue - loop builder dynamic image in the container taking last posts featured image only
brainstormforce/ultimate-addons-for-gutenberg pull request #3005
Opened 2023-04-20 02:22 UTC by abhishekrijal

### Description
Fix for issue - loop builder dynamic image in the container taking last posts featured image only

### Screenshots

### Types of changes

Bug fix (non-breaking change which fixes an issue)

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2023-04-20 02:52 UTC, rahulvarma722 requested changes

2023-04-20 02:52 UTC, rahulvarma722 commented on src/blocks/container/render.js
> +			<CustomTag { ...blockProps } style={ { backgroundImage: `url(${backgroundImageDesktop?.url})` } } key={ block_id } { ...customTagLinkAttributes }>
Please check
1. Background image for Tablet and mobile devices because there is different variable for background image according to device type.
2. If we add a background image inline-style, then we should remove the background image css from styling.js.

2023-04-20 05:44 UTC, abhishekrijal commented on src/blocks/container/render.js
> +			<CustomTag { ...blockProps } style={ { backgroundImage: `url(${backgroundImageDesktop?.url})` } } key={ block_id } { ...customTagLinkAttributes }>
@rahulvarma722 
I have handled the tablet and mobile URLs and some refactoring.

2023-04-20 07:50 UTC, rahulvarma722 approved these changes

2023-04-20 09:12 UTC, adi3890 approved these changes

2023-04-21 16:44 UTC, adi3890 approved these changes
Code looks fine
Container background property need to be tested by QA

2023-05-02 10:03 UTC, RajkiranBagal approved these changes

2023-05-02 10:19 UTC, merged