SPCTR- 2764 Loop Builder - Added filter to allowed blocks inside container when used inside loop builder
brainstormforce/ultimate-addons-for-gutenberg pull request #3050
Opened 2023-04-27 10:46 UTC by abhishekrijal

### Description
Loop Builder - Added filter to allowed blocks inside container when used inside loop builder

### Screenshots

### Types of changes

Bug fix (non-breaking change which fixes an issue) -->

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2023-05-01 04:26 UTC, RajkiranBagal approved these changes

2023-05-02 10:16 UTC, RajkiranBagal requested changes

2023-05-02 10:16 UTC, RajkiranBagal commented on src/blocks/container/render.js
> +		const { getBlockParents, getBlock } = selectStore( 'core/block-editor' );
Can we combine above slider loop & this loop? @abhishekrijal @adi3890

2023-05-02 10:25 UTC, abhishekrijal commented on src/blocks/container/render.js
> +		const { getBlockParents, getBlock } = selectStore( 'core/block-editor' );
Slider loop is using the attribute `hasSliderParent ` to get the parent value, in case of loop builder that is achieved with hook directly, while it is better approach, I'll need suggestion from @patilvikasj to modify it, as it might be used somewhere else as well.

2023-05-02 10:40 UTC, RajkiranBagal approved these changes

2023-05-02 10:40 UTC, merged