Spectra v2.5.1
brainstormforce/ultimate-addons-for-gutenberg pull request #3052
Opened 2023-04-27 12:19 UTC by RajkiranBagal

* Feature: You can now add Google Fonts to Block Based Themes from Spectra Dashboard.
* Fix: Counter - Added support for use within Slider (previously not working within Slider when it's set to infinite loop).
* Fix: Buttons - Gap settings on Mobile preview is taking desktop value as default.
* Fix: Modal - Background not applying properly when custom width is set.
* Fix: Resolve an issue of PHP error appear for block-based widget editor.

2023-04-27 12:40 UTC, patilvikasj commented on admin-core/assets/src/dashboard-app/pages/settings/FSEFontFamilies.js
> +                                {__( 'Currently no Font Families added.', 'ultimate-addons-for-gutenberg' )}
```suggestion
                                {__( 'Currently, no Font Families added.', 'ultimate-addons-for-gutenberg' )}
```

2023-04-27 12:40 UTC, patilvikasj commented on admin-core/assets/src/dashboard-app/pages/settings/FSEFontFamilies.js
> +            }
A Switch case usage will be better.

2023-04-27 12:44 UTC, patilvikasj requested changes
Added comments. Rest looks fine to me.

2023-04-27 13:22 UTC, aapatre approved these changes

2023-04-28 08:07 UTC, patilvikasj approved these changes

2023-04-28 08:45 UTC, merged