SPCTR-2763 Fix: Forms - Issue on submit failure in FSE theme.
brainstormforce/ultimate-addons-for-gutenberg pull request #3067
Opened 2023-05-01 07:24 UTC by AbhijitNage123

### Description

- https://brainstormforce.atlassian.net/browse/SPCTR-2763

### Screenshots

- https://share.getcloudapp.com/nOuKrXrn

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

### How has this been tested?

- Added to the card.

### Checklist:
- [x] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [x] I've included any necessary tests 
- [ ] I've included developer documentation 
- [x] I've added proper labels to this pull request

2023-05-02 05:29 UTC, rajmohanreddy774 approved these changes

2023-05-02 07:53 UTC, RajkiranBagal approved these changes

2023-05-02 07:57 UTC, RajkiranBagal requested changes

2023-05-02 07:57 UTC, RajkiranBagal commented on blocks-config/forms/class-uagb-forms.php
> +				$template_query = new WP_Query( $wp_query_args );
Check !empty  & is_array for `$template_query->posts`

2023-05-02 07:57 UTC, RajkiranBagal commented on blocks-config/forms/class-uagb-forms.php
> +						$current_block_attributes = $this->recursive_inner_forms( parse_blocks( $template->content ), $block_id );
Check `! empty( $blocks ) && is_array( $blocks )` here too as you have checked below.

2023-05-02 07:57 UTC, RajkiranBagal commented on blocks-config/forms/class-uagb-forms.php
> +					if ( get_template() === $template->theme ) {
Is this Right to call functions inside if the condition checks?
cc - @adi3890

2023-05-03 06:46 UTC, AbhijitNage123 commented on blocks-config/forms/class-uagb-forms.php
> +				$template_query = new WP_Query( $wp_query_args );
Updated as suggested

2023-05-03 06:52 UTC, AbhijitNage123 commented on blocks-config/forms/class-uagb-forms.php
> +						$current_block_attributes = $this->recursive_inner_forms( parse_blocks( $template->content ), $block_id );
Done

2023-05-03 06:53 UTC, AbhijitNage123 commented on blocks-config/forms/class-uagb-forms.php
> +					if ( get_template() === $template->theme ) {
@RajkiranBagal Checked `function_exists()` for `_build_block_template_result_from_post`

2023-05-07 07:01 UTC, RajkiranBagal approved these changes

2023-05-07 07:50 UTC, RajkiranBagal approved these changes

2023-05-07 07:54 UTC, merged