SPCTR-2771 Fix: Global - Fixed an issue wherein a Google error would appear when loading Google Fonts locally with a specific font weight and family set to default.
brainstormforce/ultimate-addons-for-gutenberg pull request #3104
Opened 2023-05-09 06:00 UTC by AbhijitNage123

### Description

- https://brainstormforce.atlassian.net/browse/SPCTR-2771

### Screenshots

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

### How has this been tested?

- Added to the card.

### Checklist:
- [x] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [x] I've included any necessary tests 
- [ ] I've included developer documentation 
- [x] I've added proper labels to this pull request

2023-05-09 07:16 UTC, RajkiranBagal requested changes

2023-05-09 07:16 UTC, RajkiranBagal commented on classes/class-uagb-fse-fonts-compatibility.php
> +			if ( is_array( $font_files ) && ! empty( $font_files ) && ! empty( $font_family_key ) ) {
If empty or not is_array then just return function, do not add whole foreach in if statement

2023-05-09 07:16 UTC, RajkiranBagal commented on classes/class-uagb-fse-fonts-compatibility.php
> +			if ( ! array_key_exists( 'settings', $theme_json_raw ) || ! array_key_exists( 'typography', $theme_json_raw['settings'] ) || ! array_key_exists( 'fontFamilies', $theme_json_raw['settings']['typogr
Can we just check `! empty( $theme_json_raw['settings] ) ` similar to this for all array_key_exists

2023-05-09 07:16 UTC, RajkiranBagal commented on classes/class-uagb-post-assets.php
> +			if ( ! empty( $gfont_values['fontfamily'] ) ) {
Intead of putting whole chunk of code inside if condition, please  write that condition & just continue / break foreach as per requirements.

2023-05-09 13:00 UTC, AbhijitNage123 commented on classes/class-uagb-fse-fonts-compatibility.php
> +			if ( ! array_key_exists( 'settings', $theme_json_raw ) || ! array_key_exists( 'typography', $theme_json_raw['settings'] ) || ! array_key_exists( 'fontFamilies', $theme_json_raw['settings']['typogr
Done and tested

2023-05-10 02:57 UTC, adi3890 commented on classes/class-uagb-fse-fonts-compatibility.php
> +			if ( empty( $theme_json_raw['settings'] ) || empty( $theme_json_raw['settings']['typography'] ) || empty( $theme_json_raw['settings']['typography']['fontFamilies'] ) ) { // Added condition to reso
```suggestion
			if ( empty( $theme_json_raw['settings']['typography']['fontFamilies'] ) ) { // Added condition to resolve an issue of PHP Notice:  Undefined index: fontFamilies.
```

2023-05-10 02:57 UTC, adi3890 commented on classes/class-uagb-post-assets.php
> +			if ( empty( $gfont_values['fontfamily'] ) ) {
should we also check string check as we  are performing string operations further

2023-05-10 02:57 UTC, adi3890 commented on compatibility/class-uagb-astra-compatibility.php
> +					if ( ! empty( $gfont_values['fontfamily'] ) && ! empty( $gfont_values['fontvariants'] ) ) {
should we check for expected data type here.

2023-05-10 02:57 UTC, adi3890 commented on compatibility/class-uagb-astra-compatibility.php
>  				foreach ( $google_fonts as $key => $gfont_values ) {
@AbhijitNage123  This is quite old function and is very much nested can we add a task in backlog to refactor this function.

2023-05-10 05:34 UTC, AbhijitNage123 commented on classes/class-uagb-fse-fonts-compatibility.php
> +			if ( empty( $theme_json_raw['settings'] ) || empty( $theme_json_raw['settings']['typography'] ) || empty( $theme_json_raw['settings']['typography']['fontFamilies'] ) ) { // Added condition to reso
Resolved

2023-05-10 05:34 UTC, AbhijitNage123 commented on classes/class-uagb-post-assets.php
> +			if ( empty( $gfont_values['fontfamily'] ) ) {
Resolved

2023-05-10 05:36 UTC, AbhijitNage123 commented on compatibility/class-uagb-astra-compatibility.php
> +					if ( ! empty( $gfont_values['fontfamily'] ) && ! empty( $gfont_values['fontvariants'] ) ) {
Done. If get type for font Family and font Variants then early return

2023-05-10 05:40 UTC, AbhijitNage123 commented on compatibility/class-uagb-astra-compatibility.php
>  				foreach ( $google_fonts as $key => $gfont_values ) {
Task link - https://brainstormforce.atlassian.net/browse/SPCTR-2835

2023-05-10 05:41 UTC, adi3890 approved these changes

2023-05-10 08:08 UTC, RajkiranBagal approved these changes

2023-05-10 08:08 UTC, merged