SPCTR-2573 - Popup Builder: PO's Improvements
brainstormforce/ultimate-addons-for-gutenberg pull request #3106
Opened 2023-05-09 06:32 UTC by bsf-zanev

### Description
Improved the Popup Builder as suggested by the Product Owners.

### Types of changes
Bug fix (non-breaking change which fixes an issue)

### How has this been tested?
Tested All New Features in Popups and Info-bars in Existing and Fresh Sites.

### Checklist:
- [x] My code is tested
- [x] My code follows accessibility standards 
- [x] My code has proper inline documentation 
- [x] I've included any necessary tests 
- [ ] I've included developer documentation 
- [x] I've added proper labels to this pull request

2023-05-09 09:07 UTC, patilvikasj commented on includes/blocks/popup-builder/frontend.js.php
> +				theBody.style.overflow = 'hidden';
@bsf-zanev Can we add a class to the body that will set overflow to **hidden** instead of applying it directly to the body tag?

2023-05-09 09:10 UTC, patilvikasj requested changes
Please check the comments. Rest looks good to me.

2023-05-09 09:13 UTC, adi3890 commented on includes/blocks/popup-builder/frontend.css.php
> +		'width'            => ( 'banner' === $attr['variantType'] ) ? '100% !important' : '',
adding !important. Is it very important. Are you sure it will not break any cusatomization further.

2023-05-09 09:13 UTC, adi3890 commented on includes/blocks/popup-builder/frontend.js.php
> +			<?php if ( 'banner' !== $attr['variantType'] ) : ?>
should we add that comment inside this php tag only.
Having an extra php tag just for comment does not look appropriate

2023-05-09 09:13 UTC, adi3890 commented on src/blocks/extensions/popup-builder/sidebar-settings/popup-sidebar.js
> -import { useState, useEffect, useRef, useLayoutEffect } from '@wordpress/element';
are we changing the location of this file.
or this file is just dicarded or merged into some other file.

2023-05-09 09:16 UTC, bsf-zanev commented on src/blocks/extensions/popup-builder/sidebar-settings/popup-sidebar.js
> -import { useState, useEffect, useRef, useLayoutEffect } from '@wordpress/element';
We've moved the entire popup builder directory out of the `src/blocks/extension/` folder into the `src/blocks/` folder directly in [this commit](https://github.com/brainstormforce/ultimate-addons-for-gutenberg/pull/3106/commits/5287cdc682fc7f0790550402c7e0327f17248899).

This was done to fix the static CSS generation issues.

2023-05-09 09:17 UTC, bsf-zanev commented on includes/blocks/popup-builder/frontend.js.php
> +			<?php if ( 'banner' !== $attr['variantType'] ) : ?>
The PHP Comments were added for developer's view only, so that the comment is not rendered in the final JS.

2023-05-09 09:19 UTC, bsf-zanev commented on includes/blocks/popup-builder/frontend.css.php
> +		'width'            => ( 'banner' === $attr['variantType'] ) ? '100% !important' : '',
Yes, due to the structure of this block, the width needs to be 100% at all times for the banner, and should not be affected by any other CSS.

The usage of this important tag is safe, and does not affect other cases.

2023-05-09 13:35 UTC, bsf-zanev commented on blocks-config/popup-builder/class-uagb-popup-builder.php
> +		$columns                         = apply_filters( 'spectra_pro_admin_popup_list_titles', $columns );
The filter manage_cpt_columns always passes an array, and at this point the same array is passed to the filter.

This filter is before the author and toggle, since those two need to be last.

I've added a check incase someone else corrupts the data used in this filter.

2023-05-10 03:53 UTC, bsf-zanev commented on includes/blocks/popup-builder/frontend.js.php
> +				theBody.style.overflow = 'hidden';
Done.

2023-05-10 03:54 UTC, bsf-zanev commented on includes/blocks/popup-builder/frontend.js.php
> +			<?php if ( 'banner' !== $attr['variantType'] ) : ?>
Unrequired Opening and Closing PHP Tags have been removed in Free and Pro.

2023-05-10 03:54 UTC, bsf-zanev commented on src/blocks/popup-builder/edit.js
Done.

2023-05-10 12:21 UTC, abhishekrijal approved these changes

2023-05-10 12:28 UTC, adi3890 approved these changes

2023-05-10 14:30 UTC, merged