SPCTR-2369 - Button default padding, width & radius needs to be from customizer and not from spectra editor.
brainstormforce/ultimate-addons-for-gutenberg pull request #3133
Opened 2023-05-12 04:12 UTC by supriyajjadhav

### Description
Button default padding, width & radius needs to be from customizer and not from spectra editor.

### Screenshots

### Types of changes

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2023-05-12 10:40 UTC, rahulvarma722 commented on admin-core/assets/src/dashboard-app/pages/settings/Settings.js
>  import{ useEffect } from 'react';
Import useEffect from import { useEffect } from '@wordpress/element';
Please whenever change any file and see this kind of thing import{ useEffect } from 'react'; as we have changed everything in src/block folder just change

2023-05-12 10:40 UTC, rahulvarma722 commented on includes/blocks/buttons-child/attributes.php
> +		'inheritFromTheme'       => 'disabled' === $inherit_from_theme ? false : true,
```suggestion
		'inheritFromTheme'       => ! 'disabled' === $inherit_from_theme,
```

2023-05-12 10:40 UTC, rahulvarma722 commented on includes/blocks/call-to-action/attributes.php
> +		'secondInheritFromTheme'          => 'disabled' === $inherit_from_theme ? false : true,
```suggestion
		'inheritFromTheme'                => ! 'disabled' === $inherit_from_theme,
		'secondInheritFromTheme'          => ! 'disabled' === $inherit_from_theme,
```

2023-05-12 10:40 UTC, rahulvarma722 commented on includes/blocks/call-to-action/attributes.php
> +		'secondInheritFromTheme'          => 'disabled' === $inherit_from_theme ? false : true,
```suggestion
		'inheritFromTheme'                => ! 'disabled' === $inherit_from_theme,
		'secondInheritFromTheme'          => ! 'disabled' === $inherit_from_theme,
```

2023-05-12 10:40 UTC, rahulvarma722 commented on includes/blocks/info-box/attributes.php
> +		'inheritFromTheme'           => 'disabled' === $inherit_from_theme ? false : true,
```suggestion
		'inheritFromTheme'           => ! 'disabled' === $inherit_from_theme,
```

2023-05-12 10:40 UTC, rahulvarma722 commented on src/blocks/buttons-child/attributes.js
> +		default: 'disabled' === uagb_blocks_info.btn_inherit_from_theme ? false : true,
```suggestion
		default: ! 'disabled' === uagb_blocks_info.btn_inherit_from_theme,
```

2023-05-17 06:43 UTC, aapatre commented
1. Please add the changelog
2. In the title we can use the phrase 'WordPress/block editor' rather than 'Spectra editor'

cc: @supriyajjadhav

2023-05-17 06:55 UTC, aapatre commented on admin-core/assets/src/dashboard-app/pages/settings/InheritFromTheme.js
> +    // eslint-disable-next-line react-hooks/rules-of-hooks
Do we need the eslint disables? 🤔

2023-05-18 05:32 UTC, bsf-zanev commented on README.md
> +* New: Introducing the Inherit From Theme option.
Let's add a brief on this option after a hyphen.

2023-05-18 05:33 UTC, bsf-zanev commented on README.md
> +* New: Introducing the Inherit From Theme option.
```suggestion
* New: Introducing the Inherit From Theme option - Choose to inherit you styles directly from your current theme.
```

2023-05-18 05:36 UTC, AbhijitNage123 commented on includes/blocks/call-to-action/frontend.css.php
> +if ( ! $attr['secInheritFromTheme'] ) {
In `attribute.php` we have different name and here we have a different name. It will cause an issue for CTA. Please confirm.

2023-05-18 05:37 UTC, RajkiranBagal requested changes

2023-05-18 05:37 UTC, RajkiranBagal commented on admin-core/assets/src/dashboard-app/pages/settings/InheritFromTheme.js
> +function classNames( ...classes ) {
Use uagbClassnames.

2023-05-18 05:37 UTC, RajkiranBagal commented on readme.txt
> +* New: Introducing the Inherit From Theme option.
Inherit Theme Option for What? Which Blocks?

2023-05-18 05:38 UTC, RajkiranBagal requested changes
Resolve the comments

2023-05-18 05:39 UTC, AbhijitNage123 commented on includes/blocks/info-box/attributes.php
> -		'headingAlign'               => 'center',
Why `headingAlign` is removed?

2023-05-18 05:49 UTC, rahulvarma722 commented on admin-core/assets/src/dashboard-app/pages/settings/InheritFromTheme.js
> +		}
```suggestion
        let status = enableInheritTheme ? 'enabled' : 'disabled';
```

2023-05-18 05:49 UTC, rahulvarma722 commented on includes/blocks/buttons-child/attributes.php
> +		'inheritFromTheme'       => 'disabled' === $inherit_from_theme ? false : true,
```suggestion
		'inheritFromTheme'       => ! 'disabled' === $inherit_from_theme,
```

2023-05-18 05:49 UTC, rahulvarma722 commented on includes/blocks/call-to-action/attributes.php
> +$inherit_from_theme          = UAGB_Admin_Helper::get_admin_settings_option( 'uag_btn_inherit_from_theme', 'disabled' );
```suggestion
$inherit_from_theme          = ! 'disabled' === UAGB_Admin_Helper::get_admin_settings_option( 'uag_btn_inherit_from_theme', 'disabled' );
```

2023-05-18 05:49 UTC, rahulvarma722 commented on includes/blocks/call-to-action/attributes.php
> +		'inheritFromTheme'                => 'disabled' === $inherit_from_theme ? false : true,
```suggestion
		'inheritFromTheme'                => $inherit_from_theme,
```

2023-05-18 05:49 UTC, rahulvarma722 commented on includes/blocks/call-to-action/attributes.php
> +		'secondInheritFromTheme'          => 'disabled' === $inherit_from_theme ? false : true,
```suggestion
		'secondInheritFromTheme'          => $inherit_from_theme,
```

2023-05-18 05:49 UTC, adi3890 commented on admin-core/assets/src/dashboard-app/pages/settings/InheritFromTheme.js
> +			dispatch( { type: 'UPDATE_SETTINGS_SAVED_NOTIFICATION', payload: 'Successfully saved!' } );
Should this be translatable?

2023-05-18 05:49 UTC, adi3890 commented on admin-core/assets/src/dashboard-app/pages/settings/Settings.js
>  import{ useEffect } from 'react';
should we import it from wordpress/element

2023-05-18 05:49 UTC, adi3890 commented on includes/blocks/info-box/attributes.php
> +$inherit_from_theme   = UAGB_Admin_Helper::get_admin_settings_option( 'uag_btn_inherit_from_theme', 'disabled' );
can we do comparision here only and use variable further.
as done in next line

2023-05-18 06:08 UTC, rahulvarma722 commented on src/blocks/call-to-action/attributes.js
> +		default: 'disabled' === uagb_blocks_info.btn_inherit_from_theme ? false : true,
```suggestion
		default: ! 'disabled' === uagb_blocks_info.btn_inherit_from_theme,
```

2023-05-18 06:08 UTC, rahulvarma722 commented on src/blocks/call-to-action/attributes.js
> +		default: 'disabled' === uagb_blocks_info.btn_inherit_from_theme ? false : true,
```suggestion
		default: ! 'disabled' === uagb_blocks_info.btn_inherit_from_theme,
```

2023-05-18 06:08 UTC, rahulvarma722 commented on src/blocks/info-box/attributes.js
> +		default: 'disabled' === uagb_blocks_info.btn_inherit_from_theme ? false : true,
```suggestion
		default: ! 'disabled' === uagb_blocks_info.btn_inherit_from_theme,
```

2023-05-18 06:55 UTC, bsf-zanev requested changes
Added a few comments, and also would like to know if we should implement this change in the following blocks as well:

1. Forms --> Submit Button.
2. Image Gallery --> Masonry Load More Button.
3. Modal --> Trigger Button.
4. Post Blocks --> Read More Button.

2023-05-18 06:55 UTC, bsf-zanev commented on admin-core/assets/src/dashboard-app/pages/settings/InheritFromTheme.js
> +                { __( 'Enable the "Inherit From Theme" option if you want to apply theme button stylings to the Spectra buttons. It will get automatically enabled in every Spectra block which has but
The second line here seems a bit confusing to me - does this clarify what this setting should accomplish?

```suggestion
                { __( 'Enable the "Inherit From Theme" option if you'd like to apply your theme button stylings to all buttons in every Spectra button. This will update all existing buttons as well.', 'ultimate-addons-for-gutenberg' ) }
```

2023-05-18 06:55 UTC, bsf-zanev commented on README.md
> +* New: Introducing the Inherit From Theme option.
After reviewing the PR, I've noticed that this changelog entry is different from what I'd initially thought.

Here's a more suitable changelog entry. Let me know your thoughts.

```suggestion
* New: Introducing the Inherit From Theme option - Choose to directly inherit your theme's button styles into all Spectra block buttons.
```

2023-05-22 05:30 UTC, supriyajjadhav commented on admin-core/assets/src/dashboard-app/pages/settings/InheritFromTheme.js
> +                { __( 'Enable the "Inherit From Theme" option if you want to apply theme button stylings to the Spectra buttons. It will get automatically enabled in every Spectra block which has but
@bsf-zanev Updated readme and setting description also. Please check

2023-05-22 05:32 UTC, supriyajjadhav commented
> Added a few comments, and also would like to know if we should implement this change in the following blocks as well:
> 
> 1. Forms --> Submit Button.
> 2. Image Gallery --> Masonry Load More Button.
> 3. Modal --> Trigger Button.
> 4. Post Blocks --> Read More Button.

- Currently, we are making this change for 3 blocks only. because there are a lot of changes we need to make. We will plan for the rest of the blocks after releasing this feature.

2023-05-22 05:32 UTC, supriyajjadhav commented on src/blocks/info-box/attributes.js
> +		default: 'disabled' === uagb_blocks_info.btn_inherit_from_theme ? false : true,
Updated. Please check

2023-05-22 05:33 UTC, supriyajjadhav commented on src/blocks/call-to-action/attributes.js
> +		default: 'disabled' === uagb_blocks_info.btn_inherit_from_theme ? false : true,
Updated. Please check

2023-05-22 05:33 UTC, supriyajjadhav commented on src/blocks/call-to-action/attributes.js
> +		default: 'disabled' === uagb_blocks_info.btn_inherit_from_theme ? false : true,
Updated. Please check

2023-05-22 05:33 UTC, supriyajjadhav commented on src/blocks/buttons-child/attributes.js
> +		default: 'disabled' === uagb_blocks_info.btn_inherit_from_theme ? false : true,
Updated. Please check

2023-05-22 05:33 UTC, supriyajjadhav commented on includes/blocks/info-box/attributes.php
> +$inherit_from_theme   = UAGB_Admin_Helper::get_admin_settings_option( 'uag_btn_inherit_from_theme', 'disabled' );
Updated. Please check

2023-05-22 05:34 UTC, supriyajjadhav commented on admin-core/assets/src/dashboard-app/pages/settings/InheritFromTheme.js
> +			dispatch( { type: 'UPDATE_SETTINGS_SAVED_NOTIFICATION', payload: 'Successfully saved!' } );
Updated. Please check

2023-05-22 05:34 UTC, supriyajjadhav commented on includes/blocks/call-to-action/attributes.php
> +		'secondInheritFromTheme'          => 'disabled' === $inherit_from_theme ? false : true,
Updated. Please check

2023-05-22 05:35 UTC, supriyajjadhav commented on includes/blocks/call-to-action/attributes.php
> +		'inheritFromTheme'                => 'disabled' === $inherit_from_theme ? false : true,
Updated. Please check

2023-05-22 05:35 UTC, supriyajjadhav commented on includes/blocks/call-to-action/attributes.php
> +$inherit_from_theme          = UAGB_Admin_Helper::get_admin_settings_option( 'uag_btn_inherit_from_theme', 'disabled' );
Updated. Please check

2023-05-22 05:35 UTC, supriyajjadhav commented on includes/blocks/buttons-child/attributes.php
> +		'inheritFromTheme'       => 'disabled' === $inherit_from_theme ? false : true,
Updated. Please check

2023-05-22 05:35 UTC, supriyajjadhav commented on admin-core/assets/src/dashboard-app/pages/settings/InheritFromTheme.js
> +		}
Updated. Please check

2023-05-22 05:35 UTC, supriyajjadhav commented on admin-core/assets/src/dashboard-app/pages/settings/InheritFromTheme.js
> +    const enableInheritTheme = 'disabled' === inheritFromTheme ? false : true;
Updated. Please check

2023-05-22 05:37 UTC, supriyajjadhav commented on readme.txt
> +* New: Introducing the Inherit From Theme option.
Updated readme as suggested by @bsf-zanev. Please check

2023-05-22 05:37 UTC, supriyajjadhav commented on admin-core/assets/src/dashboard-app/pages/settings/InheritFromTheme.js
> +function classNames( ...classes ) {
Updated. Please check

2023-05-22 05:37 UTC, supriyajjadhav commented on README.md
> +* New: Introducing the Inherit From Theme option.
Updated. Please check

2023-05-22 05:50 UTC, supriyajjadhav commented on includes/blocks/info-box/attributes.php
> -		'headingAlign'               => 'center',
Updated.

2023-05-22 07:29 UTC, supriyajjadhav commented on includes/blocks/call-to-action/frontend.css.php
> +if ( ! $attr['secInheritFromTheme'] ) {
@AbhijitNage123 Facing the same issue here also, I have updated the attribute again. Please check

2023-05-22 08:59 UTC, AbhijitNage123 approved these changes

2023-05-23 04:48 UTC, rahulvarma722 approved these changes

2023-05-23 05:52 UTC, bsf-zanev approved these changes

2023-05-30 04:29 UTC, supriyajjadhav commented
PR Reviewed. Looks good to me.

2023-05-30 04:51 UTC, RajkiranBagal approved these changes

2023-05-30 08:44 UTC, merged