Fix:SPCTR-2867-[Post Carousel]-When we select the preset layout 4, it is not showing as slider on the frontend.
brainstormforce/ultimate-addons-for-gutenberg pull request #3151
Opened 2023-05-17 05:38 UTC by ravinishadcoder

### Description

Fix:[Post Carousel]-When we select the preset layout 4, it is not showing as a slider on the frontend
### Screenshots

[Screencast](https://d.pr/v/Ys5SPT)
### Types of changes

Bug fix (non-breaking change which fixes an issue) 

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2023-05-17 07:52 UTC, aapatre commented on blocks-config/post/class-uagb-post.php
> +									}
As in the spacing after the bracket

2023-05-18 05:50 UTC, RajkiranBagal requested changes

2023-05-18 05:50 UTC, RajkiranBagal commented on blocks-config/post/class-uagb-post.php
> +										for( let article of articles ) {
Why this inverse change?

2023-05-22 03:50 UTC, ravinishadcoder commented on blocks-config/post/class-uagb-post.php
> +									}
Yes, I have removed the extra whitespace.

2023-05-22 03:55 UTC, ravinishadcoder commented on blocks-config/post/class-uagb-post.php
> +										for( let article of articles ) {
I have moved for loop inside `if( ! articles?.length )` this if condition. Previously, we have written returns after that check. Due to that in some cases, it will return from there and the slider code is not executed.

2023-05-22 07:32 UTC, RajkiranBagal requested changes

2023-05-22 07:56 UTC, RajkiranBagal approved these changes

2023-05-29 09:31 UTC, RajkiranBagal approved these changes

2023-05-29 09:37 UTC, merged