SPCTR-2853 Reduce svg icons file size
brainstormforce/ultimate-addons-for-gutenberg pull request #3172
Opened 2023-05-19 18:56 UTC by rahulvarma722

### Description

### Screenshots

### Types of changes

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2023-05-22 06:51 UTC, aapatre commented on classes/class-uagb-init-blocks.php
> +	 * Localize .
Please add proper comment for the function

2023-05-22 06:56 UTC, aapatre requested changes
1. Please add a proper description like the one mentioned in the JIRA card
2. Also add more code-comments where-ever necessary. (Although there are some comments already, but please go through the file changes and look for sections which might need some context/explanations for future developers)

cc: @rahulvarma722

2023-05-22 06:58 UTC, aapatre commented
We can use this description from JIRA @rahulvarma722 with some slight changes:

Due to the large size of the Font Awesome icons array, some users are facing an issue where they are unable to edit their WordPress pages. To resolve this issue, we need to optimize the Font Awesome icons array so that it loads more efficiently and does not cause performance issues for users.

2023-05-22 08:06 UTC, aapatre commented on Gruntfile.js
> +const NUMBER_OF_ICON_CHUNKS = 4;
Resolved by @rahulvarma722

2023-05-22 08:07 UTC, aapatre commented
I've updated the description (the first comment by @rahulvarma722 )

2023-05-23 04:37 UTC, AbhijitNage123 commented on classes/class-uagb-helper.php
> +		 * @since X.X.X
grunt Bump can not recognize capital X. Can we convert it into small x.x.x? Same for other file

2023-05-24 12:17 UTC, rahulvarma722 commented on classes/class-uagb-helper.php
> +		 * @since X.X.X
Done

2023-05-24 12:19 UTC, AbhijitNage123 approved these changes

2023-05-24 12:19 UTC, AbhijitNage123 approved these changes

2023-05-24 12:40 UTC, rahulvarma722 commented on classes/class-uagb-init-blocks.php
> +	 * Localize .
Added description

2023-05-24 16:37 UTC, rahulvarma722 commented on blocks-config/uagb-controls/spectra-icons-v6-0.php
> + * @package     Spectra
Changed to UAGB

2023-05-24 16:37 UTC, rahulvarma722 commented on blocks-config/uagb-controls/renderIcon.js
> +				<svg viewBox="0 0 18 12" xmlns="https://www.w3.org/2000/svg">
Modified

2023-05-24 18:48 UTC, adi3890 approved these changes

2023-07-04 10:42 UTC, merged