SPCTR-2918 Responsive CSS changes in icon, icon list and child, image, image gallery, infoBox, inline notice, lottie, marketing button, and modal
brainstormforce/ultimate-addons-for-gutenberg pull request #3191
Opened 2023-05-24 11:28 UTC by AbhijitNage123

### Description

- https://brainstormforce.atlassian.net/browse/SPCTR-2918

### Screenshots

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

### How has this been tested?

### Checklist:
- [x] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [x] I've included any necessary tests 
- [ ] I've included developer documentation 
- [x] I've added proper labels to this pull request

2023-05-24 12:37 UTC, rahulvarma722 approved these changes

2023-05-25 11:42 UTC, aapatre requested changes
As per the JIRA card, the changes are due to the upcoming iFrame update in Gutenberg. Please add the same in the PR description since this is a significant fix.

cc: @AbhijitNage123

2023-06-02 12:22 UTC, AbhijitNage123 commented
> As per the JIRA card, the changes are due to the upcoming iFrame update in Gutenberg. Please add the same in the PR description since this is a significant fix.
> 
> cc: @AbhijitNage123

No, Its not related to gutenberg changes. We found an issue that in editor responsive css is not working as expected. Changes is related to it.

2023-06-05 10:52 UTC, adi3890 approved these changes

2023-06-15 11:54 UTC, merged