SPCTR-2918 Responsive CSS changes in popup, post layout, price list, section, separator, slider and child, social share and star rating
brainstormforce/ultimate-addons-for-gutenberg pull request #3192
Opened 2023-05-24 12:15 UTC by AbhijitNage123

### Description

- https://brainstormforce.atlassian.net/browse/SPCTR-2918

### Screenshots

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

### How has this been tested?

### Checklist:
- [x] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [x] I've included any necessary tests 
- [ ] I've included developer documentation 
- [x] I've added proper labels to this pull request

2023-05-24 12:55 UTC, rahulvarma722 approved these changes

2023-05-25 11:40 UTC, aapatre requested changes
As per the JIRA card, the changes are due to the upcoming iFrame update in Gutenberg. Please add the same in the PR description since this is a significant fix.

cc: @AbhijitNage123

2023-06-05 04:31 UTC, adi3890 commented on src/blocks/star-rating/styling.js
> +function styling( attributes, clientId, name, deviceType ) {
in other Prs i see we are directly using block_id from attributes.
do we need clientId

2023-06-05 04:34 UTC, AbhijitNage123 commented on src/blocks/star-rating/styling.js
> +function styling( attributes, clientId, name, deviceType ) {
Yes its needed for block those uses clientId. some of the block are using block_id and some are using clientId.

2023-06-05 04:39 UTC, adi3890 commented on src/blocks/star-rating/styling.js
> +function styling( attributes, clientId, name, deviceType ) {
ok

2023-06-05 04:50 UTC, adi3890 approved these changes

2023-06-15 12:04 UTC, merged