SPCTR-2915- Improvements- Buttons block improvements as per core buttons
brainstormforce/ultimate-addons-for-gutenberg pull request #3230
Opened 2023-06-02 04:39 UTC by rajmohanreddy774

### Description

Updated default 2 button to 1 button, removed default border, default alignment into left and FSE button color issue fix.

### Screenshots

### Types of changes

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2023-06-02 06:17 UTC, aapatre requested changes
This will need deprecation since old users had 2 buttons.

2023-06-12 07:01 UTC, AbhijitNage123 commented on readme.txt
> += x.x.X =
Please create a 3 separate changelog as per the PR changes.

2023-06-12 07:02 UTC, AbhijitNage123 commented on readme.txt
> +* Improvement: Buttons - Updated default 2 button to 1 button, removed default border, default alignment into left, FSE button color issue fix and Alignment in block toolbar.
Please create a 3 separate changelog as per the PR changes.

2023-06-12 07:04 UTC, AbhijitNage123 commented on src/blocks/buttons-child/deprecated.js
> +	{
Could you please confirm before adding deprecated code, Do we really need deprecated support?

2023-06-12 07:06 UTC, AbhijitNage123 commented on src/blocks/buttons/style.scss
> -	a {
Make sure you have tested this with Astra too. With Inherit from theme option as well as adding a dynamic style to link

2023-06-12 07:19 UTC, bsf-zanev commented on src/blocks/buttons-child/settings.js
> +import { memo, } from '@wordpress/element';
```suggestion
import { memo } from '@wordpress/element';
```

2023-06-12 07:19 UTC, bsf-zanev commented on src/blocks/buttons-child/settings.js
> +import { Icon,  ToggleControl } from '@wordpress/components';
```suggestion
import { Icon, ToggleControl } from '@wordpress/components';
```

2023-06-12 07:19 UTC, bsf-zanev commented on src/blocks/buttons-child/settings.js
> +import { InspectorControls, BlockControls, AlignmentToolbar, store as blockEditorStore  } from '@wordpress/block-editor';
```suggestion
import {
	InspectorControls,
	BlockControls,
	AlignmentToolbar,
	store as blockEditorStore,
} from '@wordpress/block-editor';
```

2023-06-12 07:19 UTC, bsf-zanev commented on src/blocks/buttons-child/settings.js
> +		const parentClientId = getBlockHierarchyRootClientId( clientId );
Can we use a different variable name instead of disabling the `no-shadow` rule?

2023-06-12 07:19 UTC, bsf-zanev commented on src/blocks/buttons-child/settings.js
> +		const parentAttributes = getBlockAttributes( parentClientId );
Can we use a different variable name instead of disabling the `no-shadow` rule?

2023-06-12 07:19 UTC, bsf-zanev commented on src/blocks/buttons-child/settings.js
> +	const ALIGNMENT_CONTROLS = [
This constant is not as per our naming conventions...

2023-06-12 07:19 UTC, bsf-zanev commented on src/blocks/buttons/settings.js
> +
```suggestion

```

2023-06-12 07:19 UTC, bsf-zanev commented on src/blocks/buttons/settings.js
> +import { InspectorControls, BlockControls, AlignmentToolbar, } from '@wordpress/block-editor';
Let's keep this either as
```suggestion
import { InspectorControls, BlockControls, AlignmentToolbar } from '@wordpress/block-editor';
```
OR
```suggestion
import {
	InspectorControls,
	BlockControls,
	AlignmentToolbar,
} from '@wordpress/block-editor';
```

2023-06-12 07:19 UTC, bsf-zanev commented on src/blocks/buttons/settings.js
> +	const ALIGNMENT_CONTROLS = [
This variable is not as per our JS naming standards...

2023-06-12 08:59 UTC, rajmohanreddy774 commented on src/blocks/buttons/style.scss
> -	a {
Tested

2023-06-12 09:01 UTC, rajmohanreddy774 commented on readme.txt
> +* Improvement: Buttons - Updated default 2 button to 1 button, removed default border, default alignment into left, FSE button color issue fix and Alignment in block toolbar.
Added

2023-06-12 09:01 UTC, rajmohanreddy774 commented on src/blocks/buttons-child/settings.js
> +import { memo, } from '@wordpress/element';
Done changes

2023-06-12 09:02 UTC, rajmohanreddy774 commented on src/blocks/buttons-child/settings.js
> +import { Icon,  ToggleControl } from '@wordpress/components';
Done changes

2023-06-12 09:02 UTC, rajmohanreddy774 commented on src/blocks/buttons-child/settings.js
> +import { InspectorControls, BlockControls, AlignmentToolbar, store as blockEditorStore  } from '@wordpress/block-editor';
Done changes

2023-06-12 09:02 UTC, rajmohanreddy774 commented on src/blocks/buttons-child/settings.js
> +	const ALIGNMENT_CONTROLS = [
Changes to 'alignmentControls'.

2023-06-12 09:03 UTC, rajmohanreddy774 commented on src/blocks/buttons/settings.js
> +import { InspectorControls, BlockControls, AlignmentToolbar, } from '@wordpress/block-editor';
Made changes.

2023-06-12 09:03 UTC, rajmohanreddy774 commented on src/blocks/buttons/settings.js
> +	const ALIGNMENT_CONTROLS = [
Changed to alignmentControls.

2023-06-12 09:05 UTC, rajmohanreddy774 commented on src/blocks/buttons-child/settings.js
> +		const parentClientId = getBlockHierarchyRootClientId( clientId );
If we use different variable name it is breaking.

2023-06-12 09:06 UTC, rajmohanreddy774 commented on src/blocks/buttons/settings.js
> +
Removed changes

2023-06-12 09:41 UTC, aapatre approved these changes
Pre-approved from my end, please resolve other comments.

2023-06-12 13:45 UTC, adi3890 commented on README.md
> +### x.x.X ###
please check for this it should be x.x.x
changelog in readme.txt is different.
ideally we can make changes in readme.txt and run command grunt readme to update readme.md

2023-06-12 13:45 UTC, adi3890 commented on src/blocks/buttons-child/deprecated.js
> +import newAttributesV2_6_5 from './deprecated/v2.6.5/attributes';
need to be updated as per current release 2_6_6

2023-06-12 13:45 UTC, adi3890 commented on src/blocks/buttons-child/settings.js
> +		const parentAttributes = getBlockAttributes( parentClientId );
Can you please check thoroughly why this code is breaking on changing variable name.
Lets try to remove eslint comment

2023-06-13 11:19 UTC, AbhijitNage123 approved these changes

2023-06-13 11:36 UTC, rajmohanreddy774 commented on src/blocks/buttons-child/settings.js
> +		const parentClientId = getBlockHierarchyRootClientId( clientId );
Removed by fixing issue.

2023-06-13 11:36 UTC, rajmohanreddy774 commented on src/blocks/buttons-child/settings.js
> +		const parentAttributes = getBlockAttributes( parentClientId );
Removed by fixing issue.

2023-06-13 11:45 UTC, bsf-zanev approved these changes
Update the new changelog entries and get approval from other reviewers.

2023-06-13 11:47 UTC, rajmohanreddy774 commented on src/blocks/buttons-child/deprecated.js
> +import newAttributesV2_6_5 from './deprecated/v2.6.5/attributes';
Updated

2023-06-13 12:00 UTC, rajmohanreddy774 commented on README.md
> +* Fix: Buttons - Fix FSE button color is different from theme color.
updated.

2023-06-14 12:19 UTC, adi3890 approved these changes

2023-06-14 12:19 UTC, adi3890 commented on src/blocks/buttons-child/deprecated.js
> +		attributes: newAttributesV2_6_6,
unfortunately this again need to be updated to 2_6_7
also  this need to be taken vcare untill this is released.

2023-06-29 07:52 UTC, rajmohanreddy774 commented on src/blocks/buttons-child/deprecated.js
> +		attributes: newAttributesV2_6_6,
changed.

2023-10-10 07:00 UTC, AbhijitNage123 approved these changes

2023-10-10 07:09 UTC, bsf-zanev reviewed
Looks good, just one minor comment.

2023-10-10 07:09 UTC, bsf-zanev commented on src/blocks/buttons-child/settings.js
> +	// eslint-disable-next-line no-shadow
Can we remove the no-shadow exclusion here?

2023-10-10 07:19 UTC, rajmohanreddy774 commented on src/blocks/buttons-child/settings.js
> +	// eslint-disable-next-line no-shadow
Removed.

2023-10-10 07:23 UTC, bsf-zanev approved these changes
Looks good to me.

2023-10-10 07:30 UTC, merged