SPCTR-2999 [Dynamic Content] Added Context as an attribute for use inside loop builder
brainstormforce/ultimate-addons-for-gutenberg pull request #3279
Opened 2023-06-16 09:03 UTC by abhishekrijal

### Description
[Dynamic Content] Added Context as an attribute for use inside loop builder
The Attribute data is then being used as a source of postID and Post Type to fetch post specific custom meta keys inside Dynamic Content selection dropdown.

### Screenshots

### Types of changes

Bug fix (non-breaking change which fixes an issue)

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2023-06-16 10:46 UTC, rahulvarma722 requested changes

2023-06-16 10:46 UTC, rahulvarma722 commented on src/blocks/advanced-heading/edit.js
> +		setAttributes( { context } );
Should we check the context in the attribute and based on changing context we should setAttribute context?

2023-06-16 10:46 UTC, rahulvarma722 commented on src/blocks/buttons-child/edit.js
> +		setAttributes( { context } );
Should we check the context in the attribute and based on changing context we should setAttribute context?
Also, check in other blocks also this instance.

2023-06-16 15:23 UTC, mohitsbsftester commented
Is there any backward compatibility to be checked in this PR?

2023-06-19 06:36 UTC, abhishekrijal commented on src/blocks/buttons-child/edit.js
> +		setAttributes( { context } );
@rahulvarma722 Updated with check for context change.

2023-06-19 06:36 UTC, abhishekrijal commented on src/blocks/advanced-heading/edit.js
> +		setAttributes( { context } );
@rahulvarma722 Updated with check for context change.

2023-06-19 10:26 UTC, merged