Content timeline backward compatibility
brainstormforce/ultimate-addons-for-gutenberg pull request #341
Opened 2020-07-20 08:26 UTC by AbhijitNage123

### Description

### Screenshots

### Types of changes

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2020-12-17 10:33 UTC, RajkiranBagal requested changes

2020-12-17 10:33 UTC, RajkiranBagal commented on classes/class-uagb-block-helper.php
> +		 * @since 0.0.1
update since `x.x.x`

2020-12-17 10:33 UTC, RajkiranBagal commented on classes/class-uagb-block-helper.php
> +			$t_selectors = array();
These are already declared above. `$t_selectors = array();
			$m_selectors = array();`

2020-12-17 10:33 UTC, RajkiranBagal commented on src/blocks/timeline/content-timeline-child/block.js
> + // import deprecated from "./deprecated"
Remove commented code.

2020-12-17 10:33 UTC, RajkiranBagal commented on src/blocks/timeline/content-timeline-child/edit.js
> +// Import registerBlockType() from wp.blocks
Remove commented code.

2020-12-17 10:33 UTC, RajkiranBagal commented on src/blocks/timeline/content-timeline-child/edit.js
> +let svg_icons = Object.keys( UAGBIcon )
Remove unused var

2020-12-17 10:33 UTC, RajkiranBagal commented on src/blocks/timeline/content-timeline-child/edit.js
> +		toggleDisplayPostDate() {
This function is not used anywhere. Remove this.

2020-12-17 10:33 UTC, RajkiranBagal commented on src/blocks/timeline/content-timeline-child/edit.js
> +		saveDate( value, index ) {
This function is not used anywhere. Remove this.

2020-12-17 10:33 UTC, RajkiranBagal commented on src/blocks/timeline/content-timeline-child/edit.js
> +			if( null != element && "undefined" != typeof element ) {
In ES6 instead of checking `if( "undefined" != typeof element )` you can directly write `if( element )` , It's the same. Make such changes.

2020-12-17 10:33 UTC, RajkiranBagal commented on src/blocks/timeline/content-timeline-child/inline-styles.js
> +	styling_css += generateCSS( tablet_selectors, id, true, "tablet" )
If there is no CSS for tablet & mobile then why write the extra code?

2020-12-17 10:33 UTC, RajkiranBagal commented on src/blocks/timeline/content-timeline/edit.js
>  	splitBlock( before, after, ...blocks ) {
This function is not used anymore in this file. Remove this. Also, Remove all such functions which are not used.

2020-12-17 10:33 UTC, RajkiranBagal commented on src/blocks/timeline/content-timeline/styling.js
> +//    console.log(props.attributes)
Remove unwanted code

2020-12-17 10:33 UTC, RajkiranBagal commented on src/blocks/timeline/content-timeline/styling.js
> +        //    " .uagb-timeline__field:not(:last-child)" : {
Remove unwanted code.

2020-12-18 12:17 UTC, AbhijitNage123 commented on classes/class-uagb-block-helper.php
> +		 * @since 0.0.1
Done

2020-12-18 12:17 UTC, AbhijitNage123 commented on classes/class-uagb-block-helper.php
> +			$t_selectors = array();
Done

2020-12-18 12:18 UTC, AbhijitNage123 commented on src/blocks/timeline/content-timeline-child/block.js
> + // import deprecated from "./deprecated"
Done

2020-12-18 12:18 UTC, AbhijitNage123 commented on src/blocks/timeline/content-timeline-child/edit.js
> +// Import registerBlockType() from wp.blocks
Done

2020-12-18 12:18 UTC, AbhijitNage123 commented on src/blocks/timeline/content-timeline-child/edit.js
> +let svg_icons = Object.keys( UAGBIcon )
Done

2020-12-18 12:18 UTC, AbhijitNage123 commented on src/blocks/timeline/content-timeline-child/edit.js
> +			if( null != element && "undefined" != typeof element ) {
Done

2020-12-18 12:18 UTC, AbhijitNage123 commented on src/blocks/timeline/content-timeline-child/inline-styles.js
> +	styling_css += generateCSS( tablet_selectors, id, true, "tablet" )
Done

2020-12-18 12:18 UTC, AbhijitNage123 commented on src/blocks/timeline/content-timeline/styling.js
> +//    console.log(props.attributes)
Done

2020-12-18 12:19 UTC, AbhijitNage123 commented on src/blocks/timeline/content-timeline/styling.js
> +        //    " .uagb-timeline__field:not(:last-child)" : {
Done

2020-12-22 06:25 UTC, RajkiranBagal approved these changes

2020-12-28 10:38 UTC, vrundakansara approved these changes

2020-12-28 15:02 UTC, merged