SPCTR-3271: Fix - Heading block is behind the overlay of container background psudo element.
brainstormforce/ultimate-addons-for-gutenberg pull request #3435
Opened 2023-08-23 19:59 UTC by rajmohanreddy774

### Description

Heading goes underneath the ::before pseudo-element of container background overlay
https://brainstormforce.atlassian.net/browse/SPCTR-3271

### Screenshots

https://d.pr/v/X3wbWE

### Types of changes

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2023-08-24 03:57 UTC, AbhijitNage123 requested changes

2023-08-24 03:57 UTC, AbhijitNage123 commented on src/blocks/buttons/style.scss
> +}
Issue is related to Heading and container, Why CSS is added in Buttons? @rajmohanreddy774

2023-08-24 04:17 UTC, rajmohanreddy774 commented on src/blocks/buttons/style.scss
> +}
My bad I was testing the other blocks if that issue exists I think I have pushed by adding in wrong file.
reverted and pushed the right fix, and tested.

2023-08-24 04:21 UTC, AbhijitNage123 approved these changes
PR looks good to me.

2023-08-24 07:27 UTC, bsf-zanev commented on README.md
> +* Fix: Advance Heading - Resolved an issue where heading block inside container goes underneath the ::before pseudo-element.
Let's move this changelog entry to the top, since it's for our Second Core Block.

```suggestion
* Fix: Heading - Resolved an issue wherein the Heading block inside Containers would appear underneath the Container's overlay when set.
```

2023-08-24 07:27 UTC, bsf-zanev commented on src/blocks/advanced-heading/style.scss
>  	.uagb-heading-text {
```suggestion
.wp-block-uagb-advanced-heading {
	position: relative;

	.uagb-heading-text {
```

2023-08-24 07:27 UTC, bsf-zanev commented on src/blocks/advanced-heading/style.scss
Does this issue appear in any other blocks of ours?

2023-08-24 08:47 UTC, rajmohanreddy774 commented on src/blocks/advanced-heading/style.scss
>  	.uagb-heading-text {
Done.

2023-08-24 08:47 UTC, rajmohanreddy774 commented on src/blocks/advanced-heading/style.scss
No.

2023-08-24 08:47 UTC, rajmohanreddy774 commented on README.md
> +* Fix: Advance Heading - Resolved an issue where heading block inside container goes underneath the ::before pseudo-element.
Done.

2023-08-25 08:22 UTC, rajmohanreddy774 commented on src/blocks/advanced-heading/style.scss
Fixed.

2023-08-25 10:22 UTC, bsf-zanev commented on README.md
> +* Fix: Advance Heading - Resolved an issue where heading block inside container goes underneath the ::before pseudo-element.
> Let's move this changelog entry to the top, since it's for our Second Core Block.



> Let's move this changelog entry to the top, since it's for our Second Core Block.

Can we move the Container entry on top as well? Since it's out first Core Block.

2023-08-25 10:29 UTC, rajmohanreddy774 commented on README.md
> +* Fix: Advance Heading - Resolved an issue where heading block inside container goes underneath the ::before pseudo-element.
Done.

2023-08-25 10:36 UTC, AbhijitNage123 approved these changes

2023-08-25 11:04 UTC, bsf-zanev approved these changes
Looks good to me, just had one minor query.

2023-08-25 11:04 UTC, bsf-zanev commented on src/blocks/container/style.scss
>  .wp-block-uagb-container > *:not( .wp-block-uagb-container ):not( .wp-block-uagb-column ):not( .wp-block-uagb-container ):not( .wp-block-uagb-section ):not( .uagb-container__shape ):not( .uagb-contai
Has this been tested with pro block like `wp-block-spectra-pro-register` and `wp-block-spectra-pro-login`.

2023-08-27 19:01 UTC, rajmohanreddy774 commented on src/blocks/container/style.scss
>  .wp-block-uagb-container > *:not( .wp-block-uagb-container ):not( .wp-block-uagb-column ):not( .wp-block-uagb-container ):not( .wp-block-uagb-section ):not( .uagb-container__shape ):not( .uagb-contai
Pro blocks are not working I think we should fix it in spectra Pro in different PR.

2023-08-28 05:26 UTC, bsf-zanev commented on src/blocks/container/style.scss
>  .wp-block-uagb-container > *:not( .wp-block-uagb-container ):not( .wp-block-uagb-column ):not( .wp-block-uagb-container ):not( .wp-block-uagb-section ):not( .uagb-container__shape ):not( .uagb-contai
Let's add the relative CSS for these two Pro blocks in Pro itself.

2023-08-28 05:26 UTC, bsf-zanev approved these changes

2023-08-28 05:35 UTC, adi3890 approved these changes

2023-08-28 08:10 UTC, merged