SPCTR-3576 Fix:  Container dynamic background image overlay color issue
brainstormforce/ultimate-addons-for-gutenberg pull request #3676
Opened 2023-12-20 04:19 UTC by rajmohanreddy774

### Description

Image overlay color and overlay opacity not working as intended when dynamic image selected as background type
https://brainstormforce.atlassian.net/browse/SPCTR-3576

### Screenshots

https://d.pr/v/91HGDD

### Types of changes

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2024-01-03 06:49 UTC, bsf-zanev requested changes

2024-01-03 06:49 UTC, bsf-zanev commented on classes/class-uagb-block-helper.php
> +								$gen_bg_css['background-image'] = 'url(' . $bg_img . ');';
Instead of altering the styling for blocks that don't support the pseudo element background, let's make the container work in the pseudo-element approach whenever a dynamic background image is available.

2024-01-04 04:25 UTC, rajmohanreddy774 commented on classes/class-uagb-block-helper.php
> +								$gen_bg_css['background-image'] = 'url(' . $bg_img . ');';
Fixed in pro PR.

2024-01-04 09:58 UTC, bsf-zanev commented on README.md
> +* Fix: Container - Resolved an issue wherein the overlay opacity would be doubled when using a dynamic background image.
Let's move this changelog to Pro, since it is a pro-based issue.

2024-01-04 10:09 UTC, rajmohanreddy774 commented on README.md
> +* Fix: Container - Resolved an issue wherein the overlay opacity would be doubled when using a dynamic background image.
Done.

2024-01-04 10:19 UTC, bsf-zanev approved these changes
Let's merge this comment so that no other developers will face confusion when working with the pseudo-overlay feature.

2024-01-04 11:06 UTC, adi3890 commented on classes/class-uagb-block-helper.php
> +			// If 'yes' is passed, then return the overlay CSS - else return the element CSS.
I don't feel only adding yes at the end of function will be helpful for any developer to understand instead lets add all valid inputs in the description itseld
like 'yes' | 'no' | can be left empty

2024-01-04 11:52 UTC, rajmohanreddy774 commented on classes/class-uagb-block-helper.php
> +			// If 'yes' is passed, then return the overlay CSS - else return the element CSS.
Added comment in description as per suggestion.

2024-01-05 02:26 UTC, merged