SPCTR-3604: Twenty Seventeen Icon Size Fix
brainstormforce/ultimate-addons-for-gutenberg pull request #3708
Opened 2024-01-03 08:17 UTC by yash-tingre-10

### Description
Icon size get huge due to CSS not getting generated in Post Page

### Screenshots
https://bsf.d.pr/i/a6LsHY

### Types of changes

### Test Cases
https://bsf.d.pr/v/CwLBo7

### Checklist:
- [ ] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2024-01-03 09:29 UTC, AbhijitNage123 commented on classes/class-uagb-twenty-seventeen-compatibility.php
> -				$post_assets_obj->prepare_assets( $post );
@yash-tingre-10 Its seems that you have removed all the code which are working previously for simple page which not set as home/post page. Is it necessary to remove that?

2024-01-03 09:31 UTC, AbhijitNage123 requested changes

2024-01-03 09:31 UTC, AbhijitNage123 commented on classes/class-uagb-twenty-seventeen-compatibility.php
> +				}
What if I used blocks on simple post/pages? Is it work in that case. Do we need to only handle the is_home() case.

2024-01-03 10:26 UTC, yash-tingre-10 commented on classes/class-uagb-twenty-seventeen-compatibility.php
> -				$post_assets_obj->prepare_assets( $post );
I tested that but did not notice any change and while debugging the value came out to but null

2024-01-04 12:03 UTC, AbhijitNage123 approved these changes

2024-01-05 03:44 UTC, adi3890 approved these changes

2024-01-05 10:02 UTC, merged