SPCTR-3614: Fix - Tabs layout breaking issue with bold text inside title area.
brainstormforce/ultimate-addons-for-gutenberg pull request #3726
Opened 2024-01-10 12:40 UTC by rajmohanreddy774

### Description

Tab title breaks when any text is made bold and layout vertical 6.
https://brainstormforce.atlassian.net/browse/SPCTR-3614

### Screenshots

https://d.pr/v/6XpIh5

### Types of changes

### How has this been tested?

### Checklist:
- [x] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2024-01-11 09:03 UTC, AbhijitNage123 commented on src/blocks/tabs/deprecated.js
> +import newAttributesV2_11_3 from './deprecated/v2.11.3/attributes';
@rajmohanreddy774 We don't have any changes in attributes so instead of creating new file, can  we use the `import newAttributes from './attributes';` and use it

2024-01-11 09:05 UTC, AbhijitNage123 requested changes
@rajmohanreddy774 Remove attributes.js file from deprecated/v2.11.3 as we don't have any changes in original attributes.js file. Use original once instead of new one

2024-01-11 09:07 UTC, AbhijitNage123 commented on src/blocks/tabs/save.js
> +							<RichText.Content tagName='div' value={ header } />
Make sure styling applying properly in editor as well as on frontend for Title.

2024-01-11 09:46 UTC, rajmohanreddy774 commented on src/blocks/tabs/deprecated.js
> +import newAttributesV2_11_3 from './deprecated/v2.11.3/attributes';
Updated.

2024-01-11 09:46 UTC, rajmohanreddy774 commented on src/blocks/tabs/save.js
> +							<RichText.Content tagName='div' value={ header } />
Verified all the styles and settings.

2024-01-11 09:48 UTC, AbhijitNage123 approved these changes

2024-01-11 14:17 UTC, adi3890 commented on src/blocks/tabs/deprecated.js
> +import newSaveV2_11_3 from './deprecated/v2.11.3/save';
I see inconsistency in folder nmaming please check for previous deprication for same blocks 
Ca n you please confirm the correct folder structure and update other one.

2024-01-11 15:59 UTC, rajmohanreddy774 commented on src/blocks/tabs/deprecated.js
> +import newSaveV2_11_3 from './deprecated/v2.11.3/save';
Renamed.

2024-01-12 06:16 UTC, adi3890 approved these changes

2024-01-17 03:02 UTC, merged