new: Forms Block
brainstormforce/ultimate-addons-for-gutenberg pull request #404
Opened 2020-10-30 11:25 UTC by vrundakansara

### Description

#### Form Parent Block
Premade Variations

- Newsletter - Subscribe Form
- RSVP Form
- Contact Form

#### Child Blocks

- Name/Text
- Yes/No (Toggle)
- File
- Phone Number
- Email
- Select box
- Checkbox
- Radiobox
- Text Area
- Phone Number
- URL
- Hidden field
- Date
- Submit Button

### Types of changes
New feature

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2021-02-12 11:55 UTC, RajkiranBagal requested changes

2021-02-12 11:55 UTC, RajkiranBagal commented on classes/class-uagb-block-helper.php
> +			$t_selectors = array();
This is already declared above.This is already declared above.

2021-02-12 11:55 UTC, RajkiranBagal commented on classes/class-uagb-block-helper.php
> +			$m_selectors = array();
This is already declared above.

2021-02-12 11:55 UTC, RajkiranBagal commented on classes/class-uagb-block-js.php
> +		 * @since 1.13.0
since `x.x.x`

2021-02-12 11:55 UTC, RajkiranBagal commented on dist/blocks.commoneditorstyle.build.css
> +<<<<<<< HEAD
Remove these conflict comments

2021-02-12 11:55 UTC, RajkiranBagal commented on dist/blocks/forms/class-uagb-forms.php
> +		 *
Add since tags for new functions

2021-02-12 11:55 UTC, RajkiranBagal commented on src/blocks.js
> +// import "./blocks/forms/child-blocks/upload/block.js"
remove unwanted code.

2021-02-12 11:55 UTC, RajkiranBagal commented on src/blocks/forms/attributes.js
> +		default: __( "Submit" )
Add `ultimate-addons-for-gutenberg` text domain for all the strings where not added.

2021-02-12 11:55 UTC, RajkiranBagal commented on src/blocks/forms/child-blocks/date/attributes.js
> +    default: "Date"
Add translation for this & check if any others are left. Also check for text-domain also.

2021-02-12 11:55 UTC, RajkiranBagal commented on src/blocks/forms/child-blocks/date/edit.js
> +	componentDidUpdate(prevProps, prevState) {
Remove unwanted hook.

2021-02-12 11:55 UTC, RajkiranBagal commented on src/blocks/forms/child-blocks/email/edit.js
> +	componentDidUpdate(prevProps, prevState) {
Remove unwanted hook. Check for other components too.

2021-02-12 11:55 UTC, RajkiranBagal commented on src/blocks/forms/child-blocks/phone/country-option.js
> +<option data-countryCode="IS" value="+354">Iceland (+354)</option>,
Add Translations to all these

2021-02-12 11:55 UTC, RajkiranBagal commented on src/blocks/forms/child-blocks/toggle/editor.scss
> +	height: 0;
Make proper use of SCSS you can write uagb-switch child css under it. similiar for uagb-slider

2021-02-12 11:55 UTC, RajkiranBagal commented on src/blocks/forms/deprecated.js
> +                            ) }
Why Do we need deprecated.js file. We are shiping this as new block. So no Backward compatibility.

2021-02-12 11:55 UTC, RajkiranBagal commented on src/blocks/forms/edit.js
> +			//Border
Remove all commented code.

2021-02-12 11:55 UTC, RajkiranBagal commented on src/blocks/forms/styling.js
> +        //Input
Remove commented code.

2021-02-15 04:15 UTC, supriyajjadhav commented on classes/class-uagb-block-helper.php
> +			$t_selectors = array();
Resolved

2021-02-15 04:15 UTC, supriyajjadhav commented on classes/class-uagb-block-helper.php
> +			$m_selectors = array();
Resolved

2021-02-15 04:15 UTC, supriyajjadhav commented on classes/class-uagb-block-helper.php
> +			$t_selectors = array();
Resolved

2021-02-15 04:15 UTC, supriyajjadhav commented on classes/class-uagb-block-helper.php
> +			$m_selectors = array();
Resolved

2021-02-15 04:16 UTC, supriyajjadhav commented on classes/class-uagb-block-js.php
> +		 * @since 1.13.0
Resolved

2021-02-15 04:17 UTC, supriyajjadhav commented on dist/blocks.commoneditorstyle.build.css
> +<<<<<<< HEAD
Resolved

2021-02-15 04:17 UTC, supriyajjadhav commented on dist/blocks/forms/class-uagb-forms.php
> +		 *
Resolved

2021-02-15 04:17 UTC, supriyajjadhav commented on src/blocks.js
> +// import "./blocks/forms/child-blocks/upload/block.js"
Resolved

2021-02-15 04:17 UTC, supriyajjadhav commented on src/blocks/forms/attributes.js
> +		default: __( "Submit" )
Resolved

2021-02-15 04:17 UTC, supriyajjadhav commented on src/blocks/forms/child-blocks/date/attributes.js
> +    default: "Date"
Resolved

2021-02-15 04:17 UTC, supriyajjadhav commented on src/blocks/forms/child-blocks/date/edit.js
> +	componentDidUpdate(prevProps, prevState) {
Resolved

2021-02-15 04:18 UTC, supriyajjadhav commented on src/blocks/forms/child-blocks/email/edit.js
> +	componentDidUpdate(prevProps, prevState) {
Resolved

2021-02-15 04:21 UTC, supriyajjadhav commented on src/blocks/forms/child-blocks/toggle/editor.scss
> +	height: 0;
Resolved

2021-02-15 04:21 UTC, supriyajjadhav commented on src/blocks/forms/deprecated.js
> +                            ) }
Resolved

2021-02-15 04:21 UTC, supriyajjadhav commented on src/blocks/forms/styling.js
> +        //Input
Resolved

2021-02-15 04:21 UTC, supriyajjadhav commented on src/blocks/forms/edit.js
> +			//Border
Resolved

2021-02-15 04:26 UTC, supriyajjadhav commented on src/blocks/forms/child-blocks/phone/country-option.js
> +<option data-countryCode="IS" value="+354">Iceland (+354)</option>,
https://share.getcloudapp.com/v1uNN7dN

2021-02-15 05:12 UTC, RajkiranBagal approved these changes

2021-02-24 08:47 UTC, RajkiranBagal requested changes

2021-02-24 08:47 UTC, RajkiranBagal commented on src/blocks/forms/style.scss
> +    /* position: fixed; */
Remove commented code

2021-02-24 09:00 UTC, supriyajjadhav commented on src/blocks/forms/style.scss
> +    /* position: fixed; */
removed

2021-02-25 14:17 UTC, vrundakansara reviewed
Please add text domain in all files for all string.

2021-02-25 14:17 UTC, vrundakansara commented on classes/class-uagb-block-helper.php
> +				' .uagb-forms-main-form input[type=radio]::checked' => array(
Should be added only if radiobox is added in the form.

2021-02-25 14:17 UTC, vrundakansara commented on classes/class-uagb-block-helper.php
> +				' .uagb-forms-main-form input[type=checkbox]:checked' => array(
Should be added only if checkbox is added in the form. Please check for all the below dynamic CSS too.

2021-02-25 14:17 UTC, vrundakansara commented on classes/class-uagb-block-js.php
> +				UAGBForms.init( <?php echo wp_json_encode( $attr ); ?>, '<?php echo esc_attr( $selector ); ?>' );
```js
wp_json_encode( $attr );
```
Let's pass only those attrs which are necessary for the JS file.

2021-02-25 14:17 UTC, vrundakansara commented on classes/class-uagb-config.php
> +							'hidden_field_name'  => 'Hidden Field Name',
Make it translatable.

2021-02-25 14:17 UTC, vrundakansara commented on classes/class-uagb-config.php
> +							'name'     => __( 'URL' ),
Add text domain

2021-02-25 14:17 UTC, vrundakansara commented on dist/blocks/forms/class-uagb-forms.php
> +			$form_data = $_POST['form_data'];
Sanitize these input `form_data`. Create a new function entirely for it. @RajkiranBagal - Please share your guidelines here.

2021-02-25 14:17 UTC, vrundakansara commented on src/blocks/forms/child-blocks/accept/attributes.js
> +        default: __( "#" , 'ultimate-addons-for-gutenberg' )
Link must not be translated.

2021-02-25 14:17 UTC, vrundakansara commented on src/blocks/forms/child-blocks/accept/edit.js
> +					title={ __( "General" ) }
All strings should have text-domain.

2021-02-25 14:17 UTC, vrundakansara commented on src/blocks/forms/child-blocks/accept/save.js
> +const {	RichText } = wp.blockEditor
Do we need this RichText here?

2021-03-03 07:21 UTC, RajkiranBagal commented on dist/blocks/forms/class-uagb-forms.php
> +			$form_data = $_POST['form_data'];
Right. Discussed this with @supriyajjadhav on a call. Asked her to create a function to sanitize the array.

2021-03-04 09:16 UTC, supriyajjadhav commented on README.md
> +* New: Forms Block.
Updated readme file.. Added on the top of the  change log --> 
= 1.22.0 =
* New: [Forms Block](https://ultimategutenberg.com/forms/).

2021-03-04 09:20 UTC, supriyajjadhav commented on assets/js/forms.js
> +                    $('.uagb-form-reacaptcha-error-'+attr['block_id']).html('<p style="color:red !important" class="error-captcha"> Please fill up the above captcha.</p>');
Added new attribute for this and translated.. because in this js file we can't access wp.i18n functions

2021-03-04 09:21 UTC, supriyajjadhav commented on assets/js/forms.js
> +                   $('.uagb-form-reacaptcha-error-'+attr['block_id']).html('<p style="color:red !important" class="error-captcha"> Please fill up the above captcha.</p>');
Added new attribute "captchaMessage" for this and translated.. because in this js file we can't access wp.i18n functions

2021-03-04 09:24 UTC, supriyajjadhav commented on classes/class-uagb-block-helper.php
> +				' .uagb-forms-main-form input[type=radio]::checked' => array(
Added conditions here Checked block is present or not... if block is present then only this CSS will be added

2021-03-04 09:25 UTC, supriyajjadhav commented on classes/class-uagb-block-helper.php
> +				' .uagb-forms-main-form input[type=checkbox]:checked' => array(
Added conditions here... First checked block is present or not... if block is present then only this CSS will be added

2021-03-04 09:27 UTC, supriyajjadhav commented on classes/class-uagb-block-js.php
> +				UAGBForms.init( <?php echo wp_json_encode( $attr ); ?>, '<?php echo esc_attr( $selector ); ?>' );
Added $js_attr array in that I have passed those attrs which are required

2021-03-04 09:32 UTC, supriyajjadhav commented on classes/class-uagb-config.php
> +							'hidden_field_name'  => 'Hidden Field Name',
Updated string... made it translatable

2021-03-04 09:32 UTC, supriyajjadhav commented on classes/class-uagb-config.php
> +							'name'     => __( 'URL' ),
Added Text Domain in every string

2021-03-04 09:39 UTC, supriyajjadhav commented on src/blocks/forms/child-blocks/accept/attributes.js
> +        default: __( "#" , 'ultimate-addons-for-gutenberg' )
Removed translation...

2021-03-04 09:45 UTC, supriyajjadhav commented on src/blocks/forms/child-blocks/accept/edit.js
> +					title={ __( "General" ) }
Added text domain in every string

2021-03-04 09:45 UTC, supriyajjadhav commented on src/blocks/forms/child-blocks/accept/save.js
> +const {	RichText } = wp.blockEditor
No, We are not using RichText here so i removed

2021-03-04 10:26 UTC, supriyajjadhav commented on dist/blocks/forms/class-uagb-forms.php
> +			$form_data = $_POST['form_data'];
@bsf_rajkiranb As per our discussion, I am using the sanitize_text_field() function to sanitize form input data because We are getting dynamic key and value so we can't identify each input type to add particular sanitize methods.

2021-03-04 11:03 UTC, RajkiranBagal commented on dist/blocks/forms/class-uagb-forms.php
> +			$form_data = $_POST['form_data'];
👍

2021-03-09 11:21 UTC, RajkiranBagal requested changes

2021-03-09 11:21 UTC, RajkiranBagal commented on src/blocks/forms/child-blocks/checkbox/edit.js
> +						value={s.optiontitle}
Can we rename the variable name `s` to something meaningful

2021-03-09 11:21 UTC, RajkiranBagal commented on src/blocks/forms/child-blocks/radio/edit.js
> +						value={s.optiontitle}
Can we rename the variable name s to something meaningful

2021-03-10 04:23 UTC, supriyajjadhav commented on src/blocks/forms/child-blocks/checkbox/edit.js
> +						value={s.optiontitle}
Renamed s as option

2021-03-10 04:23 UTC, supriyajjadhav commented on src/blocks/forms/child-blocks/radio/edit.js
> +						value={s.optiontitle}
Renamed s. as an option. Updated the file

2021-03-10 04:27 UTC, RajkiranBagal approved these changes

2021-03-10 12:18 UTC, supriyajjadhav commented on dist/blocks/forms/class-uagb-forms.php
> +			$form_data = $_POST['form_data'];
@RajkiranBagal  As per our discussion we are not storing the data in the database, So no need to sanitize this input.. added escape function

2021-03-10 12:24 UTC, RajkiranBagal commented on dist/blocks/forms/class-uagb-forms.php
> +			$form_data = $_POST['form_data'];
Right 👍

2021-03-10 13:21 UTC, vrundakansara reviewed
@supriyajjadhav - Please have a look at these comments.

2021-03-10 13:21 UTC, vrundakansara commented on src/blocks/forms/child-blocks/hidden/save.js
> +/**
Do we need this file?
`src/blocks/forms/child-blocks/hidden/editor.scss`

2021-03-10 13:21 UTC, vrundakansara commented on src/blocks/forms/child-blocks/textarea/edit.js
> +/**
Do we need this file?
`src/blocks/forms/child-blocks/textarea/editor.scss`

2021-03-10 13:21 UTC, vrundakansara commented on src/blocks/forms/child-blocks/upload/save.js
> +/**
Do we need this file?
`src/blocks/forms/child-blocks/upload/editor.scss`

2021-03-10 13:21 UTC, vrundakansara commented on src/blocks/forms/child-blocks/url/save.js
> +/**
Do we need this file?
`src/blocks/forms/child-blocks/url/editor.scss`

2021-03-10 14:36 UTC, supriyajjadhav commented on src/blocks/forms/child-blocks/hidden/save.js
> +/**
No, the File is empty we are not adding any custom CSS. 
Removed

2021-03-10 14:37 UTC, supriyajjadhav commented on src/blocks/forms/child-blocks/textarea/edit.js
> +/**
No, the File is empty we are not adding any custom CSS. 
Removed

2021-03-10 14:37 UTC, supriyajjadhav commented on src/blocks/forms/child-blocks/url/save.js
> +/**
No, the File is empty we are not adding any custom CSS. 
Removed

2021-03-11 11:40 UTC, merged