Post layout
brainstormforce/ultimate-addons-for-gutenberg pull request #437
Opened 2020-12-08 06:44 UTC by supriyajjadhav

### Description
Converted all the component into child block (For ex:- title, meta, excerpt, image, button)
Added editmode and viewmode layout in post grid.

### Types of changes
Registered child blocks.
Added layout modes in post grid block

### How has this been tested?
Tested whether it is working on the front-end and back-end.

### Checklist:
- [x] My code is tested
- [x] My code follows accessibility standards 
- [x] My code has proper inline documentation 
- [x] I've included any necessary tests 
- [x] I've included developer documentation 
- [x] I've added proper labels to this pull request

2020-12-17 07:34 UTC, AbhijitNage123 commented
Layout is broken when drag and drop the post grid - https://share.getcloudapp.com/KoulYJG5
It should be like this -   https://share.getcloudapp.com/yAuZkyjK

2020-12-17 07:36 UTC, AbhijitNage123 commented on config/webpack.config.prod.js
> +			let new_path = file_path.replace( paths.pluginSrc + "\\blocks\\", "" );
Make all `\\` to `/`

2020-12-17 07:36 UTC, AbhijitNage123 commented on config/webpack.config.prod.js
> +			new_path = new_path.replace( "\\style.scss", "" );
Same here

2020-12-17 07:38 UTC, AbhijitNage123 commented on dist/blocks/post/class-uagb-post.php
> +		 * @since 0.0.1
We have added new function it should be @since x.x.x

2020-12-17 07:38 UTC, AbhijitNage123 commented on dist/blocks/post/class-uagb-post.php
> +		 * @since 0.0.1
@since x.x.x

2020-12-17 10:07 UTC, RajkiranBagal requested changes

2020-12-17 10:07 UTC, RajkiranBagal commented on src/blocks/post/post-meta/block.js
> +						Author Name
Translate all such strings in all newly added child components

2020-12-17 10:09 UTC, RajkiranBagal commented
- Whenever we are asking someone to review a PR or Test a task then please assign that respective task to the respective person, add the proper label & add the task in the respective column in Trello.
 - Add the respective PR which is to be reviewed & Github Branch in the Trello task comment.
 - The PR's title should always start with a prefix ( new, improvement, fix )
 - In the PR checklist do not just check all the checkboxes just for the sake of checking those, Only check those checkboxes if the PR satisfies them, If some checkboxes are irrelevant to the PR raised then simply remove that checkbox from the PR.

2020-12-17 12:30 UTC, supriyajjadhav commented on dist/blocks/post/class-uagb-post.php
> +		 * @since 0.0.1
Fixed

2020-12-17 12:30 UTC, supriyajjadhav commented on dist/blocks/post/class-uagb-post.php
> +		 * @since 0.0.1
fixed

2020-12-17 12:35 UTC, supriyajjadhav commented on dist/blocks/post/class-uagb-post.php
> +			if ( 'uagb/post-button' === $fname ) {
Fixed

2020-12-17 12:55 UTC, supriyajjadhav commented on classes/class-uagb-config.php
> +						'description' => __( 'This block fetches the blog posts you may have on your website and displays them in a grid layout.', 'ultimate-addons-for-gutenberg' ),
Done

2020-12-17 12:55 UTC, supriyajjadhav commented on dist/blocks/post/class-uagb-post.php
> +		public function rendor_layout( $fname, $attr ) {
done

2020-12-17 12:59 UTC, supriyajjadhav commented on src/blocks/post/post-button/block.js
> + * BLOCK: UAGB - post-button
Done

2020-12-17 14:12 UTC, supriyajjadhav commented on src/blocks/post/post-carousel/edit.js
> +							'uag'
Fixed

2020-12-18 05:06 UTC, supriyajjadhav commented on src/blocks/post/post-meta/block.js
> +						Author Name
Added save.js files

2020-12-28 11:44 UTC, RajkiranBagal approved these changes

2021-01-13 08:15 UTC, vrundakansara approved these changes

2021-01-13 08:15 UTC, merged