Improvement - Introduce conditions to blocks
brainstormforce/ultimate-addons-for-gutenberg pull request #446
Opened 2020-12-16 07:06 UTC by mangeshsonule

Task Link -> https://trello.com/c/GroCHrDw/112-introduce-conditions-to-block

2020-12-18 12:07 UTC, RajkiranBagal approved these changes

2021-02-23 08:33 UTC, vrundakansara requested changes
@RajkiranBagal - Please find the below reviews.

2021-02-23 08:33 UTC, vrundakansara commented on dist/blocks/post-timeline/class-uagb-post-timeline.php
> +			<div class = "uagb-timeline__outer-wrap <?php echo esc_attr( implode( ' ', $main_classes ) ); ?>" >
Add this class in the `$main_classes` array too? `uagb-timeline__outer-wrap`

2021-02-23 08:33 UTC, vrundakansara commented on src/blocks/extensions/attributes.js
> +			DisplayConditions: {
Do we need to prefix this too?

2021-02-23 08:33 UTC, vrundakansara commented on src/blocks/extensions/attributes.js
> +			UAGloggedIn: {
Use proper case `UAGloggedIn`  => `UAGLoggedIn`
Use proper case `UAGloggedOut`  => `UAGLoggedOut`

2021-02-23 08:33 UTC, vrundakansara commented on src/blocks/price-list/save.js
> +		<div className={ classnames(
Please confirm if this will not throw validation issue with older versions.

2021-02-23 08:33 UTC, vrundakansara commented on src/blocks/testimonial/save.js
> +		<div className={ classnames(
Please confirm if this will not throw validation issue with older versions.

2021-02-23 10:35 UTC, AbhijitNage123 commented on dist/blocks/post-timeline/class-uagb-post-timeline.php
> +			<div class = "uagb-timeline__outer-wrap <?php echo esc_attr( implode( ' ', $main_classes ) ); ?>" >
Resolved

2021-02-23 10:36 UTC, AbhijitNage123 commented on src/blocks/extensions/attributes.js
> +			DisplayConditions: {
Updated.

2021-02-23 10:36 UTC, AbhijitNage123 commented on src/blocks/extensions/attributes.js
> +			UAGloggedIn: {
Updated

2021-02-23 10:36 UTC, AbhijitNage123 commented on src/blocks/price-list/save.js
> +		<div className={ classnames(
Added deprecated for the price-list

2021-02-23 10:37 UTC, AbhijitNage123 commented on src/blocks/testimonial/save.js
> +		<div className={ classnames(
I check it does not throws a validation error.

2021-02-25 08:09 UTC, vrundakansara requested changes
@AbhijitNage123 - Please check the below comments.

2021-02-25 08:09 UTC, vrundakansara commented on classes/class-uagb-init-blocks.php
> +		if ( isset( $block_attributes['UAGloggedOut'] ) && $block_attributes['UAGloggedOut'] && ! is_user_logged_in() ) {
Did we miss to update here too?
https://github.com/brainstormforce/ultimate-addons-for-gutenberg/pull/446#discussion_r580846571

2021-02-25 08:09 UTC, vrundakansara commented on classes/class-uagb-init-blocks.php
> +		if ( isset( $block_attributes['UAGloggedIn'] ) && $block_attributes['UAGloggedIn'] && is_user_logged_in() ) {
Did we miss to update here too?
https://github.com/brainstormforce/ultimate-addons-for-gutenberg/pull/446#discussion_r580846571

2021-02-25 08:09 UTC, vrundakansara commented on dist/blocks/post/class-uagb-post.php
> +			if ( array_key_exists( 'DisplayConditions', $attributes ) && 'responsiveVisibility' === $attributes['DisplayConditions'] ) {
Should we change the variable here too?
https://github.com/brainstormforce/ultimate-addons-for-gutenberg/pull/446#discussion_r580845983

2021-02-25 08:09 UTC, vrundakansara commented on dist/blocks/taxonomy-list/class-uagb-taxonomy-list.php
> +			if ( array_key_exists( 'DisplayConditions', $attributes ) && 'responsiveVisibility' === $attributes['DisplayConditions'] ) {
Should we change the variable here too?
https://github.com/brainstormforce/ultimate-addons-for-gutenberg/pull/446#discussion_r580845983

2021-02-25 08:36 UTC, AbhijitNage123 commented on classes/class-uagb-init-blocks.php
> +		if ( isset( $block_attributes['UAGloggedOut'] ) && $block_attributes['UAGloggedOut'] && ! is_user_logged_in() ) {
Resolved

2021-02-25 08:36 UTC, AbhijitNage123 commented on classes/class-uagb-init-blocks.php
> +		if ( isset( $block_attributes['UAGloggedIn'] ) && $block_attributes['UAGloggedIn'] && is_user_logged_in() ) {
Resolved

2021-02-25 08:37 UTC, AbhijitNage123 commented on dist/blocks/taxonomy-list/class-uagb-taxonomy-list.php
> +			if ( array_key_exists( 'DisplayConditions', $attributes ) && 'responsiveVisibility' === $attributes['DisplayConditions'] ) {
Resolved

2021-02-25 08:37 UTC, AbhijitNage123 commented on dist/blocks/post/class-uagb-post.php
> +			if ( array_key_exists( 'DisplayConditions', $attributes ) && 'responsiveVisibility' === $attributes['DisplayConditions'] ) {
Resolved

2021-02-25 12:27 UTC, vrundakansara requested changes

2021-02-25 12:27 UTC, vrundakansara commented on README.md
> +* Improvement: Introduce conditions to blocks
* Improvement: Block Conditions - Now user can add conditions of visibility to blocks with respect to User State, Responsive Visibility, User Role, Browser, and Operating System.

2021-02-25 12:27 UTC, vrundakansara commented on dist/blocks/gf-styler/class-uagb-gf-styler.php
> +			if ( array_key_exists( 'DisplayConditions', $attributes ) && 'responsiveVisibility' === $attributes['DisplayConditions'] ) {
These are still not changed `DisplayConditions `.

2021-02-25 12:27 UTC, vrundakansara commented on dist/blocks/post-timeline/class-uagb-post-timeline.php
> +			if ( array_key_exists( 'DisplayConditions', $attributes ) && 'responsiveVisibility' === $attributes['DisplayConditions'] ) {
This is still not changed. `DisplayConditions `

2021-02-25 12:27 UTC, vrundakansara commented on src/blocks/extensions/block.js
> +const AdvancedControlsBlock = wp.compose.createHigherOrderComponent((BlockEdit) => {
Prefix this with `UAG` =>` UAGAdvancedControlsBlock`

2021-02-25 13:40 UTC, vrundakansara approved these changes
Looks okay to me. 👍🏼

2021-03-01 09:09 UTC, merged