Added post grid mobile,tablet css for editor
brainstormforce/ultimate-addons-for-gutenberg pull request #459
Opened 2020-12-28 09:44 UTC by AbhijitNage123

### Description

### Screenshots

### Types of changes

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2020-12-30 13:07 UTC, RajkiranBagal commented on src/blocks/column/editor.scss
> +    display:block !important;
Can we avoid `important`?

2021-01-04 11:14 UTC, AbhijitNage123 commented on src/blocks/column/editor.scss
> +    display:block !important;
@RajkiranBagal I check we can not remove that `! important` CSS from the columns. Also, it only works in the editor.

2021-02-11 08:52 UTC, RajkiranBagal commented on src/blocks/column/editor.scss
> +    display:block !important;
Okay!

2021-02-11 09:02 UTC, RajkiranBagal requested changes

2021-02-11 09:02 UTC, RajkiranBagal commented on src/components/typography/column-responsive.js
> + 	// console.log(desktopChildren)
Remove console.log

2021-02-11 09:02 UTC, RajkiranBagal commented on src/components/typography/range-typography.js
> +		return select( 'core/edit-post' ).__experimentalGetPreviewDeviceType();
Can we use the Column Responsive function created here instead of repeating code.?

2021-02-11 11:16 UTC, AbhijitNage123 commented on src/components/typography/range-typography.js
> +		return select( 'core/edit-post' ).__experimentalGetPreviewDeviceType();
Parameter for range typography is different. It throw the value undefined. So I think we should keep this as it is.

2021-02-11 11:52 UTC, AbhijitNage123 commented on src/blocks/post/editor.scss
> +.uagb-post-grid.uagb-editor-preview-mode-tablet .uagb-post__columns-tablet-1 article { width: 100%; }
Done

2021-02-11 11:52 UTC, AbhijitNage123 commented on src/blocks/price-list/editor.scss
> +    float: left;
Done

2021-02-11 11:52 UTC, AbhijitNage123 commented on src/components/typography/column-responsive.js
> + 	// console.log(desktopChildren)
Done

2021-02-11 11:58 UTC, RajkiranBagal approved these changes

2021-04-16 04:16 UTC, vrundakansara requested changes

2021-04-16 04:16 UTC, vrundakansara commented on dist/blocks/uagb-controls/generateCSS.js
>  	if ( isResponsive && typeof gen_styling_css !== "undefined" && gen_styling_css.length !== 0 ) {
Can we get rid of this part completely since the responsive flag has no significance now. Just return the generated CSS.

2021-04-16 06:09 UTC, AbhijitNage123 commented on dist/blocks.commoneditorstyle.build.css
> +/* .uagb-size-type-field-tabs .components-base-control.components-range-control .components-base-control__field {
Resolved

2021-04-16 06:09 UTC, AbhijitNage123 commented on src/blocks/timeline/content-timeline/styling.js
> +    //    " .uagb-timeline__center-block .uagb-timeline__line" : {
Resolved

2021-04-16 06:09 UTC, AbhijitNage123 commented on src/blocks/timeline/inline-styles.js
> +		// " .uagb-timeline__center-block.uagb-timeline__responsive-tablet .uagb-timeline__line" : {
Resolved

2021-04-16 06:10 UTC, AbhijitNage123 commented on src/blocks/timeline/inline-styles.js
> +		// " .uagb-timeline__center-block.uagb-timeline__responsive-mobile .uagb-timeline__line" : {
Resolved

2021-04-16 06:10 UTC, AbhijitNage123 commented on dist/blocks/uagb-controls/generateCSS.js
>  	if ( isResponsive && typeof gen_styling_css !== "undefined" && gen_styling_css.length !== 0 ) {
Resolved

2021-04-16 07:01 UTC, sandeshjangam approved these changes

2021-04-16 07:18 UTC, vrundakansara approved these changes

2021-04-16 08:05 UTC, RajkiranBagal approved these changes

2021-04-16 08:43 UTC, merged