Rtl issue
brainstormforce/ultimate-addons-for-gutenberg pull request #468
Opened 2021-01-08 10:45 UTC by AbhijitNage123

### Description

### Screenshots

### Types of changes

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2021-02-11 09:28 UTC, RajkiranBagal approved these changes

2021-02-23 08:59 UTC, vrundakansara requested changes

2021-02-23 08:59 UTC, vrundakansara commented on output.rtl.css
> +/* - Blockquote */
Rename this file to `blocks.style.rtl.css`, and move it in the `/dist` folder.

2021-02-23 08:59 UTC, vrundakansara commented on output.rtl.css
> +.uagb-blockquote__skin-border blockquote.uagb-blockquote{
Do we need a `.rtl` prefix here?

2021-02-23 08:59 UTC, vrundakansara commented on output.rtl.css
> +.uagb_review_block .uagb_review_entry{
Do we need a `.rtl` prefix here?

2021-02-23 08:59 UTC, vrundakansara commented on classes/class-uagb-helper.php
> +				wp_enqueue_style(  'uagb-style-rtl', UAGB_URL . 'output.rtl.css' );
Add this in the file from where we add a static CSS file. This function is meant only for dynamic CSS.

2021-02-23 12:07 UTC, AbhijitNage123 commented on classes/class-uagb-helper.php
> +				wp_enqueue_style(  'uagb-style-rtl', UAGB_URL . 'output.rtl.css' );
Updated.

2021-02-23 12:08 UTC, AbhijitNage123 commented on output.rtl.css
> +.uagb_review_block .uagb_review_entry{
Updated

2021-02-23 12:08 UTC, AbhijitNage123 commented on output.rtl.css
> +.uagb-blockquote__skin-border blockquote.uagb-blockquote{
Updated

2021-02-23 12:08 UTC, AbhijitNage123 commented on output.rtl.css
> +/* - Blockquote */
Updated

2021-02-23 12:18 UTC, vrundakansara requested changes

2021-02-23 12:18 UTC, vrundakansara commented on classes/class-uagb-block-js.php
> +			$is_rtl       = is_rtl();
Get rid of this extra defined variable.

2021-02-23 12:18 UTC, vrundakansara commented on dist/blocks.style.rtl.css
> +/* - Blockquote */
Also, can we have a minified file here?

2021-02-23 12:49 UTC, AbhijitNage123 commented on dist/blocks.style.rtl.css
> +/* - Blockquote */
Yes, we can. Added

2021-02-23 12:49 UTC, AbhijitNage123 commented on classes/class-uagb-block-js.php
> +			$is_rtl       = is_rtl();
Updated

2021-02-23 12:56 UTC, vrundakansara approved these changes

2021-02-23 12:56 UTC, merged