Toc revamp
brainstormforce/ultimate-addons-for-gutenberg pull request #480
Opened 2021-01-20 13:07 UTC by AbhijitNage123

### Description

- https://trello.com/c/604tdcVT/172-revamp-toc-with-dynamic-logic

### Types of changes

- New feature (non-breaking change which adds functionality)

### How has this been tested?

- Drag and drop TOC and check every possible case with heading

### Checklist:
- [x] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [x] I've included any necessary tests 
- [ ] I've included developer documentation 
- [x] I've added proper labels to this pull request

2021-01-20 13:14 UTC, amithire1201 commented on dist/blocks/table-of-content/class-uagb-table-of-content.php
> +								'default'=> "Table Of Contents",
Can we make this string translatable?

2021-01-20 13:24 UTC, AbhijitNage123 commented on dist/blocks/table-of-content/class-uagb-table-of-content.php
> +								'default'=> "Table Of Contents",
Done

2021-01-20 13:26 UTC, amithire1201 approved these changes

2021-02-15 04:46 UTC, RajkiranBagal requested changes

2021-02-15 04:46 UTC, RajkiranBagal commented on dist/blocks/table-of-content/class-uagb-table-of-content.php
> +
Remove the repetitive code. Make it like this.
```Remove the repetitive code.
if ( 'core/heading' === $block['blockName'] || 'uagb/advanced-heading' === $block['blockName'] ) {

					$tag            = ( isset( $block['attrs']['level'] ) ) ? $block['attrs']['level'] : 2;
					$level          = ( isset( $block['attrs']['level'] ) ) ? $block['attrs']['level'] : 2;  // h2 as default.
					$excludeheading = ( isset( $block['attrs']['className'] ) ) ? $block['attrs']['className'] : '';

					$headings[] = array(
						'tag'            => $tag,
						'title'          => wp_strip_all_tags( $block['innerHTML'] ),
						'link'           => strtolower( $this->remove_special_char( wp_strip_all_tags( $block['innerHTML'] ) ) ),
						'level'          => ( $level ),
						'excludeheading' => $excludeheading,
					);
				}
```

2021-02-15 04:46 UTC, RajkiranBagal commented on dist/blocks/table-of-content/class-uagb-table-of-content.php
> +						'title'          => wp_strip_all_tags( $block['innerHTML'] ),
Do the same thing as suggested in the above comment in the below conditions.

2021-02-15 05:32 UTC, RajkiranBagal requested changes

2021-02-15 05:32 UTC, RajkiranBagal commented on dist/blocks/table-of-content/class-uagb-table-of-content.php
> +			$sortedHeaders = array();
Why are we using camelCase variable names in PHP? Let's keep them consistent, throughout the Plugin.

ex: `$sortedHeaders` => `$sorted_headers`

Do this change for all such variables in this file.

2021-02-15 05:33 UTC, AbhijitNage123 commented on dist/blocks/table-of-content/class-uagb-table-of-content.php
> +
Resolved.

2021-02-15 05:33 UTC, AbhijitNage123 commented on dist/blocks/table-of-content/class-uagb-table-of-content.php
> +						'title'          => wp_strip_all_tags( $block['innerHTML'] ),
Resolved.

2021-02-15 05:41 UTC, AbhijitNage123 commented on dist/blocks/table-of-content/class-uagb-table-of-content.php
> +			$sortedHeaders = array();
Resolved for all

2021-02-15 05:46 UTC, RajkiranBagal approved these changes

2021-03-02 10:41 UTC, RajkiranBagal requested changes

2021-03-02 10:41 UTC, RajkiranBagal commented on assets/js/table-of-contents.js
> +			var TOC = '';
Add proper variable names in camelCase

2021-03-02 10:41 UTC, RajkiranBagal commented on assets/js/table-of-contents.js
> +			console.log(header_array)
Remove console.logs

2021-03-02 10:41 UTC, RajkiranBagal commented on assets/js/table-of-contents.js
> +						if( 2 == (new Array(openLevel - level + 1)).length ){
Why are we declaring new Array in conditions & making calculations?

2021-03-02 10:41 UTC, RajkiranBagal commented on assets/js/table-of-contents.js
> +				TOC +=  'Add a header to begin generating the table of contents';
This should be translatable.

2021-03-02 10:41 UTC, RajkiranBagal commented on classes/class-uagb-config.php
> +							'headingTitleString'      => '',
Remove this if we are not using

2021-03-02 10:42 UTC, RajkiranBagal commented
@AbhijitNage123 Pull latest next-release.

2021-03-03 11:00 UTC, AbhijitNage123 commented on assets/js/table-of-contents.js
> +			var TOC = '';
Updated

2021-03-03 11:00 UTC, AbhijitNage123 commented on assets/js/table-of-contents.js
> +			console.log(header_array)
I need it for debugging. I'll remove it later

2021-03-03 11:01 UTC, AbhijitNage123 commented on assets/js/table-of-contents.js
> +						if( 2 == (new Array(openLevel - level + 1)).length ){
Resolved

2021-03-03 11:01 UTC, AbhijitNage123 commented on assets/js/table-of-contents.js
> +				TOC +=  'Add a header to begin generating the table of contents';
Resolved

2021-03-03 11:01 UTC, AbhijitNage123 commented on classes/class-uagb-config.php
> +							'headingTitleString'      => '',
Resolved

2021-03-03 13:54 UTC, RajkiranBagal requested changes

2021-03-03 13:54 UTC, RajkiranBagal commented on classes/class-uagb-config.php
> +			$array = array_fill_keys(array(0,1,2,3,4,5), true);
Please add a meaningful name to the array. Also, add proper indentation.

2021-03-03 13:54 UTC, RajkiranBagal commented on assets/js/table-of-contents.js
> +			var UAGBToc = '';
This is not camelCase @AbhijitNage123 .

2021-03-03 13:54 UTC, RajkiranBagal commented on dist/blocks/table-of-content/class-uagb-table-of-content.php
> +			$array = array_fill_keys(array(0,1,2,3,4,5), true);
Add meaningful array name.

2021-03-03 13:54 UTC, RajkiranBagal commented on src/blocks/table-of-contents/attributes.js
>  		default: "Table Of Contents",
Add Translation.

2021-03-03 13:54 UTC, RajkiranBagal commented on src/blocks/table-of-contents/edit.js
> +				let header_text = parseTocSlug(header.text());
Please keep consistent variables, Some are camelCase some are another format. Update them accordingly.

2021-03-03 14:24 UTC, AbhijitNage123 commented on classes/class-uagb-config.php
> +			$array = array_fill_keys(array(0,1,2,3,4,5), true);
Updated.

2021-03-03 14:24 UTC, AbhijitNage123 commented on assets/js/table-of-contents.js
> +			var UAGBToc = '';
Updated.

2021-03-03 14:25 UTC, AbhijitNage123 commented on dist/blocks/table-of-content/class-uagb-table-of-content.php
> +			$array = array_fill_keys(array(0,1,2,3,4,5), true);
Added

2021-03-03 14:25 UTC, AbhijitNage123 commented on src/blocks/table-of-contents/attributes.js
>  		default: "Table Of Contents",
Done

2021-03-03 14:31 UTC, AbhijitNage123 commented on src/blocks/table-of-contents/edit.js
> +				let header_text = parseTocSlug(header.text());
Done

2021-03-19 12:07 UTC, vrundakansara requested changes

2021-03-19 12:07 UTC, vrundakansara commented on assets/js/table-of-contents.js
> +			console.log(headerArray) // For testing will remove it later
Remove debugging logs.

2021-03-19 12:07 UTC, vrundakansara commented on classes/class-uagb-config.php
> +			$mappingHeadersArray = array_fill_keys(array(0,1,2,3,4,5), true);
Why do we need this? Can we declare this statically where it is needed?

2021-03-19 12:07 UTC, vrundakansara commented on classes/class-uagb-config.php
> +							'emptyHeadingTeaxt'         => 'Add a header to begin generating the table of contents',
Make this string translatable.

2021-03-22 08:33 UTC, vrundakansara requested changes

2021-03-22 08:55 UTC, AbhijitNage123 commented on dist/blocks/table-of-content/class-uagb-table-of-content.php
> +		public function uagb_render_table_of_contents_block( $attributes ) {
Done

2021-03-22 08:56 UTC, AbhijitNage123 commented on dist/blocks/table-of-content/class-uagb-table-of-content.php
> +				'wp-block-uagb-table-of-contents ',
Not working. Added support of Additional CSS class(es) in PHP file

2021-03-24 11:35 UTC, vrundakansara approved these changes

2021-03-24 11:39 UTC, merged