New: Tabs
brainstormforce/ultimate-addons-for-gutenberg pull request #487
Opened 2021-01-22 09:26 UTC by supriyajjadhav

[Trello](https://trello.com/c/5fJaFMbz/167-new-block-tabs)

### Description
New Block  --> Tabs
Tabs Block adds a Gutenberg block for adding Tabs content to your posts and pages. Fully responsive and accessible.

### Types of changes
- Added Parent-child tabs blocks

### How has this been tested?
Checked whether it is working fine on front-end and back-end.

### Checklist:
- [x] My code is tested
- [x] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [x] I've added proper labels to this pull request

2021-02-10 12:20 UTC, AbhijitNage123 commented on README.md
> +* New: Tabs Block.
We are adding Tab block in V1.21.0. Please update it

2021-02-10 12:22 UTC, AbhijitNage123 commented on classes/class-uagb-block-helper.php
> +					'background' => $attr['activeTabBgColor'] . '!important',
Please avoid using `!important`. Please make changes for all.

2021-02-10 12:28 UTC, AbhijitNage123 commented on classes/class-uagb-block-helper.php
> +					'font-size'   => UAGB_Helper::get_css_value( $attr['titleFontSizeTablet'], $attr['titleFontSizeType'] ),
Instead of using direct CSS property for a class, We can use like this -  `UAGB_Helper::get_typography_css( $attr, 'title', ' .uagb-tabs__panel .uagb-tab p', $combined_selectors );` please make changes for all.

2021-02-10 13:04 UTC, AbhijitNage123 commented on classes/class-uagb-config.php
> +							'classMigrate' => false,
We don't need `classMigrate` and `childMigrate` please remove it.

2021-02-10 13:07 UTC, AbhijitNage123 commented on classes/class-uagb-helper.php
> +					if ( ! isset( $blockattr['layout'] ) ) {
Do we have `layout` attribute?

2021-02-10 13:08 UTC, AbhijitNage123 commented on classes/class-uagb-helper.php
> +					} elseif ( 'uagb-tabs-js' === $val ) {
Why we have added this condition?

2021-02-10 13:13 UTC, AbhijitNage123 commented on classes/class-uagb-block-helper.php
> +					'padding-top'    => $attr['tabTitleVertPadding'],
How unit is apply here ^ ? IT should be `'padding-top'   => UAGB_Helper::get_css_value( $attr['tabTitleVertPadding'], 'px' ),`  make changes accordingly.

2021-02-10 13:16 UTC, AbhijitNage123 commented on src/blocks/tabs-child/block.js
> + * BLOCK: Social Share
Correct comment for a block

2021-02-10 13:17 UTC, AbhijitNage123 commented on src/blocks/tabs-child/block.js
> +import renderSVG from "../../../dist/blocks/uagb-controls/renderIcon"
We don't need this `renderSVG ` here in block.js

2021-02-10 13:18 UTC, AbhijitNage123 commented on src/blocks/tabs-child/edit.js
> + * BLOCK: Multi Buttons
Please correct comments for a block.

2021-02-10 13:19 UTC, AbhijitNage123 commented on src/blocks/tabs-child/save.js
> + * BLOCK: Social Share - Save Block
Please correct block comment

2021-02-10 13:22 UTC, AbhijitNage123 commented on src/blocks/tabs/attributes.js
> +	classMigrate: {
No need of this `classMigrate`

2021-02-10 13:24 UTC, AbhijitNage123 commented on src/blocks/tabs/attributes.js
> +	isPreview: {
`isPreview` not used. Please remove if not usefull.

2021-02-10 13:24 UTC, AbhijitNage123 commented on src/blocks/tabs/block.js
> + * BLOCK: Social Share
Please correct comment

2021-02-10 13:24 UTC, AbhijitNage123 commented on src/blocks/tabs/block.js
> +import renderSVG from "../../../dist/blocks/uagb-controls/renderIcon"
We don't need this in block.js

2021-02-10 13:28 UTC, AbhijitNage123 commented
Tabs child is visible in UAG dashboard please check - https://share.getcloudapp.com/OAugq1RQ

2021-02-11 06:25 UTC, supriyajjadhav commented on README.md
> +* New: Tabs Block.
Resolved

2021-02-11 10:23 UTC, RajkiranBagal requested changes

2021-02-11 10:23 UTC, RajkiranBagal commented on assets/js/tabs.js
> +(function ($) {
Please try not to use jQuery on frontend.

2021-02-11 14:34 UTC, supriyajjadhav commented on classes/class-uagb-config.php
> +							'classMigrate' => false,
Resolved

2021-02-11 14:35 UTC, supriyajjadhav commented on src/blocks/tabs/attributes.js
> +	classMigrate: {
resolved

2021-02-12 05:38 UTC, supriyajjadhav commented on classes/class-uagb-helper.php
> +					if ( ! isset( $blockattr['layout'] ) ) {
Resolved

2021-02-12 05:38 UTC, supriyajjadhav commented on classes/class-uagb-helper.php
> +					} elseif ( 'uagb-tabs-js' === $val ) {
Resolved

2021-02-12 05:39 UTC, supriyajjadhav commented on classes/class-uagb-block-helper.php
> +					'padding-top'    => $attr['tabTitleVertPadding'],
resolved

2021-02-12 05:39 UTC, supriyajjadhav commented on src/blocks/tabs-child/block.js
> + * BLOCK: Social Share
resolved

2021-02-12 05:39 UTC, supriyajjadhav commented on src/blocks/tabs-child/block.js
> +import renderSVG from "../../../dist/blocks/uagb-controls/renderIcon"
resolved

2021-02-12 05:39 UTC, supriyajjadhav commented on src/blocks/tabs-child/edit.js
> + * BLOCK: Multi Buttons
resolved

2021-02-12 05:39 UTC, supriyajjadhav commented on src/blocks/tabs-child/save.js
> + * BLOCK: Social Share - Save Block
resolved

2021-02-12 05:41 UTC, supriyajjadhav commented on src/blocks/tabs/attributes.js
> +	isPreview: {
resolved

2021-02-12 05:44 UTC, supriyajjadhav commented on src/blocks/tabs/block.js
> + * BLOCK: Social Share
resolved

2021-02-12 05:45 UTC, supriyajjadhav commented on src/blocks/tabs/block.js
> +import renderSVG from "../../../dist/blocks/uagb-controls/renderIcon"
resolved

2021-02-24 13:57 UTC, vrundakansara requested changes
@supriyajjadhav - Please check these.

2021-02-24 13:57 UTC, vrundakansara commented on classes/class-uagb-helper.php
> +		 * @since 1.18.1
Change the since tag to x.x.x

2021-02-24 13:57 UTC, vrundakansara commented on classes/class-uagb-config.php
> +					'uagb/tabs-child'             => array(
We need to add the `extension` flag too here. Check Multi buttons.

2021-02-24 13:57 UTC, vrundakansara commented on src/blocks/tabs/editor.scss
> +.uagb-tabs-select-style.uagb-size-type-field-tabs .components-tab-panel__tabs{
Do we need all of the 905 lines of CSS in the editor?

2021-02-24 13:57 UTC, vrundakansara commented on classes/class-uagb-helper.php
> +					self::$uag_tab_layout = true;
What is the purpose of this static flag?

2021-02-24 14:24 UTC, supriyajjadhav commented on classes/class-uagb-helper.php
> +		 * @since 1.18.1
Removed

2021-02-24 14:26 UTC, supriyajjadhav commented on classes/class-uagb-helper.php
> +					self::$uag_tab_layout = true;
REMOVED

2021-02-24 14:29 UTC, supriyajjadhav commented on src/blocks/tabs/editor.scss
> +.uagb-tabs-select-style.uagb-size-type-field-tabs .components-tab-panel__tabs{
Removed

2021-02-25 06:48 UTC, supriyajjadhav commented on classes/class-uagb-config.php
> +					'uagb/tabs-child'             => array(
added

2021-02-25 08:22 UTC, vrundakansara requested changes
@supriyajjadhav - Please work on these comments.

2021-02-25 08:22 UTC, vrundakansara commented on classes/class-uagb-block-helper.php
> +		 * @since 1.8.2
Change this to x.x.x

2021-02-25 08:22 UTC, vrundakansara commented on classes/class-uagb-config.php
> +							'pid'                   => '',
What is this pid for?

2021-02-25 08:22 UTC, vrundakansara commented on classes/class-uagb-config.php
> +							'changed'               => '',
What is this `changed` for?

2021-02-25 08:22 UTC, vrundakansara commented on classes/class-uagb-config.php
> +							'uniqueID'              => '',
What is this `uniqueID` for?

2021-02-25 08:22 UTC, vrundakansara commented on classes/class-uagb-config.php
> +							'isTransform'           => '',
What is this `isTransform` for?

2021-02-25 08:22 UTC, vrundakansara commented on classes/class-uagb-config.php
> +							'Icon'                  => '',
Why have we added this alone variable name in caps? `Icon`

2021-02-25 08:22 UTC, vrundakansara commented on classes/class-uagb-config.php
> +							'pid'        => '',
What does this `pid` do?

2021-02-25 08:22 UTC, vrundakansara commented on classes/class-uagb-config.php
> +							'uniqueID'   => '',
What does this `uniqueID` do?

2021-02-25 08:22 UTC, vrundakansara commented on classes/class-uagb-config.php
> +							'changed'    => false,
What does this `changed` do?

2021-02-25 08:22 UTC, vrundakansara commented on src/blocks/tabs-child/attributes.js
> +			'Tab 1',
Let's make these titles translatable.

2021-02-25 08:22 UTC, vrundakansara commented on src/blocks/tabs-child/edit.js
> +			<Fragment>
Do we really need this `Fragment` here?

2021-02-25 08:22 UTC, vrundakansara commented on src/blocks/tabs-child/edit.js
> +		const tabClassName = [
Let's use the `classnames` library here instead of this filter+join functions. We have used this in other blocks.

2021-02-25 08:22 UTC, vrundakansara commented on src/blocks/tabs-child/save.js
> +    const tabClassName = [
Let's use the classnames library here instead of this filter+join functions. We have used this in other blocks.

2021-02-25 08:22 UTC, vrundakansara commented on src/blocks/tabs/attributes.js
> +	HorizontalStyle: {
Please rectify the inconsistency in the variable name `HorizontalStyle`.

2021-02-25 08:22 UTC, vrundakansara commented on src/blocks/tabs/attributes.js
> +	Icon: {
Inconsistency in the variable name.

2021-02-25 08:26 UTC, supriyajjadhav commented on classes/class-uagb-block-helper.php
> +		 * @since 1.8.2
resolved

2021-02-25 08:37 UTC, supriyajjadhav commented on src/blocks/tabs/attributes.js
> +	Icon: {
resolved

2021-02-25 10:16 UTC, supriyajjadhav commented on src/blocks/tabs/attributes.js
> +	HorizontalStyle: {
Removed

2021-02-25 10:17 UTC, supriyajjadhav commented on src/blocks/tabs-child/save.js
> +    const tabClassName = [
updated

2021-02-25 10:19 UTC, supriyajjadhav commented on src/blocks/tabs-child/edit.js
> +		const tabClassName = [
updated

2021-02-25 10:21 UTC, supriyajjadhav commented on src/blocks/tabs-child/attributes.js
> +			'Tab 1',
done

2021-02-25 10:21 UTC, supriyajjadhav commented on src/blocks/tabs-child/edit.js
> +			<Fragment>
removed

2021-02-25 10:21 UTC, supriyajjadhav commented on classes/class-uagb-config.php
> +							'changed'    => false,
removed

2021-02-25 10:21 UTC, supriyajjadhav commented on classes/class-uagb-config.php
> +							'uniqueID'   => '',
removed and used block_id

2021-02-25 10:22 UTC, supriyajjadhav commented on classes/class-uagb-config.php
> +							'pid'        => '',
removed

2021-02-25 10:22 UTC, supriyajjadhav commented on classes/class-uagb-config.php
> +							'Icon'                  => '',
Updated

2021-02-25 10:26 UTC, supriyajjadhav commented on classes/class-uagb-config.php
> +							'isTransform'           => '',
removed

2021-02-25 10:26 UTC, supriyajjadhav commented on classes/class-uagb-config.php
> +							'uniqueID'              => '',
removed

2021-02-25 10:26 UTC, supriyajjadhav commented on classes/class-uagb-config.php
> +							'changed'               => '',
removed

2021-02-25 10:26 UTC, supriyajjadhav commented on classes/class-uagb-config.php
> +							'pid'                   => '',
removed

2021-02-25 13:33 UTC, vrundakansara requested changes

2021-02-25 13:33 UTC, vrundakansara commented on classes/class-uagb-block-helper.php
> +				'.uagb-tabs__wrap.uagb-tabs__hstyle5-desktop , .uagb-tabs__wrap.uagb-tabs__vstyle10-desktop' => array(
If this is only for style 5 and style 10, add it conditionally - `.uagb-tabs__wrap.uagb-tabs__hstyle5-desktop , .uagb-tabs__wrap.uagb-tabs__vstyle10-desktop`

2021-02-25 13:33 UTC, vrundakansara commented on classes/class-uagb-block-helper.php
> +					'.uagb-tabs__wrap.uagb-tabs__hstyle5-mobile , .uagb-tabs__wrap.uagb-tabs__vstyle10-mobile , .uagb-tabs__wrap.uagb-tabs__stack4-mobile' => array(
This too should be conditional with style.

2021-02-25 13:33 UTC, vrundakansara commented on classes/class-uagb-block-helper.php
> +					'.uagb-tabs__wrap.uagb-tabs__hstyle5-tablet , .uagb-tabs__wrap.uagb-tabs__vstyle10-tablet' => array(
This too should be conditional with style.

2021-02-25 13:33 UTC, vrundakansara commented on classes/class-uagb-config.php
> +							'extension'             => false,
You added the extension at the wrong place @supriyajjadhav

2021-02-25 13:33 UTC, vrundakansara commented on classes/class-uagb-config.php
> +						'is_child'    => true,
We need `extension` flag here too.

2021-02-25 13:33 UTC, vrundakansara commented on src/blocks/tabs-child/attributes.js
> +			'Tab 1',
Doesn't look like it?

2021-02-25 13:33 UTC, vrundakansara commented on src/blocks/tabs-child/editor.scss
> +.uagb-tabs__body{
This is already added in style.scss, let's remove it from editor.scss.

2021-02-25 13:33 UTC, vrundakansara commented on src/blocks/tabs/edit.js
> +														{value: 'hstyle1', label: __('Horizontal Style 1')},
All the strings should have `ultimate-addons-for-gutenberg` as text domain. Please check in entire file.

2021-02-25 13:33 UTC, vrundakansara commented on src/blocks/tabs/edit.js
> +							max={ 50 }
Let's increase this max to 500. All of it.

2021-02-25 13:33 UTC, vrundakansara commented on src/blocks/tabs-child/attributes.js
> +	id: {
What is this `id` for? We have `blockId` everywhere, right?

2021-02-25 13:33 UTC, vrundakansara commented on readme.txt
> +* New: Tabs Block.
* New: Tabs Block - [demo_url]

2021-02-25 13:33 UTC, vrundakansara commented on assets/js/tabs.js
> +(function ($) {
I see still we use jQuery. Can you avoid it @supriyajjadhav ?

2021-02-25 15:11 UTC, supriyajjadhav commented on src/blocks/tabs-child/attributes.js
> +	id: {
we used id attribute to generate unique ids to each tab heading --> https://share.getcloudapp.com/bLugOkkR , 
 and tab body https://share.getcloudapp.com/WnuBZxkP we can not use block id here because in parent block we are creating all the tab headings and in child block we are creating tabs body only so here block_id will be different

2021-02-25 15:28 UTC, supriyajjadhav commented on classes/class-uagb-block-helper.php
> +				'.uagb-tabs__wrap.uagb-tabs__hstyle5-desktop , .uagb-tabs__wrap.uagb-tabs__vstyle10-desktop' => array(
Done

2021-02-25 15:28 UTC, supriyajjadhav commented on classes/class-uagb-block-helper.php
> +					'.uagb-tabs__wrap.uagb-tabs__hstyle5-mobile , .uagb-tabs__wrap.uagb-tabs__vstyle10-mobile , .uagb-tabs__wrap.uagb-tabs__stack4-mobile' => array(
Done

2021-02-25 15:28 UTC, supriyajjadhav commented on classes/class-uagb-config.php
> +							'extension'             => false,
fixed

2021-02-25 15:28 UTC, supriyajjadhav commented on classes/class-uagb-config.php
> +						'is_child'    => true,
added

2021-02-25 15:28 UTC, supriyajjadhav commented on src/blocks/tabs-child/editor.scss
> +.uagb-tabs__body{
removed

2021-02-25 15:29 UTC, supriyajjadhav commented on src/blocks/tabs/edit.js
> +														{value: 'hstyle1', label: __('Horizontal Style 1')},
added

2021-02-25 15:29 UTC, supriyajjadhav commented on src/blocks/tabs/edit.js
> +							max={ 50 }
updated

2021-02-25 15:29 UTC, supriyajjadhav commented on readme.txt
> +* New: Tabs Block.
Updated

2021-02-26 08:03 UTC, vrundakansara commented on src/blocks/tabs-child/attributes.js
> +	id: {
Okay. 👍🏼
Thank you for clarifying @supriyajjadhav

2021-02-26 08:06 UTC, vrundakansara requested changes

2021-02-26 08:06 UTC, vrundakansara commented on src/blocks/tabs-child/editor.scss
> +
Let's delete the entire file if we have nothing to add here.

2021-02-26 08:09 UTC, supriyajjadhav commented on src/blocks/tabs-child/editor.scss
> +
Removed

2021-02-26 09:04 UTC, supriyajjadhav commented on assets/js/tabs.js
> +(function ($) {
I have added this in improvement --> https://trello.com/c/Dyi3EjNB/102-tabs-block

2021-02-26 09:11 UTC, RajkiranBagal commented on assets/js/tabs.js
> +(function ($) {
👍

2021-03-01 08:52 UTC, vrundakansara approved these changes

2021-03-01 08:53 UTC, merged