Fix: Price List - Issue when imagePosition is undefined when used as a reusable block.
brainstormforce/ultimate-addons-for-gutenberg pull request #495
Opened 2021-02-18 12:14 UTC by AbhijitNage123

### Description

### Screenshots

### Types of changes

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2021-02-22 04:55 UTC, RajkiranBagal requested changes

2021-02-22 04:55 UTC, RajkiranBagal commented on src/blocks/price-list-child/edit.js
> +		if( parentAttributes ) {
Update the code with this.

let position = ( parentAttributes ) ? parentAttributes.imagePosition : imagePosition;

2021-02-22 05:14 UTC, AbhijitNage123 commented on src/blocks/price-list-child/edit.js
> +		if( parentAttributes ) {
Resolved

2021-02-22 05:39 UTC, RajkiranBagal approved these changes

2021-02-23 09:41 UTC, vrundakansara requested changes

2021-02-23 09:41 UTC, vrundakansara commented on readme.txt
> +### 1.21.0 ###
= 1.21.0 =

2021-02-23 10:55 UTC, AbhijitNage123 commented on readme.txt
> +### 1.21.0 ###
Updated

2021-02-23 11:43 UTC, vrundakansara approved these changes

2021-02-23 11:43 UTC, merged