Fix: Styling not applying when used as a reusable block for section/marketing button.
brainstormforce/ultimate-addons-for-gutenberg pull request #502
Opened 2021-03-03 06:51 UTC by AbhijitNage123

### Description

- trello - https://trello.com/c/pAHu2EUV/199-section-and-marketting-button-color-gradient-not-applying-when-used-as-a-reusable-block

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

### How has this been tested?

- Create a Section/Marketing button with color/gradient and save as a reusable in master.
- Update and refresh the page you will see the color style is not applying.
- Switch to `reusable-block-issue` branch refresh the editor and issue resolved.

### Checklist:
- [x] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [x] I've included any necessary tests 
- [ ] I've included developer documentation 
- [x] I've added proper labels to this pull request

2021-03-03 14:01 UTC, RajkiranBagal requested changes

2021-03-03 14:01 UTC, RajkiranBagal commented on src/blocks/section/edit.js
> +		var element = document.getElementById( "uagb-section-style-" + this.props.clientId.substr( 0, 8 ) )
Why again retrieve the element again, we already have it in $style variable.

2021-03-03 14:01 UTC, RajkiranBagal commented on readme.txt
> +* Fix: Styling not applying when used as a reusable block for section/marketting button.
I also see a change in the Column block, please add also that in the changelog.

2021-03-04 05:18 UTC, AbhijitNage123 commented on readme.txt
> +* Fix: Styling not applying when used as a reusable block for section/marketting button.
Updated

2021-03-04 05:18 UTC, AbhijitNage123 commented on src/blocks/section/edit.js
> +		var element = document.getElementById( "uagb-section-style-" + this.props.clientId.substr( 0, 8 ) )
Updated

2021-03-04 05:18 UTC, AbhijitNage123 commented on src/blocks/marketing-button/edit.js
> +		var element = document.getElementById( "uagb-style-marketing-btn-" + this.props.clientId.substr( 0, 8 ) )
Updated

2021-03-04 05:18 UTC, AbhijitNage123 commented on src/blocks/column/edit.js
> +		var element = document.getElementById( "uagb-column-style-" + this.props.clientId.substr( 0, 8 ) )
Updated

2021-03-04 05:18 UTC, AbhijitNage123 commented on languages/ultimate-addons-for-gutenberg-es_ES-a4f783c851c57db1967c3d9a58cfd198.json
> +{"translation-revision-date":"2021-03-02 12:36+0530","generator":"WP-CLI\/2.5.0-alpha-59d879d","source":"dist\/blocks.build.js","domain":"messages","locale_data":{"messages":{"":{"domain":"messages",
Removed

2021-03-05 04:15 UTC, RajkiranBagal requested changes

2021-03-05 04:15 UTC, RajkiranBagal commented on src/blocks/marketing-button/edit.js
> +		if( null !== $style && undefined !== $style ) {
Do we really need to check the null & undefined condition here, as we are creating the element here itself?

2021-03-05 04:15 UTC, RajkiranBagal commented on readme.txt
> +* Fix: Styling not applying when used as a reusable block for column/section/marketting button.
Update changelog to `Fix: Styling not applying when used as a reusable block for Advanced Columns, Section & Marketing Button Blocks.
`

2021-03-09 08:39 UTC, AbhijitNage123 commented on readme.txt
> +* Fix: Styling not applying when used as a reusable block for column/section/marketting button.
Updated

2021-03-09 11:32 UTC, RajkiranBagal approved these changes

2021-09-23 11:05 UTC, closed without merging