Fix: post masonry post_type undefined issue.
brainstormforce/ultimate-addons-for-gutenberg pull request #503
Opened 2021-03-04 12:13 UTC by AbhijitNage123

### Description

Trello - https://trello.com/c/ieHPjlAD/207-post-masonry-posttype-undefined-issue 

### Screenshots

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

### How has this been tested?

- Drag and drop masonry set pagination to Scroll or Load more.
- Visit frontend. scroll or click on load more and check the debug log.
- You will see the post_type undefined.
- Clear the debug log and Switch to this `post-type-undefined-in-masonry branch and refresh the page and check the debug log.

### Checklist:
- [x] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [x] I've included any necessary tests 
- [ ] I've included developer documentation 
- [x] I've added proper labels to this pull request

2021-03-05 04:10 UTC, RajkiranBagal approved these changes

2021-03-09 13:26 UTC, vrundakansara requested changes

2021-03-09 13:26 UTC, vrundakansara commented on README.md
> +* Fix: Post Masonary - post_type undefined issue.
```
* Fix: Post Layouts - Fixed the JS undefined error with `post_type` in block editor while using Post Masonry.
```

2021-03-09 13:30 UTC, AbhijitNage123 commented on README.md
> +* Fix: Post Masonary - post_type undefined issue.
Updated

2021-03-10 13:15 UTC, vrundakansara approved these changes

2021-03-10 13:15 UTC, merged