New: WP 5.7 Compatibility
brainstormforce/ultimate-addons-for-gutenberg pull request #504
Opened 2021-03-04 14:04 UTC by AbhijitNage123

### Description

Trello - https://trello.com/c/raylEFaO/197-wp-57-testing

### Screenshots

### Types of changes

- Bug fix

### How has this been tested?

- Drag and drop each module.
- Check it's not breaking anything.
- Drag and drop every block with no console error in the editor.

### Checklist:
- [x] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [x] I've included any necessary tests 
- [ ] I've included developer documentation 
- [x] I've added proper labels to this pull request

2021-03-10 12:05 UTC, vrundakansara requested changes

2021-03-10 12:05 UTC, vrundakansara commented on src/blocks/tabs-child/edit.js
> +	UNSAFE_componentWillMount() {
@RajkiranBagal - Any idea why we are using this? `UNSAFE_componentWillMount`

2021-03-11 04:06 UTC, RajkiranBagal commented on src/blocks/tabs-child/edit.js
> +	UNSAFE_componentWillMount() {
@supriyajjadhav Can we have an alternative to this?

2021-03-11 04:33 UTC, supriyajjadhav commented on src/blocks/tabs-child/edit.js
> +	UNSAFE_componentWillMount() {
Checking

2021-03-11 07:04 UTC, supriyajjadhav commented on src/blocks/tabs-child/edit.js
> +	UNSAFE_componentWillMount() {
@Abhijeetbhilare  At my end, I am not getting any console warning after adding the componentWillMount function in the tabs-child block. Please check this issue and update the status.

2021-03-11 07:38 UTC, AbhijitNage123 commented on src/blocks/tabs-child/edit.js
> +	UNSAFE_componentWillMount() {
@vrundakansara ma'am, warning mention that `componentWillMount has been renamed, and is not recommended for use.` 
That's why I renamed the `UNSAFE_componentWillMount`. Here is more info about it - https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html

2021-03-11 07:59 UTC, AbhijitNage123 commented on src/blocks/tabs-child/edit.js
> +	UNSAFE_componentWillMount() {
Also, To remove this warning  I tried removing `componentWillMount` and put the code in `componentDidMount`. I test every functionality of Tabs it's working fine. Is there any other test case @supriyajjadhav/ @RajkiranBagal

2021-03-11 09:54 UTC, RajkiranBagal approved these changes

2021-03-11 09:54 UTC, RajkiranBagal commented
@AbhijitNage123 Add changelog.

2021-03-12 15:30 UTC, vrundakansara requested changes

2021-03-12 15:30 UTC, vrundakansara commented on README.md
> +### 1.22.0 ###
This should be under v1.21.1

2021-03-13 05:24 UTC, AbhijitNage123 commented on README.md
> +### 1.22.0 ###
Updated

2021-03-15 08:09 UTC, vrundakansara approved these changes

2021-03-15 08:23 UTC, vrundakansara requested changes

2021-03-15 08:23 UTC, vrundakansara commented on README.md
>  **Stable tag:** 1.21.0
Add the stable tag to `1.21.1`

2021-03-15 08:27 UTC, vrundakansara requested changes

2021-03-15 08:27 UTC, vrundakansara commented on src/blocks/post/styling.js
> -	if ( true === postPagination && 'empty' === paginationMarkup ) {
Why have we removed this condition?

2021-03-15 09:03 UTC, vrundakansara approved these changes

2021-03-15 09:03 UTC, merged