Fix: Block Conditions - Conflicting the WPForms.
brainstormforce/ultimate-addons-for-gutenberg pull request #505
Opened 2021-03-08 14:13 UTC by AbhijitNage123

### Description

Trello - https://trello.com/c/qGR6uGBc/209-fix-block-conditions-conflicting-the-wpforms

### Screenshots

### Types of changes

- Bug fix (non-breaking change which fixes an issue) 

### How has this been tested?

- Create a simple WPForm (just one line)
- Create page
- Add Form to the page using WPForms block and check if an error occurred or not.

### Checklist:
- [x] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [x] I've included any necessary tests 
- [ ] I've included developer documentation 
- [x] I've added proper labels to this pull request

2021-03-09 11:24 UTC, RajkiranBagal approved these changes

2021-03-09 11:24 UTC, RajkiranBagal commented
@AbhijitNage123 Just confirm the Changelog once.

2021-03-10 13:14 UTC, vrundakansara commented on src/blocks/extensions/attributes.js
> +	if( settings.category === 'uagb' ){
Does this mean we will have these visibility options just for UAG blocks?

2021-03-11 03:34 UTC, AbhijitNage123 commented on src/blocks/extensions/attributes.js
> +	if( settings.category === 'uagb' ){
Yes, We only adding block attributes when the category is a match.

2021-03-11 10:35 UTC, vrundakansara commented on src/blocks/extensions/attributes.js
> +	if( settings.category === 'uagb' ){
This is not the expected behavior @AbhijitNage123 
We want it for all blocks.

Can you elaborate on what the conflict was?

2021-03-11 10:50 UTC, AbhijitNage123 commented on src/blocks/extensions/attributes.js
> +	if( settings.category === 'uagb' ){
After drag and drop the WPForms on-page. It shows the `Error loading block: Invalid parameter(s): attributes`. And it seems that we are adding attributes for all the blocks. and due to which the attribute is added in the ajax URL - https://share.getcloudapp.com/qGuXWPxA because that block is enabled to render it. @vrundakansara

2021-03-11 11:43 UTC, vrundakansara commented on src/blocks/extensions/attributes.js
> +	if( settings.category === 'uagb' ){
We need to fix that issue then. See why these parameters are passed and how we can avoid them.

2021-03-13 05:37 UTC, AbhijitNage123 commented on src/blocks/extensions/attributes.js
> +	if( settings.category === 'uagb' ){
Adding Responsive CSS through javascript in order to work for all blocks. And exclude the WPForms from the conditional block.

2021-03-19 15:58 UTC, vrundakansara requested changes

2021-03-19 15:58 UTC, vrundakansara commented on classes/class-uagb-block-helper.php
> +		 * @param string $id The selector ID.
Remove these two params since we don't have any function parameters.

2021-03-22 08:34 UTC, vrundakansara approved these changes

2021-03-22 08:34 UTC, merged