Fix google map
brainstormforce/ultimate-addons-for-gutenberg pull request #511
Opened 2021-03-11 07:54 UTC by supriyajjadhav

### Description
When we drag and drop the block in the editor and then we are not able to select google map again to change its settings
issue --> https://share.getcloudapp.com/7Kup9Ogr

[Trello](https://trello.com/c/ec4jPoo8/212-fix-google-map-block-not-able-to-select-again-to-change-settings)

### Types of changes
- Added padding to the main div in the editor 

### How has this been tested?
Tested whether we are able to select block easily in editor.

### Checklist:
- [x] My code is tested
- [x] My code follows accessibility standards

2021-03-11 08:43 UTC, RajkiranBagal approved these changes

2021-03-30 11:52 UTC, vrundakansara requested changes

2021-03-30 11:52 UTC, vrundakansara commented on README.md
> +* Improvement: Google Map - Now user can easily select block in editor.
`* Fix: Google Map - Added some padding for the editor to improve the experience of a selection of Google Map.`

2021-03-30 11:52 UTC, vrundakansara commented on src/blocks/google-map/style.scss
> +	padding: 25px;
Why are we adding padding in the frontend?
Will this affect existing designs?

2021-03-30 12:17 UTC, supriyajjadhav commented on README.md
> +* Improvement: Google Map - Now user can easily select block in editor.
Updated readme Added 1.22.2 version

2021-03-30 12:19 UTC, supriyajjadhav commented on src/blocks/google-map/style.scss
> +	padding: 25px;
Updated CSS. Added padding to the block editor only.

2021-03-30 17:27 UTC, vrundakansara commented on src/blocks/google-map/style.scss
> +	padding: 25px;
Will this CSS be loaded on frontend too?

2021-03-31 06:22 UTC, supriyajjadhav commented on src/blocks/google-map/style.scss
> +	padding: 25px;
Yes.. Added editor.scss file to load this CSS only on editor side

2021-04-09 11:12 UTC, sandeshjangam approved these changes

2021-04-09 11:31 UTC, merged