Fix: Display all the taxonomy names in each posts in all the post layout
brainstormforce/ultimate-addons-for-gutenberg pull request #514
Opened 2021-03-15 02:18 UTC by supriyajjadhav

[Trello](https://trello.com/c/HG217qoX/214-fix-post-grid-masonry-carousel-taxonomy-issue)

### Description
If the block has more than 2 categories selected then in the post (Grid/masonry/carousel) layout only one category name is shown. We need to add all the selected taxonomy names in the posts

### Types of changes
- Added list of arrays to display all the categories in back-end and front-end.

### How has this been tested?
Checked whether it is working on the front-end and back-end.

### Checklist:
- [x] My code is tested
- [x] My code follows accessibility standards 
- [x] I've included any necessary tests - 
- [x] [ ] I've added proper labels to this pull request

2021-03-19 13:57 UTC, vrundakansara requested changes

2021-03-19 13:57 UTC, vrundakansara commented on dist/blocks/post/class-uagb-post.php
> +					$category_id = get_cat_ID( $value->name );
Please reuse the already existing ID from `$value->term_id`.

2021-03-19 13:57 UTC, vrundakansara commented on dist/blocks/post/class-uagb-post.php
> +					<a href="<?php echo esc_url( $category_link ); ?>"><?php echo esc_html( $value->name ); ?></a>
Push all these into an array variable and echo them by exploding the array.

2021-03-19 15:21 UTC, supriyajjadhav commented on dist/blocks/post/class-uagb-post.php
> +					$category_id = get_cat_ID( $value->name );
Added $value->term_id in the function parameter

2021-03-19 15:21 UTC, supriyajjadhav commented on dist/blocks/post/class-uagb-post.php
> +					<a href="<?php echo esc_url( $category_link ); ?>"><?php echo esc_html( $value->name ); ?></a>
Created srray called $term_list and printed using implode

2021-03-22 08:33 UTC, vrundakansara approved these changes

2021-03-22 09:57 UTC, AbhijitNage123 approved these changes

2021-03-22 10:03 UTC, vrundakansara approved these changes

2021-03-22 10:04 UTC, merged