Fix reusable forms checkbox radio button issue on front-end
brainstormforce/ultimate-addons-for-gutenberg pull request #530
Opened 2021-03-23 09:46 UTC by supriyajjadhav

### Description

### Screenshots

### Types of changes

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2021-03-23 10:19 UTC, RajkiranBagal commented
@supriyajjadhav Also check the normal case, without reusable block.

2021-03-23 10:20 UTC, supriyajjadhav commented
> @supriyajjadhav Also check the normal case, without reusable block.

Checked... Working Fine

2021-03-23 10:21 UTC, RajkiranBagal commented
> > @supriyajjadhav Also check the normal case, without reusable block.
> 
> Checked... Working Fine

Not at my end - https://share.getcloudapp.com/6qu8KWpv

2021-03-23 11:11 UTC, RajkiranBagal requested changes

2021-03-23 11:11 UTC, RajkiranBagal commented on classes/class-uagb-block-helper.php
> +								);
Please eliminate the duplicate code.

2021-03-23 13:30 UTC, RajkiranBagal approved these changes

2021-03-24 07:01 UTC, supriyajjadhav commented on classes/class-uagb-block-helper.php
> +								);
Done

2021-03-24 10:44 UTC, RajkiranBagal requested changes

2021-03-24 10:44 UTC, RajkiranBagal commented on classes/class-uagb-block-helper.php
> +						$reusable_blocks      = version_compare( $wp_version, '5', '>=' ) ? parse_blocks( $content ) : gutenberg_parse_blocks( $content );
This is also declared above.

2021-03-24 10:52 UTC, supriyajjadhav commented on classes/class-uagb-block-helper.php
> +						$reusable_blocks      = version_compare( $wp_version, '5', '>=' ) ? parse_blocks( $content ) : gutenberg_parse_blocks( $content );
Right! In reusable block case, we dont find our blocks list inside the first $reusable_block. So inside the first for we are checking if the block id is present then we have added $content = get_post_field( 'post_content', $block_id ); and passing this in $reusable_block variable to get blocks data.

2021-03-24 10:54 UTC, RajkiranBagal commented on classes/class-uagb-block-helper.php
> +						$reusable_blocks      = version_compare( $wp_version, '5', '>=' ) ? parse_blocks( $content ) : gutenberg_parse_blocks( $content );
Yes, Right! Totally forgot.

2021-03-24 10:54 UTC, RajkiranBagal approved these changes

2021-03-24 11:31 UTC, vrundakansara requested changes

2021-03-24 11:42 UTC, supriyajjadhav commented on classes/class-uagb-block-helper.php
> +			$content = get_post_field( 'post_content' );
In the reusable block case, 
- we are not able to get a blocklist using $content = get_post_field( 'post_content' ); we get this --> https://share.getcloudapp.com/WnuYedgQ
- When we add this $content in $reusable_blocks = version_compare( $wp_version, '5', '>=' ) ? parse_blocks( $content ) : gutenberg_parse_blocks( $content ); we get --> https://share.getcloudapp.com/d5u1BYZm

2021-03-24 11:42 UTC, vrundakansara requested changes

2021-03-24 11:42 UTC, vrundakansara commented on classes/class-uagb-block-helper.php
> +			$content = get_post_field( 'post_content' );
Let's remove it @supriyajjadhav

2021-03-24 12:04 UTC, vrundakansara approved these changes

2021-03-24 12:05 UTC, merged