Fix: Advanced columns - Column not stacking on tablet & mobile devices.
brainstormforce/ultimate-addons-for-gutenberg pull request #537
Opened 2021-03-31 13:34 UTC by AbhijitNage123

### Description

Trello - https://trello.com/c/a0Bsp9IW/255-fix-advanced-columns-column-not-stacking-on-tablet-mobile-devices

### Screenshots

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

### How has this been tested?

- Drag and drop advanced column with 2 child with 50% width.
- Select option stack on > tablet and check is stacking on tablet and mobile both.
- Select option stack on > mobile. It should stack on mobile devices only.
- Select option stack on > none.  It should not stack on tablet & mobile devices.  

### Checklist:
- [x] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [x] I've included any necessary tests 
- [ ] I've included developer documentation 
- [x] I've added proper labels to this pull request

2021-04-01 11:15 UTC, RajkiranBagal requested changes

2021-04-01 11:15 UTC, RajkiranBagal commented on src/blocks/columns/edit.js
> +							label={ __( "Reverse Columns (Mobile only)", 'ultimate-addons-for-gutenberg' ) }
Remove only from here.

2021-04-01 11:17 UTC, RajkiranBagal requested changes

2021-04-01 11:17 UTC, RajkiranBagal commented on readme.txt
> +* Fix: Advanced Column - Column not stacking on tablet & mobile devices.
Rename `Advanced Column` to `Advanced Columns`

2021-04-01 11:27 UTC, AbhijitNage123 commented on readme.txt
> +* Fix: Advanced Column - Column not stacking on tablet & mobile devices.
Done

2021-04-01 11:27 UTC, AbhijitNage123 commented on src/blocks/columns/edit.js
> +							label={ __( "Reverse Columns (Mobile only)", 'ultimate-addons-for-gutenberg' ) }
Done

2021-04-01 12:12 UTC, RajkiranBagal requested changes

2021-04-01 12:12 UTC, RajkiranBagal commented on src/blocks/columns/edit.js
> +								{ value: "mobile", label: __( "Mobile only", 'ultimate-addons-for-gutenberg' ) },
Remove only from here.

2021-04-01 12:24 UTC, RajkiranBagal approved these changes

2021-04-07 04:53 UTC, sandeshjangam approved these changes

2021-04-07 04:54 UTC, merged