Improvement: Added filter for entry-content in Table of content block.
brainstormforce/ultimate-addons-for-gutenberg pull request #539
Opened 2021-04-02 10:29 UTC by AbhijitNage123

### Description

Trello - https://trello.com/c/VPDmEv35/253-table-of-contents-conflict-with-mediavine-ad-script

```
function toc_entry_content_function() {

	return true;

}

add_action( "uagb_toc__entry_content_wrap", 'toc_entry_content_function', 10, 2 );
```

### Screenshots

### Types of changes

- Non breaking change. 

### How has this been tested?

- Add filter return false and check this `uag-toc__entry-content` class is removed from the content or not.

### Checklist:
- [x] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [x] I've included any necessary tests 
- [ ] I've included developer documentation 
- [x] I've added proper labels to this pull request

2021-04-02 12:47 UTC, vrundakansara requested changes

2021-04-02 12:47 UTC, vrundakansara commented on classes/class-uagb-helper.php
> +				if ( true === self::$table_of_contents_flag ) {
Combine these 2 ifs - 
```php
if ( true === $toc_wrap && true === self::$table_of_contents_flag ) {
```

2021-04-02 13:30 UTC, AbhijitNage123 commented on classes/class-uagb-helper.php
> +				if ( true === self::$table_of_contents_flag ) {
Updated

2021-04-05 11:51 UTC, RajkiranBagal approved these changes

2021-04-07 05:01 UTC, sandeshjangam approved these changes

2021-04-09 11:47 UTC, sandeshjangam requested changes
src/blocks/ratings/edit.js

Why this empty file?

2021-04-09 11:54 UTC, sandeshjangam approved these changes

2021-04-09 11:57 UTC, merged