Fix : Tabs block issues
brainstormforce/ultimate-addons-for-gutenberg pull request #540
Opened 2021-04-02 11:58 UTC by supriyajjadhav

### Description
- Add alignment to tab header in horizontal styles
- Drop Tabs on page > By default paragraph is open in settings panel - [rec](https://vimeo.com/514253325)

### Types of changes

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2021-04-16 09:28 UTC, RajkiranBagal requested changes

2021-04-16 09:28 UTC, RajkiranBagal commented on assets/js/tabs.js
> +function Check(){
Add more descriptive function names. Also the function names should be in `camelCase`

2021-04-16 09:28 UTC, RajkiranBagal commented on assets/js/tabs.js
> +function Click(e , tabName , list , count){
Add more descriptive function names. Also the function names should be in camelCase

2021-04-16 09:28 UTC, RajkiranBagal commented on assets/js/tabs.js
> +    var old_active = panel.querySelector( '.uagb-tabs__active' );
Variable names should be `camelCase`. Check all in the File

2021-04-16 09:28 UTC, RajkiranBagal commented on assets/js/tabs.js
> +		if ( ( window.location.hash + '.uagb-tab' ).length ) {
Sanitize the hash before using it for security reasons.

2021-04-16 09:28 UTC, RajkiranBagal commented on src/blocks/tabs/editor.scss
> +    .uagb-tab-item__move-back{
Combine the CSS:

`.uagb-tab-item__move-forward,
 .uagb-tab-item__move-back {
        color: #fff;
        cursor: pointer;
        z-index: 1;
    }`

2021-04-16 13:41 UTC, supriyajjadhav commented on src/blocks/tabs/editor.scss
> +    .uagb-tab-item__move-back{
Updated css

2021-04-16 13:42 UTC, supriyajjadhav commented on assets/js/tabs.js
> +		if ( ( window.location.hash + '.uagb-tab' ).length ) {
Added reg exp to check URL hash /^#uagb-tabs__tab\d$/.test(window.location.hash)

2021-04-16 13:43 UTC, supriyajjadhav commented on assets/js/tabs.js
> +    var old_active = panel.querySelector( '.uagb-tabs__active' );
Added proper names to the variables

2021-04-16 13:43 UTC, supriyajjadhav commented on assets/js/tabs.js
> +function Click(e , tabName , list , count){
Added proper names to the functions in camelcase

2021-04-16 13:43 UTC, supriyajjadhav commented on assets/js/tabs.js
> +function Check(){
Added proper names to the functions in camelCase

2021-04-19 05:58 UTC, RajkiranBagal requested changes

2021-04-19 05:58 UTC, RajkiranBagal commented on assets/js/tabs.js
> +		if ( /^#uagb-tabs__tab\d$/.test(window.location.hash)) {
We can combine these 2 if statements

2021-04-19 08:14 UTC, RajkiranBagal commented on assets/js/tabs.js
> +		if ( /^#uagb-tabs__tab\d$/.test(window.location.hash)) {
Done

2021-04-21 11:31 UTC, sandeshjangam commented on src/blocks/tabs-child/edit.js
> +				) }aria-labelledby={`uagb-tabs__tab${id}`}>
Do we need space here before `aria-labelledby`?

2021-04-21 12:29 UTC, RajkiranBagal requested changes

2021-04-21 12:29 UTC, RajkiranBagal commented on src/blocks/tabs-child/edit.js
> +			<div className={`uagb-tabs__body-container uagb-tabs__inner-tab uagb-inner-tab-${id}`} style={{ display: id === tabActive ? 'block' : 'none'}}>
Instead of adding extra `div` Can we add the required class to the current div ?

2021-04-21 12:29 UTC, RajkiranBagal commented on src/blocks/tabs/style.scss
> +        min-width: 24%;
Can we combine all the 
`min-width: 24%;
  max-width: 24%;` CSS?

2021-04-21 12:29 UTC, RajkiranBagal commented on src/blocks/tabs/style.scss
> +.uagb-tabs__wrap.uagb-active-tab-9 > .uagb-tabs__body-wrap > .uagb-inner-tab-9 ,
Do all these have a common class to apply the CSS? Instead of adding these many selectors?

2021-04-21 12:36 UTC, supriyajjadhav commented on src/blocks/tabs-child/edit.js
> +			<div className={`uagb-tabs__body-container uagb-tabs__inner-tab uagb-inner-tab-${id}`} style={{ display: id === tabActive ? 'block' : 'none'}}>
In the previous version, we haven't mentioned this div. This div is added to match the edit.js and save.js return statements

2021-04-21 12:47 UTC, sandeshjangam approved these changes

2021-04-21 12:48 UTC, supriyajjadhav commented on src/blocks/tabs/style.scss
> +.uagb-tabs__wrap.uagb-active-tab-9 > .uagb-tabs__body-wrap > .uagb-inner-tab-9 ,
No, We have different classes to apply the CSS

2021-04-21 12:48 UTC, RajkiranBagal approved these changes
@supriyajjadhav Let's do the suggested optimizations in next-release. Approving PR for now.

2021-04-21 12:51 UTC, merged

2021-04-21 12:56 UTC, supriyajjadhav commented on src/blocks/tabs/style.scss
> +        min-width: 24%;
yes, we can.