Fix: Table of content - Showing default heading instead of old/previous one.
brainstormforce/ultimate-addons-for-gutenberg pull request #541
Opened 2021-04-02 13:22 UTC by AbhijitNage123

### Description

- Trello - https://trello.com/c/MRVUQh8u/258-fix-table-of-content-validation-issue-in-console

### Screenshots

### Types of changes

- Bug fix (breaking change which fixes an issue)

### How has this been tested?

- Create TOC in V1.21.1
-  Switch to Master it through block validation error.
- Switch to `toc-block-validation-issue` issue resolved.

### Checklist:
- [x] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [x] I've included any necessary tests 
- [ ] I've included developer documentation 
- [x] I've added proper labels to this pull request

2021-04-05 11:45 UTC, RajkiranBagal requested changes

2021-04-05 11:45 UTC, RajkiranBagal commented on readme.txt
> +* Fix: Table of Contents: showing default title instead of old one.
Replace with. : `Fix: Table of Contents: Showing default title instead of saved one.`

2021-04-05 11:45 UTC, RajkiranBagal commented on src/blocks/table-of-contents/edit.js
> +			this.props.setAttributes( { headingTitle: this.props.attributes.heading } )
Do the condition check empty too? Please confirm.

2021-04-05 12:26 UTC, AbhijitNage123 commented on readme.txt
> +* Fix: Table of Contents: showing default title instead of old one.
Resolved

2021-04-05 12:27 UTC, AbhijitNage123 commented on src/blocks/table-of-contents/edit.js
> +			this.props.setAttributes( { headingTitle: this.props.attributes.heading } )
No need to check empty here

2021-04-05 13:01 UTC, RajkiranBagal approved these changes

2021-04-07 04:56 UTC, sandeshjangam approved these changes

2021-04-07 06:19 UTC, sandeshjangam approved these changes

2021-04-07 06:19 UTC, merged