new: Build plugin functionality
brainstormforce/ultimate-addons-for-gutenberg pull request #557
Opened 2021-04-12 07:57 UTC by rohitp-bsf

### Description
- Added new build package and removed unwanted packages.

### Screenshots
- NA

### Types of changes
- Changes in package.json

### How has this been tested?
- NA

### Checklist:
- [ ] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2021-04-22 13:06 UTC, Nikschavan requested changes

2021-04-22 13:06 UTC, Nikschavan commented on package.json
> +    "sass-loader": "^6.0.6",
Things like `eslint`, `eslint-plugins`, `sass-loader` are added to dependencies instead of devDependencies, do move them to appropriate places.

2021-04-22 13:06 UTC, Nikschavan commented on package.json
> +    "eslint-plugin-react": "^7.5.1",
I am thinking `eslint` and all the other eslint-plugins that we are importing should already be imported with `@wordpress/scripts` - do check and remove all extra dependencies.

2021-04-22 13:06 UTC, Nikschavan commented on .eslintrc.js
> +	"extends": [
Thinking more of it - I believe `@wordpress/scripts` configuration should be good for us and should not require any custom configurations - unless we are doing something that the default config does not provide?

2021-04-22 13:06 UTC, Nikschavan commented on languages/my-plugin.pot
> +# Copyright (C) 2021 Brainstorm Force
Not sure if this file should be present?

2021-04-22 13:06 UTC, Nikschavan commented on webpack.config.js
> +module.exports = {
Why do we need a custom configuration? AFAIK `wp-scripts build` should be able to build all the files.

2021-04-26 05:47 UTC, rohitp-bsf commented on webpack.config.js
> +module.exports = {
Yes, wp-scripts build itself building on basis of `main` entry file, but in our case for the optimization purpose, we also need to prepare the build for all SCSS files individually.

2021-04-26 05:51 UTC, Nikschavan commented on webpack.config.js
> +module.exports = {
Right makes sense 👍

2021-04-26 05:55 UTC, rohitp-bsf commented on package.json
> +    "sass-loader": "^6.0.6",
Done!

2021-04-26 05:55 UTC, rohitp-bsf commented on package.json
> +    "eslint-plugin-react": "^7.5.1",
Yes, Removed!

2021-04-26 05:55 UTC, rohitp-bsf commented on .eslintrc.js
> +	"extends": [
Updated!

2021-04-27 12:56 UTC, rohitp-bsf commented on languages/my-plugin.pot
> +# Copyright (C) 2021 Brainstorm Force
Removed!

2021-04-28 07:50 UTC, sandeshjangam approved these changes

2021-04-28 07:51 UTC, sandeshjangam commented on dist/build/blocks.asset.php
> +<?php return array('dependencies' => array('react', 'react-dom', 'wp-element', 'wp-i18n', 'wp-polyfill'), 'version' => '3f51746b98b1dc07f0765274a98bb126');
It is in a plan. Will be doing it soon.

2021-04-28 07:52 UTC, merged