Improvement: Added heading tag in Taxonomy list block
brainstormforce/ultimate-addons-for-gutenberg pull request #569
Opened 2021-04-16 04:23 UTC by supriyajjadhav

[Trello](https://trello.com/c/7uiOsp6P/208-improvement-taxonomy-list-html-tag-option-for-title)

### Description
Added heading tag features for the title.

### Types of changes
- Added titleTag 

### How has this been tested?
Checked whether it is working properly or not on front-end and back-end.

### Checklist:
- [x] My code is tested
- [x] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [] I've included any necessary tests 
- [x] I've included developer documentation 
- [x] I've added proper labels to this pull request

2021-04-16 09:34 UTC, RajkiranBagal requested changes

2021-04-16 09:34 UTC, RajkiranBagal commented on dist/blocks/taxonomy-list/class-uagb-taxonomy-list.php
> +								<<?php echo esc_html( $titleTag ); ?> class="uagb-tax-link-wrap">
Please check Backward compatibility of Changing a div to `h` Tag

2021-04-16 09:34 UTC, RajkiranBagal commented
@supriyajjadhav Resolve conflicts.

2021-04-16 14:04 UTC, supriyajjadhav commented on dist/blocks/taxonomy-list/class-uagb-taxonomy-list.php
> +								<<?php echo esc_html( $titleTag ); ?> class="uagb-tax-link-wrap">
Checked Backward compatibility,  no issues were found. 
Also added a div tag in the list of titleTag

2021-04-19 05:36 UTC, RajkiranBagal approved these changes

2021-04-19 13:15 UTC, RajkiranBagal commented on dist/blocks/taxonomy-list/class-uagb-taxonomy-list.php
> +								<<?php echo esc_html( $titleTag ); ?> class="uagb-tax-link-wrap">
@akshaylakh Tested this & found an issue with Backward compatibility which was a simple case.

2021-04-20 07:56 UTC, sandeshjangam approved these changes

2021-04-20 09:01 UTC, sandeshjangam approved these changes

2021-04-20 09:01 UTC, merged