Fix: Social Share - Fixed jQuery undefined issue.
brainstormforce/ultimate-addons-for-gutenberg pull request #571
Opened 2021-04-19 06:56 UTC by AbhijitNage123

### Description

Trello - https://trello.com/c/VKry98uR/281-fix-social-share-fixed-jquery-undefind-issue

### Screenshots

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

### How has this been tested?

- Activate social share block and drag and drop on pages.
- Check out the console log for error
- Drag and drop TOC, Inline notice, Forms, Blockquote, Lottie and check everything is working fine on the frontend. No issue in the console.

### Checklist:
- [x] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [x] I've included any necessary tests 
- [ ] I've included developer documentation 
- [x] I've added proper labels to this pull request

2021-04-19 07:59 UTC, RajkiranBagal requested changes

2021-04-19 07:59 UTC, RajkiranBagal commented on classes/class-uagb-helper.php
> +				self::$script = 'document.addEventListener("DOMContentLoaded", () => { ' . self::$script . ' })';
Only remove the jQuery function here.

2021-04-19 07:59 UTC, RajkiranBagal commented on README.md
> +* Fix: Social Share - Fixed jquery undefind issue.
Always check the changelog once before updating. - `jquery => jQuery` & `undefind` => `undefined`.

Update changelog to:
`Fix: Social Share - Fixed the jQuery undefined error.`

2021-04-19 08:40 UTC, AbhijitNage123 commented on classes/class-uagb-helper.php
> +				self::$script = 'document.addEventListener("DOMContentLoaded", () => { ' . self::$script . ' })';
Updated

2021-04-19 08:40 UTC, AbhijitNage123 commented on README.md
> +* Fix: Social Share - Fixed jquery undefind issue.
Done

2021-04-19 08:57 UTC, RajkiranBagal approved these changes

2021-04-20 09:54 UTC, RajkiranBagal approved these changes

2021-04-20 12:16 UTC, sandeshjangam approved these changes

2021-04-20 12:16 UTC, merged