Fix: Multi button - Throwing an error when deactivate all the UAG blocks except the `Multi Buttons`.
brainstormforce/ultimate-addons-for-gutenberg pull request #577
Opened 2021-04-21 10:02 UTC by AbhijitNage123

### Description

Trello - https://trello.com/c/npBgSX79/288-fix-multi-button-throwing-an-error-when-deactivate-all-the-uag-blocks-except-the-multi-buttons

### Screenshots

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

### How has this been tested?

- Deactivate all blocks except multi buttons.
- Create a new page an drag and drop multi-button on page. It throws an error.
- Switch to `multi-button-is-child-issue` and drag and drop block again and check.

### Checklist:
- [x] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [x] I've included any necessary tests 
- [ ] I've included developer documentation 
- [x] I've added proper labels to this pull request

2021-04-21 11:23 UTC, RajkiranBagal commented
@AbhijitNage123 Setting Info- Box & Button as a child will cause issues to block deactivation & may break user's site. Please chec.

2021-05-13 09:33 UTC, RajkiranBagal requested changes

2021-05-13 09:33 UTC, RajkiranBagal commented on admin/assets/admin-menu-settings.js
> +				var infoBox = list.querySelector('#info-box');
@AbhijitNage123 There is no need to implementing this logic through JS. We can easily do it from ajax php function by just updating the array. Call me if needed.

2021-05-13 09:33 UTC, RajkiranBagal commented on admin/assets/admin-menu-settings.js
> +				var howTo = list.querySelector('#how-to');
Same as above

2021-05-14 08:59 UTC, supriyajjadhav commented on admin/assets/admin-menu-settings.js
> +				var infoBox = list.querySelector('#info-box');
@RajkiranBagal Updated the logic please check

2021-05-14 09:08 UTC, RajkiranBagal requested changes

2021-05-14 09:08 UTC, RajkiranBagal commented on classes/class-uagb-admin.php
> +					if ( 'info-box' === $slug && 'info-box' !== $value ) {
Instead of the foreach we can simply write this:

```suggestion
					if ( 'how-to' === $block_id && 'disabled' === $blocks[ 'info-box' ] ) {
					      $blocks[ 'info-box' ] = 'info-box' ;
					}
```

2021-05-14 09:08 UTC, RajkiranBagal commented on classes/class-uagb-admin.php
> +			if ( 'info-box' === $block_id ) {
Same as above

2021-05-14 09:44 UTC, supriyajjadhav commented on classes/class-uagb-admin.php
> +					if ( 'info-box' === $slug && 'info-box' !== $value ) {
Right! Removed foreach

2021-05-14 10:30 UTC, RajkiranBagal requested changes

2021-05-14 10:30 UTC, RajkiranBagal commented on classes/class-uagb-admin.php
> +			if ( 'info-box' === $block_id ) {
Combine these 2 if statements

2021-05-14 10:30 UTC, RajkiranBagal commented on classes/class-uagb-admin.php
> +			if ( 'how-to' === $block_id ) {
Combine these 2 if statements

2021-05-14 10:48 UTC, supriyajjadhav commented on classes/class-uagb-admin.php
> +			if ( 'how-to' === $block_id ) {
Done

2021-05-14 11:30 UTC, RajkiranBagal approved these changes

2021-05-14 12:41 UTC, sandeshjangam approved these changes

2021-05-14 12:42 UTC, merged