Fix the issue of toc JS minification.
brainstormforce/ultimate-addons-for-gutenberg pull request #598
Opened 2021-04-28 05:09 UTC by AbhijitNage123

### Description

- Fix the issue of toc JS minification.

### Screenshots

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

### How has this been tested?

### Checklist:
- [x] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [x] I've included any necessary tests 
- [ ] I've included developer documentation 
- [x] I've added proper labels to this pull request

2021-04-28 07:40 UTC, RajkiranBagal requested changes

2021-04-28 07:40 UTC, RajkiranBagal commented on assets/js/table-of-contents.js
> +				scroll = node.data( 'scroll' );
Here if you want to add `;` the var should be there for all the variables

2021-04-28 07:40 UTC, RajkiranBagal commented on readme.txt
> +* Fix: Table of Contents - Not allowed HTML tags in title and Js minification issue.
Change `Js` to `JS`

2021-04-28 07:50 UTC, AbhijitNage123 commented on assets/js/table-of-contents.js
> +				scroll = node.data( 'scroll' );
`var` is already added above here - https://github.com/brainstormforce/ultimate-addons-for-gutenberg/blob/Added-semicolon-to-toc-js/assets/js/table-of-contents.js#L3

2021-04-28 07:53 UTC, AbhijitNage123 commented on readme.txt
> +* Fix: Table of Contents - Not allowed HTML tags in title and Js minification issue.
Done

2021-04-28 08:45 UTC, RajkiranBagal approved these changes

2021-04-30 11:43 UTC, sandeshjangam approved these changes

2021-05-06 11:04 UTC, merged