Fix: Inline notice and review schema block UI broken if Gutenberg plugin is activated
brainstormforce/ultimate-addons-for-gutenberg pull request #617
Opened 2021-04-29 14:34 UTC by AbhijitNage123

### Description

Trello - https://trello.com/c/Qi4l2oJ8/292-fix-inline-notice-and-review-schema-block-ui-broken-if-gutenberg-plugin-is-activated

### Screenshots

### Types of changes

### How has this been tested?

1. Activate Gutenberg plugin
2. Add review schema and review schema block in the editor
- First test case - https://share.getcloudapp.com/yAuD94Pm
- Second Test case - https://share.getcloudapp.com/wbuwLkN0

### Checklist:
- [x] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [x] I've included any necessary tests 
- [ ] I've included developer documentation 
- [x] I've added proper labels to this pull request

2021-05-05 11:22 UTC, RajkiranBagal requested changes

2021-05-05 11:22 UTC, RajkiranBagal commented on readme.txt
> +* Fix: Inline notice and review schema block UI broken if gutenberg plugin is activated.
Capitalize Block names, Gutenberg plugin name.

2021-05-05 11:47 UTC, AbhijitNage123 commented on readme.txt
> +* Fix: Inline notice and review schema block UI broken if gutenberg plugin is activated.
Done

2021-05-05 11:47 UTC, RajkiranBagal approved these changes

2021-05-06 06:29 UTC, sandeshjangam approved these changes

2021-05-06 06:31 UTC, merged