refactor: Advanced columns.
brainstormforce/ultimate-addons-for-gutenberg pull request #619
Opened 2021-04-30 09:50 UTC by RajkiranBagal

### Description
 - Trello task - https://trello.com/c/mSbMJ7X5/144-uag-block-wise-cleanup

### Types of changes
Breaking change

### How has this been tested?
 - Check Trello Card.

### Checklist:
- [x] My code is tested
- [x] I've included any necessary tests 
- [x] I've added proper labels to this pull request

2021-05-03 03:33 UTC, rohitp-bsf requested changes

2021-05-03 03:33 UTC, rohitp-bsf commented on src/blocks/column/edit.js
> +			{ columnSettings( props ) }
Use common naming, `Settings` and `Render`.

2021-05-03 03:33 UTC, rohitp-bsf commented on src/blocks/column/edit.js
> +			{ columnSettings( props ) }
Use JSX way to call the function like <Settings />

Use React.memo to reduce extra calls.

2021-05-03 03:33 UTC, rohitp-bsf commented on src/blocks/column/inline-styles.js
> +	if ( 'image' === backgroundType ) {
Use Switch here!

2021-05-03 03:33 UTC, rohitp-bsf commented on src/blocks/columns/styling.js
> +	if ( 'video' == backgroundType ) {
Use Switch here!

2021-05-03 03:33 UTC, rohitp-bsf commented on src/blocks/columns/save.js
> +	const top_divider_html = topType != 'none' && (
Use CamelCasing everywhere for consistency.

2021-05-03 03:33 UTC, rohitp-bsf commented on src/blocks/columns/render.js
> +const getColumnsTemplate = memoize( ( columns ) => {
Use React way to memorize instead of another dependency. You can use `useMemo` or `useCallback` as per the requirement. And remove memorize from the package as well.

2021-05-13 08:04 UTC, RajkiranBagal commented on src/blocks/column/inline-styles.js
> +	if ( 'image' === backgroundType ) {
Done.

2021-05-13 08:04 UTC, RajkiranBagal commented on src/blocks/columns/styling.js
> +	if ( 'video' == backgroundType ) {
Done.

2021-05-13 08:04 UTC, RajkiranBagal commented on src/blocks/columns/save.js
> +	const top_divider_html = topType != 'none' && (
Done.

2021-05-13 09:08 UTC, RajkiranBagal commented on src/blocks/columns/render.js
> +const getColumnsTemplate = memoize( ( columns ) => {
Done.

2021-05-13 09:18 UTC, rohitp-bsf requested changes

2021-05-13 09:18 UTC, rohitp-bsf commented on src/blocks/column/settings.js
> +import GradientSettings from '../../components/gradient-settings';
Please add this in lazy and add the entire render inside suspense.

2021-05-13 09:18 UTC, rohitp-bsf commented on src/blocks/columns/edit.js
> +		<>
Removed this extra `<>`

2021-05-13 09:26 UTC, rohitp-bsf requested changes

2021-05-13 09:26 UTC, rohitp-bsf commented on src/blocks/columns/style.scss
> +	 position: relative;
Duplicate position, remove it!

2021-05-14 04:05 UTC, RajkiranBagal commented on src/blocks/column/settings.js
> +import GradientSettings from '../../components/gradient-settings';
Done

2021-05-14 04:05 UTC, RajkiranBagal commented on src/blocks/columns/edit.js
> +		<>
Done

2021-05-14 04:05 UTC, RajkiranBagal commented on src/blocks/columns/style.scss
> +	 position: relative;
Done

2021-05-14 06:09 UTC, rohitp-bsf approved these changes

2021-05-14 06:16 UTC, sandeshjangam commented on src/blocks/column/inline-styles.js
> + import generateCSSUnit from "@Controls/generateCSSUnit"
Unnecessary space. Can we fix it in any automation?

2021-05-14 06:17 UTC, sandeshjangam commented on src/blocks/column/settings.js
> +	import( /* webpackChunkName: "chunks/column/gradient-settings" */ '../../components/gradient-settings' )
@Components Alise changes.

2021-05-14 06:19 UTC, sandeshjangam commented on src/blocks/column/settings.js
> +const { __ } = wp.i18n;
Use package for
import { __ } from '@wordpress/i18n';

2021-05-14 06:21 UTC, sandeshjangam commented on src/blocks/columns/block.js
> +const { __ } = wp.i18n;
import { __ } from '@wordpress/i18n';

2021-05-14 06:25 UTC, sandeshjangam requested changes
Need changes

2021-05-14 08:09 UTC, rohitp-bsf commented on src/blocks/column/settings.js
> +	import( /* webpackChunkName: "chunks/column/gradient-settings" */ '../../components/gradient-settings' )
Please pull `refactor-uag`

2021-05-19 09:36 UTC, RajkiranBagal commented on src/blocks/column/settings.js
> +const { __ } = wp.i18n;
Done

2021-05-19 09:36 UTC, RajkiranBagal commented on src/blocks/columns/block.js
> +const { __ } = wp.i18n;
Done

2021-05-19 09:39 UTC, RajkiranBagal commented on src/blocks/column/settings.js
> +	import( /* webpackChunkName: "chunks/column/gradient-settings" */ '../../components/gradient-settings' )
Done

2021-05-25 10:17 UTC, sandeshjangam commented on src/blocks/column/settings.js
> +} = wp.blockEditor;
Use package

2021-05-25 10:17 UTC, sandeshjangam commented on src/blocks/column/settings.js
> +} = wp.components;
Use package

2021-05-25 10:19 UTC, sandeshjangam commented on src/blocks/columns/settings.js
> +} = wp.blockEditor;
Use package

2021-05-25 10:19 UTC, sandeshjangam commented on src/blocks/columns/settings.js
> +} = wp.components;
Use package

2021-05-25 10:25 UTC, RajkiranBagal commented on src/blocks/columns/settings.js
> +} = wp.components;
Done

2021-05-25 10:25 UTC, RajkiranBagal commented on src/blocks/columns/settings.js
> +} = wp.blockEditor;
Done

2021-05-25 10:25 UTC, RajkiranBagal commented on src/blocks/column/settings.js
> +} = wp.components;
Done

2021-05-25 10:25 UTC, RajkiranBagal commented on src/blocks/column/settings.js
> +} = wp.blockEditor;
Done

2021-05-25 10:30 UTC, sandeshjangam approved these changes

2021-05-27 03:51 UTC, merged