refactor: Social Share.
brainstormforce/ultimate-addons-for-gutenberg pull request #622
Opened 2021-04-30 10:47 UTC by RajkiranBagal

### Description
 - Trello task - https://trello.com/c/mSbMJ7X5/144-uag-block-wise-cleanup

### Types of changes
Breaking change

### How has this been tested?
 - Check Trello Card.

### Checklist:
- [x] My code is tested
- [x] I've included any necessary tests 
- [x] I've added proper labels to this pull request 
### Description
 - Trello task - https://trello.com/c/mSbMJ7X5/144-uag-block-wise-cleanup

### Types of changes
Breaking change

### How has this been tested?
 - Check Trello Card.

### Checklist:
- [x] My code is tested
- [x] I've included any necessary tests 
- [x] I've added proper labels to this pull request

2021-05-24 13:55 UTC, rohitp-bsf requested changes

2021-05-24 13:55 UTC, rohitp-bsf commented on src/blocks/social-share/render.js
> +import times from 'lodash/times';
Remove this dependency and use alternative.

2021-05-24 13:55 UTC, rohitp-bsf commented on src/blocks/social-share/render.js
> +import memoize from 'memize';
Remove this dependency and use an alternative.

2021-05-28 06:09 UTC, sandeshjangam approved these changes

2021-05-28 06:35 UTC, rohitp-bsf approved these changes

2021-06-03 06:24 UTC, merged