UAG Cleanup - Advanced Heading Block.
brainstormforce/ultimate-addons-for-gutenberg pull request #623
Opened 2021-04-30 12:04 UTC by supriyajjadhav

### Description
Trello task - https://trello.com/c/mSbMJ7X5/144-uag-block-wise-cleanup

### Types of changes
Breaking change

### Checklist:
- [x] My code is tested
- [x] I've included any necessary tests 
- [x] I've added proper labels to this pull request

2021-04-30 12:13 UTC, RajkiranBagal approved these changes

2021-04-30 12:43 UTC, RajkiranBagal commented
Let's keep PR titles consistent like: 

`refactor: Block Name`

2021-05-14 05:47 UTC, rohitp-bsf requested changes

2021-05-14 05:47 UTC, rohitp-bsf commented on src/blocks/advanced-heading/render.js
> +			{ heading_html }
Maintain camel casing for variables and functions.

2021-05-14 06:05 UTC, sandeshjangam commented on src/blocks/advanced-heading/settings.js
> +		/* webpackChunkName: "chunks/advanced-heading/typography-control" */ '../../components/typography'
Creat an alise for components like @Components

2021-05-14 06:07 UTC, sandeshjangam requested changes
Need changes

2021-05-14 08:10 UTC, rohitp-bsf commented on src/blocks/advanced-heading/settings.js
> +		/* webpackChunkName: "chunks/advanced-heading/typography-control" */ '../../components/typography'
Please pull `refactor-uag`

2021-05-17 04:00 UTC, supriyajjadhav commented on src/blocks/advanced-heading/render.js
> +			{ heading_html }
Updated all the variable names and function names

2021-05-17 05:13 UTC, supriyajjadhav commented on src/blocks/advanced-heading/settings.js
> +		/* webpackChunkName: "chunks/advanced-heading/typography-control" */ '../../components/typography'
Updated in all the files

2021-05-25 06:22 UTC, rohitp-bsf approved these changes

2021-05-25 11:38 UTC, merged