Final blockquote
brainstormforce/ultimate-addons-for-gutenberg pull request #624
Opened 2021-04-30 12:28 UTC by rohitp-bsf

### Description
- refactor: updated blockquite module.

### Screenshots
- NA

### Types of changes
- Refactored Class components to Functional components.
- Refactored the SCSS files.
- Refactored the import statement.

### How has this been tested?
- NA

### Checklist:
- [ ] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2021-04-30 12:42 UTC, RajkiranBagal requested changes

2021-04-30 12:42 UTC, RajkiranBagal commented on src/blocks/blockquote/components/AuthorText.js
> +const { __ } = wp.i18n;
Replace with `import { __ } from '@wordpress/i18n';`

2021-04-30 12:42 UTC, RajkiranBagal commented on src/blocks/blockquote/components/Description.js
> +const { __ } = wp.i18n;
Replace with import { __ } from '@wordpress/i18n';

2021-04-30 12:42 UTC, RajkiranBagal commented on src/blocks/blockquote/components/TweetButton.js
> +			<Fragment>
We can eliminate Fragment from everywhere.

2021-04-30 12:42 UTC, RajkiranBagal commented on src/blocks/blockquote/components/TweetButtonCTA.js
> +const { Fragment } = wp.element;
We can eliminate Fragment

2021-04-30 12:43 UTC, RajkiranBagal commented
Let's keep PR titles consistent like: 

`refactor: Block Name`

2021-04-30 12:59 UTC, rohitp-bsf commented on src/blocks/blockquote/components/AuthorText.js
> +const { __ } = wp.i18n;
Done 👍

2021-04-30 13:00 UTC, rohitp-bsf commented on src/blocks/blockquote/components/Description.js
> +const { __ } = wp.i18n;
Done 👍

2021-04-30 13:00 UTC, rohitp-bsf commented on src/blocks/blockquote/components/TweetButton.js
> +			<Fragment>
Done 👍

2021-04-30 13:00 UTC, rohitp-bsf commented on src/blocks/blockquote/edit.js
> +const { __ } = wp.i18n;
Done 👍

2021-05-03 03:19 UTC, rohitp-bsf commented on src/blocks/blockquote/edit.js
> +			</BlockControls>
Done 👍

2021-05-03 03:19 UTC, rohitp-bsf commented on src/blocks/blockquote/edit.js
> +						skinStyle !== 'border'
Done 👍

2021-05-03 03:20 UTC, rohitp-bsf commented
> Let's keep PR titles consistent like:
> 
> `refactor: Block Name`

Yup, Sure! Updated the PR title.

2021-05-03 14:47 UTC, supriyajjadhav approved these changes

2021-05-14 09:28 UTC, RajkiranBagal requested changes

2021-05-14 09:28 UTC, RajkiranBagal commented on src/blocks/blockquote/components/AuthorImage.js
> +		url_chk = attributes.authorImage.url;
User camelCase variable names.

2021-05-14 09:28 UTC, RajkiranBagal commented on src/blocks/blockquote/edit.js
> +		<>
Remove extra `<>`

2021-05-14 09:28 UTC, RajkiranBagal commented on src/blocks/blockquote/settings.js
> +	let image_name = __( 'Select Image', 'ultimate-addons-for-gutenberg' );
User camelCase variable names

2021-05-14 09:28 UTC, RajkiranBagal commented on src/blocks/blockquote/styling.js
> +	const tablet_selectors = {
User camelCase variable names throughout the file.

2021-05-14 09:53 UTC, rohitp-bsf commented on src/blocks/blockquote/styling.js
> +	const tablet_selectors = {
Done!

2021-05-14 09:53 UTC, rohitp-bsf commented on src/blocks/blockquote/settings.js
> +	let image_name = __( 'Select Image', 'ultimate-addons-for-gutenberg' );
Done!

2021-05-14 09:53 UTC, rohitp-bsf commented on src/blocks/blockquote/edit.js
> +		<>
Done!

2021-05-14 09:53 UTC, rohitp-bsf commented on src/blocks/blockquote/components/AuthorImage.js
> +		url_chk = attributes.authorImage.url;
Done!

2021-05-25 04:05 UTC, sandeshjangam approved these changes

2021-05-25 04:11 UTC, RajkiranBagal approved these changes

2021-05-25 09:05 UTC, merged