Refactor : Marketing Button
brainstormforce/ultimate-addons-for-gutenberg pull request #627
Opened 2021-04-30 13:43 UTC by supriyajjadhav

### Description
Trello task - https://trello.com/c/mSbMJ7X5/144-uag-block-wise-cleanup

### Types of changes
Breaking change

### Checklist:
- [x] My code is tested
- [x] I've included any necessary tests 
- [x] I've added proper labels to this pull request

2021-05-03 03:40 UTC, rohitp-bsf requested changes

2021-05-03 03:40 UTC, rohitp-bsf commented on src/blocks/marketing-button/edit.js
> +			{ MarketingButtonSettings( props ) }
Use JSX way to call the function like `<Settings />`

Use React.memo to reduce extra calls.

2021-05-03 03:40 UTC, rohitp-bsf commented on src/blocks/marketing-button/edit.js
> +			{ MarketingButtonSettings( props ) }
Use common naming, `Settings` and `Render`.

2021-05-03 03:40 UTC, rohitp-bsf commented on src/blocks/marketing-button/styling.js
> +	let tablet_selectors = {};
Use CamelCasing everywhere for consistency.

2021-05-17 08:18 UTC, supriyajjadhav commented on src/blocks/marketing-button/styling.js
> +	let tablet_selectors = {};
Updated all the variables

2021-05-17 08:19 UTC, supriyajjadhav commented on src/blocks/marketing-button/edit.js
> +			{ MarketingButtonSettings( props ) }
Updated

2021-05-25 08:51 UTC, rohitp-bsf requested changes

2021-05-25 08:51 UTC, rohitp-bsf commented on src/blocks/marketing-button/styling.js
> +	return styling_css;
Camel case please!

2021-05-25 08:57 UTC, supriyajjadhav commented on src/blocks/marketing-button/styling.js
> +	return styling_css;
Updated

2021-05-27 08:11 UTC, rohitp-bsf approved these changes

2021-05-27 09:05 UTC, RajkiranBagal requested changes

2021-05-27 09:05 UTC, RajkiranBagal commented on src/blocks/marketing-button/settings.js
> +const svg_icons = Object.keys( UAGBIcon );
camelCase variables.

2021-05-27 09:05 UTC, RajkiranBagal commented on src/blocks/marketing-button/settings.js
> +		<>
Add just one Suspense for whole return.

2021-05-27 12:44 UTC, supriyajjadhav commented on src/blocks/marketing-button/settings.js
> +		<>
Updated return

2021-05-28 04:30 UTC, RajkiranBagal requested changes

2021-05-28 04:30 UTC, RajkiranBagal commented on src/blocks/marketing-button/edit.js
> +		<>
Remove unwanted <>

2021-05-28 04:37 UTC, RajkiranBagal approved these changes

2021-05-28 05:05 UTC, sandeshjangam approved these changes

2021-06-01 09:53 UTC, merged