Refactor : Inline Notice.
brainstormforce/ultimate-addons-for-gutenberg pull request #628
Opened 2021-05-03 04:24 UTC by supriyajjadhav

### Description

### Screenshots

### Types of changes

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2021-05-18 05:11 UTC, rohitp-bsf requested changes
- style.scss having duplicate `width` for `span.uagb-notice-dismiss svg` selector.
- Remove unused variables, you can catch that by linters.

2021-05-18 05:11 UTC, rohitp-bsf commented on src/blocks/call-to-action/inline-styles.js
> +	styling_css += generateCSS( mobileSelectors, id, true, "mobile" )
Camel Casing!

2021-05-18 09:10 UTC, supriyajjadhav commented
> * style.scss having duplicate `width` for `span.uagb-notice-dismiss svg` selector.
> * Remove unused variables, you can catch that by linters.

2021-05-25 13:32 UTC, supriyajjadhav commented on src/blocks/call-to-action/inline-styles.js
> +	styling_css += generateCSS( mobileSelectors, id, true, "mobile" )
Updated

2021-05-25 13:50 UTC, supriyajjadhav commented on src/blocks/call-to-action/inline-styles.js
> +	styling_css += generateCSS( mobileSelectors, id, true, "mobile" )
This file is in the call to action block

2021-05-27 08:10 UTC, rohitp-bsf approved these changes

2021-05-27 08:56 UTC, RajkiranBagal requested changes

2021-05-27 08:56 UTC, RajkiranBagal commented on src/blocks/call-to-action/inline-styles.js
> +	var mobileSelectors = {
Undo these changes for this PR

2021-05-27 08:56 UTC, RajkiranBagal commented on src/blocks/inline-notice/settings.js
> +const svg_icons = Object.keys( UAGBIcon );
camelCasing Varibles.

2021-05-27 08:56 UTC, RajkiranBagal commented on src/blocks/inline-notice/settings.js
> +			<Suspense fallback={ lazyLoader() }>
Instead of adding different suspense tags throughout the file just add one tag in Return for all of it combined.

2021-05-27 12:38 UTC, RajkiranBagal approved these changes

2021-06-02 11:59 UTC, merged