Refactor : Call to Action
brainstormforce/ultimate-addons-for-gutenberg pull request #629
Opened 2021-05-03 04:25 UTC by supriyajjadhav

### Description
 - Trello task - https://trello.com/c/mSbMJ7X5/144-uag-block-wise-cleanup

### Types of changes
Breaking change

### How has this been tested?
 - Check Trello Card.

### Checklist:
- [x] My code is tested
- [x] I've included any necessary tests 
- [x] I've added proper labels to this pull request

2021-05-26 05:38 UTC, rohitp-bsf approved these changes

2021-05-26 09:07 UTC, RajkiranBagal requested changes

2021-05-26 09:07 UTC, RajkiranBagal commented on src/blocks/call-to-action/render.js
> +		<>
Removed unwanted <>

2021-05-26 09:07 UTC, RajkiranBagal commented on src/blocks/call-to-action/save.js
>  	const title_text = (
camelCase variable names.

2021-05-26 09:07 UTC, RajkiranBagal commented on src/blocks/call-to-action/settings.js
> +const svg_icons = Object.keys( UAGBIcon );
camelCase variable names.

2021-05-26 09:07 UTC, RajkiranBagal commented
Pull parent Branch.

2021-05-26 11:00 UTC, supriyajjadhav commented on src/blocks/call-to-action/render.js
> +		<>
Removed  <>

2021-05-26 11:00 UTC, supriyajjadhav commented on src/blocks/call-to-action/save.js
>  	const title_text = (
Updated

2021-05-26 11:00 UTC, supriyajjadhav commented on src/blocks/call-to-action/settings.js
> +const svg_icons = Object.keys( UAGBIcon );
Updated

2021-05-27 09:02 UTC, RajkiranBagal requested changes

2021-05-27 09:02 UTC, RajkiranBagal commented on src/blocks/call-to-action/edit.js
> +		<>
Remove unwanted <>

2021-05-27 09:02 UTC, RajkiranBagal commented on src/blocks/call-to-action/render.js
> +	return (
Add Suspense to whole return;

2021-05-27 09:02 UTC, RajkiranBagal commented on src/blocks/call-to-action/save.js
> +		<>
Remove unwanted <>

2021-05-27 09:02 UTC, RajkiranBagal commented on src/blocks/call-to-action/settings.js
> +			{ blockControls() }
Add just one SUspense to whole return;

2021-05-28 04:44 UTC, RajkiranBagal approved these changes

2021-06-02 10:43 UTC, merged