refactor: team
brainstormforce/ultimate-addons-for-gutenberg pull request #633
Opened 2021-05-03 06:21 UTC by rohitp-bsf

### Description
- refactor: team

### Screenshots
- NA

### Types of changes
- Converted Class-based components to functional-based.
- Refactored the edit JS file into render and settings.

### How has this been tested?
- NA

### Checklist:
- [ ] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2021-05-13 12:33 UTC, RajkiranBagal requested changes

2021-05-13 12:33 UTC, RajkiranBagal commented on src/blocks/team/render.js
> +	if ( '' != img_url ) {
Use camelCase variables for consistency

2021-05-13 12:33 UTC, RajkiranBagal commented on src/blocks/team/settings.js
> +	return (
Create separate functions for BlockControls & Each panel settings

2021-05-13 12:49 UTC, rohitp-bsf commented on src/blocks/team/settings.js
> +	return (
Done!

2021-05-13 12:54 UTC, rohitp-bsf commented on src/blocks/team/render.js
> +	if ( '' != img_url ) {
Done!

2021-05-24 05:38 UTC, RajkiranGajananBagal requested changes

2021-05-24 05:38 UTC, RajkiranGajananBagal commented on src/blocks/team/save.js
> +	let img_url = '';
camelCase variables.

2021-05-24 05:38 UTC, RajkiranGajananBagal commented on src/blocks/team/settings.js
> +	const svg_icons = Object.keys( UAGBIcon );
camelCase variables.

2021-05-24 05:38 UTC, RajkiranGajananBagal commented on src/blocks/team/styling.js
> +	let tablet_selectors = {};
camelCase variables.

2021-05-24 07:52 UTC, rohitp-bsf commented on src/blocks/team/styling.js
> +	let tablet_selectors = {};
done!

2021-05-24 07:52 UTC, rohitp-bsf commented on src/blocks/team/settings.js
> +	const svg_icons = Object.keys( UAGBIcon );
done!

2021-05-24 07:52 UTC, rohitp-bsf commented on src/blocks/team/save.js
> +	let img_url = '';
done!

2021-05-24 09:14 UTC, sandeshjangam commented on src/blocks/team/block.js
> +const { registerBlockType } = wp.blocks;
Use package here

2021-05-24 09:14 UTC, sandeshjangam commented on src/blocks/team/deprecated.js
> +const { RichText } = wp.blockEditor;
Use package

2021-05-24 09:16 UTC, sandeshjangam commented on src/blocks/team/edit.js
> +const { withSelect } = wp.data;
Use package

2021-05-24 09:16 UTC, sandeshjangam commented on src/blocks/team/render.js
> +const { RichText } = wp.blockEditor;
Use package

2021-05-24 09:17 UTC, sandeshjangam commented on src/blocks/team/save.js
> +const { RichText } = wp.blockEditor;
Use package

2021-05-24 09:18 UTC, sandeshjangam commented on src/blocks/team/settings.js
> +} = wp.blockEditor;
Use package

2021-05-24 09:18 UTC, sandeshjangam commented on src/blocks/team/settings.js
> +} = wp.components;
Use package

2021-05-24 09:19 UTC, sandeshjangam requested changes
Need changes

2021-05-24 09:28 UTC, rohitp-bsf commented on src/blocks/team/settings.js
> +} = wp.components;
Done!

2021-05-24 09:28 UTC, rohitp-bsf commented on src/blocks/team/settings.js
> +} = wp.blockEditor;
Done!

2021-05-24 09:28 UTC, rohitp-bsf commented on src/blocks/team/save.js
> +const { RichText } = wp.blockEditor;
Done!

2021-05-24 09:28 UTC, rohitp-bsf commented on src/blocks/team/render.js
> +const { RichText } = wp.blockEditor;
Done!

2021-05-24 09:29 UTC, rohitp-bsf commented on src/blocks/team/edit.js
> +const { withSelect } = wp.data;
Done!

2021-05-24 09:29 UTC, rohitp-bsf commented on src/blocks/team/deprecated.js
> +const { RichText } = wp.blockEditor;
Done!

2021-05-24 09:29 UTC, rohitp-bsf commented on src/blocks/team/block.js
> +const { registerBlockType } = wp.blocks;
Done!

2021-05-24 09:32 UTC, sandeshjangam approved these changes

2021-05-24 09:41 UTC, RajkiranBagal approved these changes

2021-05-25 10:51 UTC, merged