refactor: section
brainstormforce/ultimate-addons-for-gutenberg pull request #635
Opened 2021-05-03 08:19 UTC by rohitp-bsf

### Description
- refactor: section

### Screenshots
- NA

### Types of changes
- Converted Class-based components to functional-based.
- Refactored the edit JS file into render and settings.

### How has this been tested?
- NA

### Checklist:
- [ ] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2021-05-17 12:37 UTC, sandeshjangam commented on src/blocks/section/settings.js
> +		/* webpackChunkName: "chunks/section/column-responsive" */ '../../components/typography/column-responsive'
Use @Components alias here

2021-05-17 12:37 UTC, sandeshjangam commented on src/blocks/section/settings.js
> +		/* webpackChunkName: "chunks/section/gradient-settings" */ '../../components/gradient-settings'
Use @Components alias here

2021-05-17 12:37 UTC, sandeshjangam commented on src/blocks/section/settings.js
> +		/* webpackChunkName: "chunks/section/box-shadow-control" */ '../../components/box-shadow'
Use @Components alias here

2021-05-17 12:39 UTC, sandeshjangam requested changes
Need changes

2021-05-24 05:19 UTC, rohitp-bsf commented on src/blocks/section/settings.js
> +		/* webpackChunkName: "chunks/section/box-shadow-control" */ '../../components/box-shadow'
Done!

2021-05-24 05:19 UTC, rohitp-bsf commented on src/blocks/section/settings.js
> +		/* webpackChunkName: "chunks/section/gradient-settings" */ '../../components/gradient-settings'
Done!

2021-05-24 05:19 UTC, rohitp-bsf commented on src/blocks/section/settings.js
> +		/* webpackChunkName: "chunks/section/column-responsive" */ '../../components/typography/column-responsive'
Done!

2021-05-24 05:35 UTC, RajkiranGajananBagal requested changes

2021-05-24 05:35 UTC, RajkiranGajananBagal commented on src/blocks/section/inline-styles.js
> +	let section_width = '100%';
camelCase variables.

2021-05-24 05:35 UTC, RajkiranGajananBagal commented on src/blocks/section/save.js
> +	let block_controls_class = '';
camelCase variables

2021-05-24 05:35 UTC, RajkiranGajananBagal commented on src/blocks/section/style.scss
>  	.uagb-section__overlay {
We can combine common css in 
.uagb-section__overlay & .uagb-section__video-wra CSS

2021-05-24 05:35 UTC, RajkiranGajananBagal commented on src/blocks/section/styling.js
> +	let inner_width = '100%';
camelCase variables.

2021-05-24 06:26 UTC, rohitp-bsf commented on src/blocks/section/inline-styles.js
> +	let section_width = '100%';
done!

2021-05-24 06:26 UTC, rohitp-bsf commented on src/blocks/section/save.js
> +	let block_controls_class = '';
done!

2021-05-24 06:27 UTC, rohitp-bsf commented on src/blocks/section/style.scss
>  	.uagb-section__overlay {
done!

2021-05-24 06:27 UTC, rohitp-bsf commented on src/blocks/section/styling.js
> +	let inner_width = '100%';
done!

2021-05-24 06:29 UTC, RajkiranBagal approved these changes

2021-05-24 07:08 UTC, sandeshjangam commented on src/blocks/section/save.js
> +				blockControlsClass,
Attribute change will create a problem for old users.

2021-05-24 07:12 UTC, sandeshjangam approved these changes
@rohitp-bsf  Need

2021-05-24 13:08 UTC, merged