Refactor: Icon List
brainstormforce/ultimate-addons-for-gutenberg pull request #636
Opened 2021-05-03 09:14 UTC by supriyajjadhav

### Description
Trello task - https://trello.com/c/mSbMJ7X5/144-uag-block-wise-cleanup

### Types of changes
Breaking change

### Checklist:
- [x] My code is tested
- [x] I've included any necessary tests 
- [x] I've added proper labels to this pull request

2021-05-24 05:05 UTC, rohitp-bsf requested changes

2021-05-24 05:05 UTC, rohitp-bsf commented on src/blocks/icon-list/render.js
> +import memoize from 'memize';
Please remove memoize and times dependency and use react/ES alternatives.

2021-05-26 04:08 UTC, supriyajjadhav commented on src/blocks/icon-list/render.js
> +import memoize from 'memize';
Updated

2021-05-27 08:08 UTC, rohitp-bsf approved these changes

2021-05-27 08:50 UTC, RajkiranBagal requested changes

2021-05-27 08:50 UTC, RajkiranBagal commented on src/blocks/icon-list-child/deprecated.js
> +			let image_icon_html = '';
camelCase variables.

2021-05-27 08:50 UTC, RajkiranBagal commented on src/blocks/icon-list-child/deprecated.js
> +			const target_val = target ? '_blank' : '_self';
camelCase variables.

2021-05-27 08:50 UTC, RajkiranBagal commented on src/blocks/icon-list-child/deprecated.js
> +			const link_url = ! disableLink ? link : '/';
camelCase variables.

2021-05-27 08:50 UTC, RajkiranBagal commented on src/blocks/icon-list-child/save.js
> +	const target_val = target ? '_blank' : '_self';
camelCase variables.

2021-05-27 08:50 UTC, RajkiranBagal commented on src/blocks/icon-list-child/settings.js
> +const svg_icons = Object.keys( UAGBIcon );
camelCase variables.

2021-05-27 08:50 UTC, RajkiranBagal commented on src/blocks/icon-list-child/settings.js
> +						},
Add Separate functions for Settings, instead of adding them directly in return.

2021-05-27 08:50 UTC, RajkiranBagal commented on src/blocks/icon-list/settings.js
> +			{ blockControls() }
Instead of adding different suspense tags throughout the file just add one tag in Return for all of it combined.

2021-05-27 08:51 UTC, RajkiranBagal commented
I see Columns file changes is this PR, What is the reason?

2021-05-27 11:48 UTC, supriyajjadhav commented on src/blocks/icon-list-child/deprecated.js
> +			let image_icon_html = '';
Updated variable names

2021-05-31 05:16 UTC, supriyajjadhav commented
> I see Columns file changes is this PR, What is the reason?

These changes added after I run PHPCS command, not major changes. added space at end of the every file.

2021-06-01 09:58 UTC, merged