refactor: cf7-styler
brainstormforce/ultimate-addons-for-gutenberg pull request #637
Opened 2021-05-04 05:40 UTC by rohitp-bsf

### Description
- refactor: cf7-styler

### Screenshots
- NA

### Types of changes
- Converted Class-based components to functional-based.
- Refactored the edit JS file into render and settings.

### How has this been tested?
- NA

### Checklist:
- [ ] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2021-05-26 06:08 UTC, sandeshjangam approved these changes

2021-05-26 06:29 UTC, RajkiranBagal requested changes

2021-05-26 06:29 UTC, RajkiranBagal commented on src/blocks/cf7-styler/edit.js
> +	let json_data = '';
CamelCase variables.

2021-05-27 03:58 UTC, rohitp-bsf commented on src/blocks/cf7-styler/edit.js
> +	let json_data = '';
Done!

2021-05-27 04:02 UTC, RajkiranBagal approved these changes

2021-05-28 09:32 UTC, merged