Refactor : GF Styler
brainstormforce/ultimate-addons-for-gutenberg pull request #642
Opened 2021-05-04 12:13 UTC by supriyajjadhav

### Description
Trello task - https://trello.com/c/mSbMJ7X5/144-uag-block-wise-cleanup

### Types of changes
Breaking change

### Checklist:
- [x] My code is tested
- [x] I've included any necessary tests 
- [x] I've added proper labels to this pull request

2021-05-18 05:20 UTC, rohitp-bsf requested changes
- Style.scss file having line 418: ` padding: 0px 0px 0px 0px;` can we merge this to ` padding: 0`

2021-05-18 05:20 UTC, rohitp-bsf commented on src/blocks/gf-styler/styling.js
> +		" .uagb-gf-styler__check-style-enabled .gfield_checkbox input[type='checkbox'] + label:before": {
This selector is being used twice, check if we can merge that!

2021-05-18 05:20 UTC, rohitp-bsf commented on src/blocks/gf-styler/styling.js
> +		" .uagb-gf-styler__check-style-enabled .gfield_checkbox input[type='checkbox']:checked + label:before": {
This selector is being used twice, check if we can merge that!

2021-05-18 05:20 UTC, rohitp-bsf commented on src/blocks/gf-styler/styling.js
> +		" .uagb-gf-styler__check-style-enabled input[type='checkbox'] + label:before": {
This selector is being used twice, check if we can merge that!

2021-05-18 05:20 UTC, rohitp-bsf commented on src/blocks/gf-styler/styling.js
> +		" .uagb-gf-styler__check-style-enabled input[type='checkbox']:checked + label:before": {
This selector is being used twice, check if we can merge that!

2021-05-18 05:20 UTC, rohitp-bsf commented on src/blocks/gf-styler/styling.js
> +		" .uagb-gf-styler__check-style-enabled .gfield_radio input[type='radio'] + label:before": {
This selector is being used twice, check if we can merge that!

2021-06-01 11:05 UTC, rohitp-bsf approved these changes

2021-06-03 04:30 UTC, RajkiranBagal approved these changes

2021-06-03 09:18 UTC, merged