refactor: post masonry
brainstormforce/ultimate-addons-for-gutenberg pull request #643
Opened 2021-05-04 13:13 UTC by rohitp-bsf

### Description
- refactor: post masonry

### Screenshots
- NA

### Types of changes
- Converted Class-based components to functional-based.
- Refactored the edit JS file into render and settings.

### How has this been tested?
- NA

### Checklist:
- [ ] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2021-05-18 03:29 UTC, sandeshjangam commented on src/blocks/post/post-masonry/block.js
> +const { registerBlockType } = wp.blocks;
import { registerBlockType } from '@wordpress/blocks';

2021-05-18 03:31 UTC, sandeshjangam commented on src/blocks/post/post-masonry/edit.js
> +		/* webpackChunkName: "chunks/post-masonry/settings" */ '../../../components/typography'
Use alias

2021-05-18 03:31 UTC, sandeshjangam commented on src/blocks/post/post-masonry/edit.js
> +		/* webpackChunkName: "chunks/post-masonry/settings" */ '../../../components/typography/column-responsive'
Use alias

2021-05-18 03:35 UTC, sandeshjangam commented on src/blocks/post/post-masonry/settings.js
> +import WebfontLoader from '../../../components/typography/fontloader';
use alais

2021-05-18 03:35 UTC, sandeshjangam requested changes
Need changes

2021-05-18 04:35 UTC, rohitp-bsf commented on src/blocks/post/post-masonry/block.js
> +const { registerBlockType } = wp.blocks;
Done!

2021-05-18 04:35 UTC, rohitp-bsf commented on src/blocks/post/post-masonry/edit.js
> +		/* webpackChunkName: "chunks/post-masonry/settings" */ '../../../components/typography'
Done!

2021-05-18 04:35 UTC, rohitp-bsf commented on src/blocks/post/post-masonry/edit.js
> +		/* webpackChunkName: "chunks/post-masonry/settings" */ '../../../components/typography/column-responsive'
Done!

2021-05-18 04:35 UTC, rohitp-bsf commented on src/blocks/post/post-masonry/settings.js
> +import WebfontLoader from '../../../components/typography/fontloader';
Done!

2021-05-25 09:45 UTC, RajkiranBagal requested changes

2021-05-25 09:45 UTC, RajkiranBagal commented on src/blocks/post/post-masonry/edit.js
> +					}
Remove the old return & settings code above.

2021-05-25 09:45 UTC, RajkiranBagal commented on src/blocks/post/post-masonry/edit.js
> +		let rest_base = '';
camelCase variables

2021-05-25 10:11 UTC, sandeshjangam approved these changes

2021-05-25 10:19 UTC, rohitp-bsf commented on src/blocks/post/post-masonry/edit.js
> +		let rest_base = '';
Done!

2021-05-25 10:19 UTC, rohitp-bsf commented on src/blocks/post/post-masonry/edit.js
> +					}
Done!

2021-05-25 10:57 UTC, RajkiranBagal approved these changes

2021-05-28 06:38 UTC, merged