Refactor:  Testimonial
brainstormforce/ultimate-addons-for-gutenberg pull request #653
Opened 2021-05-06 09:42 UTC by supriyajjadhav

### Description
 - Trello task - https://trello.com/c/mSbMJ7X5/144-uag-block-wise-cleanup

### Types of changes
Breaking change

### How has this been tested?
 - Check Trello Card.

### Checklist:
- [x] My code is tested
- [x] I've included any necessary tests 
- [x] I've added proper labels to this pull request

2021-05-18 05:06 UTC, rohitp-bsf requested changes

2021-05-18 05:06 UTC, rohitp-bsf commented on src/blocks/testimonial/attributes.js
> +	arrowColor: {
Duplicate `arrowColor` key!

2021-05-18 05:06 UTC, rohitp-bsf commented on src/blocks/testimonial/inline-styles.js
> +	styling_css += generateCSS(
Camel caseing!

2021-05-19 09:39 UTC, supriyajjadhav commented on src/blocks/testimonial/attributes.js
> +	arrowColor: {
Removed

2021-05-19 09:41 UTC, supriyajjadhav commented on src/blocks/testimonial/inline-styles.js
> +	styling_css += generateCSS(
Updated variable names

2021-05-24 14:31 UTC, rohitp-bsf requested changes

2021-05-24 14:31 UTC, rohitp-bsf commented on src/blocks/testimonial/settings.js
> +import times from 'lodash/times';
Remove this dependency and use alternative!

2021-05-28 04:12 UTC, supriyajjadhav commented on src/blocks/testimonial/settings.js
> +import times from 'lodash/times';
Removed

2021-05-28 04:36 UTC, RajkiranBagal approved these changes

2021-05-28 06:01 UTC, sandeshjangam approved these changes

2021-06-01 11:04 UTC, merged