Fix: Lottie block issues
brainstormforce/ultimate-addons-for-gutenberg pull request #675
Opened 2021-05-14 12:41 UTC by supriyajjadhav

[Trello](https://trello.com/c/7EHNso8e/317-lottie-block-issues-present-in-master-branch)

### Description
Fix Lottie Issues added description in the card

### Types of changes
- non-breakable changes

### How has this been tested?
Tested whether it is working fine or not

### Checklist:
- [x] My code is tested
- [x] I've included developer documentation 
- [x] I've added proper labels to this pull request

2021-05-14 13:07 UTC, RajkiranBagal requested changes

2021-05-14 13:07 UTC, RajkiranBagal commented on admin/assets/admin-menu-settings.js
> +					if(id === 'how-to'){
Is this change is needed here?

2021-05-14 13:07 UTC, RajkiranBagal commented on classes/class-uagb-admin.php
> +			if ( 'how-to' === $block_id && 'disabled' === $blocks['info-box'] ) {
Is this change is needed here?

2021-05-14 13:07 UTC, RajkiranBagal commented on classes/class-uagb-admin.php
> +			if ( 'info-box' === $block_id && 'how-to' === $blocks['how-to'] ) {
Is this change is needed here?

2021-05-14 13:07 UTC, RajkiranBagal commented on classes/class-uagb-config.php
> +						'is_child'    => true,
These file changes not needed here

2021-05-14 13:44 UTC, supriyajjadhav commented on admin/assets/admin-menu-settings.js
> +					if(id === 'how-to'){
Next-release changes merged in this branch... Removed everything

2021-05-14 14:24 UTC, RajkiranBagal approved these changes

2021-05-17 03:26 UTC, sandeshjangam approved these changes

2021-05-17 03:27 UTC, merged