Fix: Margin left/Right is not working in all the cases
brainstormforce/ultimate-addons-for-gutenberg pull request #698
Opened 2021-05-21 03:40 UTC by supriyajjadhav

[Trello](https://trello.com/c/ygPpj7TS/296-fix-section-block-margin-left-margin-right-not-working)

### Description
Issue --> https://wordpress.org/support/topic/section-block-margin-left-right-not-working/

Margin-left and margin-right for the section block is working in these conditions only  --> https://share.getcloudapp.com/Jru4mkD1
Margin should work on every condition in sections block

### Types of changes
- non-breaking changes

### How has this been tested?
Tested whether it is working in all the cases on front-end and back-end.

### Checklist:
- [x] My code is tested
- [x] My code follows accessibility standards 
- [x] I've added proper labels to this pull request

2021-05-24 05:45 UTC, RajkiranBagal requested changes

2021-05-24 05:45 UTC, RajkiranBagal commented on classes/class-uagb-block-helper.php
> +				if ( 'right' === $attr['align'] ) {
Use switch case for $attr['align'] if statements

2021-05-24 05:45 UTC, RajkiranBagal commented on src/blocks/section/inline-styles.js
> +		if ( "right" == align  ) {
Use switch case for $attr['align'] if statements

2021-05-24 12:26 UTC, RajkiranBagal approved these changes

2021-05-25 13:02 UTC, sandeshjangam approved these changes

2021-05-25 13:05 UTC, merged