Fix: Advanced Column - Stack on Tablet and mobile in preview mode.
brainstormforce/ultimate-addons-for-gutenberg pull request #700
Opened 2021-05-21 09:00 UTC by supriyajjadhav

[Trello](https://trello.com/c/bfDcNh4I/322-fix-advanced-column-stack-on-tablet-and-mobile-in-preview-mode)

### Description
**Problem** - Content is only stacked for Tablet and not for Mobile devices even after selecting the Stack option for Tablet & Mobile.
Video - https://share.bsf.io/qGuEe6WQ

### Types of changes
Bugfix (non-breaking change which fixes an issue) 

### How has this been tested?
Tested on Editor 

### Checklist:
- [x] My code is tested
- [x] I've added proper labels to this pull request

2021-05-21 12:26 UTC, RajkiranBagal requested changes

2021-05-21 12:26 UTC, RajkiranBagal commented on src/blocks/column/editor.scss
> +.uagb-editor-preview-mode-mobile.uagb-columns__stack-tablet>.uagb-columns__inner-wrap>.block-editor-inner-blocks>.block-editor-block-list__layout
Can we reduce the number of selectors? Also will it work without the `important`

2021-05-24 04:46 UTC, supriyajjadhav commented on src/blocks/column/editor.scss
> +.uagb-editor-preview-mode-mobile.uagb-columns__stack-tablet>.uagb-columns__inner-wrap>.block-editor-inner-blocks>.block-editor-block-list__layout
Removed important but we cannot reduce the selectors

2021-05-24 05:40 UTC, RajkiranGajananBagal approved these changes

2021-05-25 12:36 UTC, RajkiranBagal approved these changes

2021-05-25 12:41 UTC, sandeshjangam approved these changes

2021-05-25 12:43 UTC, merged