Updated path for custom-style-block
brainstormforce/ultimate-addons-for-gutenberg pull request #725
Opened 2021-06-07 08:10 UTC by AbhijitNage123

### Description

### Screenshots

### Types of changes

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2021-06-07 08:56 UTC, RajkiranBagal requested changes

2021-06-07 08:56 UTC, RajkiranBagal commented on classes/class-uagb-admin-helper.php
> +			$wp_upload_dir = wp_upload_dir( null, false );
We can use our `get_uag_upload_dir_path` function to get the Upload DIR Path.

2021-06-07 08:56 UTC, RajkiranBagal commented on classes/class-uagb-scripts-utils.php
> +		$wp_upload_dir = wp_upload_dir( null, false );
We can use our `get_uag_upload_dir_path` function to get the Upload DIR Path.

2021-06-07 08:57 UTC, RajkiranBagal commented
Need to update here too -  https://share.getcloudapp.com/2NuqrddB

2021-06-07 08:59 UTC, RajkiranBagal commented
- Create a task for this in Trello, Add a proper description of why we are doing this in Task as well as in PR, Add Proper test cases for Tester to test, Add proper PR prefix & Title. 
 
 These things are very important for future references of PR's & should be done by default.

2021-06-07 09:56 UTC, sandeshjangam commented on classes/class-uagb-scripts-utils.php
> +				$wp_upload_dir . '/custom-style-blocks.css', // Block style CSS.
Need url here.

2021-06-07 10:07 UTC, AbhijitNage123 commented on classes/class-uagb-admin-helper.php
> +			$wp_upload_dir = wp_upload_dir( null, false );
Done

2021-06-07 10:32 UTC, AbhijitNage123 commented on classes/class-uagb-scripts-utils.php
> +		$wp_upload_dir = wp_upload_dir( null, false );
Done. Use URL instead of dir for enqueue

2021-06-07 10:32 UTC, AbhijitNage123 commented on classes/class-uagb-scripts-utils.php
> +				$wp_upload_dir . '/custom-style-blocks.css', // Block style CSS.
Updated.

2021-06-07 11:04 UTC, RajkiranBagal approved these changes

2021-06-08 05:53 UTC, sandeshjangam approved these changes

2021-06-08 06:40 UTC, merged