Fix: Twenty Seventeen - Uncaught Error on pages.
brainstormforce/ultimate-addons-for-gutenberg pull request #754
Opened 2021-06-14 05:37 UTC by AbhijitNage123

### Description

- Trello - https://trello.com/c/dDqTonHm/376-fix-twenty-seventeen-fatal-error-on-pages

### Screenshots

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

### How has this been tested?

- Mention on Trello board.

### Checklist:
- [x] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [x] I've included any necessary tests 
- [ ] I've included developer documentation 
- [x] I've added proper labels to this pull request

2021-06-14 09:44 UTC, RajkiranBagal requested changes

2021-06-14 09:44 UTC, RajkiranBagal commented on README.md
> +* Fix: Twenty Seventeen - Uncaught Error on pages.
`Fix: Twenty Seventeen Compatibility - Uncaught Error on pages.`

2021-06-14 09:59 UTC, AbhijitNage123 commented on README.md
> +* Fix: Twenty Seventeen - Uncaught Error on pages.
Updated

2021-06-14 10:04 UTC, RajkiranBagal approved these changes

2021-06-22 05:48 UTC, sandeshjangam approved these changes

2021-06-22 06:05 UTC, sandeshjangam approved these changes

2021-06-22 06:05 UTC, merged