IST-170 - Masonry gallery
brainstormforce/ultimate-addons-for-gutenberg pull request #758
Opened 2021-06-17 07:21 UTC by vrundakansara

### Description
This PR adds an option in the advanced section for Masonry Layout for Core Gallery.

### Screenshots
Option - 
![Image 2021-06-17 at 12 49 08 PM](https://user-images.githubusercontent.com/11641718/122350081-85034880-cf6a-11eb-97b2-878d31943e0c.jpg)

Output - 
https://share.getcloudapp.com/wbu69LAW

### Types of changes
New feature

### How has this been tested?
- Test if Masonry Layout is applied
- When the option is disabled its related assets should not be loaded on any page.

### Checklist:
- [x] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [x] I've added proper labels to this pull request

2021-06-21 08:50 UTC, Nikschavan commented
@vrundakansara Can the masonry layout be previewed in the block editor as well?

2021-06-21 09:08 UTC, Nikschavan requested changes

2021-06-21 09:08 UTC, Nikschavan commented on src/blocks/extensions/attributes.js
> +		if( block_type.includes(settings.name) ){
```suggestion
		if( block_type.includes( settings.name ) ){
```

2021-06-21 09:08 UTC, Nikschavan commented on src/blocks/extensions/block.js
> +const enableMasonryGallery = uagb_blocks_info.enableMasonryGallery;
Object spread can be used here

2021-06-21 09:08 UTC, Nikschavan commented on src/blocks/extensions/block.js
> +const MasonryGallery = wp.compose.createHigherOrderComponent((BlockEdit) => {
[createHigherOrderComponent](https://www.npmjs.com/package/@wordpress/compose#createHigherOrderComponent) should be imported above and used instead of accessing the global `wp`

2021-06-21 09:08 UTC, Nikschavan commented on src/blocks/extensions/block.js
> +	return (props) => {
```suggestion
	return ( props ) => {
```

2021-06-21 09:08 UTC, Nikschavan commented on src/blocks/extensions/block.js
> +		} = wp.components;
Import the dependencies from relevant npm packages instead of accessing from globals.
This allows the dependencies to be clearly distinguishable from package.json

2021-06-21 09:08 UTC, Nikschavan commented on src/blocks/extensions/block.js
> +		const blocks_name = props.name;
This can be deconstructed from line number 39 above.
Also see if this can be converted to camelCase.

2021-06-21 09:08 UTC, Nikschavan commented on src/blocks/extensions/block.js
> +		const block_type = [ 'core/gallery' ];
```suggestion
		const blockType = [ 'core/gallery' ];
```

2021-06-21 09:08 UTC, Nikschavan commented on src/blocks/extensions/block.js
> +const MasonryGallery = wp.compose.createHigherOrderComponent((BlockEdit) => {
Better to move this to a separate file - new file for each hoc.

2021-06-21 09:08 UTC, Nikschavan commented on classes/class-uagb-block-helper.php
> +				'[class*="columns-"].wp-block-gallery .blocks-gallery-grid' => array(
Is this `class*` selector required? is there an alternative class selector that we can use?

2021-06-21 09:09 UTC, Nikschavan commented
@vrundakansara Added some questions and a few minor formatting errors.

2021-06-21 11:39 UTC, vrundakansara commented on classes/class-uagb-post-assets.php
> +			$this->uag_flag             = true;
The uag flag represents and flag that indicates the page/post has a uag block used in it.
This flag eventually helps the further manipulation of asset generation. @Nikschavan

2021-06-21 11:40 UTC, vrundakansara commented on src/blocks/extensions/block.js
> +		} = wp.components;
This needs a global fix, everywhere we have used such packages. May be we can add a task for UAG here, and get it fixed all over in the plugin.

2021-06-21 11:41 UTC, vrundakansara commented on classes/class-uagb-block-helper.php
> +				'[class*="columns-"].wp-block-gallery .blocks-gallery-grid' => array(
That is necessary to override the existing CSS.

2021-06-21 17:09 UTC, vrundakansara commented on classes/class-uagb-init-blocks.php
> +				'enableMasonryGallery'   => apply_filters( 'enable_masonry_gallery', true ),
I have added the prefixes.

2021-06-21 17:09 UTC, vrundakansara commented on src/blocks/extensions/block.js
> +		} = wp.components;
I have fixed for this PR.

2021-06-21 17:10 UTC, vrundakansara commented on src/blocks/extensions/block.js
> +		const blocks_name = props.name;
Done.

2021-06-21 17:10 UTC, vrundakansara commented on src/blocks/extensions/block.js
> +		const block_type = [ 'core/gallery' ];
Done.

2021-06-21 17:10 UTC, vrundakansara commented on src/blocks/extensions/block.js
> +const MasonryGallery = wp.compose.createHigherOrderComponent((BlockEdit) => {
Done.

2021-06-22 14:12 UTC, Nikschavan commented on src/blocks/extensions/condition-block/index.js
> +}
```suggestion
}

```

@vrundakansara Setup editor [Editorconfig for VS Code](https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig) which takes care of this automatically.

2021-06-22 14:15 UTC, Nikschavan commented on src/blocks/extensions/masonry-gallery/index.js
> +const MasonryGallery = wp.compose.createHigherOrderComponent((BlockEdit) => {
This can be imported as a dependency from @wordpress/compose I think?

2021-06-22 14:16 UTC, Nikschavan commented on classes/class-uagb-init-blocks.php
> +				'enableMasonryGallery'   => apply_filters( 'enable_masonry_gallery', true ),
@vrundakansara The filter `enable_block_condition` existed since before - that will need to be deprecated when renaming, right?

2021-06-24 06:46 UTC, RajkiranBagal requested changes

2021-06-24 06:46 UTC, RajkiranBagal commented on classes/class-uagb-block-helper.php
> +				'tablet'  => array(),
Why are we passing no CSS for Tablet?

2021-06-24 08:26 UTC, monika-12 commented
> @vrundakansara
> 
> * Can the masonry layout be previewed in the block editor as well?
> * Can we bring the option out of Advanced, in "Gallery Settings" section?
> * I think with masonry gallery usually butter-width option is also provided - should we add that as well? (cc - @sandeshjangam , @monika-12)

-- It would be good if we can show a preview in the editor. (Competitors are doing we can take the reference)
--- Yes, This option should come under `Gallery Settings`. Please make the changes 
-- Nikhil - Do you mean by the Gutter Width option here?  If yes, it would be required.

2021-06-24 10:11 UTC, vrundakansara commented on src/blocks/extensions/masonry-gallery/index.js
> +const MasonryGallery = wp.compose.createHigherOrderComponent((BlockEdit) => {
Done.

2021-06-24 10:25 UTC, vrundakansara commented on classes/class-uagb-block-helper.php
> +				'tablet'  => array(),
We don't have any Tablet-based CSS here.

2021-06-24 10:26 UTC, vrundakansara commented on src/blocks/extensions/condition-block/index.js
> +}
Done

2021-06-24 10:33 UTC, vrundakansara commented
> Can the masonry layout be previewed in the block editor as well?

Done

> Can we bring the option out of Advanced, in the "Gallery Settings" section?

Yes we can bring out from Advanced, but by adding a new accordion and not "Gallery Settings" - https://share.getcloudapp.com/JruDGgqO

> I think with masonry gallery usually gutter-width option is also provided - should we add that as well?

I have added it, but it will create problems when more than 1 masonry gallery are used on the page. Since we don't have a unique class for each, adding respective CSS is a problem.

@Nikschavan - Please check.

2021-06-24 11:58 UTC, vrundakansara commented on classes/class-uagb-init-blocks.php
> +				'enableMasonryGallery'   => apply_filters( 'enable_masonry_gallery', true ),
Done.

2021-07-16 10:47 UTC, RajkiranBagal approved these changes

2021-07-16 10:55 UTC, sandeshjangam approved these changes

2021-07-16 11:08 UTC, sandeshjangam approved these changes

2021-07-16 11:10 UTC, merged