IST-169 - Star Rating Block
brainstormforce/ultimate-addons-for-gutenberg pull request #760
Opened 2021-06-17 12:40 UTC by vrundakansara

### Description
Added a new block that can add Star Rating on page. Below are the options:
- Rating
- Range of rating
- Spacing options
- Color options
- Title beside the stars
- Typography and color options for title
- Other design options

### Types of changes
New Block

### How has this been tested?
- Test all the options mentioned in the settings.

### Checklist:
- [x] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [x] I've added proper labels to this pull request

2021-06-21 11:05 UTC, Nikschavan requested changes

2021-06-21 11:24 UTC, vrundakansara commented on src/blocks/star-rating/save.js
> +} = wp.blockEditor
This needs a global fix, everywhere we have used such packages. May be we can add a task for UAG here, and get it fixed all over in the plugin.

2021-06-21 11:25 UTC, vrundakansara commented on src/blocks/star-rating/edit.js
> +} = wp.components
This needs a global fix, everywhere we have used such packages. Maybe we can add a task for UAG here, and get it fixed all over in the plugin.

2021-06-21 11:30 UTC, Nikschavan commented on src/blocks/star-rating/save.js
> +} = wp.blockEditor
why not fix in the new code? old code can be refactored at a later priority.

2021-06-21 11:30 UTC, Nikschavan commented on src/blocks/star-rating/edit.js
> +} = wp.components
Same as above

2021-06-21 13:08 UTC, vrundakansara commented on src/blocks/star-rating/edit.js
> +					<div class="uag-star-rating" title={`${rating}/${range}`} itemtype="http://schema.org/Rating" itemscope="" itemprop="reviewRating">
As per our discussion, we are skipping this. Marking as resolved.

2021-06-21 13:11 UTC, vrundakansara commented on src/blocks/star-rating/edit.js
> +		const $style = document.createElement( "style" )
Yes, done. 👍🏼

2021-06-21 13:18 UTC, vrundakansara commented on src/blocks/star-rating/save.js
> +} = wp.blockEditor
Done. 👍🏼

2021-06-21 13:18 UTC, vrundakansara commented on src/blocks/star-rating/edit.js
> +} = wp.components
Done. 👍🏼

2021-06-22 14:20 UTC, Nikschavan approved these changes

2021-06-24 06:37 UTC, RajkiranBagal requested changes

2021-06-24 06:37 UTC, RajkiranBagal commented on classes/class-uagb-config.php
> +						'extension'   => false,
I guess we can remove this extension key as we have removed it in [#764 ](https://github.com/brainstormforce/ultimate-addons-for-gutenberg/pull/764)PR.

2021-06-24 06:37 UTC, RajkiranBagal commented on src/blocks/star-rating/edit.js
> +/**
Create a Functional Component, Create Separate Components Files for Settings & Rendering.

The lazy loading & linter changes we  will get those done afterwards.

2021-06-24 12:40 UTC, vrundakansara commented on classes/class-uagb-config.php
> +						'extension'   => false,
I think I need the key for this - https://github.com/brainstormforce/ultimate-addons-for-gutenberg/pull/764

2021-06-24 12:56 UTC, vrundakansara commented on classes/class-uagb-config.php
> +						'extension'   => false,
Done.

2021-06-24 12:57 UTC, vrundakansara commented on src/blocks/star-rating/edit.js
> +/**
Done.

2021-07-13 16:33 UTC, vrundakansara commented
Handled this PR here - https://github.com/brainstormforce/ultimate-addons-for-gutenberg/pull/807
Closing this.

2021-07-13 16:33 UTC, closed without merging