React Admin UI
brainstormforce/ultimate-addons-for-gutenberg pull request #793
Opened 2021-07-06 13:54 UTC by supriyajjadhav

### Description

### Screenshots

### Types of changes

### How has this been tested?

### Checklist:
- [ ] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2021-09-15 13:37 UTC, RajkiranBagal requested changes

2021-09-15 13:37 UTC, RajkiranBagal commented on admin-core/admin-loader.php
> +	 * @since 1.0.0
Update the Since tag to x.x.x everywhere

2021-09-15 13:37 UTC, RajkiranBagal commented on admin-core/assets/src/sass/colors/_colors.scss
> +/*
We can remove unwanted code.

2021-09-15 13:37 UTC, RajkiranBagal commented on admin-core/assets/src/sass/colors/_structure.scss
> +$width-site-content: 				960px;
Are we using these variables? If not we can remove them

2021-09-15 13:37 UTC, RajkiranBagal commented on admin-core/assets/src/sass/colors/_typography.scss
> +$font-size-h1:       		2em !default;
Are we using these variables? If not we can remove them

2021-09-16 06:50 UTC, sandeshjangam approved these changes

2021-09-16 06:53 UTC, RajkiranBagal approved these changes

2021-09-16 06:54 UTC, merged