UAG-341 - Fix color not applying to content timeline arrow in editor
brainstormforce/ultimate-addons-for-gutenberg pull request #799
Opened 2021-07-08 12:15 UTC by AbhijitNage123

### Description

- Card - https://ua-gutenberg.atlassian.net/jira/software/projects/UAG/boards/2/backlog?selectedIssue=UAG-341

### Screenshots

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

### How has this been tested?

- Drag and drop Content timeline > Select orientation > Left
- Add styling to every content template and check working.

### Checklist:
- [x] My code is tested
- [x] I've included any necessary tests 
- [x] I've added proper labels to this pull request

2021-07-13 09:58 UTC, RajkiranBagal requested changes

2021-07-13 09:58 UTC, RajkiranBagal commented on src/blocks/timeline/content-timeline/styling.js
>          },
Same CSS is present below, Why Add this?

2021-07-14 05:37 UTC, AbhijitNage123 commented on src/blocks/timeline/content-timeline/styling.js
>          },
Remove unwanted CSS. Please check

2021-07-14 06:32 UTC, RajkiranBagal approved these changes

2021-07-15 10:46 UTC, RajkiranBagal commented
Closing this PR as it is not needed.

2021-07-15 10:46 UTC, closed without merging