Fix: Table of content -  Show Scroll To Top height and background color not applying issue in the editor.
brainstormforce/ultimate-addons-for-gutenberg pull request #801
Opened 2021-07-09 07:27 UTC by AbhijitNage123

### Description

- Card - https://ua-gutenberg.atlassian.net/jira/software/projects/UAG/boards/2/backlog?selectedIssue=UAG-344

### Screenshots

### Types of changes

- Bug fix (non-breaking change which fixes an issue) 

### How has this been tested?

- Drag and drop TOC add styling to block.
- Enable scroll to top and styling to it.
- Check all is working fine or not.
- Check all possible cases you have on your list.

### Checklist:
- [ ] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2021-07-13 10:03 UTC, RajkiranBagal requested changes

2021-07-13 10:03 UTC, RajkiranBagal commented on src/blocks/table-of-contents/styling.js
> +		styling_css += ".block-editor-page .uagb-toc__scroll-top.uagb-toc__show-scroll { background: " + scrollToTopBgColor + "; }"
Keep both the selectors:
`.block-editor-page .uagb-toc__scroll-top.uagb-toc__show-scroll,
.uagb-toc__scroll-top.uagb-toc__show-scroll {`

2021-07-13 13:46 UTC, AbhijitNage123 commented on src/blocks/table-of-contents/styling.js
> +		styling_css += ".block-editor-page .uagb-toc__scroll-top.uagb-toc__show-scroll { background: " + scrollToTopBgColor + "; }"
Updated

2021-07-14 06:11 UTC, RajkiranBagal approved these changes

2021-07-15 10:46 UTC, RajkiranBagal commented
Closing this PR as it is not needed.

2021-07-15 10:46 UTC, closed without merging