UAG-303 Fix: Responsive visibility not working on woo-commerce pages.
brainstormforce/ultimate-addons-for-gutenberg pull request #802
Opened 2021-07-12 08:55 UTC by AbhijitNage123

### Description

- Card - https://ua-gutenberg.atlassian.net/jira/software/projects/UAG/boards/2?selectedIssue=UAG-303

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

### How has this been tested?

- Added in a card.

### Checklist:
- [x] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [x] I've included any necessary tests 
- [ ] I've included developer documentation 
- [x] I've added proper labels to this pull request

2021-07-12 10:17 UTC, RajkiranBagal requested changes

2021-07-12 10:17 UTC, RajkiranBagal commented on classes/class-uagb-post-assets.php
> +			// Assets Required for woocommerce pages.
We can combine these 2 if statements.

2021-07-12 10:17 UTC, RajkiranBagal commented on classes/class-uagb-post-assets.php
> +			// Global Required assets.
We can combine this else & if statement

2021-07-12 10:17 UTC, RajkiranBagal commented on classes/class-uagb-helper.php
> +		 * @deprecated x.x.x
Remove deprecated tag

2021-07-12 10:25 UTC, AbhijitNage123 commented on classes/class-uagb-post-assets.php
> +			// Assets Required for woocommerce pages.
Updated please check

2021-07-12 10:25 UTC, AbhijitNage123 commented on classes/class-uagb-post-assets.php
> +			// Global Required assets.
Updated please check

2021-07-12 10:26 UTC, AbhijitNage123 commented on classes/class-uagb-helper.php
> +		 * @deprecated x.x.x
Done

2021-07-12 10:46 UTC, RajkiranBagal approved these changes

2021-07-15 09:20 UTC, RajkiranBagal commented
Closing this PR as this issue get's fixed here - https://github.com/brainstormforce/ultimate-addons-for-gutenberg/pull/811

2021-07-15 09:20 UTC, closed without merging