UAG-330 Improvement: Table of content - Added scroll to specific anchor tag feature.
brainstormforce/ultimate-addons-for-gutenberg pull request #806
Opened 2021-07-13 13:08 UTC by AbhijitNage123

### Description

- Card - https://ua-gutenberg.atlassian.net/jira/software/projects/UAG/boards/2?selectedIssue=UAG-330

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

### How has this been tested?

- Drag and drop Table of Content block on page/post.
- Visit frontend, click on heading, scroll to specific heading.
- Copy the hyperlink from url open in incognito browser and check it's scrolling to specific heading or not.

### Checklist:
- [ ] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

2021-07-14 08:53 UTC, RajkiranBagal requested changes

2021-07-14 08:53 UTC, RajkiranBagal commented on assets/js/table-of-contents.js
> +			}else{
We can eliminate the else here. Just write.

`if (  ' ' === hash && ! /[^a-z0-9-_]/.test( hash )  ) {
   return;
}`

2021-07-14 09:29 UTC, AbhijitNage123 commented on assets/js/table-of-contents.js
> +			}else{
Updated please check

2021-07-16 13:06 UTC, RajkiranBagal approved these changes

2021-07-19 06:12 UTC, sandeshjangam approved these changes

2021-07-19 06:13 UTC, merged