UI/UX Changes suggested by QA in blocks
brainstormforce/ultimate-addons-for-gutenberg pull request #942
Opened 2021-09-01 11:26 UTC by AbhijitNage123

### Description

- Marketting button - https://ua-gutenberg.atlassian.net/browse/UAG-423
- CTA block - https://ua-gutenberg.atlassian.net/browse/UAG-421
- Icon List - https://ua-gutenberg.atlassian.net/browse/UAG-406
- Advanced Heading - https://ua-gutenberg.atlassian.net/browse/UAG-417

### Types of changes

- Improvement

### How has this been tested?

- Verify all changes as per block.

### Checklist:
- [x] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [x] I've included any necessary tests 
- [ ] I've included developer documentation 
- [x] I've added proper labels to this pull request

2021-09-02 04:35 UTC, RajkiranBagal requested changes

2021-09-02 04:35 UTC, RajkiranBagal commented on src/blocks/call-to-action/settings.js
> +				{ ( ctaType === 'text' || ctaType === 'button' ) && (
Just check ctaType === 'button' & remove inside check.

2021-09-02 04:35 UTC, RajkiranBagal commented on src/blocks/call-to-action/settings.js
> +							<MultiButtonsControl
Instead of writing check again add this in above check.

2021-09-02 04:35 UTC, RajkiranBagal commented on src/blocks/icon-list-child/settings.js
>  							'Disable Link',
Rename this Label, Righnow after your change it's creating more confusion.

2021-09-02 05:02 UTC, AbhijitNage123 commented on src/blocks/call-to-action/settings.js
> +				{ ( ctaType === 'text' || ctaType === 'button' ) && (
Resolved Please review

2021-09-02 05:02 UTC, AbhijitNage123 commented on src/blocks/icon-list-child/settings.js
>  							'Disable Link',
Updated label to `Enable Link`. Please check

2021-09-02 05:03 UTC, AbhijitNage123 commented on src/blocks/call-to-action/settings.js
> +							<MultiButtonsControl
Updated the condition. please review

2021-09-02 05:09 UTC, RajkiranBagal commented on src/blocks/icon-list-child/settings.js
>  							'Disable Link',
Update Label to `Link`

2021-09-02 05:11 UTC, AbhijitNage123 commented on src/blocks/icon-list-child/settings.js
>  							'Disable Link',
Done

2021-09-06 04:09 UTC, RajkiranBagal approved these changes

2021-09-06 09:54 UTC, sandeshjangam approved these changes

2021-09-06 09:54 UTC, merged