UAG-385 - Fix: UAG blocks losses style on single post when Auto Load Previous Posts is ON.
brainstormforce/ultimate-addons-for-gutenberg pull request #954
Opened 2021-09-06 12:59 UTC by AbhijitNage123

### Description

- https://ua-gutenberg.atlassian.net/browse/UAG-385

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

### How has this been tested?

- Create few posts.
- Add the UAG ToC block to the content of those posts.
- Activate "Auto Load Previous Posts" option in Customizer > Blog > Single Post.
- Click on full Post text and scroll down to the next auto-loaded post. You will see that the ToC container is gone and it is converted to a simple listing. 
- Check UAG block asset is loading on post and all is working fine.

### Checklist:
- [x] My code is tested
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [x] I've included any necessary tests 
- [ ] I've included developer documentation 
- [x] I've added proper labels to this pull request

2021-09-07 10:43 UTC, RajkiranBagal approved these changes

2021-09-07 11:14 UTC, sandeshjangam commented on classes/class-uagb-front-assets.php
> +		}
Ideally, We should do this on the actions from a separate compatibility file. Move this code into a separate file and only load it when Astra is activated. 

Never add any 3rd party compatibility code directly in your main execution. It should be always on actions and filters.

Create a compatibility folder for all such 3rd part compatibilities.

2021-09-22 06:50 UTC, Nikschavan requested changes

2021-09-22 06:50 UTC, Nikschavan commented on classes/class-uagb-front-assets.php
> +				'numberposts' => -1,
Is there any way to avoid `'numberposts' => -1`?

2021-09-22 06:54 UTC, sandeshjangam commented on classes/class-uagb-front-assets.php
> +				'numberposts' => -1,
Yes, we are not going to include this code. As it is not the right way to do this. Trying a more optimized way to load CSS.

2021-10-04 04:58 UTC, AbhijitNage123 commented
This needs to be fixed by Astra. Added task here - https://wp-astra.atlassian.net/browse/AST-1010

2021-10-04 04:58 UTC, closed without merging